### PR TITLE
Fix a sync issue of tess factor read

### PR DESCRIPTION
**Pull request by amdrexu**
Before the return of HS, we will read back tess factors from on-chip LDS.
We must make sure previous tess factor stores are finished. Otherwise,
the values could be invalid. This case occurs when there are multiple HS
waves and output vertex threads of one boundary patch cross two waves like
this:

Wave 1: VVV ...
Wave 2: ...  VV

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5e7a322262576fac3f5b6b6cbfe7c88e98d16abd
<details><summary>CTS tests (Failed: 1/187820)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 36645/65225 (56.2%)</li>
<li>Failed: 0/65225 (0.0%)</li>
<li>Not Supported: 28580/65225 (43.8%)</li><li>Warnings: 0/65225 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31111/57370 (54.2%)</li>
<li>Failed: 0/57370 (0.0%)</li>
<li>Not Supported: 26259/57370 (45.8%)</li><li>Warnings: 0/57370 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37802/65225 (58.0%)</li>
<li><details><summary>Failed: 1/65225 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.multi_secondary_command_buffer
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, *fence): VK_TIMEOUT at vktSynchronizationBasicEventTests.cpp:337

```
</p></details></li>

<li>Not Supported: 27422/65225 (42.0%)</li><li>Warnings: 0/65225 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5e7a322262576fac3f5b6b6cbfe7c88e98d16abd
<details><summary>CTS tests (Failed: 1/187820)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 36645/65225 (56.2%)</li>
<li>Failed: 0/65225 (0.0%)</li>
<li>Not Supported: 28580/65225 (43.8%)</li><li>Warnings: 0/65225 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31111/57370 (54.2%)</li>
<li>Failed: 0/57370 (0.0%)</li>
<li>Not Supported: 26259/57370 (45.8%)</li><li>Warnings: 0/57370 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37802/65225 (58.0%)</li>
<li><details><summary>Failed: 1/65225 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.multi_secondary_command_buffer
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, *fence): VK_TIMEOUT at vktSynchronizationBasicEventTests.cpp:337

```
</p></details></li>

<li>Not Supported: 27422/65225 (42.0%)</li><li>Warnings: 0/65225 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
Shouldn't there already be a barrier instruction somewhere for other TCS->TES data? (Which chips are still using LDS for that anyway?)

As per some discussion we had elsewhere, I believe we now need to insert fence instructions around barriers to guarantee that the required `s_waitcnt` are emitted.

**Comment by nhaehnle** [comment]
Okay, that sounds good to me.

**Review by linqun — APPROVED** [review]

**Pull request merged**
