### PR TITLE
Support integer dot product

### PR DESCRIPTION
**Pull request by xuechen417**
This change is to utilize HW native support for integer dot product.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit b362c6bfc44b79be0e1cace9d55c9c8b7fc01606
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 83635fbee82fb21662a4737e34437c41172c6fe0</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>XGL: dev f67223913cf046cb65adcc3bd3f06c6ad232f150</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 661ac9b7d0d9edcbd07bd1b40c334934ff2297ac</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/239863)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30438/59952 (50.8%)</li>
<li>Failed: 0/59952 (0.0%)</li>
<li>Not supported: 29514/59952 (49.2%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30437/59952 (50.8%)</li>
<li>Failed: 0/59952 (0.0%)</li>
<li>Not supported: 29515/59952 (49.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30630/60037 (51.0%)</li>
<li><details><summary>Failed: 1/60037 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.op.single_queue.barrier.write_image_geometry_read_image_compute_indirect.image_128x128_r8_unorm
Stack trace: Fail
```
</p></details></li>

<li>Not supported: 29406/60037 (49.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34000/59922 (56.7%)</li>
<li><details><summary>Failed: 1/59922 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization2.timeline_semaphore.device_host.write_blit_image_read_image_tess_eval.image_128x128_r16g16b16a16_uint
Stack trace: Fail
```
</p></details></li>

<li>Not supported: 25921/59922 (43.3%)</li>
</ul></details>


</ul></details>

**Comment by xuechen417** [comment]
V1: Remove the support of vectors of i32 and i64 from the CreateIntegerDotProduct, which will be emulated in spir-v reader.

**Review by amdrexu — APPROVED** [review]
LGTM

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 29bc2de8155b9db337b92665218ca3efd54cce87
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 83635fbee82fb21662a4737e34437c41172c6fe0</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>XGL: dev f67223913cf046cb65adcc3bd3f06c6ad232f150</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 661ac9b7d0d9edcbd07bd1b40c334934ff2297ac</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/222275)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30438/55574 (54.8%)</li>
<li>Failed: 0/55574 (0.0%)</li>
<li>Not supported: 25136/55574 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30437/55574 (54.8%)</li>
<li>Failed: 0/55574 (0.0%)</li>
<li>Not supported: 25137/55574 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30630/55553 (55.1%)</li>
<li><details><summary>Failed: 1/55553 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.device_set_reset
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, DE_NULL): VK_ERROR_UNKNOWN at vktSynchronizationBasicEventTests.cpp:117

```
</p></details></li>

<li>Not supported: 24922/55553 (44.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34000/55574 (61.2%)</li>
<li><details><summary>Failed: 1/55574 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.device_set_reset
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, DE_NULL): VK_ERROR_UNKNOWN at vktSynchronizationBasicEventTests.cpp:117

```
</p></details></li>

<li>Not supported: 21573/55574 (38.8%)</li>
</ul></details>


</ul></details>

**Pull request merged**
