### PR TITLE
Move shared/continuations/ to shared/lgccps/

### PR DESCRIPTION
**Pull request by nhaehnle**
Also perform corresponding renames of CMake targets etc. and move the includes into an include/lgccps/ subdirectory.

This resolves a conflict with an upcoming internal change and aligns the code structure with that of lgcrt.

cc @ruiling

### CODE REVIEW

**Comment by nhaehnle** [comment]
retest this please

**Review by ruiling — APPROVED** [review]
Thanks for making the change!

**Comment by amdvlk-admin** [comment]
### Test summary for commit ceaabf1fb087f8f46bfebd5cb3a62edf94e9edd5
<details><summary>CTS tests (Failed: 0/211353)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35147/70456 (49.9%)</li>
<li>Failed: 0/70456 (0.0%)</li>
<li>Not Supported: 35309/70456 (50.1%)</li><li>Warnings: 0/70456 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39026/70456 (55.4%)</li>
<li>Failed: 0/70456 (0.0%)</li>
<li>Not Supported: 31430/70456 (44.6%)</li><li>Warnings: 0/70456 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39058/70441 (55.4%)</li>
<li>Failed: 0/70441 (0.0%)</li>
<li>Not Supported: 31383/70441 (44.6%)</li><li>Warnings: 0/70441 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
ping @amdrexu

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
