### PR TITLE
Fix tests to pass after LLVM update.

### PR DESCRIPTION
**Pull request by kosarev**

### CODE REVIEW

**Comment by kosarev** [comment]
@dstutt Hi David, it seems I don't have commit access for this repo (likely because of long inactivity?), so can't even add reviewers.

**Review by dstutt — APPROVED** [review]
I think this is ok in this case since there's no auto-update being used.
I suspect there will at some point, but I guess by then the llvm version will have propagated.

**Comment by dstutt** [comment]
> @dstutt Hi David, it seems I don't have commit access for this repo (likely because of long inactivity?), so can't even add reviewers.

Ok - I'll merge this for you when it passes.

**Comment by dstutt** [comment]
test this please

**Pull request merged**
