### PR TITLE
[CI] Reflect nightly CI changes in per-PR CI configuration.

### PR DESCRIPTION
**Pull request by vettoreldaniele**
Reflect changes made in https://github.com/GPUOpen-Drivers/llpc/pull/1543 to apply the same modifications for the per-PR CI.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Review by Flakebi — APPROVED** [review]

**Review by kuhar — COMMENTED** [review]
LGTM. Once #1543 lands, this needs to be force-pushed to confirm the CI works.

**Review by kuhar — CHANGES_REQUESTED** [review]
The clang tidy check also needs to be updated: https://github.com/GPUOpen-Drivers/llpc/blob/dev/.github/workflows/check-clang-tidy-llpc.yml

**Comment by vettoreldaniele** [comment]
V1: also apply changes to the clang tidy check workflow.

**Review by kuhar — APPROVED** [review]
LGTM. Once #1543 lands, this needs to be force-pushed to confirm the CI works.

**Comment by vettoreldaniele** [comment]
@kuhar regarding freeing up space in this workflow, the following options are available:
1) Always free up space, but this step can take up to 2min.
2) Only free up space for sanitizers and coverage. For this, since there's no regex support for `contains`, we can use either:
    * `if: contains(matrix.feature-set, 'san') || contains(matrix.feature-set, '+coverage')`. This is short but may be confusing.
    * `if: contains(matrix.feature-set, '+ubsan') || if: contains(matrix.feature-set, '+asan') || if: contains(matrix.feature-set, '+tsan') || contains(matrix.feature-set, '+coverage')`. This is very verbose.
    
I personally would go with 2), short-hand version with a comment explaining that `san` matches any sanitizer. What do you think?

**Comment by kuhar** [comment]
> @kuhar regarding freeing up space in this workflow, the following options are available:
> 
> 1. Always free up space, but this step can take up to 2min.
> 2. Only free up space for sanitizers and coverage. For this, since there's no regex support for `contains`, we can use either:
>    
>    * `if: contains(matrix.feature-set, 'san') || contains(matrix.feature-set, '+coverage')`. This is short but may be confusing.
>    * `if: contains(matrix.feature-set, '+ubsan') || if: contains(matrix.feature-set, '+asan') || if: contains(matrix.feature-set, '+tsan') || contains(matrix.feature-set, '+coverage')`. This is very verbose.
> 
> I personally would go with 2), short-hand version with a comment explaining that `san` matches any sanitizer. What do you think?

@vettoreldaniele options 2) sounds good for me. This is the only logic in this workflow file so I don't think being explicit hurts. This code is unlikely to grow in complexity because of it.

**Review by kuhar — DISMISSED** [review]
LGTM. Make sure to mark this as ready to review -- we can't merge draft PRs.

**Comment by trenouf** [comment]
This can't possibly make the Jenkins run fail as that does not use the .github directory. :-)

**Pull request merged**
