### PR TITLE
Removed relocatable descriptor offset test

### PR DESCRIPTION
**Pull request by trenouf**
This test asserts in PatchEntryPointMutate in a debug build for me. (I
can't xfail it, as it works, possibly by luck, on a release build.)

Change-Id: Ic39d51d044beab30c41484b6b00a087fd61ba515

### CODE REVIEW

**Comment by kuhar** [comment]
Why not XFAIL this instead?

**Comment by csyonghe** [comment]
Please don't remove these tests. I've fixed the issue and will create a PR for it.

**Comment by csyonghe** [comment]
Please see PR#603.

**Comment by trenouf** [comment]
OK; I'll wait for #603.

**Pull request closed without merging**
