### PR TITLE
Fix setting subgroupSize

### PR DESCRIPTION
**Pull request by Flakebi**
@OutOfCache noticed a missing `v_mbcnt_hi` in #2238, due to the subgroup size being different from the wave size.

setShaderDefaultWaveSize set the wave size but missed to also set the subgroup size in some cases.
When a shader on gfx10.3+ did not observe the subgroup size and the workgroup size was >64, a shader ended up with waveSize=64 and subgroupSize=32.

This patch fixes setting the subgroup size.
It also changes the behavior for workgroup sizes <=32, which now always run with waveSize=32 and may have subgroupSize=64 (previously, the wave size would have been forced to 64, with the upper 32 lanes inactive).

For testing, llpc and lgc tests failed with the new assert `waveSize <= subgroupSize`.

### CODE REVIEW

**Review by nhaehnle — COMMENTED** [review]
Seems plausible and thank you for looking into it, but the test error looks legitimate...

**Comment by Flakebi** [comment]
From the code I found so far, the driver never sets `getShaderOptions(checkingStage).subgroupSize`. Using `getShaderOptions(checkingStage).waveSize` instead (which is set by the driver) works.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 10e790d7875e30ded98ef1ee212620b9b521d414
<details><summary>CTS tests (Failed: 16/211534)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39245/70518 (55.7%)</li>
<li><details><summary>Failed: 6/70518 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.subgroups.builtin_var.framebuffer.subgroupsize_geometry
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.framebuffer.subgroupsize_tess_control
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.framebuffer.subgroupsize_tess_eval
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.framebuffer.subgroupsize_vertex
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.graphics.subgroupsize
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.ray_tracing.subgroupsize
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31267/70518 (44.3%)</li><li>Warnings: 0/70518 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39494/70507 (56.0%)</li>
<li><details><summary>Failed: 5/70507 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.subgroups.builtin_var.compute.subgroupsize_compute
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.framebuffer.subgroupsize_tess_control
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.framebuffer.subgroupsize_tess_eval
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.framebuffer.subgroupsize_vertex
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.ray_tracing.subgroupsize
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31008/70507 (44.0%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36341/70509 (51.5%)</li>
<li><details><summary>Failed: 5/70509 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.subgroups.builtin_var.compute.subgroupsize_compute
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.framebuffer.subgroupsize_tess_control
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.framebuffer.subgroupsize_tess_eval
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.builtin_var.framebuffer.subgroupsize_vertex
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.size_control.compute.require_full_subgroups
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 34163/70509 (48.5%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit a27404708cf712948d978c5159ab24dd5325378b
<details><summary>CTS tests (Failed: 0/211534)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39251/70518 (55.7%)</li>
<li>Failed: 0/70518 (0.0%)</li>
<li>Not Supported: 31267/70518 (44.3%)</li><li>Warnings: 0/70518 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39499/70507 (56.0%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31008/70507 (44.0%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36346/70509 (51.5%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34163/70509 (48.5%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]

**Pull request merged**
