### PR TITLE
Changes for LLVM removal of LoadInst::setAlignment(unsigned) etc

### PR DESCRIPTION
**Pull request by trenouf**
This will be needed from LLVM 373195.

Change-Id: I39424d1f913caccf4f93cd8b7b4b65427f1a416b

### CODE REVIEW

**Comment by trenouf** [comment]
I think this will fail because we do not have a new enough llvm yet.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9873ecc7f90240bd2c975f35c2605e1bdc3e2d38
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 3e28ea331cf8e7b0e5733e5bd7f7d16582c603c5</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 3252b6223947f9fc67399e0798b1062983925fce</li>
<li>LLVM: amd-vulkan-dev dcb42575c3d374467bb6e4e609f8bf6d1302c297</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:659:67: error: no matching function for call to ‘llvm::LoadInst::setAlignment(llvm::MaybeAlign)’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:1568:69: error: no matching function for call to ‘llvm::LoadInst::setAlignment(llvm::MaybeAlign)’

</ul></details>

**Comment by trenouf** [comment]
V2: Also fix uses of setAlignment on StoreInst, GlobalVariable,
        AllocaInst.

Still expecting this to fail because we don't have a new enough llvm yet.

**Comment by amdvlk-admin** [comment]
### Test summary for commit ffaac9f48c8e0bb6f7f374b2457bfbb2616069f5
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 3e28ea331cf8e7b0e5733e5bd7f7d16582c603c5</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 3252b6223947f9fc67399e0798b1062983925fce</li>
<li>LLVM: amd-vulkan-dev dcb42575c3d374467bb6e4e609f8bf6d1302c297</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:659:67: error: no matching function for call to ‘llvm::LoadInst::setAlignment(llvm::MaybeAlign)’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:1568:69: error: no matching function for call to ‘llvm::LoadInst::setAlignment(llvm::MaybeAlign)’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:1840:71: error: no matching function for call to ‘llvm::StoreInst::setAlignment(llvm::MaybeAlign)’

</ul></details>

**Comment by trenouf** [comment]
We got the equivalent of this change in the merge from master, so closing this now.

**Pull request closed without merging**
