### PR TITLE
Fix some piplines under shaderdb/relocatable_shaders

### PR DESCRIPTION
**Pull request by LLJJDD**
Some resource mapping are missing, which will crash our internal compiler tool.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
04b49c911908e681db90b303dcdd2d2253c65822 Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/Patch.cpp:75:10: fatal error: llvm/Transforms/IPO/PassManagerBuilder.h: No such file or directory
 #include  llvm/Transforms/IPO/PassManagerBuilder.h 
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[2858/3046] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/elfLinker/ColorExportShader.cpp.o
[2859/3046] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/builder/YCbCrConverter.cpp.o

**Comment by amdvlk-admin** [comment]
04b49c911908e681db90b303dcdd2d2253c65822 Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/Patch.cpp:75:10: fatal error: llvm/Transforms/IPO/PassManagerBuilder.h: No such file or directory
 #include  llvm/Transforms/IPO/PassManagerBuilder.h 
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[2854/3046] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/elfLinker/GlueShader.cpp.o
[2855/3046] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/elfLinker/RelocHandler.cpp.o

**Comment by amdvlk-admin** [comment]
### Test summary for commit b1c7f70d5aaf61ba1fac312c56d96cadd04362ae
<details><summary>CTS tests (Failed: 0/207358)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 36986/69126 (53.5%)</li>
<li>Failed: 0/69126 (0.0%)</li>
<li>Not Supported: 32140/69126 (46.5%)</li><li>Warnings: 0/69126 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 37206/69104 (53.8%)</li>
<li>Failed: 0/69104 (0.0%)</li>
<li>Not Supported: 31898/69104 (46.2%)</li><li>Warnings: 0/69104 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 34225/69128 (49.5%)</li>
<li>Failed: 0/69128 (0.0%)</li>
<li>Not Supported: 34903/69128 (50.5%)</li><li>Warnings: 0/69128 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by LLJJDD** [comment]
Kindly ping for an approval.

**Review by Flakebi — APPROVED** [review]

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
