### PR TITLE
[CI] Don't build llvm tools in docker builds

### PR DESCRIPTION
**Pull request by kuhar**
Reduce docker disk usage by not building unnecessary llvm tools
in CI builds. This saves ~45% of disk space used by Release builds
and saves some time by building fewer targets.

Bug: https://github.com/GPUOpen-Drivers/llpc/issues/879

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6e7f45e7e4f39663f128cf5eb7c284d4566908f8
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 3909a9fa55548c66e069a04ff79c96c8a7260851</li>
<li>SPVGEN: dev 8dc855026f2502ab3f45dadaf0bb802a57d6ad60</li>
<li>XGL: dev f4a992dd7e556ed5e7e2ffa2c830f1cd79bd4596</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c2ea9a11546d054e3918c44ac3b3ad930686cd79</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/130900)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43839 (52.0%)</li>
<li>Failed: 0/43839 (0.0%)</li>
<li>Skipped: 21055/43839 (48.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22781/43843 (52.0%)</li>
<li><details><summary>Failed: 2/43843 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.draw.instanced.draw_indirect_vk_primitive_topology_line_strip_attrib_divisor_4
Stack trace: Flake

FAILURE: dEQP-VK.tessellation.shader_input_output.tess_level_inner_0_tes
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 21060/43843 (48.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43218 (50.0%)</li>
<li>Failed: 0/43218 (0.0%)</li>
<li>Skipped: 21609/43218 (50.0%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6e7f45e7e4f39663f128cf5eb7c284d4566908f8
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 3909a9fa55548c66e069a04ff79c96c8a7260851</li>
<li>SPVGEN: dev 8dc855026f2502ab3f45dadaf0bb802a57d6ad60</li>
<li>XGL: dev f4a992dd7e556ed5e7e2ffa2c830f1cd79bd4596</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c2ea9a11546d054e3918c44ac3b3ad930686cd79</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/130900)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43839 (52.0%)</li>
<li>Failed: 0/43839 (0.0%)</li>
<li>Skipped: 21055/43839 (48.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22783/43843 (52.0%)</li>
<li>Failed: 0/43843 (0.0%)</li>
<li>Skipped: 21060/43843 (48.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43218 (50.0%)</li>
<li>Failed: 0/43218 (0.0%)</li>
<li>Skipped: 21609/43218 (50.0%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
> As a sidenote: How about setting `LLPC_BUILD_LLVM_TOOLS` to `OFF` by default? It isn’t needed for the driver or the tests, so it seems like a waste to build them by default. This shouldn’t block this PR though.

I didn't want to break other builds that may assume that llvm tools (e.g., llvm-objdump) are present. Flipping it off by default can be a separate PR.

**Comment by kuhar** [comment]
@trenouf @amdrexu @JaxLinAMD Can you merge this PR?
I believe this is the most reasonable to the public CI issues.

**Pull request merged**
