### PR TITLE
Update tests to handle new version of llvm

### PR DESCRIPTION
**Pull request by mbrkusanin**

### CODE REVIEW

**Comment by mbrkusanin** [comment]
ok to test

**Comment by dstutt** [comment]
This change is in anticipation of:
https://reviews.llvm.org/D155681 [AMDGPU] Insert s_nop before s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)

**Comment by dstutt** [comment]
https://github.com/GPUOpen-Drivers/xgl/pull/172 is required before this will pass actions (although may not be required to merge)

**Review by nhaehnle — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit e70928ee1804df5e2746d6c6faf6af9a58e8099f
<details><summary>CTS tests (Failed: 0/211360)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35147/70459 (49.9%)</li>
<li>Failed: 0/70459 (0.0%)</li>
<li>Not Supported: 35312/70459 (50.1%)</li><li>Warnings: 0/70459 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39024/70457 (55.4%)</li>
<li>Failed: 0/70457 (0.0%)</li>
<li>Not Supported: 31433/70457 (44.6%)</li><li>Warnings: 0/70457 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39058/70444 (55.4%)</li>
<li>Failed: 0/70444 (0.0%)</li>
<li>Not Supported: 31386/70444 (44.6%)</li><li>Warnings: 0/70444 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
