### PR TITLE
Refine LLPC

### PR DESCRIPTION
**Pull request by amdrexu**
Rename xfbLocOffset to xfbExtraOffset

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit ef33d177557c7ebfa2e7814dd3f4d7f6dd0a83a2
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 39abe2297ca58a2b84dcd9bc5e238fbc399bd6e0</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 19a031d9f73b95101fd4d3d594aca27c00feb180</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 40fbaf4c5446a361269c241d9112fff26575b5d0</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 64854/64854 (100.0%)</li>
<li>Failed: 0/64854 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 64886/64886 (100.0%)</li>
<li>Failed: 0/64886 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
Please do not merge pull request this quickly. You need to give others some time to review and comment.

Please follow best practices for commit messages. "Refine LLPC" is uninformative. The headline should be something along the lines of "`Rename xfbLocOffset to xfbExtraOffset`".

Also, this commit introduces a lot of churn and may make progress more difficult for people working on other branches by introducing gratuitious merge conflicts. At the very least, you need to justify yourself for such a change: the body of the commit message must explain *why* you're doing this rename.

**Comment by amdrexu** [comment]
Thank you for pointing out this problem. For such renaming change, we will add more details of our thoughts to the description and suspend it for more time to let everyone notice this change and make comments.

But renaming and code move might be frequent when you find something is unclear, inaccurate, improper, or you introduce more functionalities to a parameter, to a temporary variable, to a source file. It unaviodably breaks others' development for a while.

**Comment by nhaehnle** [comment]
Yes, I agree we should not be afraid to refactor where it makes sense. But some explanation would be good, thank you!

**Pull request merged**
