### PR TITLE
NggPrimShader: Improve attribute-through-memory code generation

### PR DESCRIPTION
**Pull request by nhaehnle**
Previously, we would export attributes on gfx11 like:

    ; v3 is threadIdInSubgroup
    s_add_i32 s8, s9, 0x200
    buffer_store_b128 v[10:13], v3, s[0:3], s8 idxen glc slc
    buffer_store_b128 v[32:35], v3, s[0:3], s9 idxen glc slc

With this change, we export attributes like:

    buffer_store_b128 v[10:13], v3, s[0:3], s9 idxen offset:16 glc slc
    buffer_store_b128 v[32:35], v3, s[0:3], s9 idxen glc slc

That is, we lean on the buffer swizzling to avoid setting up different offsets for the different locations.

The change also cuts a few SALU instructions from the buffer descriptor fixup.

I started this hoping to get rid of the index VGPR, but have run into issues that may or may not be a hardware problem. In the meantime, this is a smaller improvement that should just work.

### CODE REVIEW

**Comment by nhaehnle** [comment]
@amdrexu This particular change should also apply to mesh shader. How do you typically test those? Just CTS?

**Comment by amdvlk-admin** [comment]
### Test summary for commit a6687997ac83af7a383502da98d7692bf702a517
<details><summary>CTS tests (Failed: 0/211487)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39248/70495 (55.7%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 31247/70495 (44.3%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39498/70495 (56.0%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 30997/70495 (44.0%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36345/70497 (51.6%)</li>
<li>Failed: 0/70497 (0.0%)</li>
<li>Not Supported: 34152/70497 (48.4%)</li><li>Warnings: 0/70497 (0.0%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]
Thanks. I didn't realize we can use idxen +offen mode to simplify the buffer store operation. Maybe apply it to mesh shader as well.

**Comment by nhaehnle** [comment]
Yes, I will prepare a change for mesh shader as well.

**Pull request merged**
