### PR TITLE
Integrate amdllpc lit tests into cmake build system

### PR DESCRIPTION
**Pull request by trenouf**
This commit allows the use of "make check-amdllpc" from the normal
driver build directory. It automatically supplies the location of
amdllpc and spvgen.so to the lit tests. The check-amdllpc target depends
on amdllpc and spvgen, so causes them to be built first. It also depends
on the applicable llvm utilities e.g. FileCheck.

Change-Id: I598b0949481616b2c37e79d18d2e20e5a725819e

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0a0ec1814250bd25f0c3388c092ebb7a3f71a77e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 99901922d67e502ff4233a8bfcbfa0347c0ffa1b</li>
<li>SPVGEN: dev 69311f7c1e220d190909298b9c7bd702ecc237ff</li>
<li>XGL: dev 5b4058dc288a25f6554fcc61f80bf3f27eb35d8d</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by JacobHeAMD** [comment]
Hi @trenouf , could you please help to resolve the conflicts?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 23b336ead00fa9879f8587039124a261c31e70b6
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 99901922d67e502ff4233a8bfcbfa0347c0ffa1b</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 9795e006e9adb7b49b8abd32cd47c49b290fa3fc</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by trenouf** [comment]
Hopefully this version still works with the old way of invoking the tests, so will pass testing here.

**Comment by trenouf** [comment]
retest this please

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit a196c5b58841619df058bd06a7b3b37626610d94
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 99901922d67e502ff4233a8bfcbfa0347c0ffa1b</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 9795e006e9adb7b49b8abd32cd47c49b290fa3fc</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 901/901 (100.0%)</li>
<li>Failed: 0/901 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Vega20</summary><ul>

<li>Passed: 312687/312687 (100.0%)</li>
<li>Failed: 0/312687 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
