### PR TITLE
[lgcdis] Support disassembling long jumps.

### PR DESCRIPTION
**Pull request by kosarev**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by Flakebi** [comment]
ok to test (← command to allow jenkins testing)

**Comment by amdvlk-admin** [comment]
### Test summary for commit a5cfb977d7f6022d6aea819584ab7049dd83810a
<details><summary>CTS tests (Failed: 1/179025)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35420/63739 (55.6%)</li>
<li>Failed: 0/63739 (0.0%)</li>
<li>Not Supported: 28319/63739 (44.4%)</li><li>Warnings: 0/63739 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27341/51547 (53.0%)</li>
<li><details><summary>Failed: 1/51547 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.reconvergence.workgroup_uniform_control_flow_elect.compute.nesting4.4.34
Stack trace: Script:
Crash

```
</p></details></li>

<li>Not Supported: 24205/51547 (47.0%)</li><li>Warnings: 0/51547 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37681/63739 (59.1%)</li>
<li>Failed: 0/63739 (0.0%)</li>
<li>Not Supported: 26058/63739 (40.9%)</li><li>Warnings: 0/63739 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by kosarev** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit a5cfb977d7f6022d6aea819584ab7049dd83810a
<details><summary>CTS tests (Failed: 0/216210)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35449/73547 (48.2%)</li>
<li>Failed: 0/73547 (0.0%)</li>
<li>Not Supported: 38098/73547 (51.8%)</li><li>Warnings: 0/73547 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33142/69116 (48.0%)</li>
<li>Failed: 0/69116 (0.0%)</li>
<li>Not Supported: 35974/69116 (52.0%)</li><li>Warnings: 0/69116 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37710/73547 (51.3%)</li>
<li>Failed: 0/73547 (0.0%)</li>
<li>Not Supported: 35837/73547 (48.7%)</li><li>Warnings: 0/73547 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by kosarev** [comment]
@trenouf Ping.

**Review by trenouf — APPROVED** [review]
Sorry, didn't notice the review request the first time. LGTM.

**Pull request merged**
