### PR TITLE
Cleanup amdllpc.cpp functions. NFC.

### PR DESCRIPTION
**Pull request by kuhar**
-  Add missing documentation.
-  Format code.
-  Move Windows functions towards the bottom.

Required for https://github.com/GPUOpen-Drivers/llpc/pull/1372.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6d1d8e7ac7ba01ea87f60703b9cc10efcfbd109a
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev cd4f8b28b5d923e8d65a1ef1d3dee5137a89d6bd</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev b78601f5e66f80505bce5222fbd92f4e27e704c2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fd071e5c2971c07fd4cd4b22c69f7bc0d6ddc59b</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/221024)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31436/55256 (56.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 23820/55256 (43.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34187/55256 (61.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 21069/55256 (38.1%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
Ping for code review @amdrexu @trenouf

**Comment by kuhar** [comment]
V1: Rebase

**Review by amdrexu — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5e6877639b2d717b499c685930bfbb8c56e9043f
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev cd4f8b28b5d923e8d65a1ef1d3dee5137a89d6bd</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev b78601f5e66f80505bce5222fbd92f4e27e704c2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fd071e5c2971c07fd4cd4b22c69f7bc0d6ddc59b</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/221024)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31436/55256 (56.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 23820/55256 (43.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34187/55256 (61.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 21069/55256 (38.1%)</li>
</ul></details>


</ul></details>

**Pull request merged**
