### PR TITLE
Promotion from AMD internal branch for 2022.Q4.2

### PR DESCRIPTION
**Pull request by WenqingLiAMD**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2e4c95093e41287111cfea6a6472dc4fdbefb1d2
<details><summary>CTS tests (Failed: 0/0)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Timeout or crash</li>

</ul></details>


</ul></details>

**Review by Flakebi — COMMENTED** [review]
@amdrexu These promotion PRs get larger and larger with each cycle. Shouldn’t most of the changes go through pull requests here?
There’s quite a few changes for task/mesh shaders that I don’t know much about. LGTM for the rest.

**Comment by amdrexu** [comment]
> There’s quite a few changes for task/mesh shaders that I don’t know much about. LGTM for the rest.

This is because many implementation codes stay in internal repo and couldn't be published until the spec is released :( We couldn't avoid this unless we always do implementation after the spec is finalize and is published. Actually, this is infeasible because internal testing needs the implementation earlier than the spec release date.

The task/mesh shader stuffs in LLPC front-end is reviewed by Nicolai internally. It is being updated and proceeds from 10 month ago. And the spec is changed for several times.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0387abed4e07b602fd14cb900bd5e6249d0645fc
<details><summary>CTS tests (Failed: 0/0)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Timeout or crash</li>

</ul></details>


</ul></details>

**Pull request merged**
