### PR TITLE
Moved most of LLPC into llpc subdirectory

### PR DESCRIPTION
**Pull request by trenouf**
Future commits will move some code out of the llpc subdirectory that is
not strictly part of LLPC, such as the pipeline dumper.

This change requires xgl change
https://github.com/GPUOpen-Drivers/xgl/pull/47

### CODE REVIEW

**Comment by trenouf** [comment]
Rebased. Hopefully will pass testing now that the required xgl commit is merged.

**Comment by trenouf** [comment]
I think I need FORCE on the set XGL_LLPC_PATH lines, otherwise it remembers the old setting in CMakeCache.txt.

**Comment by amdrexu** [comment]
It seems the CI system build is broken :(

**Comment by trenouf** [comment]
One-char change just to get a test run on the newly merged xgl pr48.

**Comment by amdvlk-admin** [comment]
### Test summary for commit df1707e6ad7be9637ea5865cd18bde23a6826b94
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 9fab16015e522fff05890a045a1e9d8d3c23a636</li>
<li>SPVGEN: dev 6c9a5cf8789681e31b9cd3df8af245b9aaa2c259</li>
<li>XGL: dev 06941016ac74e30b8510afb97c3f4909d211187f</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by trenouf** [comment]
Even though I have the benefit of being able to see the internal test system :-) I still can't see why this failed. So I will retry it.

**Comment by trenouf** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit df1707e6ad7be9637ea5865cd18bde23a6826b94
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 9fab16015e522fff05890a045a1e9d8d3c23a636</li>
<li>SPVGEN: dev 6c9a5cf8789681e31b9cd3df8af245b9aaa2c259</li>
<li>XGL: dev c0791473c087f5b5d75a21c6f2ace72ccd232a65</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by trenouf** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit df1707e6ad7be9637ea5865cd18bde23a6826b94
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 9fab16015e522fff05890a045a1e9d8d3c23a636</li>
<li>SPVGEN: dev 6c9a5cf8789681e31b9cd3df8af245b9aaa2c259</li>
<li>XGL: dev c0791473c087f5b5d75a21c6f2ace72ccd232a65</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 73424276b2a5ccb58e643ddf01ca51ceee7a9208
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 9fab16015e522fff05890a045a1e9d8d3c23a636</li>
<li>SPVGEN: dev 6c9a5cf8789681e31b9cd3df8af245b9aaa2c259</li>
<li>XGL: dev c0791473c087f5b5d75a21c6f2ace72ccd232a65</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by trenouf** [comment]
Hopefully will pass testing now spvgen change
https://github.com/GPUOpen-Drivers/spvgen/pull/5
is merged.

**Comment by trenouf** [comment]
Fixed a problem in how llpc's CMakeLists.txt finds the spvgen one.

**Comment by trenouf** [comment]
V7:
    This commit leaves a test/CMakeLists.txt that forwards to
    llpc/test/CMakeLists.txt, to cope with an old build script that still
    looks for it in the old location.

**Comment by trenouf** [comment]
retest this please

**Comment by trenouf** [comment]
Actually I don't want to retest this until I have merged other changes and then rebased this one. So I have aborted that build.

**Comment by trenouf** [comment]
Rebased.

**Comment by trenouf** [comment]
Fixed the rebase. (I had accidentally left a couple of new test files behind.)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 99102f751c2ff9f49d49c3964c09c72cdabea4cd
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 9fab16015e522fff05890a045a1e9d8d3c23a636</li>
<li>SPVGEN: dev a61db14f75728e91c243d4bfc1c39700e9dc0ba6</li>
<li>XGL: dev c0791473c087f5b5d75a21c6f2ace72ccd232a65</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65463/65463 (100.0%)</li>
<li>Failed: 0/65463 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
Rebased again.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 73cab7ca4080d76ac2194709bcacd2d38627f82c
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 9fab16015e522fff05890a045a1e9d8d3c23a636</li>
<li>SPVGEN: dev a61db14f75728e91c243d4bfc1c39700e9dc0ba6</li>
<li>XGL: dev c0791473c087f5b5d75a21c6f2ace72ccd232a65</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 941/941 (100.0%)</li>
<li>Failed: 0/941 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65463/65463 (100.0%)</li>
<li>Failed: 0/65463 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
