### PR TITLE
Opaque Pointers: Enable opaque pointers in LLPC and LGC

### PR DESCRIPTION
**Pull request by mariusz-sikora-at-amd**
All known tests are working without any performance degradation.

### CODE REVIEW

**Review by piotrAMD — DISMISSED** [review]
Thanks!

**Comment by piotrAMD** [comment]
There are many TODOs "Remove this when LLPC will switch fully to opaque pointers.". Is your intention to remove them at some later point in not-so-distant future?

**Comment by amdvlk-admin** [comment]
### Test summary for commit d13b2520da0e89fc4eb77a3fe5cf3fd00a98fea2
<details><summary>CTS tests (Failed: 2/207298)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39112/70485 (55.5%)</li>
<li><details><summary>Failed: 2/70485 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.0_00
Stack trace: Flake

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.max
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by Flakebi** [comment]
Nice!

> There are many TODOs "Remove this when LLPC will switch fully to opaque pointers.". Is your intention to remove them at some later point in not-so-distant future?

I hope we can leave them in for a promotion cycle or so? There may be problems popping up when all the testing is done.

**Comment by Flakebi** [comment]
retest this please

Let’s see if this was a flake

**Comment by mariusz-sikora-at-amd** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit d13b2520da0e89fc4eb77a3fe5cf3fd00a98fea2
<details><summary>CTS tests (Failed: 2/207298)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39112/70485 (55.5%)</li>
<li><details><summary>Failed: 2/70485 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
More crash observed with navi31.
05:32:33  [68116/70485] Pass: 37190 Fail: 0 Skip: 19519 ExpectedFail: 0 UnexpectedPass: 0 Crash: 361 Timeout: 0 Missing: 11046 Flake: 0 Duration: 38:24 Remaining: 1:20

**Comment by amdvlk-admin** [comment]
### Test summary for commit d13b2520da0e89fc4eb77a3fe5cf3fd00a98fea2
<details><summary>CTS tests (Failed: 0/207298)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70485 (55.5%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by mariusz-sikora-at-amd** [comment]
> More crash observed with navi31. 05:32:33 [68116/70485] Pass: 37190 Fail: 0 Skip: 19519 ExpectedFail: 0 UnexpectedPass: 0 Crash: 361 Timeout: 0 Missing: 11046 Flake: 0 Duration: 38:24 Remaining: 1:20

Thanks, now I noticed that it was crashing on navi3x all the time. Somehow I missed this in the logs and was focused on navi2x.
I will verify this.

**Comment by amdvlk-admin** [comment]
### Test summary for commit d13b2520da0e89fc4eb77a3fe5cf3fd00a98fea2
<details><summary>CTS tests (Failed: 376/277947)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38488/70526 (54.6%)</li>
<li><details><summary>Failed: 376/70526 (0.5%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.first.line_list
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.first.line_list_with_adjacency
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.first.line_strip
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.first.line_strip_with_adjacency
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.first.triangle_fan
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.first.triangle_list
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.first.triangle_list_with_adjacency
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.first.triangle_strip
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.first.triangle_strip_with_adjacency
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.last.line_list
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.last.line_list_with_adjacency
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.last.line_strip
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.last.line_strip_with_adjacency
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.last.triangle_fan
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.last.triangle_list
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.last.triangle_list_with_adjacency
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.last.triangle_strip
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.last.triangle_strip_with_adjacency
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.per_pipeline.line_list
Stack trace: Crash

FAILURE: dEQP-VK.rasterization.provoking_vertex.transform_feedback.per_pipeline.line_list_with_adjacency
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 31662/70526 (44.9%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70526 (55.5%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31412/70526 (44.5%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70528 (51.0%)</li>
<li>Failed: 0/70528 (0.0%)</li>
<li>Not Supported: 34569/70528 (49.0%)</li><li>Warnings: 0/70528 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66367 (50.7%)</li>
<li>Failed: 0/66367 (0.0%)</li>
<li>Not Supported: 32689/66367 (49.3%)</li><li>Warnings: 0/66367 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by mariusz-sikora-at-amd** [comment]
Issue with Navi3x was caused by lack one change which wasn't pushed to upstream.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 775a666901dd2a708a1525252cd9fa47e45aba13
<details><summary>CTS tests (Failed: 0/282101)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70526 (55.1%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31662/70526 (44.9%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70526 (55.5%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31412/70526 (44.5%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70528 (51.0%)</li>
<li>Failed: 0/70528 (0.0%)</li>
<li>Not Supported: 34569/70528 (49.0%)</li><li>Warnings: 0/70528 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 35861/70521 (50.9%)</li>
<li>Failed: 0/70521 (0.0%)</li>
<li>Not Supported: 34660/70521 (49.1%)</li><li>Warnings: 0/70521 (0.0%)</li>
</ul></details>


</ul></details>

**Review by Flakebi — APPROVED** [review]
Nice, Jenkins passed, so LGTM.

**Comment by mariusz-sikora-at-amd** [comment]
> Nice, Jenkins passed, so LGTM.

Yes, I had to upstream one missing change from internal repo.

**Review by nhaehnle — APPROVED** [review]

**Comment by piotrAMD** [comment]
Nice! :tada:

**Pull request merged**
