### PR TITLE
Move SpirvLowerRayTracing to the end of lower passes

### PR DESCRIPTION
**Pull request by LLJJDD**
To make it work correctly:

Add proper memory attributes so that intrinsic calls won't get optimized away.

Use dialect for hit attribute / incoming payload / incoming callable data, as there will be no allocas after SROA pass.

### CODE REVIEW

**Review by nhaehnle — COMMENTED** [review]
According to [the documentation for lgc.rt](https://github.com/GPUOpen-Drivers/llpc/blob/2b0995bc14af88917eea151cd3a12a849ab3c1f0/shared/lgcrt/include/lgcrt/LgcRtDialect.td#L35), hit attributes and payloads should be passed as pointers to the functions themselves. Can you change SpirvLowerGlobal so that it changes the function signature of the shader functions, i.e. should look something like:
```
define spir_func void @chs(ptr addrspace(5) %payload, ptr addrspace (5) %hit.attr) !lgc.rt.paq !0 !lgc.rt.attribute.size !1 { ... }
```
... using `lgc::rt::setShaderPaq,setShaderHitAttributeSize` and `setShaderArgSize` (for callable shader). You should be able to reuse `lgc::addFunctionArgs`, maybe move it to a utility header.

I was wondering about some of the `Memory<...>` changes in the dialect definitions because callable shaders can write to storage buffers etc., but ultimately I think your changes there are correct: if a callable shader writes to a storage buffer, the write is only visible to the calling shader if an appropriate memory barrier is used. The Vulkan spec says this (in section 40.1):

> For ray tracing invocations that are [shader-call-related](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#shader-call-related):
>
> * [memory operations](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#memory-model-memory-operation) on StorageBuffer, Image, and ShaderRecordBufferKHR storage classes can be synchronized using the ShaderCallKHR scope.

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfa3ac6d3b5bde23da9a34a22f517f8efd13d799
<details><summary>CTS tests (Failed: 0/211633)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70549 (50.3%)</li>
<li>Failed: 0/70549 (0.0%)</li>
<li>Not Supported: 35053/70549 (49.7%)</li><li>Warnings: 0/70549 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39381/70550 (55.8%)</li>
<li>Failed: 0/70550 (0.0%)</li>
<li>Not Supported: 31169/70550 (44.2%)</li><li>Warnings: 0/70550 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70534 (55.9%)</li>
<li>Failed: 0/70534 (0.0%)</li>
<li>Not Supported: 31121/70534 (44.1%)</li><li>Warnings: 0/70534 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109f7400e60b460d4293291ca229d42011f7efc8
<details><summary>CTS tests (Failed: 0/211633)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70549 (50.3%)</li>
<li>Failed: 0/70549 (0.0%)</li>
<li>Not Supported: 35053/70549 (49.7%)</li><li>Warnings: 0/70549 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39381/70550 (55.8%)</li>
<li>Failed: 0/70550 (0.0%)</li>
<li>Not Supported: 31169/70550 (44.2%)</li><li>Warnings: 0/70550 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70534 (55.9%)</li>
<li>Failed: 0/70534 (0.0%)</li>
<li>Not Supported: 31121/70534 (44.1%)</li><li>Warnings: 0/70534 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by LLJJDD** [comment]
> You should be able to reuse `lgc::addFunctionArgs`, maybe move it to a utility header.

I use `llvm::CloneFunctionInto` instead, to avoid moving a bunch of code :)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 181922abf0a881d95c646b49df397c44a4bf3304
<details><summary>CTS tests (Failed: 0/211633)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70549 (50.3%)</li>
<li>Failed: 0/70549 (0.0%)</li>
<li>Not Supported: 35053/70549 (49.7%)</li><li>Warnings: 0/70549 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39381/70550 (55.8%)</li>
<li>Failed: 0/70550 (0.0%)</li>
<li>Not Supported: 31169/70550 (44.2%)</li><li>Warnings: 0/70550 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70534 (55.9%)</li>
<li>Failed: 0/70534 (0.0%)</li>
<li>Not Supported: 31121/70534 (44.1%)</li><li>Warnings: 0/70534 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 16ee0a68c0b463c07988cfe668e644bbf78873fd
<details><summary>CTS tests (Failed: 0/211633)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70549 (50.3%)</li>
<li>Failed: 0/70549 (0.0%)</li>
<li>Not Supported: 35053/70549 (49.7%)</li><li>Warnings: 0/70549 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39381/70550 (55.8%)</li>
<li>Failed: 0/70550 (0.0%)</li>
<li>Not Supported: 31169/70550 (44.2%)</li><li>Warnings: 0/70550 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70534 (55.9%)</li>
<li>Failed: 0/70534 (0.0%)</li>
<li>Not Supported: 31121/70534 (44.1%)</li><li>Warnings: 0/70534 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
