### PR TITLE
Rework of location info recording (particularly for XFB)

### PR DESCRIPTION
**Pull request by amdrexu**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 97afa3fba169eda403e4f74ce6ba4625274fd344
<details><summary>CTS tests (Failed: 282/215993)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40418/72001 (56.1%)</li>
<li><details><summary>Failed: 282/72001 (0.4%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.blit_image.all_formats.color.3d.r16g16b16a16_sfloat.r16g16b16a16_sfloat.general_optimal_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.blit_image.simple_tests.mirror_xy.nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.clear_color_image.3d.optimal.single_layer.a8b8g8r8_srgb_pack32_200x180x16
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.buffer_device_address.set3.depth1.basessbo.crossconvertu2p.store.multi.std140.vert
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.descriptor_copy.graphics.inline_uniform_block_4
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.descriptor_copy.graphics.uniform_buffer_1
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.descriptorset_random.sets16.runtimesize.noubo.nosbo.nosampledimg.lowimgsingletex.iublimitlow.uab.sect.noia.0
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.shader_access.secondary_cmd_buf.storage_image.geometry.multiple_discontiguous_descriptor_sets.multiple_discontiguous_descriptors.2d_base_slice
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.shader_access.secondary_cmd_buf.with_push_template.combined_image_sampler_mutable.vertex_fragment.single_descriptor.2d_array
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_cull_distance.vert_tess_geom.2_6_fragmentshader_read
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_distance.vert_geom.3
Stack trace: Flake

FAILURE: dEQP-VK.compute.basic.ssbo_cmd_barrier_single
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.zero.uint8_t_array_to_double_float_array_3
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.dispatch.condition_local_memory_inherited_expect_noop_inverted.dispatch
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.draw.condition_host_memory_expect_noop_inverted.draw_indirect_count
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.draw_clear.clear.depth.clear_attachment_twice_no_discard_invert_partial_offset_local_memory
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.draw_clear.draw.case_13_host_memory
Stack trace: Flake

FAILURE: dEQP-VK.fragment_shading_barycentric.data.provoking_first.static.triangle_list_with_adjacency.type.uint
Stack trace: Flake

FAILURE: dEQP-VK.fragment_shading_barycentric.data.provoking_last.dynamic.line_list.struct.ivec2
Stack trace: Flake

FAILURE: dEQP-VK.fragment_shading_rate.dynamic_rendering.primary_cmd_buff.monolithic.basic.dynamic.attachment.shaderrate.min.mul.1x1.samples2.ms
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 31301/72001 (43.5%)</li><li>Warnings: 0/72001 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40713/71984 (56.6%)</li>
<li>Failed: 0/71984 (0.0%)</li>
<li>Not Supported: 31271/71984 (43.4%)</li><li>Warnings: 0/71984 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36765/72008 (51.1%)</li>
<li>Failed: 0/72008 (0.0%)</li>
<li>Not Supported: 35243/72008 (48.9%)</li><li>Warnings: 0/72008 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit fe94e30fc315edbadf6ecb047c5927dd560368df
<details><summary>CTS tests (Failed: 44/215998)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40641/72006 (56.4%)</li>
<li><details><summary>Failed: 44/72006 (0.1%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.transform_feedback.fuzz.2_level_array.dmat3.geometry
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.3_level_array.dvec4.geometry
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_instance_array.41
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_instance_array.80
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_instance_array.92
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_instance_array.97
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.35
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.40
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.51
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.52
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.98
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_instance_array.10
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_instance_array.83
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.14
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.17
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.3
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.47
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.70
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.74
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.75
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 31321/72006 (43.5%)</li><li>Warnings: 0/72006 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40713/71984 (56.6%)</li>
<li>Failed: 0/71984 (0.0%)</li>
<li>Not Supported: 31271/71984 (43.4%)</li><li>Warnings: 0/71984 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36765/72008 (51.1%)</li>
<li>Failed: 0/72008 (0.0%)</li>
<li>Not Supported: 35243/72008 (48.9%)</li><li>Warnings: 0/72008 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit bac8d0d91c02dd8557d2cf84610e0d55578fbe95
<details><summary>CTS tests (Failed: 48/215993)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40647/72001 (56.5%)</li>
<li><details><summary>Failed: 48/72001 (0.1%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.transform_feedback.fuzz.2_level_array.dmat3.geometry
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.3_level_array.dvec4.geometry
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_instance_array.41
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_instance_array.63
Stack trace: Crash

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_instance_array.80
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_instance_array.92
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_instance_array.97
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.35
Stack trace: Crash

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.40
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.51
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.52
Stack trace: Crash

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.98
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_instance_array.10
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_instance_array.50
Stack trace: Crash

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_instance_array.83
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.14
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.17
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.29
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.3
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.47
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 31306/72001 (43.5%)</li><li>Warnings: 0/72001 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40713/71984 (56.6%)</li>
<li>Failed: 0/71984 (0.0%)</li>
<li>Not Supported: 31271/71984 (43.4%)</li><li>Warnings: 0/71984 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36765/72008 (51.1%)</li>
<li>Failed: 0/72008 (0.0%)</li>
<li>Not Supported: 35243/72008 (48.9%)</li><li>Warnings: 0/72008 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8f772e4113b32548e901100cca4f8e0f26c64f88
<details><summary>CTS tests (Failed: 6/215993)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40689/72001 (56.5%)</li>
<li><details><summary>Failed: 6/72001 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_instance_array.63
Stack trace: Crash

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.35
Stack trace: Crash

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_missing.52
Stack trace: Crash

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_instance_array.50
Stack trace: Crash

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.nested_structs_arrays.28
Stack trace: Crash

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.nested_structs_arrays.32
Stack trace: Crash
```
</p></details></li>

<li>Not Supported: 31306/72001 (43.5%)</li><li>Warnings: 0/72001 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40713/71984 (56.6%)</li>
<li>Failed: 0/71984 (0.0%)</li>
<li>Not Supported: 31271/71984 (43.4%)</li><li>Warnings: 0/71984 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36765/72008 (51.1%)</li>
<li>Failed: 0/72008 (0.0%)</li>
<li>Not Supported: 35243/72008 (48.9%)</li><li>Warnings: 0/72008 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 7c12884148285966319a47a620ca039600b4d8c5
<details><summary>CTS tests (Failed: 0/215993)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40695/72001 (56.5%)</li>
<li>Failed: 0/72001 (0.0%)</li>
<li>Not Supported: 31306/72001 (43.5%)</li><li>Warnings: 0/72001 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40713/71984 (56.6%)</li>
<li>Failed: 0/71984 (0.0%)</li>
<li>Not Supported: 31271/71984 (43.4%)</li><li>Warnings: 0/71984 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36765/72008 (51.1%)</li>
<li>Failed: 0/72008 (0.0%)</li>
<li>Not Supported: 35243/72008 (48.9%)</li><li>Warnings: 0/72008 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 05e8143332bc6d958b86d35fcf8fcc50093dfd73
<details><summary>CTS tests (Failed: 0/215993)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40695/72001 (56.5%)</li>
<li>Failed: 0/72001 (0.0%)</li>
<li>Not Supported: 31306/72001 (43.5%)</li><li>Warnings: 0/72001 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40713/71984 (56.6%)</li>
<li>Failed: 0/71984 (0.0%)</li>
<li>Not Supported: 31271/71984 (43.4%)</li><li>Warnings: 0/71984 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36765/72008 (51.1%)</li>
<li>Failed: 0/72008 (0.0%)</li>
<li>Not Supported: 35243/72008 (48.9%)</li><li>Warnings: 0/72008 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 82f02bb8af2e90ba32fdeb5c00869682a1dbaba2
<details><summary>CTS tests (Failed: 0/142050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40073/71024 (56.4%)</li>
<li>Failed: 0/71024 (0.0%)</li>
<li>Not Supported: 30951/71024 (43.6%)</li><li>Warnings: 0/71024 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36219/71026 (51.0%)</li>
<li>Failed: 0/71026 (0.0%)</li>
<li>Not Supported: 34807/71026 (49.0%)</li><li>Warnings: 0/71026 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6785f6eb45946b7cb8c6e771f4c4df9ba8e1358a
<details><summary>CTS tests (Failed: 286/142050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39792/71024 (56.0%)</li>
<li><details><summary>Failed: 286/71024 (0.4%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.buffer.suballocation.transfer_src.transfer_dst.uniform_texel.uniform.storage.create.binding_residency_aliased
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.blit_image.simple_tests.mirror_subregions.r32_sfloat_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.2d.r32g32b32a32_uint.bc6h_sfloat_block.optimal_general
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.image_to_image.dimensions.src6x8192_dst6x8192.r32g32b32a32_uint.r32g32b32a32_uint.optimal_general
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.all_formats.color.2d.r4g4_unorm_pack8.r4g4b4a4_unorm_pack16.optimal_optimal_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.all_formats.color.3d.r16_snorm.r16_snorm.optimal_general_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.buffer_to_depthstencil.buffer_offset_d16_unorm_D
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.image_to_image.all_formats.color.2d.a8b8g8r8_sint_pack32.r8g8b8a8_unorm.optimal_general
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.core.clear_color_image.3d.optimal.single_layer.r16g16_snorm_200x180x16
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.core.partial_clear_color_attachment.cube_layers.r16g16b16a16_unorm
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.clear_color_attachment.multiple_layers.b8g8r8a8_snorm_200x180
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.clear_color_attachment.multiple_layers.r16g16_snorm_1x33
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.clear_color_attachment.single_layer.r8g8b8a8_snorm
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.clear_color_image.2d.linear.remaining_array_layers_twostep.a2r10g10b10_uint_pack32_33x128
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.clear_color_image.2d.optimal.remaining_array_layers.r8_snorm_64x11
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.partial_clear_color_attachment.multiple_layers.r16_unorm_64x11
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.partial_clear_color_attachment.multiple_layers.r16g16_snorm_200x180
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.partial_clear_depth_stencil_attachment.multiple_layers.d16_unorm_64x11
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.partial_clear_depth_stencil_attachment.multiple_layers.d16_unorm_s8_uint_separate_layouts_depth
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.partial_clear_depth_stencil_attachment.single_layer.d16_unorm_200x180
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 30946/71024 (43.6%)</li><li>Warnings: 0/71024 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36219/71026 (51.0%)</li>
<li>Failed: 0/71026 (0.0%)</li>
<li>Not Supported: 34807/71026 (49.0%)</li><li>Warnings: 0/71026 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6785f6eb45946b7cb8c6e771f4c4df9ba8e1358a
<details><summary>CTS tests (Failed: 0/142050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40073/71024 (56.4%)</li>
<li>Failed: 0/71024 (0.0%)</li>
<li>Not Supported: 30951/71024 (43.6%)</li><li>Warnings: 0/71024 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36219/71026 (51.0%)</li>
<li>Failed: 0/71026 (0.0%)</li>
<li>Not Supported: 34807/71026 (49.0%)</li><li>Warnings: 0/71026 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6785f6eb45946b7cb8c6e771f4c4df9ba8e1358a
<details><summary>CTS tests (Failed: 0/213050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40073/71010 (56.4%)</li>
<li>Failed: 0/71010 (0.0%)</li>
<li>Not Supported: 30937/71010 (43.6%)</li><li>Warnings: 0/71010 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40113/71014 (56.5%)</li>
<li>Failed: 0/71014 (0.0%)</li>
<li>Not Supported: 30901/71014 (43.5%)</li><li>Warnings: 0/71014 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36219/71026 (51.0%)</li>
<li>Failed: 0/71026 (0.0%)</li>
<li>Not Supported: 34807/71026 (49.0%)</li><li>Warnings: 0/71026 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
I wonder if we shouldn't lower 64-bit values far earlier in the compile pipeline, given some of the additional complexity that's related to them.

Anyway, while I'm currently not able to follow everything in detail, I'm okay with the change.

**Pull request merged**
