### PR TITLE
Remove the register group USER_ACCUM

### PR DESCRIPTION
**Pull request by amdrexu**
This is now managed by PAL not by compiler.

Change-Id: Ib049eaa8776558efda427eec9cba808f6802a3e2

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8ba54c8cef8fb362b554ed0306751d31e5056f19
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev b638e90ca4e6e5a6fc4f00029d62f8e064aa18eb</li>
<li>SPVGEN: dev 6c2f36bcf0f8ff7ba8d20c8b789ca6346d1e16b1</li>
<li>XGL: dev 89a4cf115b9a2972ff00e2fe4959f4f1c8e7175b</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c20ba7614ecdc78b3d99601423783100835200c1</li>
</ul></details>

<details><summary>CTS tests (Failed: 3/266476)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 37643/66619 (56.5%)</li>
<li><details><summary>Failed: 2/66619 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_src_transfer_dst.65536
Stack trace: Script:
11:BufferCopyToBuffer Result differs from reference, Expected: 0x00000014, Got: 0x00000000, At offset: 21952


FAILURE: dEQP-VK.pipeline.extended_dynamic_state.before_draw.stencil_state_face_both_dual_ge_keep_clear_102_ref_102_pass
Stack trace: Script:
Incorrect value found in attachments; please check logged images

```
</p></details></li>

<li>Not Supported: 28974/66619 (43.5%)</li><li>Warnings: 0/66619 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 37475/66619 (56.3%)</li>
<li>Failed: 0/66619 (0.0%)</li>
<li>Not Supported: 29143/66619 (43.7%)</li><li>Warnings: 1/66619 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 38643/66619 (58.0%)</li>
<li>Failed: 0/66619 (0.0%)</li>
<li>Not Supported: 27976/66619 (42.0%)</li><li>Warnings: 0/66619 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 41268/66619 (61.9%)</li>
<li><details><summary>Failed: 1/66619 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.framebuffer_attachment.no_attachments_ms
Stack trace: Script:
Fail

```
</p></details></li>

<li>Not Supported: 25350/66619 (38.1%)</li><li>Warnings: 0/66619 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by vettoreldaniele** [comment]
Are these changes safe to use with an older version of XGL or should they be guarded with a version bump?

**Comment by amdrexu** [comment]
> Are these changes safe to use with an older version of XGL or should they be guarded with a version bump?

Yes, very safe. This register group is for performance tracking. The support are added when PAL does GFX11 bringup. We make duplicate and unnecessary efforts in compiler. Should be very old codes to remove.

**Review by trenouf — COMMENTED** [review]
LGTM, but you have conflicts.

**Review by linqun — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 7aa655221998d5778b41b853be0006e02b2a240b
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev b638e90ca4e6e5a6fc4f00029d62f8e064aa18eb</li>
<li>SPVGEN: dev 6c2f36bcf0f8ff7ba8d20c8b789ca6346d1e16b1</li>
<li>XGL: dev 89a4cf115b9a2972ff00e2fe4959f4f1c8e7175b</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev b439932ec28c68cd68daf8420cc649c18f9fe955</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/199929)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 37585/66643 (56.4%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 29058/66643 (43.6%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 37436/66643 (56.2%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 29207/66643 (43.8%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 38645/66643 (58.0%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 27998/66643 (42.0%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
