### PR TITLE
Use llvm intrinsic smin, smax, umin and umax instead of icmp and select

### PR DESCRIPTION
**Pull request by petar-avramovic**
LLVM IR intrinsics were introduced in D84125.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by Flakebi** [comment]
ok to test (← comment to run Jenkins test)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 514bea1a1051cd575bfa780331f71db3b80d739c
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 1e61f9ab6eb2041c73d7e7bd8f2021fa05a4bdd8</li>
<li>SPVGEN: dev 7c1cf34dd7eb4d3a6e6652c26292eef1bfcbcaf0</li>
<li>XGL: dev 3237b046add2809634e7f5f3fcdea1af4ad6613d</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 294f18dfb21b21ca76f4b742bffa3177babe46ff</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/224557)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 26814/56120 (47.8%)</li>
<li>Failed: 0/56120 (0.0%)</li>
<li>Skipped: 29306/56120 (52.2%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26813/56120 (47.8%)</li>
<li><details><summary>Failed: 1/56120 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.texture.explicit_lod.2d.sizes.128x128_linear_linear_mipmap_nearest_clamp
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 29306/56120 (52.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 25403/56197 (45.2%)</li>
<li>Failed: 0/56197 (0.0%)</li>
<li>Skipped: 30794/56197 (54.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 26829/56120 (47.8%)</li>
<li>Failed: 0/56120 (0.0%)</li>
<li>Skipped: 29291/56120 (52.2%)</li>
</ul></details>


</ul></details>

**Comment by piotrAMD** [comment]
LGTM.

**Review by piotrAMD — APPROVED** [review]

**Comment by jayfoad** [comment]
Can you please do the same for:
GLSLstd450UClamp
GLSLstd450SClamp
UMin3AMD
UMax3AMD
UMid3AMD
SMin3AMD
SMax3AMD
SMid3AMD

It can be a separate PR if you like.

**Review by jayfoad — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8dbc47cc9d09a8385675016c9f34458203829293
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 1e61f9ab6eb2041c73d7e7bd8f2021fa05a4bdd8</li>
<li>SPVGEN: dev 7c1cf34dd7eb4d3a6e6652c26292eef1bfcbcaf0</li>
<li>XGL: dev 3237b046add2809634e7f5f3fcdea1af4ad6613d</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 294f18dfb21b21ca76f4b742bffa3177babe46ff</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/224557)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 26814/56120 (47.8%)</li>
<li>Failed: 0/56120 (0.0%)</li>
<li>Skipped: 29306/56120 (52.2%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26814/56120 (47.8%)</li>
<li>Failed: 0/56120 (0.0%)</li>
<li>Skipped: 29306/56120 (52.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 25403/56197 (45.2%)</li>
<li>Failed: 0/56197 (0.0%)</li>
<li>Skipped: 30794/56197 (54.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 26829/56120 (47.8%)</li>
<li>Failed: 0/56120 (0.0%)</li>
<li>Skipped: 29291/56120 (52.2%)</li>
</ul></details>


</ul></details>

**Pull request merged**
