### PR TITLE
Fix physical buffer pointer in push constants

### PR DESCRIPTION
**Pull request by xuechen417**
Fix assertion in dEQP-VK.memory_model.message_passing.ext.u32.\*physbuffer\*
- Try to unspill a push constant element that is a physical buffer pointer. The problem is that getPrimitiveSizeInBits() does not work on a pointer, because the size of a pointer depends on the IR module’s data layout. Instead, we have to get its size in bytes with DataLayout::getTypeAllocSize().
- Another change is a bit lower down to cope with trying to bitcast the shader user data input to the physical buffer pointer

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 394d553968da1cfb1f01b2a4d654c1d1ee596bcd
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev d128e79bf98557761304e6aa46ba143fffb551d8</li>
<li>SPVGEN: dev 6205d0b42ebec5c8c01ff41e97fe51b56aa67343</li>
<li>XGL: dev d34fcbf7a0a5755cbac7b27c5784b7ed6782e4c2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev b3a0782762d195b57a2bebaabca24be90a35db2a</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/441729)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 147197/147197 (100.0%)</li>
<li>Failed: 0/147197 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 147241/147241 (100.0%)</li>
<li>Failed: 0/147241 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 147291/147291 (100.0%)</li>
<li>Failed: 0/147291 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by xuechen417** [comment]
Fixed PhiWithArgument.lgc failing.

**Comment by amdvlk-admin** [comment]
### Test summary for commit e3d4c45afca2aeec1f5629c260b4411b049ac112
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev b30561984a7b697ed7c709be76ff2e4d30532728</li>
<li>SPVGEN: dev b28e58f562591f335b9a3b5ae7e578a426df210b</li>
<li>XGL: dev 9bcc23fb29dab0b7ed1ebff17f3e99ae4da0bdf9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev b3a0782762d195b57a2bebaabca24be90a35db2a</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/441732)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 147198/147198 (100.0%)</li>
<li>Failed: 0/147198 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 147242/147242 (100.0%)</li>
<li>Failed: 0/147242 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 147292/147292 (100.0%)</li>
<li>Failed: 0/147292 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
Thanks Xue for pushing this through.

LGTM, but maybe someone else should approve as I suggested the change.

**Pull request merged**
