### PR TITLE
Fix problems with out-of-range shift amounts

### PR DESCRIPTION
**Pull request by jayfoad**
In SPIR-V the result of a shift with an out-of-range shift amount is an undefined value. In LLVM IR it is poison, which is more undefined. To avoid correctness problems, mask the shift amount in IR so that it is always in-range.

This is prompted by some recent LLVM patches which optimize poison values more aggressively, and triggered a Vulkan CTS test failure in dEQP-VK.graphicsfuzz.cov-fold-shift-gte32.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9163a693a2b3aba2fe9b0d6eb4e27629485c6bea
<details><summary>CTS tests (Failed: 0/211360)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35147/70459 (49.9%)</li>
<li>Failed: 0/70459 (0.0%)</li>
<li>Not Supported: 35312/70459 (50.1%)</li><li>Warnings: 0/70459 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39024/70457 (55.4%)</li>
<li>Failed: 0/70457 (0.0%)</li>
<li>Not Supported: 31433/70457 (44.6%)</li><li>Warnings: 0/70457 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39058/70444 (55.4%)</li>
<li>Failed: 0/70444 (0.0%)</li>
<li>Not Supported: 31386/70444 (44.6%)</li><li>Warnings: 0/70444 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — DISMISSED** [review]
Still not directly using the bitwise AND, I see ;) But it's fine either way.

**Comment by jayfoad** [comment]
> Still not directly using the bitwise AND, I see ;)

I still don't understand how and where non-power-of-two integer types are banned.

**Comment by nhaehnle** [comment]
The Validation Rules section of the SPIR-V spec says:

> Data rules
> * Scalar floating-point types must be parameterized only as 32 bit, plus any additional sizes enabled by [capabilities](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Capability).
> * Scalar integer types must be parameterized only as 32 bit, plus any additional sizes enabled by [capabilities](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Capability).
> * Vector types must be parameterized only with numerical types or the [OpTypeBool](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpTypeBool) type.
> * Vector types must be parameterized only with 2, 3, or 4 components, plus any additional sizes enabled by [capabilities](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Capability).
> * Matrix types must be parameterized only with floating-point types.
> * Matrix types must be parameterized only with 2, 3, or 4 columns.

And there aren't any capabilities for non-POT integer sizes.

**Comment by jayfoad** [comment]
Now using `and` instead of `urem`.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 63118ff420766b8665519d4fcfb354890c27eefb
<details><summary>CTS tests (Failed: 0/211363)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35147/70459 (49.9%)</li>
<li>Failed: 0/70459 (0.0%)</li>
<li>Not Supported: 35312/70459 (50.1%)</li><li>Warnings: 0/70459 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39026/70460 (55.4%)</li>
<li>Failed: 0/70460 (0.0%)</li>
<li>Not Supported: 31434/70460 (44.6%)</li><li>Warnings: 0/70460 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39058/70444 (55.4%)</li>
<li>Failed: 0/70444 (0.0%)</li>
<li>Not Supported: 31386/70444 (44.6%)</li><li>Warnings: 0/70444 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
