### PR TITLE
Add inliner pass for GPURT library

### PR DESCRIPTION
**Pull request by LLJJDD**
Move all linkage setting into SpirvProcessGpuRtLibrary pass, and add an inliner pass at the end of GPURT library creation.

### CODE REVIEW

**Review by nhaehnle — DISMISSED** [review]
LGTM

**Comment by qiaojbao** [comment]
17:19:20  /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/llpc/lower/llpcSpirvLowerRayQuery.cpp: In member function ‘void Llpc::SpirvLowerRayQuery::processLibraryFunction(llvm::Function*&)’:
17:19:20  /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/llpc/lower/llpcSpirvLowerRayQuery.cpp:332:7: error: ‘mangledName’ was not declared in this scope
17:19:20    332 |   if (mangledName.startswith(RtName::GetStaticId)) {
17:19:20        |       ^~~~~~~~~~~
17:19:21  [2858/3097] Building CXX object compiler/llpc/CMakeFiles/llpcinternal.dir/lower/llpcSpirvLowerRayQueryPostInline.cpp.o
17:19:21  [2859/3097] Building CXX object compiler/llpc/CMakeFiles/llpcinternal.dir/util/llpcError.cpp.o
17:19:22  [2860/3097] Building CXX object compiler/llpc/CMakeFiles/llpcinternal.dir/lower/llpcSpirvLowerRayTracingBuiltIn.cpp.o

**Review by nhaehnle — APPROVED** [review]

**Comment by Flakebi** [comment]
There seems to be a failing assertion in `shaderdb/general/PipelineRays_TestLgcRtTraceRayOp.pipe` (not visible in the log but I’m guessing as builds with assertions off are succeeding).

**Comment by LLJJDD** [comment]
> There seems to be a failing assertion in `shaderdb/general/PipelineRays_TestLgcRtTraceRayOp.pipe` (not visible in the log but I’m guessing as builds with assertions off are succeeding).

Thanks for pointing out! I fix that. (GpurtShim misses some entries)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 285a4edbf68ecb1b2c4ce773af7269ce0eed325d
<details><summary>CTS tests (Failed: 123/211363)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 8.9, Gfx10</summary><ul>

<li>Passed: 35026/70459 (49.7%)</li>
<li><details><summary>Failed: 123/70459 (0.2%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.binding_model.buffer_device_address.set3.depth1.baseubo.crossconvertu2p.store.replay.scalar.frag
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.mutable_descriptor.single.storage_image.update_copy.nonmutable_source.normal_source.pool_expand_types.update_after_bind.no_array.tesc
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.shader_access.primary_cmd_buf.with_push.sampler_mutable.compute.single_descriptor.2d_base_slice
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.shader_access.secondary_cmd_buf.combined_image_sampler_immutable.vertex.descriptor_array.1d_array_base_mip
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.shader_access.secondary_cmd_buf.with_template.combined_image_sampler_mutable.tess_ctrl.multiple_arbitrary_descriptors.2d
Stack trace: Flake

FAILURE: dEQP-VK.clipping.clip_volume.inside.line_list
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_cull_distance.vert.8
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_distance.vert_geom.2_fragmentshader_read
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.alias.u8_to_i8_std140
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.zero.uint8_t_array_to_bool_uint16_t_array_3
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.zero.uint8_t_array_to_uvec3_bool_array_4
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.dispatch.condition_host_memory_inherited_expect_noop_inverted.dispatch_indirect
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.draw.condition_host_memory_expect_noop.draw_indexed
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.draw.condition_host_memory_expect_noop.draw_indexed_indirect
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.draw_clear.clear.color.discard_no_invert_partial_no_offset_host_memory
Stack trace: Flake

FAILURE: dEQP-VK.fragment_operations.transient_attachment_bit.depth_load_store_op_test_local_bit
Stack trace: Flake

FAILURE: dEQP-VK.fragment_shading_barycentric.data.provoking_last.dynamic.line_strip_with_adjacency.type.dvec4
Stack trace: Flake

FAILURE: dEQP-VK.fragment_shading_barycentric.weights.pipeline_topology_dynamic.msaa_sample_qualifier.line_strip_with_adjacency.noperspective
Stack trace: Flake

FAILURE: dEQP-VK.glsl.builtin.precision.dot.mediump.vec3
Stack trace: Flake

FAILURE: dEQP-VK.glsl.builtin_var.fragcoord_msaa_input.8_bit
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 35310/70459 (50.1%)</li><li>Warnings: 0/70459 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39026/70460 (55.4%)</li>
<li>Failed: 0/70460 (0.0%)</li>
<li>Not Supported: 31434/70460 (44.6%)</li><li>Warnings: 0/70460 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39058/70444 (55.4%)</li>
<li>Failed: 0/70444 (0.0%)</li>
<li>Not Supported: 31386/70444 (44.6%)</li><li>Warnings: 0/70444 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by LLJJDD** [comment]
retest this please

**Review by nhaehnle — APPROVED** [review]

**Pull request merged**
