### PR TITLE
Dialectify and refactor userdata accessors

### PR DESCRIPTION
**Pull request by nhaehnle**
This is a first sequence of changes for refactoring how we access PAL userdata and handle resource mappings, built on PR #2620. The first real commit belonging to this PR is [lgc/PatchEntryPointMutate: cleanup the "compute with calls" detection](https://github.com/GPUOpen-Drivers/llpc/commit/6c99e818832dd26a134732b505c6350223756103).

By PAL userdata, we mean the userdata as seen in the interface between the driver and PAL, as described by the offsets and sizes of top-level nodes in the resource mapping. (This is distinct from the SPI USER_DATA registers of the hardware that lead to initialization values for SGPRs at wave launch: a subset of the PAL userdata is mapped to SPI USER_DATA registers; but also additional, non-PAL userdata values can be written into SPI USER_DATA; those are certain system values such as the draw ID or dispatch size pointer.)

The fundamental underlying idea is that referencing PAL userdata will be layered in two levels of abstraction:

1. The low level allows access to raw userdata dwords using `lgc.user.data` and `lgc.load.user.data` ops.
2. The high level allows access in terms of descriptors identified by set and binding, push constants, etc.

Only the higher level will make use of the resource mapping for most purposes. (This may not be entirely true for a while: the lower level does need to know the overall size of the PAL userdata, and where push constants start.)

This sequence of changes lays most of the ground work. A follow-up change will also replace `lgc.descriptor.table.addr` by uses of `lgc.load.user.data`.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2063d944a569c87248c63e54a87aaaa736a9b9e4
<details><summary>CTS tests (Failed: 0/211876)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70631 (50.3%)</li>
<li>Failed: 0/70631 (0.0%)</li>
<li>Not Supported: 35135/70631 (49.7%)</li><li>Warnings: 0/70631 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39379/70629 (55.8%)</li>
<li>Failed: 0/70629 (0.0%)</li>
<li>Not Supported: 31250/70629 (44.2%)</li><li>Warnings: 0/70629 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70616 (55.8%)</li>
<li>Failed: 0/70616 (0.0%)</li>
<li>Not Supported: 31203/70616 (44.2%)</li><li>Warnings: 0/70616 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
Rebase to resolve conflicts and after pushing the dependency PR. It should be easier to review now :)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 06b03e1c4a982a3232ed021508330c7c119a0a45
<details><summary>CTS tests (Failed: 0/211879)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70631 (50.3%)</li>
<li>Failed: 0/70631 (0.0%)</li>
<li>Not Supported: 35135/70631 (49.7%)</li><li>Warnings: 0/70631 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39381/70632 (55.8%)</li>
<li>Failed: 0/70632 (0.0%)</li>
<li>Not Supported: 31251/70632 (44.2%)</li><li>Warnings: 0/70632 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70616 (55.8%)</li>
<li>Failed: 0/70616 (0.0%)</li>
<li>Not Supported: 31203/70616 (44.2%)</li><li>Warnings: 0/70616 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
Ping for review

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
