### PR TITLE
Cleanup includes in llpcPatch. NFC.

### PR DESCRIPTION
**Pull request by kuhar**

### CODE REVIEW

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by kuhar** [comment]
Ping. What happened with Jenkins here?

**Comment by JacobHeAMD** [comment]
Failures:
```
FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.uniform_float_16_to_64.uniform_buffer_block_scalar_float_const_idx_4_vert
Stack trace: Timeout or crahsed
```

**Comment by kuhar** [comment]
@JacobHeAMD can this be caused by just changing the includes?

**Comment by JacobHeAMD** [comment]
What does "includes" mean? Do you mean exclude dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.uniform_float_16_to_64.uniform_buffer_block_scalar_float_const_idx_4_vert from test list?

**Comment by kuhar** [comment]
This patch is supposed to be purely cosmetic and use `"` for including llvm headers. I expect it to include include exactly the same headers in exactly the same order, and produce exactly the same file after preprocessing.
I'm suprised to see any change in LLPC's behavior, and even more suprised to see a new test failure.

**Comment by JacobHeAMD** [comment]
Right, but we can't conclude that it's same llvm header files yet. Let me check it further.

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by JacobHeAMD** [comment]
I've logged on the Navi10 agent, and run the test manually, the issue is not seen. I'm not sure why it was segfault? Let's trigger a new test to see if the issue is gone?

**Comment by amdvlk-admin** [comment]
### Test summary for commit aed26216b3677d9c2bfe33369ebd5173945e21b2
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 831f334a9f4ef429b5d4e953b86b4624a7c2db54</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 54a1ba508fd82ed2a11d0960f0f2f35f975b2f12</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev cc9adb37fb5f602ddef382813fcbc1c0eac7a24a</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
All tests passed. I will do pull request.

Thanks,
Jax

**Pull request merged**
