### PR TITLE
Set wave size for color export shader

### PR DESCRIPTION
**Pull request by AMD-dwang**
1. If enable dual source blend, color export shader will depends on wavesize.

2. Fix an issue that when ResourceNodeType::DescriptorBufferCompact is root node, we also need to fix up the register.

### CODE REVIEW

**Comment by AMD-dwang** [comment]
PatchSetupTargetFeatures pass contains more attributes, and in some cases we may need to set additional attributes, can we add this pass to passManager in PassManagerCache::getPassManager?

**Comment by nhaehnle** [comment]
> PatchSetupTargetFeatures pass contains more attributes, and in some cases we may need to set additional attributes, can we add this pass to passManager in PassManagerCache::getPassManager?

Yes, I think that's a good idea!

**Comment by ruiling** [comment]
I would suggest you split the change into several git commits. If we get some regression report, it would be easy to determine which part of code change cause the regression.

**Comment by AMD-dwang** [comment]
> I would suggest you split the change into several git commits. If we get some regression report, it would be easy to determine which part of code change cause the regression.

Okay. I will split this into two commits.

**Comment by amdvlk-admin** [comment]
### Test summary for commit ade5ba45ee58079523d8e70d7c4376ef4cc41542
<details><summary>CTS tests (Failed: 0/211498)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39250/70506 (55.7%)</li>
<li>Failed: 0/70506 (0.0%)</li>
<li>Not Supported: 31256/70506 (44.3%)</li><li>Warnings: 0/70506 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39498/70495 (56.0%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 30997/70495 (44.0%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36345/70497 (51.6%)</li>
<li>Failed: 0/70497 (0.0%)</li>
<li>Not Supported: 34152/70497 (48.4%)</li><li>Warnings: 0/70497 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
Thanks, LGTM

**Comment by AMD-dwang** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6f050554a22c0bf1cd9f2527da7588c37ec7d05f
<details><summary>CTS tests (Failed: 0/211487)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39248/70495 (55.7%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 31247/70495 (44.3%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39498/70495 (56.0%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 30997/70495 (44.0%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36345/70497 (51.6%)</li>
<li>Failed: 0/70497 (0.0%)</li>
<li>Not Supported: 34152/70497 (48.4%)</li><li>Warnings: 0/70497 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
