### PR TITLE
lgc/patch: some cleanups in the pass pipeline

### PR DESCRIPTION
**Pull request by nhaehnle**
Separate commits with:

* minor functional change of moving the IPSCCP pass out of the way
* cleanup comments

### CODE REVIEW

**Comment by nhaehnle** [comment]
> > To be honest, it's kind of unclear to me why we're using this pass in
> > the first place. Is there any example where we compile anything that
> > could benefit from generic inter-procedural constant propagation?
> 
> As far as I know, the only practical benefit of running it is to avoid adding unnecessary arguments to an entry point. Perhaps we can move some of the logic to EntryPointMutate itself, and remove IPSCCP pass.

How does IPSCCP help remove arguments of an entry-point, though? The pass pipeline previously had it before PatchEntryPointMutate. Before that pass, entry-points don't even have arguments.

(Interestingly, the pass does have an effect of propagating undefs, hence the test fix which I'd missed before.)

Maybe something with true function calls?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 11561fcc6c7c48224aad2b8492fe3b47e81ad74e
<details><summary>CTS tests (Failed: 0/216059)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35298/73410 (48.1%)</li>
<li>Failed: 0/73410 (0.0%)</li>
<li>Not Supported: 38112/73410 (51.9%)</li><li>Warnings: 0/73410 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33017/69239 (47.7%)</li>
<li>Failed: 0/69239 (0.0%)</li>
<li>Not Supported: 36222/69239 (52.3%)</li><li>Warnings: 0/69239 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37553/73410 (51.2%)</li>
<li>Failed: 0/73410 (0.0%)</li>
<li>Not Supported: 35857/73410 (48.8%)</li><li>Warnings: 0/73410 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 11561fcc6c7c48224aad2b8492fe3b47e81ad74e
<details><summary>CTS tests (Failed: 0/216059)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35298/73410 (48.1%)</li>
<li>Failed: 0/73410 (0.0%)</li>
<li>Not Supported: 38112/73410 (51.9%)</li><li>Warnings: 0/73410 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33017/69239 (47.7%)</li>
<li>Failed: 0/69239 (0.0%)</li>
<li>Not Supported: 36222/69239 (52.3%)</li><li>Warnings: 0/69239 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37553/73410 (51.2%)</li>
<li>Failed: 0/73410 (0.0%)</li>
<li>Not Supported: 35857/73410 (48.8%)</li><li>Warnings: 0/73410 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5bde2e2b2bae072f121379a02f98742831e3d407
<details><summary>CTS tests (Failed: 0/216059)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35298/73410 (48.1%)</li>
<li>Failed: 0/73410 (0.0%)</li>
<li>Not Supported: 38112/73410 (51.9%)</li><li>Warnings: 0/73410 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33017/69239 (47.7%)</li>
<li>Failed: 0/69239 (0.0%)</li>
<li>Not Supported: 36222/69239 (52.3%)</li><li>Warnings: 0/69239 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37553/73410 (51.2%)</li>
<li>Failed: 0/73410 (0.0%)</li>
<li>Not Supported: 35857/73410 (48.8%)</li><li>Warnings: 0/73410 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5bde2e2b2bae072f121379a02f98742831e3d407
<details><summary>CTS tests (Failed: 0/216059)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35298/73410 (48.1%)</li>
<li>Failed: 0/73410 (0.0%)</li>
<li>Not Supported: 38112/73410 (51.9%)</li><li>Warnings: 0/73410 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33017/69239 (47.7%)</li>
<li>Failed: 0/69239 (0.0%)</li>
<li>Not Supported: 36222/69239 (52.3%)</li><li>Warnings: 0/69239 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37553/73410 (51.2%)</li>
<li>Failed: 0/73410 (0.0%)</li>
<li>Not Supported: 35857/73410 (48.8%)</li><li>Warnings: 0/73410 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by piotrAMD** [comment]
> How does IPSCCP help remove arguments of an entry-point, though? The pass pipeline previously had it before PatchEntryPointMutate. Before that pass, entry-points don't even have arguments.
> 
> (Interestingly, the pass does have an effect of propagating undefs, hence the test fix which I'd missed before.)

I'd been mainly looking at the effects of removing IPSCCP and noticed that with IPSCCP removed in some cases we enter the codegen with IR containing an entry point (e.g. _amdgpu_ps_main) with input attributes (e.g. pushConst0), which are never accessed in the body of the function.

I did not look at the specific reasons for these effects, and it looks likely we can fix that elsewhere.

**Review by piotrAMD — APPROVED** [review]

**Review by piotrAMD — APPROVED** [review]

**Review by piotrAMD — APPROVED** [review]

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
