### PR TITLE
Remove PatchImageOpCollect pass

### PR DESCRIPTION
**Pull request by kuhar**
This pass is unused and does not compile.

Fixes: https://github.com/GPUOpen-Drivers/llpc/issues/1252

### CODE REVIEW

**Review by amdrexu — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 876fdcc5d17aa74bc5b68cb795bd93f3a64a0b5b
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 9786fa8c34df6d9baddeff40d331106799fcbb07</li>
<li>SPVGEN: dev 5bf4618ac00d4675f57ca5b571a485bbc4d4fa33</li>
<li>XGL: dev 9b77f6008d4316922cde45baf39d079b4d328893</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1b94c3bf02ef6b638e199aa5c41d2fa31ea5455d</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/225557)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30786/56392 (54.6%)</li>
<li>Failed: 0/56392 (0.0%)</li>
<li>Not Supported: 25606/56392 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30785/56392 (54.6%)</li>
<li>Failed: 0/56392 (0.0%)</li>
<li>Not Supported: 25607/56392 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30917/56381 (54.8%)</li>
<li>Failed: 0/56381 (0.0%)</li>
<li>Not Supported: 25464/56381 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34386/56392 (61.0%)</li>
<li><details><summary>Failed: 1/56392 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.glsl.shader_clock.compute.clockARB
Stack trace: Script:
Result comparison failed

```
</p></details></li>

<li>Not Supported: 22005/56392 (39.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5c477261f8d779a282ea76f2416854302e88bff2
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 9786fa8c34df6d9baddeff40d331106799fcbb07</li>
<li>SPVGEN: dev 5bf4618ac00d4675f57ca5b571a485bbc4d4fa33</li>
<li>XGL: dev 9b77f6008d4316922cde45baf39d079b4d328893</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1b94c3bf02ef6b638e199aa5c41d2fa31ea5455d</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/225557)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30786/56392 (54.6%)</li>
<li>Failed: 0/56392 (0.0%)</li>
<li>Not Supported: 25606/56392 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30785/56392 (54.6%)</li>
<li>Failed: 0/56392 (0.0%)</li>
<li>Not Supported: 25607/56392 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30917/56381 (54.8%)</li>
<li>Failed: 0/56381 (0.0%)</li>
<li>Not Supported: 25464/56381 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34387/56392 (61.0%)</li>
<li>Failed: 0/56392 (0.0%)</li>
<li>Not Supported: 22005/56392 (39.0%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
@amdrexu @trenouf Ping. Could we get this merged?

**Comment by amdrexu** [comment]
@kuhar Jax is responsible for merging this.
@JaxLinAMD Could you please merge this PR? Thanks.

**Comment by kuhar** [comment]
Ping. @JaxLinAMD

**Pull request merged**
