### PR TITLE
NGG coding rework: Move two members out of NGG inputs

### PR DESCRIPTION
**Pull request by amdrexu**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2c6bb6ccb2cb7d400cf6451b201002e99ebb6129
<details><summary>CTS tests (Failed: 3/277947)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70526 (55.1%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31662/70526 (44.9%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39111/70526 (55.5%)</li>
<li><details><summary>Failed: 3/70526 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.0_00
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31412/70526 (44.5%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70528 (51.0%)</li>
<li>Failed: 0/70528 (0.0%)</li>
<li>Not Supported: 34569/70528 (49.0%)</li><li>Warnings: 0/70528 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66367 (50.7%)</li>
<li>Failed: 0/66367 (0.0%)</li>
<li>Not Supported: 32689/66367 (49.3%)</li><li>Warnings: 0/66367 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2c6bb6ccb2cb7d400cf6451b201002e99ebb6129
<details><summary>CTS tests (Failed: 0/277948)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70526 (55.1%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31662/70526 (44.9%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70526 (55.5%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31412/70526 (44.5%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70528 (51.0%)</li>
<li>Failed: 0/70528 (0.0%)</li>
<li>Not Supported: 34569/70528 (49.0%)</li><li>Warnings: 0/70528 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66368 (50.7%)</li>
<li>Failed: 0/66368 (0.0%)</li>
<li>Not Supported: 32690/66368 (49.3%)</li><li>Warnings: 0/66368 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
+1 for also using more PoisonValue

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0cfacc9fa54a486678318c87342c31c3c791e3ce
<details><summary>CTS tests (Failed: 3/283117)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70780 (54.9%)</li>
<li>Failed: 0/70780 (0.0%)</li>
<li>Not Supported: 31916/70780 (45.1%)</li><li>Warnings: 0/70780 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39111/70780 (55.3%)</li>
<li><details><summary>Failed: 3/70780 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_4.triangles.degenerate.0_00
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_4.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_4.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31666/70780 (44.7%)</li><li>Warnings: 0/70780 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70782 (50.8%)</li>
<li>Failed: 0/70782 (0.0%)</li>
<li>Not Supported: 34823/70782 (49.2%)</li><li>Warnings: 0/70782 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 35861/70775 (50.7%)</li>
<li>Failed: 0/70775 (0.0%)</li>
<li>Not Supported: 34914/70775 (49.3%)</li><li>Warnings: 0/70775 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0cfacc9fa54a486678318c87342c31c3c791e3ce
<details><summary>CTS tests (Failed: 0/283117)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70780 (54.9%)</li>
<li>Failed: 0/70780 (0.0%)</li>
<li>Not Supported: 31916/70780 (45.1%)</li><li>Warnings: 0/70780 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70780 (55.3%)</li>
<li>Failed: 0/70780 (0.0%)</li>
<li>Not Supported: 31666/70780 (44.7%)</li><li>Warnings: 0/70780 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70782 (50.8%)</li>
<li>Failed: 0/70782 (0.0%)</li>
<li>Not Supported: 34823/70782 (49.2%)</li><li>Warnings: 0/70782 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 35861/70775 (50.7%)</li>
<li>Failed: 0/70775 (0.0%)</li>
<li>Not Supported: 34914/70775 (49.3%)</li><li>Warnings: 0/70775 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
