### PR TITLE
llpc/raytracing: fuse two loops over shader modules

### PR DESCRIPTION
**Pull request by nhaehnle**
There doesn't seem to be a reason to iterate twice. Using a single loop makes the code clearer and easier to maintain, and may have a small side benefit of compile-time improvement via better cache locality.

I'm also removing some pointless comments that only describe *what* the next line does (without going into the *why*).

### CODE REVIEW

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
| Test Result (658 failures  / -3)dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.regular.chitdEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.regular.missdEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.regular.rgendEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push.chitdEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push.missdEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push.rgendEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push_template.chitdEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push_template.missdEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push_template.rgendEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_template.chitdEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_template.missdEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_template.rgendEQP-VK.ray_query.acceleration_structures.format.miss_shader.gpu_built.r16g16_snorm.nopadding.index_uint16dEQP-VK.ray_query.acceleration_structures.format.miss_shader.gpu_built.r16g16b16a16_snorm.padded.index_uint32dEQP-VK.ray_query.acceleration_structures.format.miss_shader.gpu_built.r32g32_sfloat.nopadding.index_nonedEQP-VK.ray_query.acceleration_structures.instance_triangle_culling.miss_shader.gpu_built.index_uint16.notransform_ccwdEQP-VK.ray_query.acceleration_structures.instance_triangle_culling.miss_shader.gpu_built.index_uint32.notransform_ccw_noculldEQP-VK.ray_query.ray_flags.miss_shader.opacity.aabbs.cullnoopaquedEQP-VK.ray_query.ray_flags.miss_shader.opacity.aabbs.none
-- | --


[Test Result](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/) (658 failures / -3)

    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.regular.chit](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/regular/chit/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.regular.miss](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/regular/miss/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.regular.rgen](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/regular/rgen/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push.chit](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/with_push/chit/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push.miss](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/with_push/miss/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push.rgen](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/with_push/rgen/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push_template.chit](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/with_push_template/chit/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push_template.miss](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/with_push_template/miss/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_push_template.rgen](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/with_push_template/rgen/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_template.chit](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/with_template/chit/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_template.miss](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/with_template/miss/)
    [dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing.with_template.rgen](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_tracing/with_template/rgen/)
    [dEQP-VK.ray_query.acceleration_structures.format.miss_shader.gpu_built.r16g16_snorm.nopadding.index_uint16](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.ray_query.acceleration_structures.format.miss_shader.gpu_built.r16g16_snorm/nopadding/index_uint16/)
    [dEQP-VK.ray_query.acceleration_structures.format.miss_shader.gpu_built.r16g16b16a16_snorm.padded.index_uint32](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.ray_query.acceleration_structures.format.miss_shader.gpu_built.r16g16b16a16_snorm/padded/index_uint32/)
    [dEQP-VK.ray_query.acceleration_structures.format.miss_shader.gpu_built.r32g32_sfloat.nopadding.index_none](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.ray_query.acceleration_structures.format.miss_shader.gpu_built.r32g32_sfloat/nopadding/index_none/)
    [dEQP-VK.ray_query.acceleration_structures.instance_triangle_culling.miss_shader.gpu_built.index_uint16.notransform_ccw](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.ray_query.acceleration_structures.instance_triangle_culling.miss_shader.gpu_built/index_uint16/notransform_ccw/)
    [dEQP-VK.ray_query.acceleration_structures.instance_triangle_culling.miss_shader.gpu_built.index_uint32.notransform_ccw_nocull](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.ray_query.acceleration_structures.instance_triangle_culling.miss_shader.gpu_built/index_uint32/notransform_ccw_nocull/)
    [dEQP-VK.ray_query.ray_flags.miss_shader.opacity.aabbs.cullnoopaque](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.ray_query.ray_flags.miss_shader.opacity/aabbs/cullnoopaque/)
    [dEQP-VK.ray_query.ray_flags.miss_shader.opacity.aabbs.none](http://vulkan-ci.amd.com/job/vulkan/job/sanitized-opensource/job/Github-PR/job/llpc-github-pr/1080/testReport/junit/dEQP-VK.ray_query.ray_flags.miss_shader.opacity/aabbs/none/)

**Comment by jiaolu** [comment]
i remember the raytracing context would need to collect information in the first loop.
collectBuiltIn
collectPayloadSize
collectCallableDataSize

**Comment by nhaehnle** [comment]
Thanks for that background. That is indeed at least one issue with my attempted change.

* collectPayloadSize / collectCallableDataSize: These surprise me. I thought there was a rule that the payload types have to match?
* collectBuiltIn: This seems mostly like an optimization -- but an important one.

I'm going to drop this for now, may revisit later.

**Pull request closed without merging**
