### PR TITLE
Discard OpStore to NonWritable memory declarations.

### PR DESCRIPTION
**Pull request by perlfu**
Apparently some SPIRV generators can output this (probably illegal) sequence where constant buffers are written with their initializer.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1bf614bfcbed88cd561794073ba36b03e942540c
<details><summary>CTS tests (Failed: 0/213076)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71028 (56.9%)</li>
<li>Failed: 0/71028 (0.0%)</li>
<li>Not Supported: 30602/71028 (43.1%)</li><li>Warnings: 0/71028 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71018 (57.0%)</li>
<li>Failed: 0/71018 (0.0%)</li>
<li>Not Supported: 30554/71018 (43.0%)</li><li>Warnings: 0/71018 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36471/71030 (51.3%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 34559/71030 (48.7%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by dstutt** [comment]
Do you know which generator has done this? (Just curious).

**Review by nhaehnle — COMMENTED** [review]
How annoying. Please adjust the comment to explicitly mention that stores to non-writable memory are not allowed, but unfortunately there is code out there that does this.

**Comment by perlfu** [comment]
> How annoying. Please adjust the comment to explicitly mention that stores to non-writable memory are not allowed, but unfortunately there is code out there that does this.

Comments updated.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2f2a529b08dcf9dd8d0acb2b01d78ed2e57e0477
<details><summary>CTS tests (Failed: 0/213076)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71028 (56.9%)</li>
<li>Failed: 0/71028 (0.0%)</li>
<li>Not Supported: 30602/71028 (43.1%)</li><li>Warnings: 0/71028 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71018 (57.0%)</li>
<li>Failed: 0/71018 (0.0%)</li>
<li>Not Supported: 30554/71018 (43.0%)</li><li>Warnings: 0/71018 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36471/71030 (51.3%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 34559/71030 (48.7%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>


</ul></details>

**Review by dstutt — COMMENTED** [review]
This change LGTM.

**Review by nhaehnle — APPROVED** [review]

**Pull request merged**
