### PR TITLE
Add modfStruct in glslArithOpEmu.ll.

### PR DESCRIPTION
**Pull request by linqunzju**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JacobHeAMD** [comment]
ok to test

**Comment by JacobHeAMD** [comment]
test this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit ef55149617511d4f0f78ac1e50a2998b5371b234
<details open><summary>Driver branches used in build</summary><ul>

<li>PAL: _dev_</li>
<li>XGL: _dev_</li>
<li>LLVM: _amd-vulkan-dev_</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 795/795 (100.0%)</li>
<li>Failed: 0/795 (0.0%)</li>
</ul></details>

#### CTS tests (built with branch _Vulkan-CTS-1.1.1.2-cherry-picks_)
<details open><summary>ubuntu, 18-04, ellesmere</summary><ul>

<li>Passed: 312610/312610 (100.0%)</li>
<li>Failed: 0/312610 (0.0%)</li>
</ul></details>

**Pull request merged**
