### PR TITLE
[LGC] Update and disable test due to upstream LLVM changes

### PR DESCRIPTION
**Pull request by mariusz-sikora-at-amd**

### CODE REVIEW

**Review by jayfoad — APPROVED** [review]

**Comment by jayfoad** [comment]
Would be nice to mention which LLVM change caused this, in the commit message.

**Review by amdrexu — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 32e520744ed4600149e447f292b01bed3241e530
<details><summary>CTS tests (Failed: 0/211876)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35146/70631 (49.8%)</li>
<li>Failed: 0/70631 (0.0%)</li>
<li>Not Supported: 35485/70631 (50.2%)</li><li>Warnings: 0/70631 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39023/70629 (55.3%)</li>
<li>Failed: 0/70629 (0.0%)</li>
<li>Not Supported: 31606/70629 (44.7%)</li><li>Warnings: 0/70629 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39057/70616 (55.3%)</li>
<li>Failed: 0/70616 (0.0%)</li>
<li>Not Supported: 31559/70616 (44.7%)</li><li>Warnings: 0/70616 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by mariusz-sikora-at-amd** [comment]
> Would be nice to mention which LLVM change caused this, in the commit message.

Updated the commit message.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 137402bea555e9ea21f05d9febab396a86903a92
<details><summary>CTS tests (Failed: 0/211876)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35146/70631 (49.8%)</li>
<li>Failed: 0/70631 (0.0%)</li>
<li>Not Supported: 35485/70631 (50.2%)</li><li>Warnings: 0/70631 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39023/70629 (55.3%)</li>
<li>Failed: 0/70629 (0.0%)</li>
<li>Not Supported: 31606/70629 (44.7%)</li><li>Warnings: 0/70629 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39057/70616 (55.3%)</li>
<li>Failed: 0/70616 (0.0%)</li>
<li>Not Supported: 31559/70616 (44.7%)</li><li>Warnings: 0/70616 (0.0%)</li>
</ul></details>


</ul></details>

**Review by perlfu — APPROVED** [review]

**Pull request merged**
