### PR TITLE
llpc: fix image/sample/sampledImage resource collection

### PR DESCRIPTION
**Pull request by amingriyue**
1. add array size for them
2. visit them in resource collection pass in spirv lower phase.

v2:
1. switch to use Function way
2. remove array size arg

v3: improve coding style

v4: fix function iterate

Signed-off-by: Chunming Zhou <david1.zhou@amd.com>

### CODE REVIEW

**Comment by amdrexu** [comment]
I am OK with it. Let's keep it open for a few days and let other reviewers make comments.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 98c1797b0c6037c1e1d2376d111e78057d13f0e5
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 40af910391fb8c287cb37bf520c41310bf88d405</li>
<li>SPVGEN: dev ce06cb5e3116ba77a22c3278dfeadfd865a8977c</li>
<li>XGL: dev 7e13a8bd0bb57d3cfb3bc014f6b26a8c9bb8bfd9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 08268e9955d48ca075b239ae46328694ddff2413</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit a8b22d387afa96263f4801d41887daa5217a8252
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 40af910391fb8c287cb37bf520c41310bf88d405</li>
<li>SPVGEN: dev ce06cb5e3116ba77a22c3278dfeadfd865a8977c</li>
<li>XGL: dev 7e13a8bd0bb57d3cfb3bc014f6b26a8c9bb8bfd9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 08268e9955d48ca075b239ae46328694ddff2413</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 7cb6956fa7d765ce6c7ec71bcfb16a8becf36e65
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 40af910391fb8c287cb37bf520c41310bf88d405</li>
<li>SPVGEN: dev ce06cb5e3116ba77a22c3278dfeadfd865a8977c</li>
<li>XGL: dev 7e13a8bd0bb57d3cfb3bc014f6b26a8c9bb8bfd9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 08268e9955d48ca075b239ae46328694ddff2413</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
