### PR TITLE
Should use ShaderStageCount

### PR DESCRIPTION
**Pull request by jiaolu**
ShaderStageCount is more general number of the shader stages

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2b7f85e6a47748ca777b7e4af3590a9d6ec7bf4d
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 831f334a9f4ef429b5d4e953b86b4624a7c2db54</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 54a1ba508fd82ed2a11d0960f0f2f35f975b2f12</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev cc0df5ace776584f5f7c0c20704d28f445f0e074</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 39c12e46d13eff561c6b04ed54e3568649382171
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 831f334a9f4ef429b5d4e953b86b4624a7c2db54</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 54a1ba508fd82ed2a11d0960f0f2f35f975b2f12</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 0549a86140ab4e138db4f2a6ea72fbacb69bdddb</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:1289:62: error: no matching function for call to ‘llvm::IRBuilder<>::CreateMemSet(llvm::Value* const&, llvm::Value* const&, uint32_t&, int)’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:1351:62: error: no matching function for call to ‘llvm::IRBuilder<>::CreateMemSet(llvm::Value* const&, llvm::Value* const&, unsigned int, int)’

</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 39c12e46d13eff561c6b04ed54e3568649382171
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 831f334a9f4ef429b5d4e953b86b4624a7c2db54</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 54a1ba508fd82ed2a11d0960f0f2f35f975b2f12</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 0549a86140ab4e138db4f2a6ea72fbacb69bdddb</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:1289:62: error: no matching function for call to ‘llvm::IRBuilder<>::CreateMemSet(llvm::Value* const&, llvm::Value* const&, uint32_t&, int)’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:1351:62: error: no matching function for call to ‘llvm::IRBuilder<>::CreateMemSet(llvm::Value* const&, llvm::Value* const&, unsigned int, int)’

</ul></details>

**Comment by JacobHeAMD** [comment]
Please rebase the PR to the latest LLPC

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit d761449f9ccc51073f36f2325368906e89dbe422
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 831f334a9f4ef429b5d4e953b86b4624a7c2db54</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 54a1ba508fd82ed2a11d0960f0f2f35f975b2f12</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 0549a86140ab4e138db4f2a6ea72fbacb69bdddb</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
