### PR TITLE
Modularize LGC include files

### PR DESCRIPTION
**Pull request by trenouf**
(Only the top four commits belong to this PR. The others are from other PRs waiting to merge.)

This is from the top commit's commit message:

    Include files used by code in a different subdirectory in LGC are now in
    the lgc/privateInc hierarchy, and is #included with a qualified path.
    For example, PipelineState.h is now in
    lgc/privateInc/lgc/state/PipelineState.h, so that it is #included as:
      #include "lgc/state/PipelineState.h"
    
    This makes it more obvious which include files define functionality used
    from different LGC subdirectories, and makes the inclusion of them work
    in a way more like LLVM does. Unlike LLVM, we have two include
    hierachies: we have lgc/include/lgc for include files that make up the
    LGC interface used by the LLPC front-end, and a separate
    lgc/privateInc/lgc for include files not exposed to the front-end.

The other three commits are changes to prepare for that change.

### CODE REVIEW

**Comment by amdrexu** [comment]
I wonder how LLVM handles such private include files that are not public interfaces and shouldn't stay in `include`.

**Comment by trenouf** [comment]
> I wonder how LLVM handles such private include files that are not public interfaces and shouldn't stay in `include`.

LLVM is structured as a bunch of libraries (Support, IR, Analysis etc), and each one has public include files in include/llvm/<libname>, and private include files in with the .cpp files in lib/<libname>. There is no concept of an interface that is more restricted than just being able to access all libraries' public interfaces.

LGC is a bit different in that this change allows for three categories of include file:
1. Public ones that we want to expose to front-end clients
2. Ones that expose functionality of some part of LGC to other parts of LGC
3. Private ones within a single part of LGC.

**Comment by amdrexu** [comment]
Thanks for explanation. I just feel this is a little bit confusing we have two include directory, one is for public and one is for private. Can we rename them to this:
`/include -> /interface` (used by front-ends, just like our internal compiler)
`/privateInc -> /include` (header files that could be shared within LGC)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 7718daa545afdfe4a14cda934315b84d2730a98d
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev bb7398b1c7509a30ba4f7d947b5ad5549a4d58db</li>
<li>SPVGEN: dev dc2b146de03ef54f188172d8fa2f9be708cbfaca</li>
<li>XGL: dev ffd39443fec0ce821b7702173eba7184855c7b5e</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 7b14353794b408b8d7fd87ae9a9f4f553e6d4782</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 955/955 (100.0%)</li>
<li>Failed: 0/955 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103142/103142 (100.0%)</li>
<li>Failed: 0/103142 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103198/103198 (100.0%)</li>
<li>Failed: 0/103198 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 103198/103198 (100.0%)</li>
<li>Failed: 0/103198 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
> Thanks for explanation. I just feel it is a little bit confusing that we have two include directories, one is for public and one is for private. Can we rename them to this:
> `/include -> /interface` (used by front-ends, just like our internal compiler)
> `/privateInc -> /include` (header files that could be shared within LGC)

Sounds good to me.

**Comment by trenouf** [comment]
V2: interface and include, rather than include and privateInclude

Also rebased.

**Comment by trenouf** [comment]
Rebased

**Comment by trenouf** [comment]
The CTS run passed on two agents and spuriously crashed on the third, so I am going to take that as a pass.

**Pull request merged**
