### PR TITLE
Disable CS fixed user data layout restriction

### PR DESCRIPTION
**Pull request by trenouf**
PAL used to have restrictions on user data layout in a compute shader
that have now been lifted (as of PAL version 624). This commit takes
advantage of that in LGC, giving the same freedom in user data layout as
in a graphics shader.

That will be required when shader compilation is extended to compute
shaders, as the user data will not be available at compile time to apply
the restrictions.

Change-Id: I0432e35de9c255bb5bd77014bfbc92203aad4adf

### CODE REVIEW

**Comment by trenouf** [comment]
Only the topmost commit "Disable CS fixed user data layout restriction" belongs here. The other two commits are from a different PR.

**Comment by trenouf** [comment]
V2: clang-format

**Comment by amdvlk-admin** [comment]
### Test summary for commit ea820d3b781c7a3bd630c427ebe01f784e5f69e2
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev c9937b277c491a55c689eec7cdd48fb238b8004c</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev c6c90450fb1abf5f414acf1e38a0f51a72c426c1</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1598ada40008302abedfd724275329f8e7dea637</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/93899)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 24006/46960 (51.1%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 22954/46960 (48.9%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>No Results</li>

</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 22647/46939 (48.2%)</li>
<li>Failed: 0/46939 (0.0%)</li>
<li>Skipped: 24292/46939 (51.8%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM (for the last commit)

**Comment by trenouf** [comment]
V3: Rebase so it is no longer on top of compute library change.
For testing purposes, temporarily still use fixed layout.

**Comment by trenouf** [comment]
(Converted to draft because of that temporary change to still use fixed layout.)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3d943ca4b9becfd100bfb95ab5597a4665941d61
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 007816f4bd2fd3ace30f8af9629cff7ec1dcb998</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev b25c1eac19f1773b753ed727314aa3cf2c0897dd</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev e09ed8b4a5ed4201e59b8d5dc66e17dd05eca428</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/140859)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26166/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20794/46960 (44.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26165/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20795/46960 (44.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24701/46939 (52.6%)</li>
<li><details><summary>Failed: 1/46939 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.object_management.single_alloc_callbacks.instance
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 22237/46939 (47.4%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
That jenkins pipeline failure was a single flake on a single agent, so I am happy that my change does not break fixed-layout CS when it is used.

**Comment by trenouf** [comment]
V4: Now no longer uses CS fixed layout for PAL version >= 624.
Remove a test that (a) fails and (b) no longer tests what it purports to test.

**Comment by amdvlk-admin** [comment]
### Test summary for commit e47d56b51b71956cf6c34d84859044e47357c4d2
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 007816f4bd2fd3ace30f8af9629cff7ec1dcb998</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev b25c1eac19f1773b753ed727314aa3cf2c0897dd</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev e09ed8b4a5ed4201e59b8d5dc66e17dd05eca428</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/140859)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26166/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20794/46960 (44.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26165/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20795/46960 (44.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24702/46939 (52.6%)</li>
<li>Failed: 0/46939 (0.0%)</li>
<li>Skipped: 22237/46939 (47.4%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
V5: Fix another bit of code that is only needed for fixed layout.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 552e9d2f1d252ae3f26cabbeb1027b9c2b96a1f0
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 007816f4bd2fd3ace30f8af9629cff7ec1dcb998</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev b25c1eac19f1773b753ed727314aa3cf2c0897dd</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev e09ed8b4a5ed4201e59b8d5dc66e17dd05eca428</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/140859)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26166/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20794/46960 (44.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26165/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20795/46960 (44.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24702/46939 (52.6%)</li>
<li>Failed: 0/46939 (0.0%)</li>
<li>Skipped: 22237/46939 (47.4%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM

**Pull request merged**
