### PR TITLE
Use suffix .spvasm instead of .spvas for SPIR-V assembly text files.

### PR DESCRIPTION
**Pull request by dnovillo**
This fixes https://github.com/GPUOpen-Drivers/llpc/issues/529.

Tested with check-amdllpc.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JacobHeAMD** [comment]
ok to test

**Comment by JacobHeAMD** [comment]
test this please

**Comment by dnovillo** [comment]
Thanks @amdrexu.  Could you please submit this for me?  I don't have write access.

**Comment by amdrexu** [comment]
@dnovillo Today, we update SPIRV-tools and fix some test issues: https://github.com/GPUOpen-Drivers/llpc/pull/531. You have to do a rebase and update this PR. Tomorrow, Jax will help to merge it and port to our internal code base. We need an internal change at the same time to recognize the new extension name .spvasm :)

**Comment by dnovillo** [comment]
> @dnovillo Today, we update SPIRV-tools and fix some test issues: #531. You have to do a rebase and update this PR. Tomorrow, Jax will help to merge it and port to our internal code base. We need an internal change at the same time to recognize the new extension name .spvasm :)

Done.  Thank you.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 950c302b41e9603da30908db09f808ed0cf7ff80
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev bb7398b1c7509a30ba4f7d947b5ad5549a4d58db</li>
<li>SPVGEN: dev b30c124e7a042c5251aeb20780a83089355e74a1</li>
<li>XGL: dev ffd39443fec0ce821b7702173eba7184855c7b5e</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ebc431ac299fa294a4e730432520d37f326843c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 955/955 (100.0%)</li>
<li>Failed: 0/955 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103137/103137 (100.0%)</li>
<li>Failed: 0/103137 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdrexu** [comment]
Once the code conflict is resolved, please pine @JaxLinAMD for merging. Thanks.

**Comment by dnovillo** [comment]
> Once the code conflict is resolved, please pine @JaxLinAMD for merging. Thanks.

Code conflict?  I don't know what you're referring to.  What is it?  And how can I tell that it has been resolved?  Thanks.

**Comment by amdrexu** [comment]
@dnovillo See the bottom of this link: https://github.com/GPUOpen-Drivers/llpc/pull/530. The page says "This branch cannot be rebased due to conflicts". Maybe Jax will help us to what is wrong.

**Comment by dnovillo** [comment]
Well, all I see

> @dnovillo See the bottom of this link: #530. The page says "This branch cannot be rebased due to conflicts". Maybe Jax will help us to what is wrong.

I don't see that.  I see this on my page (attached)

image

**Comment by amdrexu** [comment]
That's OK. I will check this with Jax tomorrow.

**Comment by JaxLinAMD** [comment]
@dnovillo , could you do a rebase? maybe you can observe conflicts during rebase.

**Comment by dnovillo** [comment]
I did a couple of days ago.  That had conflicts, which I fixed.  I just did another one with no conflicts.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 631155ba4bb286518735e9ba7f337d97c5b98d69
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev bb7398b1c7509a30ba4f7d947b5ad5549a4d58db</li>
<li>SPVGEN: dev b30c124e7a042c5251aeb20780a83089355e74a1</li>
<li>XGL: dev ffd39443fec0ce821b7702173eba7184855c7b5e</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ebc431ac299fa294a4e730432520d37f326843c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 955/955 (100.0%)</li>
<li>Failed: 0/955 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103137/103137 (100.0%)</li>
<li>Failed: 0/103137 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
