### PR TITLE
[Do not merge this] This is only test

### PR DESCRIPTION
**Pull request by mariusz-sikora-at-amd**

### CODE REVIEW

**Comment by mariusz-sikora-at-amd** [comment]
This is for testing only. Right now I want to see if Jenkins will start the Job. If not I will ask someone to give me "0k_t0_test" and I will see if I will be able to trigger Jenkins by "retest thls please"

**Comment by mariusz-sikora-at-amd** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit a28c2ab406fbe980de41435910effb6ec8bd12eb
<details><summary>CTS tests (Failed: 0/211523)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39248/70507 (55.7%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31259/70507 (44.3%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39498/70507 (56.0%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31009/70507 (44.0%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36345/70509 (51.5%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34164/70509 (48.5%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by mariusz-sikora-at-amd** [comment]
retest this please

**Comment by mariusz-sikora-at-amd** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit a28c2ab406fbe980de41435910effb6ec8bd12eb
<details><summary>CTS tests (Failed: 1/211534)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39250/70518 (55.7%)</li>
<li>Failed: 0/70518 (0.0%)</li>
<li>Not Supported: 31268/70518 (44.3%)</li><li>Warnings: 0/70518 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39497/70507 (56.0%)</li>
<li><details><summary>Failed: 1/70507 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_2.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31009/70507 (44.0%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36345/70509 (51.5%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34164/70509 (48.5%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by mariusz-sikora-at-amd** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit a28c2ab406fbe980de41435910effb6ec8bd12eb
<details><summary>CTS tests (Failed: 0/211534)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39251/70518 (55.7%)</li>
<li>Failed: 0/70518 (0.0%)</li>
<li>Not Supported: 31267/70518 (44.3%)</li><li>Warnings: 0/70518 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39499/70507 (56.0%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31008/70507 (44.0%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36346/70509 (51.5%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34163/70509 (48.5%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit a28c2ab406fbe980de41435910effb6ec8bd12eb
<details><summary>CTS tests (Failed: 0/211534)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39251/70518 (55.7%)</li>
<li>Failed: 0/70518 (0.0%)</li>
<li>Not Supported: 31267/70518 (44.3%)</li><li>Warnings: 0/70518 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39499/70507 (56.0%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31008/70507 (44.0%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36346/70509 (51.5%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34163/70509 (48.5%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request closed without merging**
