### PR TITLE
Add abstractType input parameter to the getDescPtr

### PR DESCRIPTION
**Pull request by jiaolu**
lgc.descriptor.table.addr also add new abstractType input parameter

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9610d7e38f67599ac0da3c812eeaf91e025c4bac
<details><summary>CTS tests (Failed: 0/220366)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 37494/73370 (51.1%)</li>
<li>Failed: 0/73370 (0.0%)</li>
<li>Not Supported: 35876/73370 (48.9%)</li><li>Warnings: 0/73370 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/73498 (52.4%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 35007/73498 (47.6%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35388/73498 (48.1%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 38110/73498 (51.9%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM

**Comment by amdvlk-admin** [comment]
### Test summary for commit 160f2a064bff55b88dddaabb21a4f6ce1ec22024
<details><summary>CTS tests (Failed: 0/289643)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 37494/73370 (51.1%)</li>
<li>Failed: 0/73370 (0.0%)</li>
<li>Not Supported: 35876/73370 (48.9%)</li><li>Warnings: 0/73370 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/73498 (52.4%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 35007/73498 (47.6%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35388/73498 (48.1%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 38110/73498 (51.9%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 36014/69277 (52.0%)</li>
<li>Failed: 0/69277 (0.0%)</li>
<li>Not Supported: 33263/69277 (48.0%)</li><li>Warnings: 0/69277 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM

**Pull request merged**
