### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by ruiling**
some minor fixes

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit ab650b9cad7d74f69ed9133ab00b58c81b173b10
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 9074bd0bdaf67fa84399dfabed3ec437951838f8</li>
<li>SPVGEN: dev c054813a9a894e32aaaa04c6717a667c15f60cfd</li>
<li>XGL: dev 598c6832a4983f5b75b38a589fca5be80a2f3bb0</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev ccbc834ac4f92e63a9a003bd5a18cb9fcf3c6121</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/129722)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43245 (52.7%)</li>
<li>Failed: 0/43245 (0.0%)</li>
<li>Skipped: 20461/43245 (47.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22783/43249 (52.7%)</li>
<li>Failed: 0/43249 (0.0%)</li>
<li>Skipped: 20466/43249 (47.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43228 (50.0%)</li>
<li>Failed: 0/43228 (0.0%)</li>
<li>Skipped: 21619/43228 (50.0%)</li>
</ul></details>


</ul></details>

**Comment by ruiling** [comment]
I think this is an obvious copy-paste typo, so I fix it. This is not a fix against any reported bug. So I don't know how to test it. I will update the commit message and title.

**Review by amdrexu — APPROVED** [review]
In the future, I think this could be two separate PRs since the commits are not logically linked. We include multiple commits in a PR to finish one task that have several related parts.

**Comment by amdrexu** [comment]
Some codes have conflicts.  Please fetch latest codes and  make rebase.

**Comment by ruiling** [comment]
conflicts resolved. sure, will split into separate PR as I can in the future. I didn't separate them because this is really very minor changes.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 69b5fc745ed73ee43a76a277977f15dcebe79bf1
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 9074bd0bdaf67fa84399dfabed3ec437951838f8</li>
<li>SPVGEN: dev c054813a9a894e32aaaa04c6717a667c15f60cfd</li>
<li>XGL: dev 598c6832a4983f5b75b38a589fca5be80a2f3bb0</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c72fe645f96434578da68c6fdb44bd28bb2fa6f1</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/131652)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43891 (51.9%)</li>
<li>Failed: 0/43891 (0.0%)</li>
<li>Skipped: 21107/43891 (48.1%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22783/43891 (51.9%)</li>
<li>Failed: 0/43891 (0.0%)</li>
<li>Skipped: 21108/43891 (48.1%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43870 (49.3%)</li>
<li>Failed: 0/43870 (0.0%)</li>
<li>Skipped: 22261/43870 (50.7%)</li>
</ul></details>


</ul></details>

**Pull request merged**
