### PR TITLE
Fixed cmake llpc build to not need pal

### PR DESCRIPTION
**Pull request by trenouf**
Change-Id: I8d894ced7eb651762c8310322e41e4d124163986

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit d30bccab090933426c21f284ac1e9d576270214b
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev bb7398b1c7509a30ba4f7d947b5ad5549a4d58db</li>
<li>SPVGEN: dev b30c124e7a042c5251aeb20780a83089355e74a1</li>
<li>XGL: dev ffd39443fec0ce821b7702173eba7184855c7b5e</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ebc431ac299fa294a4e730432520d37f326843c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 955/955 (100.0%)</li>
<li>Failed: 0/955 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103137/103137 (100.0%)</li>
<li>Failed: 0/103137 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
I'm gonna merge this without approval because it is needed to fix an internal CI build.

**Comment by nhaehnle** [comment]
Don't we still have a dependency on palPipelineAbi.h? So presumably the cmake change is fine in that we don't actually need to *link* against PAL, but we do need the PAL source.

**Comment by trenouf** [comment]
> Don't we still have a dependency on palPipelineAbi.h? So presumably the cmake change is fine in that we don't actually need to _link_ against PAL, but we do need the PAL source.

LGC no longer has a dependency on palPipelineAbi.h. The pipeline dumper might still do. But you're right that we do not need to build PAL or link against it. The problem I was fixing was building amdllpc on an OS that PAL does not support building on.

**Pull request merged**
