### PR TITLE
Recreate LGC context if optimization level changes

### PR DESCRIPTION
**Pull request by perlfu**
LGC context must be recreated if pipeline context optimization level
changes so that the target machine optimization level is correct.

### CODE REVIEW

**Comment by perlfu** [comment]
Not sure why cppcheck is complaining about new unit test.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 593207faf8ec5dfa382511d5374df0f3435b7448
<details><summary>CTS tests (Failed: 0/186371)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 37104/65208 (56.9%)</li>
<li>Failed: 0/65208 (0.0%)</li>
<li>Not Supported: 28104/65208 (43.1%)</li><li>Warnings: 0/65208 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30377/55953 (54.3%)</li>
<li>Failed: 0/55953 (0.0%)</li>
<li>Not Supported: 25576/55953 (45.7%)</li><li>Warnings: 0/55953 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 39403/65210 (60.4%)</li>
<li>Failed: 0/65210 (0.0%)</li>
<li>Not Supported: 25807/65210 (39.6%)</li><li>Warnings: 0/65210 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 570229a1db8955ad7aff78d52b844d43b881c32e
<details><summary>CTS tests (Failed: 0/186371)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 37104/65208 (56.9%)</li>
<li>Failed: 0/65208 (0.0%)</li>
<li>Not Supported: 28104/65208 (43.1%)</li><li>Warnings: 0/65208 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30377/55953 (54.3%)</li>
<li>Failed: 0/55953 (0.0%)</li>
<li>Not Supported: 25576/55953 (45.7%)</li><li>Warnings: 0/55953 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 39403/65210 (60.4%)</li>
<li>Failed: 0/65210 (0.0%)</li>
<li>Not Supported: 25807/65210 (39.6%)</li><li>Warnings: 0/65210 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by Flakebi** [comment]
> Not sure why cppcheck is complaining about new unit test.

It doesn’t understand the test macros. Can you add a `// cppcheck-suppress syntaxError` comment above like here?
https://github.com/GPUOpen-Drivers/llpc/blob/439cb80f00ec704e9334f939cdd79f2f2dfc2810/llpc/unittests/context/testShaderCache.cpp#L87-L88

**Review by dstutt — APPROVED** [review]
LGTM

**Comment by amdvlk-admin** [comment]
### Test summary for commit e09ffa601a295503359e3ad0dc3660265f1bbc66
<details><summary>CTS tests (Failed: 0/186371)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 37104/65208 (56.9%)</li>
<li>Failed: 0/65208 (0.0%)</li>
<li>Not Supported: 28104/65208 (43.1%)</li><li>Warnings: 0/65208 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30377/55953 (54.3%)</li>
<li>Failed: 0/55953 (0.0%)</li>
<li>Not Supported: 25576/55953 (45.7%)</li><li>Warnings: 0/55953 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 39403/65210 (60.4%)</li>
<li>Failed: 0/65210 (0.0%)</li>
<li>Not Supported: 25807/65210 (39.6%)</li><li>Warnings: 0/65210 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
