### PR TITLE
LLPC frontend lower: Change UndefValue to PoisonValue

### PR DESCRIPTION
**Pull request by amdrexu**
To follow the upcoming LLVM change: https://reviews.llvm.org/D152658.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
12b736147a190bc6b47e94dc8750cb785351f860 Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/LowerDebugPrintf.cpp:93:32: error: cannot convert ‘llvm::Value’ to ‘llvm::Value*’ in initialization
   93 |   for (Value *var : op.getArgs()) {
      |                                ^
[2897/3084] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/elfLinker/GlueShader.cpp.o
[2898/3084] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/Gfx6ConfigBuilder.cpp.o
[2899/3084] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/PatchCheckShaderCache.cpp.o

**Comment by amdvlk-admin** [comment]
6b8800b526cda7f4b79bc9e729ac2e9e0a29a7fc Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/LowerDebugPrintf.cpp:93:32: error: cannot convert ‘llvm::Value’ to ‘llvm::Value*’ in initialization
   93 |   for (Value *var : op.getArgs()) {
      |                                ^
[2902/3088] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/PatchCheckShaderCache.cpp.o
[2903/3088] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/Gfx6ConfigBuilder.cpp.o
[2904/3088] Building CXX object compiler/llpc/CMakeFiles/llpcinternal.dir/translator/lib/SPIRV/libSPIRV/SPIRVEntry.cpp.o

**Comment by amdvlk-admin** [comment]
### Test summary for commit b0ac5a00830d26a8b2db3a3ebae0ade12536fdc0
<details><summary>CTS tests (Failed: 0/211329)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39099/70446 (55.5%)</li>
<li>Failed: 0/70446 (0.0%)</li>
<li>Not Supported: 31347/70446 (44.5%)</li><li>Warnings: 0/70446 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39131/70435 (55.6%)</li>
<li>Failed: 0/70435 (0.0%)</li>
<li>Not Supported: 31304/70435 (44.4%)</li><li>Warnings: 0/70435 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35186/70448 (49.9%)</li>
<li>Failed: 0/70448 (0.0%)</li>
<li>Not Supported: 35262/70448 (50.1%)</li><li>Warnings: 0/70448 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit b0ac5a00830d26a8b2db3a3ebae0ade12536fdc0
<details><summary>CTS tests (Failed: 206/211332)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38943/70447 (55.3%)</li>
<li><details><summary>Failed: 156/70447 (0.2%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.16
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_16_even_repeat_2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_4_even_repeat_2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_64_even_repeat_8
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_64_odd_repeat_4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_64_odd_repeat_8
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_1_6
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_2_3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_2_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_2_6
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_3_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_4_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_5_1
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_5_3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_7_2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_7_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_8_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_8_7
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 31348/70447 (44.5%)</li><li>Warnings: 0/70447 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39106/70436 (55.5%)</li>
<li><details><summary>Failed: 25/70436 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.8
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.16
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.bvec2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.bvec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat2x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat3x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat2x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat3x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32vec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat2x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat3x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat3x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat4x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64vec3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.float64_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.i8vec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int16_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int32_t
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 31305/70436 (44.4%)</li><li>Warnings: 0/70436 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35161/70449 (49.9%)</li>
<li><details><summary>Failed: 25/70449 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.8
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.16
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.bvec2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.bvec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat2x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat3x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat2x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat3x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32vec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat2x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat3x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat3x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat4x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64vec3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.float64_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.i8vec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int16_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int32_t
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 35263/70449 (50.1%)</li><li>Warnings: 0/70449 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
