### PR TITLE
lgc: Add visibility to ResourceNode

### PR DESCRIPTION
**Pull request by trenouf**
Allows a front-end to specify what shader stages a resource node is visible to.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit f4b0f56dad4ac6c89f2c96930027e71b26b9d6d3
<details><summary>CTS tests (Failed: 0/213076)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71028 (56.9%)</li>
<li>Failed: 0/71028 (0.0%)</li>
<li>Not Supported: 30602/71028 (43.1%)</li><li>Warnings: 0/71028 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71018 (57.0%)</li>
<li>Failed: 0/71018 (0.0%)</li>
<li>Not Supported: 30554/71018 (43.0%)</li><li>Warnings: 0/71018 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36471/71030 (51.3%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 34559/71030 (48.7%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
Ping for review please.

**Review by nhaehnle — COMMENTED** [review]
I missed this before, but I commented on the internal version: I think we should consistently use shaderStage instead of visibilityMask, and remove the code in RelocHandler that can't provide that.

**Comment by trenouf** [comment]
I would rather not remove the elf linker code as part of this commit, so for now I'll hack it to pass an "unknown" shader stage.

**Comment by nhaehnle** [comment]
Fair enough.

**Comment by trenouf** [comment]
This now has the 64-bit descSet change in it, just to avoid me needing to do more conflict resolution when it lands. The only real new change is the "pass shaderStage instead of visibilityMask into find funcs" commit.

**Review by nhaehnle — DISMISSED** [review]
It would be better to have this as a properly rebased change because as-is it's a bit difficult to review. But it does look okay.

**Comment by trenouf** [comment]
I'll do a rebase when the 64-bit descSet change has landed, and you can have another look then.

**Comment by trenouf** [comment]
Squashed and rebased now that the 64-bit descSet change has landed. Ping for reapproval.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4b7460c21e53df6e755e0148ab6eef79c80e7f81
<details><summary>CTS tests (Failed: 0/140881)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39058/70446 (55.4%)</li>
<li>Failed: 0/70446 (0.0%)</li>
<li>Not Supported: 31388/70446 (44.6%)</li><li>Warnings: 0/70446 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39090/70435 (55.5%)</li>
<li>Failed: 0/70435 (0.0%)</li>
<li>Not Supported: 31345/70435 (44.5%)</li><li>Warnings: 0/70435 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — DISMISSED** [review]
LGTM

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8ed67456d8a6eb3a1f153ad57bb9671d58f5ebfb
<details><summary>CTS tests (Failed: 0/211315)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39059/70432 (55.5%)</li>
<li>Failed: 0/70432 (0.0%)</li>
<li>Not Supported: 31373/70432 (44.5%)</li><li>Warnings: 0/70432 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39090/70435 (55.5%)</li>
<li>Failed: 0/70435 (0.0%)</li>
<li>Not Supported: 31345/70435 (44.5%)</li><li>Warnings: 0/70435 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35145/70448 (49.9%)</li>
<li>Failed: 0/70448 (0.0%)</li>
<li>Not Supported: 35303/70448 (50.1%)</li><li>Warnings: 0/70448 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]

**Pull request merged**
