### PR TITLE
ColorExport: Add internal pipeline hash

### PR DESCRIPTION
**Pull request by AMD-dwang**
Add internal pipeline hash for color export shader.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3d780d7d12a9efa8279df0d346cd30ab1d67e7be
<details><summary>CTS tests (Failed: 0/139021)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 41144/69517 (59.2%)</li>
<li>Failed: 0/69517 (0.0%)</li>
<li>Not Supported: 28373/69517 (40.8%)</li><li>Warnings: 0/69517 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41177/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28327/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4e67115d650146947f6ba9181f705dcb0929903f
<details><summary>CTS tests (Failed: 0/139021)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 41143/69517 (59.2%)</li>
<li>Failed: 0/69517 (0.0%)</li>
<li>Not Supported: 28374/69517 (40.8%)</li><li>Warnings: 0/69517 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41178/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28326/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
Should this really only be done for color export shaders? It feels like we should rather do this unconditionally in GlueShader, or perhaps conditional on the hash bytes being non-zero.

**Comment by AMD-dwang** [comment]
> Should this really only be done for color export shaders? It feels like we should rather do this unconditionally in GlueShader, or perhaps conditional on the hash bytes being non-zero.

Yes, it is only for color export shader. For glue shader, it is essentially PS, and internal pipeline hash has been added in fragment shader.

**Comment by nhaehnle** [comment]
Right. The real problem here is to have a mysteriously-named `internalCompile` method. The name doesn't say anything.

If you want to keep the hash setting in ColorExportShader, can it be moved to the main build method?

**Comment by AMD-dwang** [comment]
That's okay. Will update it. Thanks.

**Comment by amdvlk-admin** [comment]
fbad4077dd9649533944af516294e09e120ec198 Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/disassembler/Disassembler.cpp:141:12: error: ‘endianness’ in namespace ‘llvm::support’ does not name a type; did you mean ‘endian’?
  141 |   support::endianness endian() { return m_objFile->isLittleEndian() ? support::little : support::big; }
      |            ^~~~~~~~~~
      |            endian
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/disassembler/Disassembler.cpp: In member function ‘void {anonymous}::ObjDisassembler::addBinaryEncodingComment(llvm::raw_ostream&, unsigned int, llvm::ArrayRef<unsigned char>)’:
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/disassembler/Disassembler.cpp:677:9: error: ‘endian’ was not declared in this scope
  677 |     if (endian() == support::little)
      |         ^~~~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/disassembler/Disassembler.cpp:677:9: note: suggested alternatives:
In file included from /usr/include/c++/9/memory:93,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llvm-project/llvm/include/llvm/ADT/SmallVector.h:28,
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/disassembler/Disassembler.cpp:677:30: error: ‘little’ is not a member of ‘llvm::support’; did you mean ‘little_t’?
  677 |     if (endian() == support::little)
      |                              ^~~~~~
      |                              little_t
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/disassembler/Disassembler.cpp: In member function ‘size_t {anonymous}::ObjDisassembler::decodeNote(llvm::StringRef)’:
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/disassembler/Disassembler.cpp:794:60: error: ‘endian’ was not declared in this scope
  794 |   unsigned nameSize = support::endian::read32(data.data(), endian());
      |                                                            ^~~~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/disassembler/Disassembler.cpp:794:60: note: suggested alternatives:
In file included from /usr/include/c++/9/memory:93,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llvm-project/llvm/include/llvm/ADT/SmallVector.h:28,

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6d8ce725b3f24043d4a25734e80af7184a2075ad
<details><summary>CTS tests (Failed: 0/138995)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 41144/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28360/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41177/69491 (59.3%)</li>
<li>Failed: 0/69491 (0.0%)</li>
<li>Not Supported: 28314/69491 (40.7%)</li><li>Warnings: 0/69491 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
Thanks! :)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6d8ce725b3f24043d4a25734e80af7184a2075ad
<details><summary>CTS tests (Failed: 1/208499)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Rhel 8.9, Gfx10</summary><ul>

<li>Passed: 36572/69504 (52.6%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 32932/69504 (47.4%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 41144/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28360/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41178/69491 (59.3%)</li>
<li><details><summary>Failed: 1/69491 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.sparse_resources.device_group_mipmap_sparse_residency.2d.rg8i.512_256_1
Stack trace: Flake
```
</p></details></li>

<li>Not Supported: 28312/69491 (40.7%)</li><li>Warnings: 0/69491 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by AMD-dwang** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6d8ce725b3f24043d4a25734e80af7184a2075ad
<details><summary>CTS tests (Failed: 0/138994)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 41144/69503 (59.2%)</li>
<li>Failed: 0/69503 (0.0%)</li>
<li>Not Supported: 28359/69503 (40.8%)</li><li>Warnings: 0/69503 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41177/69491 (59.3%)</li>
<li>Failed: 0/69491 (0.0%)</li>
<li>Not Supported: 28314/69491 (40.7%)</li><li>Warnings: 0/69491 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
