### PR TITLE
Implement new functions from gpurt

### PR DESCRIPTION
**Pull request by jiaolu**
Add AmdTraceRayGetKnownSetRayFlags/AmdTraceRayGetKnownUnsetRayFlags implementations

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2b38a27d0911e9ac4a1a8e11747064000701d8fd
<details><summary>CTS tests (Failed: 0/138443)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35211/69228 (50.9%)</li>
<li>Failed: 0/69228 (0.0%)</li>
<li>Not Supported: 34017/69228 (49.1%)</li><li>Warnings: 0/69228 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35242/69215 (50.9%)</li>
<li>Failed: 0/69215 (0.0%)</li>
<li>Not Supported: 33973/69215 (49.1%)</li><li>Warnings: 0/69215 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by jasilvanus** [comment]
Are we not analyzing constant TraceRay flags in LLPC, and optimize Traversal for it?

**Comment by jiaolu** [comment]
> Are we not analyzing constant TraceRay flags in LLPC, and optimize Traversal for it?

this PR is originated from internal project souce.

**Comment by LLJJDD** [comment]
> Are we not analyzing constant TraceRay flags in LLPC, and optimize Traversal for it?

We aren't so far, I suppose this would rely on Nicolai's internal proposal about library.

**Comment by jasilvanus** [comment]
> > Are we not analyzing constant TraceRay flags in LLPC, and optimize Traversal for it?
> 
> We aren't so far,
 
Interesting.

>I suppose this would rely on Nicolai's internal proposal about library.

Only when compiling libraries, correct? For full pipelines, we should have everything we need available.

**Comment by LLJJDD** [comment]
> > I suppose this would rely on Nicolai's internal proposal about library.
> 
> Only when compiling libraries, correct? For full pipelines, we should have everything we need available.

Oh yes, it should be doable for full pipelines for now.

**Comment by jiaolu** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 62b90cf59377632e138389c09f8c3fd95834dc7f
<details><summary>CTS tests (Failed: 0/138443)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35211/69228 (50.9%)</li>
<li>Failed: 0/69228 (0.0%)</li>
<li>Not Supported: 34017/69228 (49.1%)</li><li>Warnings: 0/69228 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35242/69215 (50.9%)</li>
<li>Failed: 0/69215 (0.0%)</li>
<li>Not Supported: 33973/69215 (49.1%)</li><li>Warnings: 0/69215 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
Yes, we certainly should apply such optimizations in the future, but the point of this PR is primarily to allow us to have the GPURT change move forward. LGTM.

**Pull request merged**
