### PR TITLE
Initialize shaderIdExtraBits

### PR DESCRIPTION
**Pull request by jiaolu**
also initialize RayTracingShaderProperty field onlyGpuVaLo

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 699240f927373ecc28e04fe77cfa9e37f1f711bd
<details><summary>CTS tests (Failed: 0/211633)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70549 (50.3%)</li>
<li>Failed: 0/70549 (0.0%)</li>
<li>Not Supported: 35053/70549 (49.7%)</li><li>Warnings: 0/70549 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39381/70550 (55.8%)</li>
<li>Failed: 0/70550 (0.0%)</li>
<li>Not Supported: 31169/70550 (44.2%)</li><li>Warnings: 0/70550 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70534 (55.9%)</li>
<li>Failed: 0/70534 (0.0%)</li>
<li>Not Supported: 31121/70534 (44.1%)</li><li>Warnings: 0/70534 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by jiaolu** [comment]
Hi, @nhaehnle 

it seems your comits breaks lgc/test/lgcdis.lgc

**Comment by nhaehnle** [comment]
> Hi, @nhaehnle
> 
> it seems your comits breaks lgc/test/lgcdis.lgc

Yes, #2635 works for me locally at least.

**Review by nhaehnle — APPROVED** [review]

**Comment by jiaolu** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 699240f927373ecc28e04fe77cfa9e37f1f711bd
<details><summary>CTS tests (Failed: 0/211630)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 8.9, Gfx10</summary><ul>

<li>Passed: 35497/70549 (50.3%)</li>
<li>Failed: 0/70549 (0.0%)</li>
<li>Not Supported: 35052/70549 (49.7%)</li><li>Warnings: 0/70549 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39379/70547 (55.8%)</li>
<li>Failed: 0/70547 (0.0%)</li>
<li>Not Supported: 31168/70547 (44.2%)</li><li>Warnings: 0/70547 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70534 (55.9%)</li>
<li>Failed: 0/70534 (0.0%)</li>
<li>Not Supported: 31121/70534 (44.1%)</li><li>Warnings: 0/70534 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
