### PR TITLE
Do not dereference nullptrs in SPIRVEntry

### PR DESCRIPTION
**Pull request by kuhar**

### CODE REVIEW

**Comment by kuhar** [comment]
If this change looks OK, I plan to send out a separate patch to SPIRV-LLVM-Translator, as suggested on llpc-chat.

I submit the PR to the dev branch of llpc; the seems identical to the one on master.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1db5b363199a16849cdd6456ee1c299bd2e87afc
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 88d997710b4e405f3a8e3fd60a38afee9e3e77e2</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 2cb5558b94c5dc839e093cb439057a1802426c8e</li>
<li>LLVM: amd-vulkan-dev 1fc1a7d4248b4749c3df21eb48f7ae97b6cddf74</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/pal/src/util/lnx/lnxHashProvider.h:36:10: fatal error: openssl/sha.h: No such file or directory

</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1db5b363199a16849cdd6456ee1c299bd2e87afc
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 88d997710b4e405f3a8e3fd60a38afee9e3e77e2</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 2cb5558b94c5dc839e093cb439057a1802426c8e</li>
<li>LLVM: amd-vulkan-dev 1fc1a7d4248b4749c3df21eb48f7ae97b6cddf74</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory

</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1db5b363199a16849cdd6456ee1c299bd2e87afc
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 88d997710b4e405f3a8e3fd60a38afee9e3e77e2</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 2cb5558b94c5dc839e093cb439057a1802426c8e</li>
<li>LLVM: amd-vulkan-dev 1fc1a7d4248b4749c3df21eb48f7ae97b6cddf74</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palMsgPack.h:41:10: fatal error: cwpack.h: No such file or directory

</ul></details>

**Comment by kuhar** [comment]
Any idea why the automatic checks keep failing on this commit?

**Comment by trenouf** [comment]
No; I don't see any particular error in the log of the last one. It looks like it just gave up at about 91% of the build.

Assuming Jacob is not available to look at it properly right now (he's on UTC+8 timezone), I'll retrigger it.

**Comment by trenouf** [comment]
retest this please

**Comment by amdrexu** [comment]
@JacobHeAMD Please help to check why the build always fails for this commit. The change is simple and other commits pass testing normally. Thanks.

**Comment by JacobHeAMD** [comment]
The problem here is this commit is too old and it's not compatible with the latest PAL/XGL. It should be rebased to the latest LLPC. Please note that Jenkins test is not using the diff of pull request, it's check out the whole PR commit. Considering this change has nothing to do with cwpack and I've tested locally, I'll merge it directly.

**Pull request merged**
