### PR TITLE
Added -spvgen-dir option to all lit tests

### PR DESCRIPTION
**Pull request by trenouf**
All lit test RUN: lines now say "amdllpc -spvgen-dir=%spvgendir%", in
preperation for a future change that gives llvm-lit the location of
spvgen.so.

For now, %spvgendir% just expands to nothing, so tests behave as before.

Change-Id: I7de19e3eadd3c0b8e5ab76ff2c58454de4ea6a11

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1b8486c71d9568497e10ebf735affb169e65ae85
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 99901922d67e502ff4233a8bfcbfa0347c0ffa1b</li>
<li>SPVGEN: dev 69311f7c1e220d190909298b9c7bd702ecc237ff</li>
<li>XGL: dev 5b4058dc288a25f6554fcc61f80bf3f27eb35d8d</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.
FileCheck error: '-' is empty.

</ul></details>

**Comment by JacobHeAMD** [comment]
Hi @trenouf , does this change depends on https://github.com/GPUOpen-Drivers/llpc/pull/51 ?

**Comment by trenouf** [comment]
Yes, it depends on #51, so it should stop failing tests once #51 has been merged and I have rebased this one.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9289311ecb0738c4448e0e48af3f432050fed81e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 99901922d67e502ff4233a8bfcbfa0347c0ffa1b</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 9795e006e9adb7b49b8abd32cd47c49b290fa3fc</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 901/901 (100.0%)</li>
<li>Failed: 0/901 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Vega20</summary><ul>

<li>Passed: 312687/312687 (100.0%)</li>
<li>Failed: 0/312687 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
