### PR TITLE
MeshShader: Improve attributes through memory code generation

### PR DESCRIPTION
**Pull request by nhaehnle**
This is intended to be equivalent to commit 0e032888eb4 ("NggPrimShader: Improve attribute-through-memory code generation").

### CODE REVIEW

**Review by amdrexu — APPROVED** [review]

**Comment by nhaehnle** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit f3b9cd4fbc14637b4697bb5be7b079364ce28b2b
<details><summary>CTS tests (Failed: 205/211487)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39248/70495 (55.7%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 31247/70495 (44.3%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39498/70495 (56.0%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 30997/70495 (44.0%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36142/70497 (51.3%)</li>
<li><details><summary>Failed: 205/70497 (0.3%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.binding_model.buffer_device_address.set3.depth2.baseubo.convertcheckuv2.store.multi.scalar.comp
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.descriptorset_random.sets4.dynindexed.ubolimitlow.sbolimitlow.sampledimghigh.lowimgnotex.noiub.uab.comp.noia.0
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.descriptorset_random.sets4.unifindexed.ubolimitlow.sbolimitlow.sampledimglow.outimgtexlow.iublimitlow.uab.comp.noia.0
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.shader_access.secondary_cmd_buf.sampler_immutable.fragment.single_descriptor.cube_array_base_mip
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_cull_distance.vert_geom.7_1
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_distance.vert_tess.3
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.alias.i64_to_u64_default_func_read
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.zero.uint16_t_array_to_float_uint16_t_array_4
Stack trace: Flake

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.5_4_4
Stack trace: Flake

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.6_3_4
Stack trace: Flake

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.6_3_5
Stack trace: Flake

FAILURE: dEQP-VK.descriptor_indexing.storage_texel_buffer_after_bind_in_loop
Stack trace: Flake

FAILURE: dEQP-VK.draw.renderpass.shader_viewport_index.fragment_shader_13
Stack trace: Flake

FAILURE: dEQP-VK.fragment_operations.early_fragment.discard_early_and_late_fragment_tests_depth
Stack trace: Flake

FAILURE: dEQP-VK.fragment_operations.early_fragment.early_and_late_fragment_tests_stencil_no_attachment
Stack trace: Flake

FAILURE: dEQP-VK.fragment_shading_barycentric.data.provoking_last.static.point_list.type.uvec3
Stack trace: Flake

FAILURE: dEQP-VK.geometry.emit.triangle_strip_emit_1_end_2
Stack trace: Flake

FAILURE: dEQP-VK.glsl.440.linkage.varying.component.vert_in.vec2.as_float_float_unused
Stack trace: Flake

FAILURE: dEQP-VK.glsl.builtin.precision.normalize.mediump.vec4
Stack trace: Flake

FAILURE: dEQP-VK.glsl.builtin.precision.roundeven.mediump.vec2
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 34150/70497 (48.4%)</li><li>Warnings: 0/70497 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit f3b9cd4fbc14637b4697bb5be7b079364ce28b2b
<details><summary>CTS tests (Failed: 424/211487)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39248/70495 (55.7%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 31247/70495 (44.3%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39498/70495 (56.0%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 30997/70495 (44.0%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35929/70497 (51.0%)</li>
<li><details><summary>Failed: 424/70497 (0.6%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.buffer.suballocation.transfer_dst.storage.vertex.create.binding_aliased
Stack trace: Flake

FAILURE: dEQP-VK.api.buffer.suballocation.transfer_dst.storage_texel.storage.index.indirect.create.binding_residency
Stack trace: Flake

FAILURE: dEQP-VK.api.command_buffers.submit_count_equal_zero
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.blit_image.all_formats.color.2d.e5b9g9r9_ufloat_pack32.r8_snorm.optimal_general_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.blit_image.all_formats.generate_mipmaps.from_previous_level.layercount_6.r32g32b32a32_uint.optimal_general_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.image_to_image.all_formats.color.2d.r8_srgb.r8_snorm.general_general
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.image_to_image.dimensions.src4096x4_dst4096x4.r8g8b8a8_unorm.r32_sfloat.optimal_general
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.blit_image.all_formats.color.2d.r16g16_snorm.r32g32b32a32_sfloat.optimal_optimal_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.blit_image.all_formats.color.2d.r16g16_unorm.r32_sfloat.linear_general_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.2d.bc5_snorm_block.bc6h_ufloat_block.general_optimal
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.2d.bc6h_ufloat_block.bc2_unorm_block.general_general
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.2d.r16_uint.r8g8_uint.general_general
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.2d.r32g32_sint.bc1_rgb_unorm_block.general_optimal
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_256_11_4_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.all_formats.color.1d.r16_snorm.r16_snorm.general_general_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.all_formats.color.2d.r4g4_unorm_pack8.r16_unorm.general_linear_linear
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.all_formats.generate_mipmaps.from_base_level.layercount_1.r8g8b8a8_snorm.optimal_general_linear
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.all_formats.generate_mipmaps.from_base_level.layercount_6.a2b10g10r10_uint_pack32.optimal_general_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.image_to_image.all_formats.color.2d.a2r10g10b10_uint_pack32.r32_sfloat.general_general
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.image_to_image.all_formats.color.2d.r32_sfloat.b8g8r8a8_srgb.optimal_general
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 34144/70497 (48.4%)</li><li>Warnings: 0/70497 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
The failed tests aren't even mesh shader tests... I expect this is something spurious

**Comment by nhaehnle** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit f3b9cd4fbc14637b4697bb5be7b079364ce28b2b
<details><summary>CTS tests (Failed: 0/211487)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39248/70495 (55.7%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 31247/70495 (44.3%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39498/70495 (56.0%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 30997/70495 (44.0%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36345/70497 (51.6%)</li>
<li>Failed: 0/70497 (0.0%)</li>
<li>Not Supported: 34152/70497 (48.4%)</li><li>Warnings: 0/70497 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
