### PR TITLE
Add YCbCr Sampler Descriptor Parsing Framework in Llpc

### PR DESCRIPTION
**Pull request by jiaxie-amd**
- Expand sampler desc from <4 x i32> to <8 x i32> in builder procedure.
- Add ResourceMappingNodeType::DescriptorYCbCrSampler.

### CODE REVIEW

**Comment by jiaxie-amd** [comment]
How to resolve LLPC Docker CI / Test branch dev failure as showed above?

**Comment by JaxLinAMD** [comment]
please wait.

**Comment by JaxLinAMD** [comment]
Hi @jiaxie-amd , a CI fix is just merged, could you rebase your branch and force-push? it may fix the test failure.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 666a5a74061d4655554f25060a1935c5a8fe690f
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 40af910391fb8c287cb37bf520c41310bf88d405</li>
<li>SPVGEN: dev ce06cb5e3116ba77a22c3278dfeadfd865a8977c</li>
<li>XGL: dev 7e13a8bd0bb57d3cfb3bc014f6b26a8c9bb8bfd9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c22b8992220d645b9f781e4a47947ae546fcd11c</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by JaxLinAMD** [comment]
Hi @jiaxie-amd , this is the failure log:

Failing Tests (46):
    LLPC_SHADERTEST :: shaderdb/ObjSampler_TestLargeId_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpFunctionCall_TestArguTexArray_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpFunctionCall_TestParamSimpleTex_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpFunctionCall_TestParamTexArray_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpFunctionCall_TestParamTexNestedCall_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageDrefGather_TestBasic_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageDrefGather_TestTextureGatherOffset_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageDrefGather_TestTextureGatherOffsets_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageDrefGather_TestTextureGather_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageGather_TestConstOffsets_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageGather_TestDrefConstOffsets_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageGather_TestIntegerSampler.fragOpImageGather_TestIntegerSampler_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageGather_TestOffset_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageGather_TestTextureGatherBiasLod_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageGather_TestTextureGatherOffset_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageGather_TestTextureGatherOffsets_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageGather_TestTextureGather_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageQueryLod_TestBasic_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageQueryLod_TestTextureQueryLod_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleExplicitLod_TestLod_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleExplicitLod_TestTextureGradClamp_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_Test1DArray_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_Test1D_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_Test2DArray_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_Test2DRect_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_Test3D_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestArrayDirectAccess_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestBasic_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestBias_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestCubeArray_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestCubeShadow_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestCube_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestDrefGrad_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestGrad_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestIntegerSampler_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestMultiDimArrayDirectAccess_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestOffset_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestProjDrefGradOffset_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestSeparate_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestTextureBiasClamp_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestTextureClamp_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestTextureGradClamp_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestTextureGradOffsetClamp_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSampleImplicitLod_TestTextureOffsetClamp_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpImageSample_TestSeparateSampler_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpUndef_TestUndefImage_lit.spvas

  Expected Passes    : 893
  Unexpected Failures: 46

Hopefully it will help.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 31dd0325343e6b8ce508d5383d45d3342278498d
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 40af910391fb8c287cb37bf520c41310bf88d405</li>
<li>SPVGEN: dev ce06cb5e3116ba77a22c3278dfeadfd865a8977c</li>
<li>XGL: dev 7e13a8bd0bb57d3cfb3bc014f6b26a8c9bb8bfd9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c22b8992220d645b9f781e4a47947ae546fcd11c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
