### PR TITLE
lgc: test individual passes

### PR DESCRIPTION
**Pull request by nhaehnle**
This sequence of self-contained changes enables us to test (some) individual LGC passes using lit testing, a la `opt`-based tests in LLVM.

It does not address the issue of outside-IR state that makes it impossible to run some of the more complex passes in isolation. I do hope we'll be able to chip away at that problem over time, but for now, let's start somewhere simpler :)

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit b28d48c1ea7ef3da24c184a270427ed2ea9dc1e1
<details><summary>CTS tests (Failed: 0/277760)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 34841/70472 (49.4%)</li>
<li>Failed: 0/70472 (0.0%)</li>
<li>Not Supported: 35631/70472 (50.6%)</li><li>Warnings: 0/70472 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38907/70483 (55.2%)</li>
<li>Failed: 0/70483 (0.0%)</li>
<li>Not Supported: 31576/70483 (44.8%)</li><li>Warnings: 0/70483 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35750/70483 (50.7%)</li>
<li>Failed: 0/70483 (0.0%)</li>
<li>Not Supported: 34733/70483 (49.3%)</li><li>Warnings: 0/70483 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33476/66322 (50.5%)</li>
<li>Failed: 0/66322 (0.0%)</li>
<li>Not Supported: 32846/66322 (49.5%)</li><li>Warnings: 0/66322 (0.0%)</li>
</ul></details>


</ul></details>

**Review by trenouf — COMMENTED** [review]
This looks fine, but I was thinking of a less intrusive approach of having -start-at and -stop-before and -stop-after options for the instrumentor to use. That doesn't allow testing of an arbitrary sequence of passes, but it does allow a single pass, or a bunch of passes in the same sequence they are in normally.

Admittedly when I was thinking that it was on the old pass manager, but I think it should be possible on the new pass manager.

Did you consider something like that?

**Comment by amdvlk-admin** [comment]
### Test summary for commit b22020a13d24c688ebf22c7125b87f316d26aaa0
<details><summary>CTS tests (Failed: 0/277760)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 34841/70472 (49.4%)</li>
<li>Failed: 0/70472 (0.0%)</li>
<li>Not Supported: 35631/70472 (50.6%)</li><li>Warnings: 0/70472 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38907/70483 (55.2%)</li>
<li>Failed: 0/70483 (0.0%)</li>
<li>Not Supported: 31576/70483 (44.8%)</li><li>Warnings: 0/70483 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35750/70483 (50.7%)</li>
<li>Failed: 0/70483 (0.0%)</li>
<li>Not Supported: 34733/70483 (49.3%)</li><li>Warnings: 0/70483 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33476/66322 (50.5%)</li>
<li>Failed: 0/66322 (0.0%)</li>
<li>Not Supported: 32846/66322 (49.5%)</li><li>Warnings: 0/66322 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
I did consider it briefly. The reasons why I went with the -passes approach:

1. The analogy with `opt` is convenient and familiar.
2. -start/-stop only really allows you to run a single pass in a flexible manner, and then you always have to pass the pass name twice on the command-line.

In the past, I've found it convenient to be able to see what a sequence of passes does, e.g. imagine some of our transforms followed by generic optimization transforms for cleanups.

**Review by trenouf — APPROVED** [review]
LGTM

**Pull request merged**
