### PR TITLE
Remove per-shader table

### PR DESCRIPTION
**Pull request by amdrexu**
Per-shader table occupies the second user data SGPR. However, it is unused. This SGPR is wasted and sometime cause push constants to use spill table because of the oversizing of SGPR usage.

### CODE REVIEW

**Comment by amdrexu** [comment]
Reopen it: https://github.com/GPUOpen-Drivers/llpc/pull/2530

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2241daf4c1dc4a8f5796eed57eff5fade0798fb0
<details><summary>CTS tests (Failed: 0/211876)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70631 (50.3%)</li>
<li>Failed: 0/70631 (0.0%)</li>
<li>Not Supported: 35135/70631 (49.7%)</li><li>Warnings: 0/70631 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39379/70629 (55.8%)</li>
<li>Failed: 0/70629 (0.0%)</li>
<li>Not Supported: 31250/70629 (44.2%)</li><li>Warnings: 0/70629 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70616 (55.8%)</li>
<li>Failed: 0/70616 (0.0%)</li>
<li>Not Supported: 31203/70616 (44.2%)</li><li>Warnings: 0/70616 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 159c5293e7d5e0181a00323334fd366c38dd6e93
<details><summary>CTS tests (Failed: 0/211876)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70631 (50.3%)</li>
<li>Failed: 0/70631 (0.0%)</li>
<li>Not Supported: 35135/70631 (49.7%)</li><li>Warnings: 0/70631 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39379/70629 (55.8%)</li>
<li>Failed: 0/70629 (0.0%)</li>
<li>Not Supported: 31250/70629 (44.2%)</li><li>Warnings: 0/70629 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70616 (55.8%)</li>
<li>Failed: 0/70616 (0.0%)</li>
<li>Not Supported: 31203/70616 (44.2%)</li><li>Warnings: 0/70616 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM, yay for removing some waste :)

**Comment by jayfoad** [comment]
@amdrexu this is causing two CTS failures on Navi31 on internal testing:
```
CTS Test / ubuntu_22-04_navi31_vk-llvm-test / CTS.dEQP-VK.mesh_shader.ext.misc.mixed_pipelines
CTS Test / ubuntu_22-04_navi31_vk-llvm-test / CTS.dEQP-VK.mesh_shader.ext.misc.mixed_pipelines_dynamic_topology
```

**Comment by amdrexu** [comment]
Got it. I will investigate them. Thank you.

**Pull request merged**
