### PR TITLE
Tidy up use of Builder in SPIR-V reader

### PR DESCRIPTION
**Pull request by trenouf**
1. Changed name of field to SPIRVToLLVM::Builder instead of m_pBuilder,
   as it is in an LLVM-style class declaration.
2. Changed all uses of it to use a new method getBuilder().
3. Replaced almost all occurrences of Builder::SetInsertPoint(BB) with a
   single one at the top of the translate function.

Change-Id: I2b091b30d94ec60abfda587b7e6457e4731f7a6e

### CODE REVIEW

**Comment by trenouf** [comment]
All but topmost commit will disappear on rebase. Please review just the topmost commit.

**Comment by trenouf** [comment]
SPIRVReader.cpp:541:12: error: declaration of ‘Llpc::Builder* SPIRV::SPIRVToLLVM::Builder’ [-fpermissive]
builder/llpcBuilder.h:140:7: error: changes meaning of ‘Builder’ from ‘class Llpc::Builder’ [-fpermissive]

Oops. I should have tried building it on gcc first.

**Comment by trenouf** [comment]
V2: Fixed newer gcc compile error by not renaming m_pBuilder to Builder.
Also rebased.

**Comment by trenouf** [comment]
I will land this.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 50c834154292192396bcb500ef3f139950128800
<details open><summary>Driver commits used in build</summary><ul>

<li>METROHASH: amd-mainline 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 68b57dba33a4d922e8f1ef1b3781c2f659ffbd1c</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 331558e93794068a786bf699d3fe23bb11bac021</li>
<li>LLVM: amd-vulkan-dev f0a8af5e93d57b890687c7ced43943a0c3a167ca</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 925/925 (100.0%)</li>
<li>Failed: 0/925 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 366250/366250 (100.0%)</li>
<li>Failed: 0/366250 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 366376/366376 (100.0%)</li>
<li>Failed: 0/366376 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
