### PR TITLE
Add null image descriptor check for i64 imageLoad

### PR DESCRIPTION
**Pull request by amdrexu**
According to GL spec, unused components are filled with (0, 0, 0, 1)
for imageLoad(). Thus, the i64 image returns 1 in W channel. But the
robustness requirement expects a all-zero value when the image
descriptor is null. Thus, we have to add runtime check to handle this
special case since the W channel value is not from HW (hard-coded by
us). HW is unable to handle this.

Change-Id: I23aa29bf1fcd5fca459ada43678e2b994a85d175

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit d683611d3a51f94c3d0fa55a85b805ea78976808
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 3909a9fa55548c66e069a04ff79c96c8a7260851</li>
<li>SPVGEN: dev 8dc855026f2502ab3f45dadaf0bb802a57d6ad60</li>
<li>XGL: dev f4a992dd7e556ed5e7e2ffa2c830f1cd79bd4596</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev ea979e90c306a6ddec5db687e9c8d33b5289a23c</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/131499)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43839 (52.0%)</li>
<li>Failed: 0/43839 (0.0%)</li>
<li>Skipped: 21055/43839 (48.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22782/43843 (52.0%)</li>
<li><details><summary>Failed: 1/43843 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.float16.logical_nan.opfordgreaterthanequal_vector_vert
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 21060/43843 (48.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43817 (49.3%)</li>
<li>Failed: 0/43817 (0.0%)</li>
<li>Skipped: 22208/43817 (50.7%)</li>
</ul></details>


</ul></details>

**Comment by amdrexu** [comment]
retest this please

**Review by linqun — APPROVED** [review]
looks good to me. It is better if you can do the check before create image sample instruction.

**Comment by amdrexu** [comment]
> looks good to me. It is better if you can do the check before create image sample instruction.

To skip image instruction, you have to split current basic block and insert a branch instruction with null descriptor as the checking condition. I don't want to complicate code logic to handle such a corner case especially it is seldom used :)

**Comment by amdvlk-admin** [comment]
### Test summary for commit d683611d3a51f94c3d0fa55a85b805ea78976808
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 3909a9fa55548c66e069a04ff79c96c8a7260851</li>
<li>SPVGEN: dev 8dc855026f2502ab3f45dadaf0bb802a57d6ad60</li>
<li>XGL: dev f4a992dd7e556ed5e7e2ffa2c830f1cd79bd4596</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev ea979e90c306a6ddec5db687e9c8d33b5289a23c</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/131507)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43840 (52.0%)</li>
<li>Failed: 0/43840 (0.0%)</li>
<li>Skipped: 21056/43840 (48.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22783/43844 (52.0%)</li>
<li>Failed: 0/43844 (0.0%)</li>
<li>Skipped: 21061/43844 (48.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43823 (49.3%)</li>
<li>Failed: 0/43823 (0.0%)</li>
<li>Skipped: 22214/43823 (50.7%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
This is annoying -- but let's rely on the fact that in practice, if people are using the 64-bit texel support, they're not going to use the W channel realistically, so this code is going to be dead-code-eliminated. LGTM

**Comment by amdrexu** [comment]
> if people are using the 64-bit texel support, they're not going to use the W channel realistically,

Yes, only CTS tests are so crazy :)

**Pull request merged**
