### PR TITLE
Remove inline asm hack from CreateSubgroupBroadcastFirst

### PR DESCRIPTION
**Pull request by jayfoad**

### CODE REVIEW

**Comment by jayfoad** [comment]
This depends on #2747 - without that it will cause CTS failures.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5e3a86f32053e0513b6c3e084f7bb5946fd33cf3
<details><summary>CTS tests (Failed: 98/139021)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 41095/69517 (59.1%)</li>
<li><details><summary>Failed: 49/69517 (0.1%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_float
Stack trace: Crash

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_float_requiredsubgroupsize
Stack trace: Crash

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_i64vec3
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_i64vec4
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec2
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec3_requiredsubgroupsize
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec4
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_u64vec4
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_u64vec4_requiredsubgroupsize
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_uint_requiredsubgroupsize
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec4_requiredsubgroupsize
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_i64vec4_fragment
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec4_fragment
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_u64vec3_fragment
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uint_fragment
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec4_fragment
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.framebuffer.subgroupallequal_i64vec2_tess_control
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.framebuffer.subgroupallequal_i64vec4_tess_eval
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.framebuffer.subgroupallequal_int64_t_geometry
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.framebuffer.subgroupallequal_int_tess_control
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 28373/69517 (40.8%)</li><li>Warnings: 0/69517 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 41128/69504 (59.2%)</li>
<li><details><summary>Failed: 49/69504 (0.1%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_float
Stack trace: Crash

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_float_requiredsubgroupsize
Stack trace: Crash

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_i64vec3
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_i64vec4
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec2
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec3_requiredsubgroupsize
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec4
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_u64vec4
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_u64vec4_requiredsubgroupsize
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_uint_requiredsubgroupsize
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec4_requiredsubgroupsize
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_i64vec4_fragment
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec4_fragment
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_u64vec3_fragment
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uint_fragment
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec4_fragment
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.framebuffer.subgroupallequal_i64vec2_tess_control
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.framebuffer.subgroupallequal_i64vec4_tess_eval
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.framebuffer.subgroupallequal_int64_t_geometry
Stack trace: Fail

FAILURE: dEQP-VK.subgroups.vote.framebuffer.subgroupallequal_int_tess_control
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 28327/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by jayfoad** [comment]
I am confident that the CTS failures will go away if I retest after #2747 has been merged.

**Review by nhaehnle — COMMENTED** [review]
LGTM

**Comment by jayfoad** [comment]
Rebased.

**Comment by jayfoad** [comment]
> The retest should be done automatically by the way.

I could see that the internal CI build had finished but did not seem to have reported its status back to github.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 01271b9698d0032ef411c0f6d26e83712d286e45
<details><summary>CTS tests (Failed: 0/139021)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 41144/69517 (59.2%)</li>
<li>Failed: 0/69517 (0.0%)</li>
<li>Not Supported: 28373/69517 (40.8%)</li><li>Warnings: 0/69517 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 41177/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28327/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
