### PR TITLE
[CI] Fix git checkout for pull requests

### PR DESCRIPTION
**Pull request by kuhar**
This attempts to fix CI for incoming pull requests

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by kuhar** [comment]
(Investigating the issue exposed by the PR by @piotrAMD here)

I'm trying to understand why the GITHUB_REPOSITORY variable is not expanded for pull requests.
Perhaps we should be using some other environment variable instead?

**Comment by kuhar** [comment]
@piotrAMD Turns out that pull requests are not fetched by default and this is why the CI on your other PR failed. This PR fixes it.

**Comment by trenouf** [comment]
ok to test

**Comment by trenouf** [comment]
test this please

**Comment by trenouf** [comment]
I was hoping that would start the other half of the testing. Maybe I'm not admin-y enough and we'll have to wait for Jacob or Jax.

**Comment by kuhar** [comment]
> I was hoping that would start the other half of the testing. Maybe I'm not admin-y enough and we'll have to wait for Jacob or Jax.
Thanks for the effort :)
Anyhow, commits like this clearly don't effect the actual source of LLPC so Jenkins won't find anything...

**Comment by trenouf** [comment]
Agreed, but I definitely don't have the power to bypass that test and merge the change anyway.

**Comment by trenouf** [comment]
Oh, it has started a jenkins test now. I was just being impatient. :-)

**Comment by kuhar** [comment]
Sure, it was just an observation

**Comment by trenouf** [comment]
Oh dear. That was a spurious failure (ran out of disk space on a server). I'll leave it to Jacob and Jax to fix.

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0b951fca68d71e4d0d018c2df2b0cbef5fbe3789
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 40af910391fb8c287cb37bf520c41310bf88d405</li>
<li>SPVGEN: dev ce06cb5e3116ba77a22c3278dfeadfd865a8977c</li>
<li>XGL: dev 7e13a8bd0bb57d3cfb3bc014f6b26a8c9bb8bfd9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c22b8992220d645b9f781e4a47947ae546fcd11c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
