### PR TITLE
Fix unused push const variable

### PR DESCRIPTION
**Pull request by AMD-dwang**
Unused push const variables still also occupy spgr. In the following

operators, we will calculate the offset of the spgr according to the

arguments of entrypoint, so we must fill the whole push const.

### CODE REVIEW

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit c69e0c6c6f1bad3a46506fefdb8badecb16e2022
<details><summary>CTS tests (Failed: 1/215435)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 0/73202 (0.0%)</li>
<li>Failed: 0/73202 (0.0%)</li>
<li>Not Supported: 73202/73202 (100.0%)</li><li>Warnings: 0/73202 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 0/69031 (0.0%)</li>
<li>Failed: 0/69031 (0.0%)</li>
<li>Not Supported: 69031/69031 (100.0%)</li><li>Warnings: 0/69031 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37553/73202 (51.3%)</li>
<li><details><summary>Failed: 1/73202 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.graphicsfuzz.cov-instruction-simplify-atanh-log-undefined
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 35648/73202 (48.7%)</li><li>Warnings: 0/73202 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
Can you please explain this better? I thought part of the point of the code was to *not* add SGPR arguments for push constant dwords that are unused, so that we can be more efficient by avoiding to load those extra SGPRs.

A test case would probably help, too.

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit c69e0c6c6f1bad3a46506fefdb8badecb16e2022
<details><summary>CTS tests (Failed: 0/214796)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 0/72989 (0.0%)</li>
<li>Failed: 0/72989 (0.0%)</li>
<li>Not Supported: 72989/72989 (100.0%)</li><li>Warnings: 0/72989 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 0/68818 (0.0%)</li>
<li>Failed: 0/68818 (0.0%)</li>
<li>Not Supported: 68818/68818 (100.0%)</li><li>Warnings: 0/68818 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37553/72989 (51.5%)</li>
<li>Failed: 0/72989 (0.0%)</li>
<li>Not Supported: 35436/72989 (48.5%)</li><li>Warnings: 0/72989 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by AMD-dwang** [comment]
> Can you please explain this better? I thought part of the point of the code was to _not_ add SGPR arguments for push constant dwords that are unused, so that we can be more efficient by avoiding to load those extra SGPRs.
> 
> A test case would probably help, too.

All push constant dwords seem to be initialized in driver, so we have to keep consistent in compiler. I added a test.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 10dacfe6bf14056bbf0b9d5ef2a35f44032941c1
<details><summary>CTS tests (Failed: 0/218967)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35298/72989 (48.4%)</li>
<li>Failed: 0/72989 (0.0%)</li>
<li>Not Supported: 37691/72989 (51.6%)</li><li>Warnings: 0/72989 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/72989 (52.7%)</li>
<li>Failed: 0/72989 (0.0%)</li>
<li>Not Supported: 34498/72989 (47.3%)</li><li>Warnings: 0/72989 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37553/72989 (51.5%)</li>
<li>Failed: 0/72989 (0.0%)</li>
<li>Not Supported: 35436/72989 (48.5%)</li><li>Warnings: 0/72989 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
Is this fixing a real bug that was encountered somewhere?

I see code in PAL's `CmdStream::WriteUserDataEntriesToSgprs` that at least seems to attempt to handle the case where the user data mapping is not 1:1 between the `SPI_SHADER_USER_DATA_*` registers and the user data entries provided by the Vulkan driver. Specifically, note the part that does:
```
   pCmdPayload[sgpr] = entries.entries[entryMap.mappedEntry[sgpr]];
```
I.e., there's indirection via the mappedEntry table.

So at least the intention seems to be for the driver to support this better?

**Comment by AMD-dwang** [comment]
> Is this fixing a real bug that was encountered somewhere?
> 
> I see code in PAL's `CmdStream::WriteUserDataEntriesToSgprs` that at least seems to attempt to handle the case where the user data mapping is not 1:1 between the `SPI_SHADER_USER_DATA_*` registers and the user data entries provided by the Vulkan driver. Specifically, note the part that does:
> 
> ```
>    pCmdPayload[sgpr] = entries.entries[entryMap.mappedEntry[sgpr]];
> ```
> 
> I.e., there's indirection via the mappedEntry table.
> 
> So at least the intention seems to be for the driver to support this better?

Yes,  Please look at the added lit test. If we don't add the unused push constant, the exported `viewIndex` will be incorrect. but confusingly, the same shader is correct in some cases.  I can forward the test to you, that you can refer. Thanks.

**Comment by nhaehnle** [comment]
FWIW, there's an ongoing internal discussion about the underlying test failure, and so far I don't believe the root cause is properly understood. We should avoid this particular change because reserving unnecessary user data registers has a negative performance impact.

**Pull request closed without merging**
