### PR TITLE
Handle null descriptor in patchCubeDescriptor on pre gfx9

### PR DESCRIPTION
**Pull request by xuechen417**
Add extral check for null descriptor when patching descriptor with cube
dimision pre gfx9. This change will keep a null descritpor unchanged
before and after patching when allowNullDescriptor option is enabled.

Fixes: dEQP-VK.robustness.robustness2.bind.*.r64*.*.storage_image.*.null_descriptor.samples_1.cube*

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit ba395285fa8b0ef5de1c78c6a20f78454e0c635d
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev c9937b277c491a55c689eec7cdd48fb238b8004c</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev c6c90450fb1abf5f414acf1e38a0f51a72c426c1</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1598ada40008302abedfd724275329f8e7dea637</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/131664)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 24006/43895 (54.7%)</li>
<li>Failed: 0/43895 (0.0%)</li>
<li>Skipped: 19889/43895 (45.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 24005/43895 (54.7%)</li>
<li>Failed: 0/43895 (0.0%)</li>
<li>Skipped: 19890/43895 (45.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 22647/43874 (51.6%)</li>
<li>Failed: 0/43874 (0.0%)</li>
<li>Skipped: 21227/43874 (48.4%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
This seems reasonable, but wouldn't it be even better to instead do two selects of elem3 and elem4 before the CreateInsertElement? Something like:
```
  if (m_pipelineState->getOptions().allowNullDescriptor) {
  depth = CreateAdd(depth, getInt32(5));
    // Check dword3 against 0 for a null descriptor
    Value *zero = getInt32(0);
    Value *isNullDesc = CreateICmpEQ(originalElem3, zero);
    elem3 = CreateSelect(isNullDesc, zero, elem3);
    elem4 = CreateSelect(isNullDesc, zero, elem4);
  } 

  // Reassemble descriptor.
  desc = CreateInsertElement(desc, elem4, 4);
  desc = CreateInsertElement(desc, elem3, 3);
```
That way, we only need 2 x s_cselect_b32 instructions (which the backend could perhaps even optimize to a single s_cselect_b64) instead of 3 x s_cselect_b32.

**Comment by xuechen417** [comment]
V1: Fix to use two selects of elem3 and elem4. Please review.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8df04160a2d06e6c54603182683383c7e5edb19a
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev c9937b277c491a55c689eec7cdd48fb238b8004c</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev c6c90450fb1abf5f414acf1e38a0f51a72c426c1</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1598ada40008302abedfd724275329f8e7dea637</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/140859)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 24006/46960 (51.1%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 22954/46960 (48.9%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 24005/46960 (51.1%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 22955/46960 (48.9%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 22647/46939 (48.2%)</li>
<li>Failed: 0/46939 (0.0%)</li>
<li>Skipped: 24292/46939 (51.8%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
