### PR TITLE
Add VKGC defines for providing pipeline-level resource mapping

### PR DESCRIPTION
**Pull request by mdinkov**
The newly defined structures here are needed for the compiler
independent code in Vulkan as a common vehicle of the resource mapping
data. The LLPC implementation code has been seperated into a seperate
change so that it can undergo a more scrutinous review.

The LLPC internals use pipeline-level resource mapping. However, the
VKGC interface used shader-level resource mapping due to other Vulkan
dependencies. Now that those dependencies have moved to pipeline-level
mapping, the compiler independent code (and the VKGC interface) are
being switched over to pipeline-level resource mapping as well.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4a4349edabcbca1ac97c2dda7c526b71b2ff321c
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev ea5db60841dab7d067f5010f28a980ef222bdf81</li>
<li>SPVGEN: dev 8dc855026f2502ab3f45dadaf0bb802a57d6ad60</li>
<li>XGL: dev 8d9da0426ba869f5f3da23fd72cfaa669ce99c25</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 8abd9486af1727c8c38afcfef7390d70bb7d7d89</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/294076)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>No Results</li>

</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 147018/147018 (100.0%)</li>
<li>Failed: 0/147018 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 147058/147058 (100.0%)</li>
<li>Failed: 0/147058 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4a4349edabcbca1ac97c2dda7c526b71b2ff321c
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev ea5db60841dab7d067f5010f28a980ef222bdf81</li>
<li>SPVGEN: dev 8dc855026f2502ab3f45dadaf0bb802a57d6ad60</li>
<li>XGL: dev 8d9da0426ba869f5f3da23fd72cfaa669ce99c25</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 8abd9486af1727c8c38afcfef7390d70bb7d7d89</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/294076)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>No Results</li>

</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 147018/147018 (100.0%)</li>
<li>Failed: 0/147018 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 147058/147058 (100.0%)</li>
<li>Failed: 0/147058 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
Can we please wait to merge this until the main points of the dependent PR #849 have been sorted out? I'm asking this merely in case the discussion there leads to some necessary changes here.

**Comment by amdrexu** [comment]
@nhaehnle It's OK. You can request changes and block it tentatively until the other PR is modified as your expectation.

**Pull request merged**
