### PR TITLE
Removed now-unused image op .ll files

### PR DESCRIPTION
**Pull request by trenouf**
Thanks to Qun for spotting this.

Change-Id: I7fe2dd06f66351bac542fe4c1cd98345bfecd62e

### CODE REVIEW

**Comment by trenouf** [comment]
Thanks; good point. :-)

**Comment by trenouf** [comment]
I will land this.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 7ae0cfedd247e49edd5a2ababbba6f2e75c384d5
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 46251728a7137f399b564b0886bd9bf9888c48ef</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev c740412cd4afe87d79a487bd375996d52360a3a0</li>
<li>LLVM: amd-vulkan-dev 9bc5dd4450a6361faf5c5661056a7ee494fad830</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 925/925 (100.0%)</li>
<li>Failed: 0/925 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 365531/365531 (100.0%)</li>
<li>Failed: 0/365531 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 365657/365657 (100.0%)</li>
<li>Failed: 0/365657 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 62e9f1842c846513ce8bd01687f96f736f902b90
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 46251728a7137f399b564b0886bd9bf9888c48ef</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev c740412cd4afe87d79a487bd375996d52360a3a0</li>
<li>LLVM: amd-vulkan-dev 9bc5dd4450a6361faf5c5661056a7ee494fad830</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 925/925 (100.0%)</li>
<li>Failed: 0/925 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 365531/365531 (100.0%)</li>
<li>Failed: 0/365531 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 365657/365657 (100.0%)</li>
<li>Failed: 0/365657 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
