### PR TITLE
Fix a latent issue when rasterization stream of GS is not 0

### PR DESCRIPTION
**Pull request by amdrexu**
We do in-out matching for GS-FS. But GS could support non-zero rasterization stream. This was not tested before because of the disablement of Vulkan driver capability
transformFeedbackRasterizationStreamSelect = VK_FALSE.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
e5557ce33790945bf2ae449d95bd330daba7b013 Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:2814:15: error: ‘struct Vkgc::PipelineOptions’ has no member named ‘enableImplicitInvariantExports’
     pOptions->enableImplicitInvariantExports = (settings.disableImplicitInvariantExports == false);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2990/3062] Building CXX object icd/CMakeFiles/xgl.dir/api/vk_cmd_pool.cpp.o
In file included from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/../gpurt/gpurt/gpurt.h:34:0,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/include/vk_conv.h:53,

**Comment by amdvlk-admin** [comment]
e5557ce33790945bf2ae449d95bd330daba7b013 Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:2814:15: error: ‘struct Vkgc::PipelineOptions’ has no member named ‘enableImplicitInvariantExports’
     pOptions->enableImplicitInvariantExports = (settings.disableImplicitInvariantExports == false);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2990/3062] Building CXX object icd/CMakeFiles/xgl.dir/api/virtual_stack_mgr.cpp.o
In file included from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/../gpurt/gpurt/gpurt.h:34:0,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/include/vk_conv.h:53,

**Review by nhaehnle — COMMENTED** [review]
The change mostly LGTM, but one question. Perhaps this is a bit theoretical, but I suspect that after finding `origLocInfo` in the `nextStageInputLocInfoMap`, we should still check whether the output call's stream ID is equal to the rasterStream. If it isn't, then the locations match but the GS output would be written to a different stream and logically isn't sent to the FS. Does that make sense?

**Comment by amdrexu** [comment]
> The change mostly LGTM, but one question. Perhaps this is a bit theoretical, but I suspect that after finding `origLocInfo` in the `nextStageInputLocInfoMap`, we should still check whether the output call's stream ID is equal to the rasterStream. If it isn't, then the locations match but the GS output would be written to a different stream and logically isn't sent to the FS. Does that make sense?

This is done in `PatchCopyShader::exportOutput`. See this code piece :)

```
  // Following non-XFB output exports are only for rasterization stream
  if (resUsage->inOutUsage.gs.rasterStream != streamId)
    return;
```

**Comment by amdvlk-admin** [comment]
### Test summary for commit a91e48fa2dbf47bc3859f6cf876fbce4fc1b98ad
<details><summary>CTS tests (Failed: 0/213076)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71028 (56.9%)</li>
<li>Failed: 0/71028 (0.0%)</li>
<li>Not Supported: 30602/71028 (43.1%)</li><li>Warnings: 0/71028 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71018 (57.0%)</li>
<li>Failed: 0/71018 (0.0%)</li>
<li>Not Supported: 30554/71018 (43.0%)</li><li>Warnings: 0/71018 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36471/71030 (51.3%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 34559/71030 (48.7%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
