### PR TITLE
Rationalize Builder methods, opcodes and call names

### PR DESCRIPTION
**Pull request by trenouf**
Previously, the opcodes and call names for recorded builder calls were
inconsistent with the builder method names. The method names do not
have a prepended category, which is right, because the division of
BuilderImpl into categories is an internal implementation detail.

This commit similarly changes the opcodes and call names to match --
there is no need for a prepended category, because the categories are an
internal implementation detail of BuilderImpl.

So, for example, to "create a load of a buffer descriptor", the method
name already used that natural order of words:
  Builder::CreateLoadBufferDesc.
I have now changed the opcode to match:
  BuilderRecorder::Opcode::LoadBufferDesc
and I have changed the call name to match:
  llpc.call.load.buffer.desc.

Change-Id: Id37bb3a022d9d8a4c737d27d60d4e69cc3ff6902

### CODE REVIEW

**Comment by trenouf** [comment]
This PR currently contains 3 commits. Once the first two are merged from their separate PRs, I will rebase this one.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 63581c241c3b4638fba4645e616f6785a577af95
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev fb9a4dc951c0afd737460b26afb716c96e966b77</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev eaecf6b9ad7bc3d310e752528f84fd52fba23747</li>
<li>LLVM: amd-vulkan-dev f41e1a873108a371ae5574d518c1ee6eb3814cee</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 893/893 (100.0%)</li>
<li>Failed: 0/893 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 312578/312622 (100.0%)</li>
<li><details><summary>Failed: 44/312622 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.1
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.5
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.12
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.14
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.37
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.40
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.49
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.56
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.58
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.70
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.suballocation.attachment_allocation.input_output.91
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.dedicated_allocation.attachment_allocation.input_output.1
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.dedicated_allocation.attachment_allocation.input_output.5
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.dedicated_allocation.attachment_allocation.input_output.12
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.dedicated_allocation.attachment_allocation.input_output.14
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.dedicated_allocation.attachment_allocation.input_output.37
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.dedicated_allocation.attachment_allocation.input_output.40
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.dedicated_allocation.attachment_allocation.input_output.49
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.dedicated_allocation.attachment_allocation.input_output.56
Stack trace: Result verification failed

FAILURE: dEQP-VK.renderpass.dedicated_allocation.attachment_allocation.input_output.58
Stack trace: Result verification failed
...
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
Please ignore this test result, I'll trigger it again after switching to CTS 1.1.2.3.

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by trenouf** [comment]
OK thanks Jacob.

**Comment by JacobHeAMD** [comment]
Hi @trenouf , please rebase the pull request to the latest dev code, there is a change to add an option to enable lit test. Jenkins test can't pass without it. Please rebase your other Pull requests as well. Sorry for the inconvenience.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 287ef44368e5478a28ca22991d1defc3b02446ba
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev fb9a4dc951c0afd737460b26afb716c96e966b77</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 9490055b71ec89be68c1ed4a3a847569c0ac3cbf</li>
<li>LLVM: amd-vulkan-dev f41e1a873108a371ae5574d518c1ee6eb3814cee</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 893/893 (100.0%)</li>
<li>Failed: 0/893 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 234747/234748 (100.0%)</li>
<li><details><summary>Failed: 1/234748 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.spirv_assembly.type.vec4.u16.clamp_test_high_part_zero_geom
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 375327/375327 (100.0%)</li>
<li>Failed: 0/375327 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 287ef44368e5478a28ca22991d1defc3b02446ba
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev fb9a4dc951c0afd737460b26afb716c96e966b77</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 9490055b71ec89be68c1ed4a3a847569c0ac3cbf</li>
<li>LLVM: amd-vulkan-dev f41e1a873108a371ae5574d518c1ee6eb3814cee</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 893/893 (100.0%)</li>
<li>Failed: 0/893 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 366444/366444 (100.0%)</li>
<li>Failed: 0/366444 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 366444/366444 (100.0%)</li>
<li>Failed: 0/366444 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
Hi trenouf, please resolve conflicts.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 7eb2e323ff2d0d26ca50ecfcf67c4996b5a569e2
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev fb9a4dc951c0afd737460b26afb716c96e966b77</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 9490055b71ec89be68c1ed4a3a847569c0ac3cbf</li>
<li>LLVM: amd-vulkan-dev f41e1a873108a371ae5574d518c1ee6eb3814cee</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 893/893 (100.0%)</li>
<li>Failed: 0/893 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 366444/366444 (100.0%)</li>
<li>Failed: 0/366444 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 366444/366444 (100.0%)</li>
<li>Failed: 0/366444 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
