### PR TITLE
lgc: Remove Builder::setShaderStage() and Pipeline::setShaderStageMask()

### PR DESCRIPTION
**Pull request by trenouf**
Follow-up changes after removing builder direct mode, so we know that the front-end is always using BuilderRecorder:

Builder no longer needs the front-end to say what shader stage it is currently generating, so I have pushed setShaderStage() down into BuilderImplBase for use by BuilderReplayer. The only thing the front-end was using it for was as the implicit current shader stage for setCommonShaderMode(), so I have added an explicit shaderStage arg to that.

Builder no longer needs the front-end to specify the shader stage mask up front, so I have removed Pipeline::setShaderStageMask from the LGC interface.

Also remove the m_isBuilderRecorder flag.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
cad67e64aca6ee50a5a6b3b9ebe4a4437b381100 Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/builder/Builder.cpp:440:0: error: unterminated #if
 #if VKI_RAY_TRACING
 
[2411/2957] Building CXX object compiler/llpc/llvm/lib/Target/AMDGPU/CMakeFiles/LLVMAMDGPUCodeGen.dir/AMDGPUAliasAnalysis.cpp.o
[2412/2957] Building CXX object compiler/llpc/CMakeFiles/amdllpc.dir/tool/amdllpc.cpp.o
[2413/2957] Building CXX object compiler/llpc/CMakeFiles/llpc.dir/translator/lib/SPIRV/libSPIRV/SPIRVModule.cpp.o

**Comment by trenouf** [comment]
This won't work until I have got #2198 merged.

**Review by nhaehnle — COMMENTED** [review]
Spurious change in llvm-dialects?

Apart from that this seems reasonable. Conceptually, the _insertion_ of a dialect op shouldn't have to know the shader stage. It might factor into some validity checks, but that's it. It's the *lowering* which is more likely to need to know the stage, but the lowering is a pass, not a builder. If that makes sense :)

**Comment by amdvlk-admin** [comment]
fdf92a0d5f842cc585256b7b0e0bb474f733211e Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/builder/Builder.cpp:440:0: error: unterminated #if
 #if VKI_RAY_TRACING
 
[2418/2957] Building CXX object compiler/llpc/CMakeFiles/llpc_standalone_compiler.dir/tool/llpcCompilationUtils.cpp.o
[2419/2957] Building CXX object compiler/llpc/CMakeFiles/amdllpc.dir/tool/amdllpc.cpp.o
[2420/2957] Building CXX object compiler/llpc/CMakeFiles/llpc.dir/translator/lib/SPIRV/libSPIRV/SPIRVModule.cpp.o

**Comment by amdvlk-admin** [comment]
### Test summary for commit a59a2be56f87cb098912a6e91e82339e49419230
<details><summary>CTS tests (Failed: 1/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38863/70485 (55.1%)</li>
<li><details><summary>Failed: 1/70485 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.op.multi_queue.timeline_semaphore.write_clear_color_image_read_image_compute_indirect.image_128_r32_uint_concurrent
Stack trace: Flake
```
</p></details></li>

<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70485 (55.5%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit a59a2be56f87cb098912a6e91e82339e49419230
<details><summary>CTS tests (Failed: 0/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70485 (55.1%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70485 (55.5%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
