### PR TITLE
LLPC frontend SPIR-V reader: Change UndefValue to PoisonValue

### PR DESCRIPTION
**Pull request by amdrexu**
To follow the upcoming LLVM change: https://reviews.llvm.org/D152658.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 29fe4cb588b71a60b575895629fa4df28252ce2e
<details><summary>CTS tests (Failed: 1/211329)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39098/70446 (55.5%)</li>
<li><details><summary>Failed: 1/70446 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_uniform_buffer.1024
Stack trace: Flake
```
</p></details></li>

<li>Not Supported: 31347/70446 (44.5%)</li><li>Warnings: 0/70446 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39131/70435 (55.6%)</li>
<li>Failed: 0/70435 (0.0%)</li>
<li>Not Supported: 31304/70435 (44.4%)</li><li>Warnings: 0/70435 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35186/70448 (49.9%)</li>
<li>Failed: 0/70448 (0.0%)</li>
<li>Not Supported: 35262/70448 (50.1%)</li><li>Warnings: 0/70448 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8287d598d0637e049d64cc6b36a02be3200a8b7c
<details><summary>CTS tests (Failed: 0/211329)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39099/70446 (55.5%)</li>
<li>Failed: 0/70446 (0.0%)</li>
<li>Not Supported: 31347/70446 (44.5%)</li><li>Warnings: 0/70446 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39131/70435 (55.6%)</li>
<li>Failed: 0/70435 (0.0%)</li>
<li>Not Supported: 31304/70435 (44.4%)</li><li>Warnings: 0/70435 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35186/70448 (49.9%)</li>
<li>Failed: 0/70448 (0.0%)</li>
<li>Not Supported: 35262/70448 (50.1%)</li><li>Warnings: 0/70448 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit c23ff7810a767b6944ae4ccc3baf65b59280ef92
<details><summary>CTS tests (Failed: 0/211329)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39099/70446 (55.5%)</li>
<li>Failed: 0/70446 (0.0%)</li>
<li>Not Supported: 31347/70446 (44.5%)</li><li>Warnings: 0/70446 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39131/70435 (55.6%)</li>
<li>Failed: 0/70435 (0.0%)</li>
<li>Not Supported: 31304/70435 (44.4%)</li><li>Warnings: 0/70435 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35186/70448 (49.9%)</li>
<li>Failed: 0/70448 (0.0%)</li>
<li>Not Supported: 35262/70448 (50.1%)</li><li>Warnings: 0/70448 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit c23ff7810a767b6944ae4ccc3baf65b59280ef92
<details><summary>CTS tests (Failed: 206/211318)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38944/70433 (55.3%)</li>
<li><details><summary>Failed: 156/70433 (0.2%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.16
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_16_even_repeat_2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_4_even_repeat_2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_64_even_repeat_8
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_64_odd_repeat_4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_64_odd_repeat_8
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_1_6
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_2_3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_2_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_2_6
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_3_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_4_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_5_1
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_5_3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_7_2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_7_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_8_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_8_7
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 31333/70433 (44.5%)</li><li>Warnings: 0/70433 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39106/70436 (55.5%)</li>
<li><details><summary>Failed: 25/70436 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.8
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.16
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.bvec2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.bvec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat2x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat3x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat2x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat3x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32vec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat2x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat3x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat3x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat4x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64vec3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.float64_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.i8vec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int16_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int32_t
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 31305/70436 (44.4%)</li><li>Warnings: 0/70436 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35161/70449 (49.9%)</li>
<li><details><summary>Failed: 25/70449 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.8
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.16
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.max_workgroup_memory.4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.bvec2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.bvec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat2x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat3x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat2x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat3x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32vec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat2x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat3x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat3x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat4x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64vec3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.float64_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.i8vec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int16_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int32_t
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 35263/70449 (50.1%)</li><li>Warnings: 0/70449 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
