### PR TITLE
Refine LLPC

### PR DESCRIPTION
**Pull request by linqun**
1. Simplify API shader hash code, API shader hash code isn't used as a shader cache key, we needn't make it unique, this change use SPIRV hash code as API shader code in BIL.
2. Move CodeGenManager::Run to Llpc::PassManager and set LlpcDiagnosticHandler in llpcCompiler
3. Remove unused code

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit c6855fe3c24c1c9ce6141db22a94635a59df8ab5
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 99901922d67e502ff4233a8bfcbfa0347c0ffa1b</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 9795e006e9adb7b49b8abd32cd47c49b290fa3fc</li>
<li>LLVM: amd-vulkan-dev 1ca248e6fc6d4d15491756f92f4da139222ef3ca</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit c6855fe3c24c1c9ce6141db22a94635a59df8ab5
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 99901922d67e502ff4233a8bfcbfa0347c0ffa1b</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 9795e006e9adb7b49b8abd32cd47c49b290fa3fc</li>
<li>LLVM: amd-vulkan-dev 1ca248e6fc6d4d15491756f92f4da139222ef3ca</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit c6855fe3c24c1c9ce6141db22a94635a59df8ab5
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 99901922d67e502ff4233a8bfcbfa0347c0ffa1b</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 9795e006e9adb7b49b8abd32cd47c49b290fa3fc</li>
<li>LLVM: amd-vulkan-dev 1ca248e6fc6d4d15491756f92f4da139222ef3ca</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit c6855fe3c24c1c9ce6141db22a94635a59df8ab5
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 14045067091d226072437527359a54c8b8e898eb</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 54194f5ebb7d1d6b44b9eb87217041f44e08f789</li>
<li>LLVM: amd-vulkan-dev 1ca248e6fc6d4d15491756f92f4da139222ef3ca</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit c6855fe3c24c1c9ce6141db22a94635a59df8ab5
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 14045067091d226072437527359a54c8b8e898eb</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 54194f5ebb7d1d6b44b9eb87217041f44e08f789</li>
<li>LLVM: amd-vulkan-dev 1ca248e6fc6d4d15491756f92f4da139222ef3ca</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 901/901 (100.0%)</li>
<li>Failed: 0/901 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
