### PR TITLE
Refine NGG implementation

### PR DESCRIPTION
**Pull request by amdrexu**
- Remove NGG culling .ll files.
- Add NGG culling creator by IR builder.
- Export more dummy positions based on actual position exporting.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9ad3922a0b37a54544b892d72577e6ffc7fca509
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 66e78b997748d03d77e1d706c10f1f17e18e5654</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 9b632ef4f132bddc94769702ed8b49efbc39d89c</li>
<li>LLVM: amd-vulkan-dev 9bc5dd4450a6361faf5c5661056a7ee494fad830</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 925/925 (100.0%)</li>
<li>Failed: 0/925 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 365531/365531 (100.0%)</li>
<li>Failed: 0/365531 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 365657/365657 (100.0%)</li>
<li>Failed: 0/365657 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
Hi Rex. This gives me an error on clang with warnings-as-errors cranked up:

../icd/api/llpc/patch/gfx9/llpcNggPrimShader.cpp:4059:14: error: unused variable 'pZFar' [-Werror,-Wunused-variable]
        auto pZFar = ConstantFP::get(m_pBuilder->getFloatTy(), 1.0);

**Comment by amdrexu** [comment]
Thanks, Tim. I fix it.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 59f96046e03e45f4d79d6d2a695383624034ce7e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 66e78b997748d03d77e1d706c10f1f17e18e5654</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 9b632ef4f132bddc94769702ed8b49efbc39d89c</li>
<li>LLVM: amd-vulkan-dev 9bc5dd4450a6361faf5c5661056a7ee494fad830</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 925/925 (100.0%)</li>
<li>Failed: 0/925 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 365531/365531 (100.0%)</li>
<li>Failed: 0/365531 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 365657/365657 (100.0%)</li>
<li>Failed: 0/365657 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
