### PR TITLE
Add to retrieveShader the return ErrorOutOfMemory

### PR DESCRIPTION
**Pull request by ArkadiuszSarwaAMD**

### CODE REVIEW

**Review by amdrexu — APPROVED** [review]
I think this is internally discussed and is reviewed.

**Review by nhaehnle — APPROVED** [review]
Yes, it looks good to me.

**Comment by nhaehnle** [comment]
I'm not sure if @ArkadiuszSarwaAMD  is able to merge, so I went ahead and did it.

**Comment by ArkadiuszSarwaAMD** [comment]
I wasn't able to merge it, Thank you Nicolai

**Pull request merged**
