### PR TITLE
Disable relocatable shader compilation when DescriptorBufferCompact is used.

### PR DESCRIPTION
**Pull request by csyonghe**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by s-perron** [comment]
We can do it however you would like.  I had a preference to fail early.  If things are not cached, we will end up compiling the shader twice if we wait until the link step to decide if we can do the relocatable shaders.

In the situation where we want to build a cache offline, we won't have the user data, and we will want to build each shader individually without link at all  However, that is different from the in-game path.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by csyonghe** [comment]
Any details on the failure?

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
> Any details on the failure?

seem likes test system's issue.

**Comment by JaxLinAMD** [comment]
> Any details on the failure?

seems like it's a problem of test system

**Comment by JaxLinAMD** [comment]
@csyonghe , it seems your pull request is not bases on the latets revsion, could you rebase your pull request so that jekins build can pass?

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit f3cd1d949913afef5f378640c24c9d717c21b9e4
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev ddcaa1009ecde219613042a5a53c6d3752bf4b9d</li>
<li>SPVGEN: dev d4817ab957f79762da83b7fc1d3f2816dbdc13fd</li>
<li>XGL: dev 278ee18285659b865ddc65f3a156c98264c8c801</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 53692d985a53a336e07907c2d4b86bf2deb66908</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 958/958 (100.0%)</li>
<li>Failed: 0/958 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103143/103143 (100.0%)</li>
<li>Failed: 0/103143 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103199/103199 (100.0%)</li>
<li>Failed: 0/103199 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 103199/103199 (100.0%)</li>
<li>Failed: 0/103199 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
I know this is already merged :-) but I don't see the point of this particular check. Firstly, if you have a compact descriptor in the pipeline state, you don't actually know whether it is going to be used in the shader, so it seems a bit over-conservative to say you can't do shader compilation. Secondly, if you have user data layout available at the time you do shader compilation, then we can make it so that compact descriptors are allowed, because we can pass the user data layout into LGC and we don't need to do relocs at all. (Currently it suppresses the user data layout when doing a shader compilation from Compiler::buildPipelineWithRelocatableElf, because that is how we test relocs.)

**Comment by csyonghe** [comment]
The point of relocatable shaders compilation is to build reusable shaders regardless of user data nodes. The current way to trigger shader compilation is still to run the game/traces and store the generated shader cache. This requires us to tell whether a pipeline can be compiled by relocatable path in the driver. Since the relocatable path currently doesn't support compact buffers, we need to add this check to guard the path selection. I don't quite understand what you mean by "making it so that compact descriptors are allowed" if the compilation path cannot support it. It also makes no sense to me to go through the relocatable path if the compiled shader is dependent on the user data node. In my understanding, the way to "allow" it, is to fall back to the default compilation path.

**Pull request merged**
