### PR TITLE
Add a helper function gets componenet count for deriv in one direction

### PR DESCRIPTION
**Pull request by xazhangAMD**

### CODE REVIEW

**Comment by trenouf** [comment]
ok to test

(I think that's what I need to say to get testing to start)

**Review by trenouf — APPROVED** [review]
LGTM

**Comment by trenouf** [comment]
Typo componenet -> component in commit message summary line. Could you "squash-and-merge" and fix the typo when it lets you edit the commit message please?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 90a30d1f7821b70d496c252739ee8909c74052b9
<details><summary>CTS tests (Failed: 1/141308)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40067/70655 (56.7%)</li>
<li>Failed: 0/70655 (0.0%)</li>
<li>Not Supported: 30588/70655 (43.3%)</li><li>Warnings: 0/70655 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40105/70653 (56.8%)</li>
<li><details><summary>Failed: 1/70653 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.clipping.user_defined.clip_cull_distance_dynamic_index.vert.2_6_fragmentshader_read
Stack trace: Flake
```
</p></details></li>

<li>Not Supported: 30547/70653 (43.2%)</li><li>Warnings: 0/70653 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 90a30d1f7821b70d496c252739ee8909c74052b9
<details><summary>CTS tests (Failed: 0/141320)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40065/70667 (56.7%)</li>
<li>Failed: 0/70667 (0.0%)</li>
<li>Not Supported: 30602/70667 (43.3%)</li><li>Warnings: 0/70667 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40106/70653 (56.8%)</li>
<li>Failed: 0/70653 (0.0%)</li>
<li>Not Supported: 30547/70653 (43.2%)</li><li>Warnings: 0/70653 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by xazhangAMD** [comment]
> Typo componenet -> component in commit message summary line. Could you "squash-and-merge" and fix the typo when it lets you edit the commit message please?

I doesn't seem to have the write access so I cannot squash-and-merge... Can you please help to do this？

**Pull request merged**
