### PR TITLE
Add unittest

### PR DESCRIPTION
**Pull request by AMD-dwang**
Add the topology hash test for commit '6b3f2109a0c8c17080f3cd60c80f89d9e9f7a73f'.

### CODE REVIEW

**Review by s-perron — APPROVED** [review]

**Comment by amdrexu** [comment]
@AMD-dwang Please check if there are any testing issues that are relevant to your changes. If not, I will approve and merge it tomorrow. Thanks.

**Comment by AMD-dwang** [comment]
> @AMD-dwang Please check if there are any testing issues that are relevant to your changes. If not, I will approve and merge it tomorrow. Thanks.

The failures are irrelevant to my change. Thanks.

**Review by amdrexu — APPROVED** [review]

**Comment by dstutt** [comment]
There was a test failure related to this change - the following line is required before the TEST macros for the tests:
// cppcheck-suppress syntaxError
which appears after the inserted unit test.
See #1736

**Comment by AMD-dwang** [comment]
> There was a test failure related to this change - the following line is required before the TEST macros for the tests: // cppcheck-suppress syntaxError which appears after the inserted unit test. See #1736

Thanks.

**Pull request merged**
