### PR TITLE
Fix Red dead redemption2 crash when PackInOut enabled

### PR DESCRIPTION
**Pull request by xuechen417**
- The root cause is there is a potential memeory release crash by using std::unordered_set for dead calls collection. The dead call set is used to collect scalarized output.export.generic* calls when PackInOut enabled.
- I made a test it will crash when the number of calls is over 65. Unfortunately, this game has 74 output.export.generic* calls after scalarizing.
- The fix is to use llvm::DenseSet as the container for m_deadCalls.

### CODE REVIEW

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit efa575f871ed5e67d777fb128eae774016743968
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 82390674c40402c81dbf311a5ee488fb972894f5</li>
<li>SPVGEN: dev 2f679769a8491f423f5cf2f06adfa2870a82935d</li>
<li>XGL: dev 116d28a446eba3a9f8e6f577bab34fc07e090993</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 0c3b9cd01021a1b221ea7b08733989d322adf395</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 965/965 (100.0%)</li>
<li>Failed: 0/965 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx8</summary><ul>

<li>Passed: 103165/103165 (100.0%)</li>
<li>Failed: 0/103165 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Gfx9</summary><ul>

<li>Passed: 103221/103221 (100.0%)</li>
<li>Failed: 0/103221 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx10</summary><ul>

<li>Passed: 103221/103221 (100.0%)</li>
<li>Failed: 0/103221 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3c5fefad421f605361867bd5ca88a7d42f5fabe4
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 82390674c40402c81dbf311a5ee488fb972894f5</li>
<li>SPVGEN: dev 2f679769a8491f423f5cf2f06adfa2870a82935d</li>
<li>XGL: dev 116d28a446eba3a9f8e6f577bab34fc07e090993</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 0c3b9cd01021a1b221ea7b08733989d322adf395</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 965/965 (100.0%)</li>
<li>Failed: 0/965 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx8</summary><ul>

<li>Passed: 103165/103165 (100.0%)</li>
<li>Failed: 0/103165 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Gfx9</summary><ul>

<li>Passed: 103221/103221 (100.0%)</li>
<li>Failed: 0/103221 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx10</summary><ul>

<li>Passed: 2082/2083 (100.0%)</li>
<li><details><summary>Failed: 1/2083 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.object_management.max_concurrent.command_buffer_primary
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by xuechen417** [comment]
Use std::vector for m_deadCalls. There are remove redundant instructions passes before resource collect. So the CallInst from visitCallInst() should be unique here.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit e58b8e89c87b11ccc860eceb1b97fbcf1fd479cd
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 82390674c40402c81dbf311a5ee488fb972894f5</li>
<li>SPVGEN: dev 2f679769a8491f423f5cf2f06adfa2870a82935d</li>
<li>XGL: dev 116d28a446eba3a9f8e6f577bab34fc07e090993</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 3274df1841b8f799a490a6be7d58ef9870662fa7</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 965/965 (100.0%)</li>
<li>Failed: 0/965 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx8</summary><ul>

<li>Passed: 103165/103165 (100.0%)</li>
<li>Failed: 0/103165 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Gfx9</summary><ul>

<li>Passed: 88428/88429 (100.0%)</li>
<li><details><summary>Failed: 1/88429 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.subgroups.arithmetic.compute.subgroupexclusiveor_uint16_t
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>

<details open><summary>Ubuntu 18.04, Gfx10</summary><ul>

<li>Passed: 88316/88317 (100.0%)</li>
<li><details><summary>Failed: 1/88317 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.subgroups.arithmetic.graphics.subgroupxor_u16vec2
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit e58b8e89c87b11ccc860eceb1b97fbcf1fd479cd
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 82390674c40402c81dbf311a5ee488fb972894f5</li>
<li>SPVGEN: dev 2f679769a8491f423f5cf2f06adfa2870a82935d</li>
<li>XGL: dev 116d28a446eba3a9f8e6f577bab34fc07e090993</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 3274df1841b8f799a490a6be7d58ef9870662fa7</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 965/965 (100.0%)</li>
<li>Failed: 0/965 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx8</summary><ul>

<li>Passed: 103165/103165 (100.0%)</li>
<li>Failed: 0/103165 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Gfx9</summary><ul>

<li>Passed: 103221/103221 (100.0%)</li>
<li>Failed: 0/103221 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx10</summary><ul>

<li>Passed: 103221/103221 (100.0%)</li>
<li>Failed: 0/103221 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
