### PR TITLE
lgc/PatchBufferOp: crash when the phiNode's user is invariant_start intrinsic

### PR DESCRIPTION
**Pull request by nhaehnle**
When the IR like this, it will crash:

      %2653 = load <4 x i32>, ptr addrspace(4) %2652, align 16
      ...
      %2654 = call ptr addrspace(7) @lgc.buffer.desc.to.ptr(<4 x i32> %2653)
      %2853 = call ptr addrspace(7) @lgc.buffer.desc.to.ptr(<4 x i32> %2852)
      %2932 = call ptr addrspace(7) @lgc.buffer.desc.to.ptr(<4 x i32> %2931)
      ...
      %.lcssa8772 = phi ptr addrspace(7) [ %2654, %branch27_true ], [ %2853, %branch27_true.1 ], [ %2932, %branch27_true.2 ]
      ...
      %3186 = call ptr @llvm.invariant.start.p7(i64 -1, ptr addrspace(7) %.lcssa8772)

Root Cause:
    removeUsersForInvariantStarts in BufferOpLowering hasn't considered on the phiNode.

Solution:
    Add a proper visit of @llvm.invariant.start.p7 in BufferOpLowering

### CODE REVIEW

**Comment by nhaehnle** [comment]
cc @ruiminzhao This is a proper fix for #2490. It took me making changes locally to finally see how this should work, so since I already had the changes on my computer I just pushed them to this new PR. The proper solution is to use `m_typeLowering.getValue` to map from the pointer argument to the underlying descriptor when visiting `invariant.start` intrinsics.

**Comment by amdvlk-admin** [comment]
025ff0444c74ff9ed71e6f76a2b9df5da53ae70c Jenkins build error.
error: Leaf constant_fold_fabs is unreachable
note: Leaf idempotent_prop will have already matched
error: Leaf constant_fold_fabs is unreachable
note: Leaf idempotent_prop will have already matched
[2353/3068] Building CXX object compiler/llpc/llvm/lib/LineEditor/CMakeFiles/LLVMLineEditor.dir/LineEditor.cpp.o
[2354/3068] Linking CXX static library compiler/llpc/llvm/lib/libLLVMLineEditor.a
[2355/3068] Building AMDGPUGenMCPseudoLowering.inc...
[2356/3068] Building AMDGPUGenRegBankGICombiner.inc...
--
error: Leaf constant_fold_fabs is unreachable
note: Leaf idempotent_prop will have already matched
error: Leaf constant_fold_fabs is unreachable
note: Leaf idempotent_prop will have already matched
[2359/3068] Building AMDGPUGenSearchableTables.inc...
[2360/3068] Building CXX object compiler/llpc/llvm/lib/AsmParser/CMakeFiles/LLVMAsmParser.dir/Parser.cpp.o
[2361/3068] Building CXX object compiler/llpc/llvm/lib/ProfileData/CMakeFiles/LLVMProfileData.dir/GCOV.cpp.o
[2362/3068] Building AMDGPUGenSubtargetInfo.inc...
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/util/vkgcElfReader.h:33:10: fatal error: g_palPipelineAbiMetadata.h: No such file or directory
   33 | #include  g_palPipelineAbiMetadata.h 
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[2930/3068] Building CXX object compiler/dumper/CMakeFiles/dumper_base.dir/vkgcPipelineDumperRegs.cpp.o
FAILED: compiler/dumper/CMakeFiles/dumper_base.dir/vkgcPipelineDumperRegs.cpp.o 
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/tool/dumper/vkgcPipelineDumper.h:34:10: fatal error: vkgcMetroHash.h: No such file or directory
   34 | #include  vkgcMetroHash.h 
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
[2931/3068] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/util/Internal.cpp.o
[2932/3068] Building CXX object compiler/llpc/llvm/third-party/benchmark/src/CMakeFiles/benchmark_main.dir/benchmark_main.cc.o

**Comment by amdvlk-admin** [comment]
### Test summary for commit 025ff0444c74ff9ed71e6f76a2b9df5da53ae70c
<details><summary>CTS tests (Failed: 0/142050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71030 (56.9%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 30604/71030 (43.1%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71020 (57.0%)</li>
<li>Failed: 0/71020 (0.0%)</li>
<li>Not Supported: 30556/71020 (43.0%)</li><li>Warnings: 0/71020 (0.0%)</li>
</ul></details>


</ul></details>

**Review by ruiminzhao — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9f9405b681ec9bf0dfe0537249c30416b33b39fa
<details><summary>CTS tests (Failed: 0/142050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71030 (56.9%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 30604/71030 (43.1%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71020 (57.0%)</li>
<li>Failed: 0/71020 (0.0%)</li>
<li>Not Supported: 30556/71020 (43.0%)</li><li>Warnings: 0/71020 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
ping @amdrexu

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
