### PR TITLE
Fix tests to pass after LLVM update.

### PR DESCRIPTION
**Pull request by kosarev**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by Flakebi** [comment]
ok to test

**Review by Flakebi — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit c30d58dabc7934b5d8a83b11e1a50c2992914064
<details><summary>CTS tests (Failed: 0/208496)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36978/69503 (53.2%)</li>
<li>Failed: 0/69503 (0.0%)</li>
<li>Not Supported: 32525/69503 (46.8%)</li><li>Warnings: 0/69503 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 41144/69503 (59.2%)</li>
<li>Failed: 0/69503 (0.0%)</li>
<li>Not Supported: 28359/69503 (40.8%)</li><li>Warnings: 0/69503 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 41178/69490 (59.3%)</li>
<li>Failed: 0/69490 (0.0%)</li>
<li>Not Supported: 28312/69490 (40.7%)</li><li>Warnings: 0/69490 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by kosarev** [comment]
@dstutt @Flakebi Can you submit this, please?

**Comment by dstutt** [comment]
Can you rebase the change - I'll merge it once it's through testing again.

**Comment by Flakebi** [comment]
Let’s try if the rebase button works

**Comment by dstutt** [comment]
retest this please

**Comment by dstutt** [comment]
test this please

**Comment by kosarev** [comment]
Does this count failed?

**Comment by dstutt** [comment]
Not sure what you mean.
For some reason the Jenkins Pipelines are a bit unstable. There's a job that should complete shortly (looks ok so far).
(Whatever the cause, the failures are unrelated to this change)

**Comment by kosarev** [comment]
What I see is all jobs succeeded, except the 'Jenkins Pipeline' one saying 'build and test aborted'. So no builds in progress?

**Comment by dstutt** [comment]
There is still one going (I aborted another one after the test agent crashed for some reason).

**Comment by kosarev** [comment]
Looking at the buildbot output, it doesn't seem to make any progress.

**Comment by dstutt** [comment]
It's run 2 of the 3 variations required, but all the test agents that match the last one are now offline, hence it won't make progress. I'm attempting to get them back online.

**Comment by trenouf** [comment]
David asked me to force this through as there are problems with test machines.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1a170b51b7edca8558338077a00c6c9d4bd4210a
<details><summary>CTS tests (Failed: 0/208497)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36978/69503 (53.2%)</li>
<li>Failed: 0/69503 (0.0%)</li>
<li>Not Supported: 32525/69503 (46.8%)</li><li>Warnings: 0/69503 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 41144/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28360/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 41178/69490 (59.3%)</li>
<li>Failed: 0/69490 (0.0%)</li>
<li>Not Supported: 28312/69490 (40.7%)</li><li>Warnings: 0/69490 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
