### PR TITLE
Revert "Add cache hash note to shader ELF"

### PR DESCRIPTION
**Pull request by sudonatalie**
This reverts commit e6247f101f0f2dfc07054866a571673650c84655.

The required cache hash info is now written to and used from PAL
metadata and this option to write to the notes section is no longer
needed.

This is not a complete revert. Its new test (which has already been
updated), additional log statements used by tests, and other logic that
is still in use, have not been removed.

https://github.com/GPUOpen-Drivers/xgl/pull/107 must land first.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by sudonatalie** [comment]
@jaebaek PTAL (I can't assign Reviewers)

**Review by kuhar — APPROVED** [review]
LGTM.
@JaxLinAMD please wait before merging, the XGL change should land first.

**Review by amdrexu — APPROVED** [review]

**Review by s-perron — APPROVED** [review]

**Review by jaebaek — APPROVED** [review]
LGTM

**Comment by JaxLinAMD** [comment]
> LGTM.
> @JaxLinAMD please wait before merging, the XGL change should land first.

got it.

**Comment by JaxLinAMD** [comment]
xgl 107 is merged, so I will merge this PR

**Pull request merged**
