### PR TITLE
Refine LlvmDbg info recording

### PR DESCRIPTION
**Pull request by jiaolu**
1.Add OpSource File
2.Use the OpSource File whenever the entry does not file name
3.If the function first instruction file name if the DiSubProgram does not have
  file name

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit d16dbfcf79a9743a35b286019c8f1ab0df6ffd84
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 4ea0bad02244d155423be0a77d702c3a5a6e950f</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>XGL: dev 6f20dd5e34cfc3416942d0c934c6c22a9b83f1bc</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 06c283bff7b90ebc273564c573af501e8dcd2b7d</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/223127)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30621/55787 (54.9%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>NotSupported: 25166/55787 (45.1%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30620/55787 (54.9%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>NotSupported: 25167/55787 (45.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30805/55766 (55.2%)</li>
<li>Failed: 0/55766 (0.0%)</li>
<li>NotSupported: 24961/55766 (44.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34235/55787 (61.4%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>NotSupported: 21552/55787 (38.6%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit e4af0a8e46d143b5feaea71316495ee8aa7881a4
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 4ea0bad02244d155423be0a77d702c3a5a6e950f</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>XGL: dev 6f20dd5e34cfc3416942d0c934c6c22a9b83f1bc</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 06c283bff7b90ebc273564c573af501e8dcd2b7d</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/223127)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30621/55787 (54.9%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>NotSupported: 25166/55787 (45.1%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30620/55787 (54.9%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>NotSupported: 25167/55787 (45.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30805/55766 (55.2%)</li>
<li>Failed: 0/55766 (0.0%)</li>
<li>NotSupported: 24961/55766 (44.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34235/55787 (61.4%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>NotSupported: 21552/55787 (38.6%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 959c9abab4644104078da54832476c7b1e853ed9
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 83635fbee82fb21662a4737e34437c41172c6fe0</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>XGL: dev 6b6a620a693342f5785671759aee9b5e9a265097</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 06c283bff7b90ebc273564c573af501e8dcd2b7d</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/223127)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30621/55787 (54.9%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>Not supported: 25166/55787 (45.1%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30620/55787 (54.9%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>Not supported: 25167/55787 (45.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30805/55766 (55.2%)</li>
<li>Failed: 0/55766 (0.0%)</li>
<li>Not supported: 24961/55766 (44.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34235/55787 (61.4%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>Not supported: 21552/55787 (38.6%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit e439f04ec85260619a3460314c566080b8e25008
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 83635fbee82fb21662a4737e34437c41172c6fe0</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>XGL: dev f67223913cf046cb65adcc3bd3f06c6ad232f150</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 661ac9b7d0d9edcbd07bd1b40c334934ff2297ac</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/223127)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30621/55787 (54.9%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>Not supported: 25166/55787 (45.1%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30620/55787 (54.9%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>Not supported: 25167/55787 (45.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30805/55766 (55.2%)</li>
<li>Failed: 0/55766 (0.0%)</li>
<li>Not supported: 24961/55766 (44.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34235/55787 (61.4%)</li>
<li>Failed: 0/55787 (0.0%)</li>
<li>Not supported: 21552/55787 (38.6%)</li>
</ul></details>


</ul></details>

**Pull request merged**
