### PR TITLE
Add lgc lit test to docker

### PR DESCRIPTION
**Pull request by JaxLinAMD**
lgc lit test will then be removed from jenkins test.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0fa02cddb1180cbc9412519edbde6f1dd3fad036
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8b97c9b85aaec59fd151ff259b208f877074ab9b
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142129/142129 (100.0%)</li>
<li>Failed: 0/142129 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142129/142129 (100.0%)</li>
<li>Failed: 0/142129 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
@kuhar , could you help verify this PR? thanks.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 71b4c580cf5fecf92732edc84154d2c0c6ac85aa</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 109839da28db705217aad91b1ec78cf1bd437944
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev b3a0782762d195b57a2bebaabca24be90a35db2a</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 142087/142087 (100.0%)</li>
<li>Failed: 0/142087 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
