### PR TITLE
Improve cmake of dumper and vfx

### PR DESCRIPTION
**Pull request by Flakebi**
Only the topmost commit is part of this PR, the other one fixes warnings (#705).

- Make -Werror optional, overwritten by LLPC_ENABLE_WERROR
- Unify clang and gcc flags
- Add back colorful diagnostics
- Move the compiler flags for all projects into one file to ease maintenance

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 56d1220786f7c1d6d01ac457cb0993e3be839762
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 85170384d0ee5447ac267d478f7a21bc036ea71c</li>
<li>SPVGEN: dev 704f4adddb6867d633431c2c9c2c0bfa6d294ce2</li>
<li>XGL: dev 9c4fe791366e730131a0d99a7519855068f216ef</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c57487b76215ee74b1038039f47b210a28cad65e</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 960/960 (100.0%)</li>
<li>Failed: 0/960 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103143/103143 (100.0%)</li>
<li>Failed: 0/103143 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 103199/103199 (100.0%)</li>
<li>Failed: 0/103199 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
> What do you think about moving the function that sets compiler flags
> from `/llpc/CMakeLists.txt` into either `/CMakeLists.txt` or
> `/cmake/compiler_flags.cmake`?

That's effectively what you've already done in this change, right? I think it makes a lot of sense. At a cursory glance (and apart from the build failures :)), this change looks good to me.

**Comment by Flakebi** [comment]
> That's effectively what you've already done in this change, right?

Right, I did that today and planned to write a comment once the builds are passing :)

**Comment by amdrexu** [comment]
Need a code rebase.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Pull request merged**
