### PR TITLE
lgc: UTC-ify some more tests

### PR DESCRIPTION
**Pull request by nhaehnle**

### CODE REVIEW

**Comment by dstutt** [comment]
I think that there's no requirement for REQUIRES: gfx11 any more since you've now integrated the only gfx11 specific test into the others?
Do you think we could/should remove that from lit.cfg.py?

**Comment by nhaehnle** [comment]
I had to add "VALU" to the allowed words for the typo checker...

> I think that there's no requirement for REQUIRES: gfx11 any more since you've now integrated the only gfx11 specific test into the others?
> Do you think we could/should remove that from lit.cfg.py?

Good point, I'll look into it.

**Review by dstutt — APPROVED** [review]
LGTM

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9c78f1512ed564bd0c8815c6d1d1e8821e2b454c
<details><summary>CTS tests (Failed: 0/277947)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70526 (55.1%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31662/70526 (44.9%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70526 (55.5%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31412/70526 (44.5%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70528 (51.0%)</li>
<li>Failed: 0/70528 (0.0%)</li>
<li>Not Supported: 34569/70528 (49.0%)</li><li>Warnings: 0/70528 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66367 (50.7%)</li>
<li>Failed: 0/66367 (0.0%)</li>
<li>Not Supported: 32689/66367 (49.3%)</li><li>Warnings: 0/66367 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
At the moment there seems to be some skew between the different LLVM branches that causes some tests to fail. I'm going to give it a day or two before I dig into it.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0cb1650e33ff70ae5320ea56d49b6548a002bd6a
<details><summary>CTS tests (Failed: 0/282025)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38862/70507 (55.1%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31645/70507 (44.9%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39112/70507 (55.5%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31395/70507 (44.5%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70509 (51.0%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34550/70509 (49.0%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 35861/70502 (50.9%)</li>
<li>Failed: 0/70502 (0.0%)</li>
<li>Not Supported: 34641/70502 (49.1%)</li><li>Warnings: 0/70502 (0.0%)</li>
</ul></details>


</ul></details>

**Review by dstutt — APPROVED** [review]
I haven't looked in detail again - but presumably it is much the same as before?

**Comment by dstutt** [comment]
Oh - just realized it is failing checks, but presumably that's the cache-creator issue that @Flakebi is looking at?

**Comment by nhaehnle** [comment]
Rebasing to retrigger the tests in the hope that they pass now...

**Comment by nhaehnle** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 02862b075808f621534314da6981aa0fdebb9c18
<details><summary>CTS tests (Failed: 0/282025)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38862/70507 (55.1%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31645/70507 (44.9%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39112/70507 (55.5%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31395/70507 (44.5%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70509 (51.0%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34550/70509 (49.0%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 35861/70502 (50.9%)</li>
<li>Failed: 0/70502 (0.0%)</li>
<li>Not Supported: 34641/70502 (49.1%)</li><li>Warnings: 0/70502 (0.0%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
