### PR TITLE
Coding standards change

### PR DESCRIPTION
**Pull request by trenouf**

### CODE REVIEW

**Comment by trenouf** [comment]
Only the top 7 commits are part of this PR. The rest will disappear once other PRs are merged and this one is rebased.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8f1d2c0c23896a63f1d1d3e312c707a2f072c0de
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev bb7398b1c7509a30ba4f7d947b5ad5549a4d58db</li>
<li>SPVGEN: dev dc2b146de03ef54f188172d8fa2f9be708cbfaca</li>
<li>XGL: dev ffd39443fec0ce821b7702173eba7184855c7b5e</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ebc431ac299fa294a4e730432520d37f326843c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 955/955 (100.0%)</li>
<li>Failed: 0/955 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103137/103137 (100.0%)</li>
<li>Failed: 0/103137 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
Ping for review.

@amdrexu, what did we decide in the meeting yesterday about SPIRVReader.cpp? Shall we include it in the changes here, so it at least has a consistent style? As you noted, it then has other issues such as single-letter variable names, and lack of top-of-function comments, that can be fixed later.

Note that I am only including SPIRVReader.cpp and SPIRVInternal.h in the changes. All the other SPIRV* code that we originally got from Khronos I am leaving unchanged.

**Comment by amdrexu** [comment]
@trenouf For translator, it would be another rework item to completely make it consistent with other parts of LLPC. This will involve both coding adjustment and redesign the component. Below are what I am thinking of besides coding changes in SRIRVReader.h/.cpp (for the whole translator):

Do these items in your PR (should be minor changes):
(1) `A* a -> A *a`, `B& b -> B &b`
(2) `Func(...) -> func(...)`
(3) 2-space indentation and remove unnecessary parenthesis
(4) Use uppercase for global variables
(5) Replace `#ifndef X ... #define X... #endif` with `#pragme once`

Don't do these items in your PR:
(1) `V -> v` (lowercase variable name, there are too many single-character names)
(2) 120 character line width (I think many codes could stay in one line now)
(3) Add "`m_`" prefix for class members
(4) Comment style

**Comment by amdrexu** [comment]
Since you have a good opportunity to reformat the code, I also want to make those items clear:
(1) A separate line "// =====" is always required for a class definition and any function implementation.
(2) A separate line "// -----" could be added to separate member functions and data member in the same access section (public, protected, private) within a class.

**Comment by kuhar** [comment]
> Since you have a good opportunity to reformat the code, I also want to make those items clear:
> (1) A separate line "// =====" is always required for a class definition and any function implementation.
> (2) A separate line "// -----" could be added to separate member functions and data member in the same access section (public, protected, private) within a class.

Does clang-format support auto-generating those?

**Comment by amdrexu** [comment]
> Does clang-format support auto-generating those?

I don't think clang-format supports this. This is introduced by PAL coding style and we decide to follow it to make code easy to read with those delimiters.

**Comment by kuhar** [comment]
> I don't think clang-format supports this. This is introduced by PAL coding style and we decide to follow it to make code easy to read with those delimiters.
I see. Would be cool to add it to clang-format to have one fewer thing to worry about.

**Comment by trenouf** [comment]
The last, substantively the same, version of this change passed Jenkins and internal testing, so I'm going to merge it anyway.

**Comment by trenouf** [comment]
> @trenouf For translator, it would be another rework item to completely make it consistent with other parts of LLPC. This will involve both coding adjustment and redesign the component. Below are what I am thinking of besides coding changes in SRIRVReader.h/.cpp (for the whole translator):
> 
> Do these items in your PR (should be minor changes):
> (1) `A* a -> A *a`, `B& b -> B &b`
> (2) `Func(...) -> func(...)`
> (3) 2-space indentation and remove unnecessary parenthesis
> (4) Use uppercase for global variables
> (5) Replace `#ifndef X ... #define X... #endif` with `#pragme once`
> (6) `if (p != nullptr) -> if (p)`
> 
> Don't do these items in your PR:
> (1) `V -> v` (lowercase variable name, there are too many single-character names)
> (2) 120 character line width (I think many codes could stay in one line now)
> (3) Add "`m_`" prefix for class members
> (4) Comment style

I have now merged this PR, and I did not do anything to translator files other than SPIRVReader.cpp and SPIRVInternal.h. We could modify other files in a future PR, but I don't think it is worth it at the moment.

**Comment by amdrexu** [comment]
Understand. If possible, please remove "// -----" styled separate line with a PR as we have already used it and new files will not follow this rule in the future.

**Pull request merged**
