### PR TITLE
Use DPP updates instead of DPP movs in subgroup reductions

### PR DESCRIPTION
**Pull request by jayfoad**
This matches what we do in subgroup inclusive scans, and it allows the
LLVM GCN DPP combine pass to combine the DPP operations into the ALU
operations, generating much shorter code overall.

### CODE REVIEW

**Comment by jayfoad** [comment]
@JacobHeAMD The Vulkan CTS tests passed on Ubuntu but stopped abruptly ("Timeout or crahsed") on RHEL. Perhaps it ran out of memory?

**Comment by trenouf** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 04b2da2dfef3893c54b29d028c3cb05050ee410b
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 88d997710b4e405f3a8e3fd60a38afee9e3e77e2</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 2cb5558b94c5dc839e093cb439057a1802426c8e</li>
<li>LLVM: amd-vulkan-dev 1fc1a7d4248b4749c3df21eb48f7ae97b6cddf74</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/pal/src/util/lnx/lnxHashProvider.h:36:10: fatal error: openssl/sha.h: No such file or directory

</ul></details>

**Comment by amdvlk-admin** [comment]
Hi @jayfoad , the build failure is caused by the Jenkins agent itself, I've already asked infrastructure team to install the dependent package. I'll re-trigger the build once it gets installed.

**Comment by amdrexu** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 04b2da2dfef3893c54b29d028c3cb05050ee410b
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 88d997710b4e405f3a8e3fd60a38afee9e3e77e2</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 2cb5558b94c5dc839e093cb439057a1802426c8e</li>
<li>LLVM: amd-vulkan-dev 1fc1a7d4248b4749c3df21eb48f7ae97b6cddf74</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 68331/68331 (100.0%)</li>
<li>Failed: 0/68331 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 68363/68363 (100.0%)</li>
<li>Failed: 0/68363 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
