### PR TITLE
Update check-cppcheck-llpc.yml to ubuntu 24.04

### PR DESCRIPTION
**Pull request by qiaojbao**
To catch error.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit c7e8178fdcf99fee150de313be8908858a8e5b77
<details><summary>CTS tests (Failed: 0/148731)</summary><ul><li>Built with version 1.3.5.2.RC</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35840/75073 (47.7%)</li>
<li>Failed: 0/75073 (0.0%)</li>
<li>Not Supported: 39233/75073 (52.3%)</li><li>Warnings: 0/75073 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 34691/73658 (47.1%)</li>
<li>Failed: 0/73658 (0.0%)</li>
<li>Not Supported: 38967/73658 (52.9%)</li><li>Warnings: 0/73658 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
Looks like there are some new failures that need looking at. Apart from that this LGTM.

**Comment by amdvlk-admin** [comment]
### Test summary for commit c7e8178fdcf99fee150de313be8908858a8e5b77
<details><summary>CTS tests (Failed: 0/148731)</summary><ul><li>Built with version 1.3.5.2.RC</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35840/75073 (47.7%)</li>
<li>Failed: 0/75073 (0.0%)</li>
<li>Not Supported: 39233/75073 (52.3%)</li><li>Warnings: 0/75073 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 34691/73658 (47.1%)</li>
<li>Failed: 0/73658 (0.0%)</li>
<li>Not Supported: 38967/73658 (52.9%)</li><li>Warnings: 0/73658 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0fced47ce89eaaf1d6fdf27ddfc4636054276cfb
<details><summary>CTS tests (Failed: 193/148731)</summary><ul><li>Built with version 1.3.5.2.RC</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 27493/75073 (36.6%)</li>
<li><details><summary>Failed: 191/75073 (0.3%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.device_init.create_device_global_priority.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_device_global_priority_khr.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_device_global_priority_query.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_device_global_priority_query_khr.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_instance_name_version.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.driver_properties.conformance_version
Stack trace: Fail

FAILURE: dEQP-VK.api.info.extension_core_versions.extension_core_versions
Stack trace: Fail

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.buffer_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.buffer_8095
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_257_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_257_8
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_33_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_33_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_8_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_8_8
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.buffer_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.image_257_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.image_257_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.image_33_33
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 47389/75073 (63.1%)</li><li>Warnings: 0/75073 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 34888/73658 (47.4%)</li>
<li><details><summary>Failed: 2/73658 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail.basic
Stack trace: Timeout

FAILURE: dEQP-VK.api.driver_properties.conformance_version
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 38768/73658 (52.6%)</li><li>Warnings: 0/73658 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by Flakebi** [comment]
I only looked at the reported errors coarsely, but it seems like they are all false positives.
I’m ok with removing the cppcheck job. It didn’t find many real issues, but it seems rather annoying to keep it passing.

**Comment by qiaojbao** [comment]
> I only looked at the reported errors coarsely, but it seems like they are all false positives. I’m ok with removing the cppcheck job. It didn’t find many real issues, but it seems rather annoying to keep it passing.

Yes, I create this PR just for test static-check, try to update the check system to 22.04.
These failures should be agent issue.
The dEQP-VK.api.driver_properties.conformance_version should be the dev vkcts issue.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1873e38adc1c94a831203e608b6f137264c12f8e
<details><summary>CTS tests (Failed: 193/148731)</summary><ul><li>Built with version 1.3.5.2.RC</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 27493/75073 (36.6%)</li>
<li><details><summary>Failed: 191/75073 (0.3%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.device_init.create_device_global_priority.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_device_global_priority_khr.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_device_global_priority_query.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_device_global_priority_query_khr.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_instance_name_version.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.driver_properties.conformance_version
Stack trace: Fail

FAILURE: dEQP-VK.api.info.extension_core_versions.extension_core_versions
Stack trace: Fail

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.buffer_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.buffer_8095
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_257_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_257_8
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_33_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_33_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_8_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_8_8
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.buffer_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.image_257_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.image_257_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.image_33_33
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 47389/75073 (63.1%)</li><li>Warnings: 0/75073 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 34888/73658 (47.4%)</li>
<li><details><summary>Failed: 2/73658 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail.basic
Stack trace: Timeout

FAILURE: dEQP-VK.api.driver_properties.conformance_version
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 38768/73658 (52.6%)</li><li>Warnings: 0/73658 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit ad1eb5b41127ef5a77009f0a633f8ca5a0485b7f
<details><summary>CTS tests (Failed: 193/148731)</summary><ul><li>Built with version 1.3.5.2.RC</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 27493/75073 (36.6%)</li>
<li><details><summary>Failed: 191/75073 (0.3%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.device_init.create_device_global_priority.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_device_global_priority_khr.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_device_global_priority_query.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_device_global_priority_query_khr.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.device_init.create_instance_name_version.basic
Stack trace: Fail

FAILURE: dEQP-VK.api.driver_properties.conformance_version
Stack trace: Fail

FAILURE: dEQP-VK.api.info.extension_core_versions.extension_core_versions
Stack trace: Fail

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.buffer_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.buffer_8095
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_257_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_257_8
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_33_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_33_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_8_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.aliasing.suballocated.image_8_8
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.buffer_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.image_257_257
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.image_257_33
Stack trace: Crash

FAILURE: dEQP-VK.memory.binding.priority_dynamic.regular.dedicated.image_33_33
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 47389/75073 (63.1%)</li><li>Warnings: 0/75073 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 34888/73658 (47.4%)</li>
<li><details><summary>Failed: 2/73658 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail.basic
Stack trace: Timeout

FAILURE: dEQP-VK.api.driver_properties.conformance_version
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 38768/73658 (52.6%)</li><li>Warnings: 0/73658 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit ad1eb5b41127ef5a77009f0a633f8ca5a0485b7f
<details><summary>CTS tests (Failed: 3/148731)</summary><ul><li>Built with version 1.3.9.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 44907/75073 (59.8%)</li>
<li><details><summary>Failed: 1/75073 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail.basic
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 30165/75073 (40.2%)</li><li>Warnings: 0/75073 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 43077/73658 (58.5%)</li>
<li><details><summary>Failed: 2/73658 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail.basic
Stack trace: Timeout

FAILURE: dEQP-VK.api.frame_boundary.wsi.wayland
Stack trace: Timeout
```
</p></details></li>

<li>Not Supported: 30579/73658 (41.5%)</li><li>Warnings: 0/73658 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request closed without merging**
