### PR TITLE
Opaque pointers: Update function mangling name

### PR DESCRIPTION
**Pull request by mariusz-sikora-at-amd**

### CODE REVIEW

**Review by Flakebi — DISMISSED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit e9f9b9ec47097cb034c87077bda4042e3423f554
<details><summary>CTS tests (Failed: 0/286639)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 36222/72710 (49.8%)</li>
<li>Failed: 0/72710 (0.0%)</li>
<li>Not Supported: 36488/72710 (50.2%)</li><li>Warnings: 0/72710 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 40419/72714 (55.6%)</li>
<li>Failed: 0/72714 (0.0%)</li>
<li>Not Supported: 32295/72714 (44.4%)</li><li>Warnings: 0/72714 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 37135/72724 (51.1%)</li>
<li>Failed: 0/72724 (0.0%)</li>
<li>Not Supported: 35589/72724 (48.9%)</li><li>Warnings: 0/72724 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 34834/68491 (50.9%)</li>
<li>Failed: 0/68491 (0.0%)</li>
<li>Not Supported: 33657/68491 (49.1%)</li><li>Warnings: 0/68491 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by mariusz-sikora-at-amd** [comment]
While testing I noticed that I need to add return type for mangling name. I will update this.

**Comment by mariusz-sikora-at-amd** [comment]
Updated

**Comment by amdvlk-admin** [comment]
### Test summary for commit ee67ba49c447c1d5c4566dbd16e218a45a64da4e
<details><summary>CTS tests (Failed: 0/286639)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 36222/72710 (49.8%)</li>
<li>Failed: 0/72710 (0.0%)</li>
<li>Not Supported: 36488/72710 (50.2%)</li><li>Warnings: 0/72710 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 40419/72714 (55.6%)</li>
<li>Failed: 0/72714 (0.0%)</li>
<li>Not Supported: 32295/72714 (44.4%)</li><li>Warnings: 0/72714 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 37135/72724 (51.1%)</li>
<li>Failed: 0/72724 (0.0%)</li>
<li>Not Supported: 35589/72724 (48.9%)</li><li>Warnings: 0/72724 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 34834/68491 (50.9%)</li>
<li>Failed: 0/68491 (0.0%)</li>
<li>Not Supported: 33657/68491 (49.1%)</li><li>Warnings: 0/68491 (0.0%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Review by nhaehnle — APPROVED** [review]

**Pull request merged**
