### PR TITLE
Fix user data handling when reading off end of push const

### PR DESCRIPTION
**Pull request by trenouf**
This fixes a compiler crash introduced in #650
68414fe49 Rationalized user data usage

The crash happened when a shader uses a larger push constant than the
size indicated in the pipeline state.

Change-Id: Iec7ef011e89ed199b34609896699881b502b59c4

### CODE REVIEW

**Comment by JaxLinAMD** [comment]
reest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Review by nhaehnle — COMMENTED** [review]
Isn't that illegal according to the spec? As in, shouldn't that fail validation? We probably shouldn't just compile this without complaining loudly about it...

**Comment by trenouf** [comment]
Yes it sounds like it is illegal. But we have at least one real game doing it, and it works on our closed source compiler, and on LLPC before #650.

**Pull request merged**
