### PR TITLE
Add ddn of PartialPipelineComiple

### PR DESCRIPTION
**Pull request by amingriyue**
This DDN proposes a method to build pipeline layout from SPIRV binary and
make it compatible with APP’s pipeline layout without recompile.

v2: add more design details.

Signed-off-by: Chunming Zhou <david1.zhou@amd.com>
Signed-off-by: Qun Lin <Quentin.Lin@amd.com>

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 7798fb87704007d612dc0b3d9eb04a16820aa231
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 40af910391fb8c287cb37bf520c41310bf88d405</li>
<li>SPVGEN: dev ce06cb5e3116ba77a22c3278dfeadfd865a8977c</li>
<li>XGL: dev 7e13a8bd0bb57d3cfb3bc014f6b26a8c9bb8bfd9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdrexu** [comment]
@amingriyue Please update the commit

**Comment by amingriyue** [comment]
Yeah, will update it today.

**Comment by amingriyue** [comment]
updated.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6227fe2a1d5a7d3b4bd1d7849389d447a3011216
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 9fab16015e522fff05890a045a1e9d8d3c23a636</li>
<li>SPVGEN: dev a61db14f75728e91c243d4bfc1c39700e9dc0ba6</li>
<li>XGL: dev c0791473c087f5b5d75a21c6f2ace72ccd232a65</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 942/942 (100.0%)</li>
<li>Failed: 0/942 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65463/65463 (100.0%)</li>
<li>Failed: 0/65463 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
