### PR TITLE
Remove trailing whitespaces and newlines

### PR DESCRIPTION
**Pull request by Flakebi**
The first commit removes all trailing whitespaces in a line.
The second commit ensures that there is exactly one `\n` at the end of every file. So it removes trailing newlines.

### CODE REVIEW

**Comment by trenouf** [comment]
My clang-format run in #543 will remove trailing whitespace, right? Will it also remove trailing newlines?

**Comment by Flakebi** [comment]
Seems like it does remove trailing newlines. Trailing whitespaces are only in `test/` so I think your format run does not do that. Your `.clang-format` has a trailing newline btw ;)
I’ll redo these changes once your formatting is merged.

**Comment by JaxLinAMD** [comment]
@Flakebi please resolve conflicts

**Comment by JaxLinAMD** [comment]
merge process is started, please freeze force-push.

**Comment by JaxLinAMD** [comment]
please resolve conflicts...

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6e80cec57b2c6344c5152a8ebd33e5570fd8b4d3
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev bb7398b1c7509a30ba4f7d947b5ad5549a4d58db</li>
<li>SPVGEN: dev dc2b146de03ef54f188172d8fa2f9be708cbfaca</li>
<li>XGL: dev ffd39443fec0ce821b7702173eba7184855c7b5e</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 7b14353794b408b8d7fd87ae9a9f4f553e6d4782</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 955/955 (100.0%)</li>
<li>Failed: 0/955 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103142/103142 (100.0%)</li>
<li>Failed: 0/103142 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 33281/33282 (100.0%)</li>
<li><details><summary>Failed: 1/33282 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.binding_model.shader_access.primary_cmd_buf.uniform_buffer_dynamic.geometry.multiple_discontiguous_descriptor_sets.descriptor_array.offset_view_zero_dynamic_zero
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 103198/103198 (100.0%)</li>
<li>Failed: 0/103198 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
merge process is started, please don't force-push any more.

**Pull request merged**
