### PR TITLE
Fixed clang release build unused variable compile errors

### PR DESCRIPTION
**Pull request by trenouf**
Change-Id: I9d2f37b539bf21eb5d3653ffbec9711ba75f2e02

### CODE REVIEW

**Comment by trenouf** [comment]
V2: Fixed broken debug build

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5d95c86981ad874b0a3ada11a2a23a7cf74b2e7f
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 3e28ea331cf8e7b0e5733e5bd7f7d16582c603c5</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 68e79ff09849f32d0bbe929d94b19d58af7e0850</li>
<li>LLVM: amd-vulkan-dev 21b028dc97ee9b0c6629ff83c2924b3b80c5d6e7</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 50133/50134 (100.0%)</li>
<li><details><summary>Failed: 1/50134 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.image.swapchain_mutable.xlib.2d.r8g8b8a8_unorm_r8g8b8a8_snorm_copy_texture_format_list
Stack trace: Failed to open display: '' at tcuLnxX11.cpp:67
```
</p></details></li>


</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b76f2b1f02ed1199a61a0d181cde84073202aced
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 3e28ea331cf8e7b0e5733e5bd7f7d16582c603c5</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 68e79ff09849f32d0bbe929d94b19d58af7e0850</li>
<li>LLVM: amd-vulkan-dev 21b028dc97ee9b0c6629ff83c2924b3b80c5d6e7</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 50133/50134 (100.0%)</li>
<li><details><summary>Failed: 1/50134 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.image.swapchain_mutable.xlib.2d.r8g8b8a8_unorm_r8g8b8a8_snorm_copy_texture_format_list
Stack trace: Failed to open display: '' at tcuLnxX11.cpp:67
```
</p></details></li>


</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b76f2b1f02ed1199a61a0d181cde84073202aced
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 3e28ea331cf8e7b0e5733e5bd7f7d16582c603c5</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 68e79ff09849f32d0bbe929d94b19d58af7e0850</li>
<li>LLVM: amd-vulkan-dev 21b028dc97ee9b0c6629ff83c2924b3b80c5d6e7</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 50133/50134 (100.0%)</li>
<li><details><summary>Failed: 1/50134 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.image.swapchain_mutable.xlib.2d.r8g8b8a8_unorm_r8g8b8a8_snorm_copy_texture_format_list
Stack trace: Failed to open display: '' at tcuLnxX11.cpp:67
```
</p></details></li>


</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b76f2b1f02ed1199a61a0d181cde84073202aced
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 39abe2297ca58a2b84dcd9bc5e238fbc399bd6e0</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 19a031d9f73b95101fd4d3d594aca27c00feb180</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 40fbaf4c5446a361269c241d9112fff26575b5d0</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:659:55: error: no matching function for call to ‘llvm::LoadInst::setAlignment(unsigned int)’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:1568:57: error: no matching function for call to ‘llvm::LoadInst::setAlignment(unsigned int)’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchDescriptorLoad.cpp:548:51: error: no matching function for call to ‘llvm::LoadInst::setAlignment(int)’

</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b76f2b1f02ed1199a61a0d181cde84073202aced
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 39abe2297ca58a2b84dcd9bc5e238fbc399bd6e0</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 19a031d9f73b95101fd4d3d594aca27c00feb180</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 40fbaf4c5446a361269c241d9112fff26575b5d0</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:659:55: error: no matching function for call to ‘llvm::LoadInst::setAlignment(unsigned int)’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:1568:57: error: no matching function for call to ‘llvm::LoadInst::setAlignment(unsigned int)’

</ul></details>

**Comment by JaxLinAMD** [comment]
a rebase will help.

**Comment by trenouf** [comment]
I think this got superseded somewhere along the line.

**Pull request closed without merging**
