### PR TITLE
lgc: Make setLlpcOuts() thread local

### PR DESCRIPTION
**Pull request by trenouf**
... so it is more useful when used in the driver.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 25be54762cd86fc1a265ebb05416ca70d40df9b7
<details><summary>CTS tests (Failed: 0/211879)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35146/70631 (49.8%)</li>
<li>Failed: 0/70631 (0.0%)</li>
<li>Not Supported: 35485/70631 (50.2%)</li><li>Warnings: 0/70631 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39025/70632 (55.3%)</li>
<li>Failed: 0/70632 (0.0%)</li>
<li>Not Supported: 31607/70632 (44.7%)</li><li>Warnings: 0/70632 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39057/70616 (55.3%)</li>
<li>Failed: 0/70616 (0.0%)</li>
<li>Not Supported: 31559/70616 (44.7%)</li><li>Warnings: 0/70616 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
`setLlpcOuts` is only called from `ICompiler::Create`, which xgl only calls once during physical device initialization, which isn't necessarily in the same thread as later compiles. So while I think having a thread-local setting for the logging may be convenient, I don't think this works as-is :(

**Comment by trenouf** [comment]
Hmm, good point. Looks like I need to move where LLPC calls setLlpcOuts.

**Review by nhaehnle — DISMISSED** [review]
LGTM. I think the two commits technically need to be squashed.

**Comment by trenouf** [comment]
Yes, I will squash.

**Review by nhaehnle — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit f2fac33139bbd60a261d940522c2366489647127
<details><summary>CTS tests (Failed: 0/209324)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 34735/69779 (49.8%)</li>
<li>Failed: 0/69779 (0.0%)</li>
<li>Not Supported: 35044/69779 (50.2%)</li><li>Warnings: 0/69779 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38617/69779 (55.3%)</li>
<li>Failed: 0/69779 (0.0%)</li>
<li>Not Supported: 31162/69779 (44.7%)</li><li>Warnings: 0/69779 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 38651/69766 (55.4%)</li>
<li>Failed: 0/69766 (0.0%)</li>
<li>Not Supported: 31115/69766 (44.6%)</li><li>Warnings: 0/69766 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
