### PR TITLE
Fix assertion failure in PielineVsFs_RelocConst.pipe test

### PR DESCRIPTION
**Pull request by csyonghe**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by trenouf** [comment]
Do the other two tests need the same fix? I was getting asserts on those too.

**Comment by csyonghe** [comment]
No they don't. I don't get any assertion errors on the other tests.

**Comment by trenouf** [comment]
Actually it looks like I broke the other two tests in #588. I'll fix it.

**Comment by trenouf** [comment]
I've put my fix into #602.

**Comment by trenouf** [comment]
I will merge this once #602 is approved and merged.

**Pull request merged**
