### PR TITLE
Add a test for non-sematic info instructions

### PR DESCRIPTION
**Pull request by xuechen417**
Add a lit test for `SPV_KHR_non_semantic_info`.

### CODE REVIEW

**Comment by xuechen417** [comment]
V1: Fix typos

**Comment by amdvlk-admin** [comment]
### Test summary for commit f3a3a02c6a53d94e3045477a55f49a8fa829b240
<details><summary>CTS tests (Failed: 6/291482)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 37494/73926 (50.7%)</li>
<li>Failed: 0/73926 (0.0%)</li>
<li>Not Supported: 36432/73926 (49.3%)</li><li>Warnings: 0/73926 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 41798/73925 (56.5%)</li>
<li><details><summary>Failed: 6/73925 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.sparse_resources.device_group_image_sparse_memory_aliasing.2d_array.r16i.503_137_3
Stack trace: Flake

FAILURE: dEQP-VK.sparse_resources.image_sparse_memory_aliasing.3d.rg8i.128_128_8
Stack trace: Flake

FAILURE: dEQP-VK.synchronization2.cross_instance.dedicated.write_blit_image_read_image_vertex.image_128x128_r8_unorm_binary_semaphore_win32
Stack trace: Flake

FAILURE: dEQP-VK.synchronization2.cross_instance.suballocated.write_clear_color_image_read_image_geometry.image_128x128_r16g16b16a16_uint_binary_semaphore_fd
Stack trace: Flake

FAILURE: dEQP-VK.synchronization2.op.single_queue.fence.write_image_compute_read_blit_image.image_128x128_r8g8b8a8_unorm
Stack trace: Flake

FAILURE: dEQP-VK.synchronization2.timeline_semaphore.device_host.write_image_geometry_read_image_compute_indirect.image_128x128_r16_uint
Stack trace: Flake
```
</p></details></li>

<li>Not Supported: 32121/73925 (43.5%)</li><li>Warnings: 0/73925 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 38445/73925 (52.0%)</li>
<li>Failed: 0/73925 (0.0%)</li>
<li>Not Supported: 35480/73925 (48.0%)</li><li>Warnings: 0/73925 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 36014/69706 (51.7%)</li>
<li>Failed: 0/69706 (0.0%)</li>
<li>Not Supported: 33692/69706 (48.3%)</li><li>Warnings: 0/69706 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit bd9e8a103c62ecac47ccb6bb967158f4f1d99687
<details><summary>CTS tests (Failed: 0/291482)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 37494/73926 (50.7%)</li>
<li>Failed: 0/73926 (0.0%)</li>
<li>Not Supported: 36432/73926 (49.3%)</li><li>Warnings: 0/73926 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 41801/73925 (56.5%)</li>
<li>Failed: 0/73925 (0.0%)</li>
<li>Not Supported: 32124/73925 (43.5%)</li><li>Warnings: 0/73925 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 38445/73925 (52.0%)</li>
<li>Failed: 0/73925 (0.0%)</li>
<li>Not Supported: 35480/73925 (48.0%)</li><li>Warnings: 0/73925 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 36014/69706 (51.7%)</li>
<li>Failed: 0/69706 (0.0%)</li>
<li>Not Supported: 33692/69706 (48.3%)</li><li>Warnings: 0/69706 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM

**Pull request merged**
