### PR TITLE
Remove special handling of JumpThreading pass

### PR DESCRIPTION
**Pull request by jayfoad**
The legacy JumpThreading pass has been removed by a recent upstream LLVM commit so the getPassIdFromName call will fail, but anyway there is no need to try to handle it here.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
de3af55da7b79139a459bdd83fdfde3ed49e7980 Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchInOutImportExport.cpp:662:57: error: cannot convert ‘llvm::Type*’ to ‘llvm::Value*’ in initialization
       Value *locOffset = genericLocationOp.getLocOffset();
                                                         ^
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchInOutImportExport.cpp:715:48: error: cannot convert ‘llvm::Type*’ to ‘llvm::Value*’ in assignment
         elemIdx = genericLocationOp.getElemIdx();
                                                ^
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchInOutImportExport.cpp:724:96: error: no matching function for call to ‘lgc::PatchInOutImportExport::patchTcsGenericInputImport(llvm::Type*&, unsigned int&, llvm::Value*&, llvm::Value*&, llvm::Type*&, lgc::BuilderBase&)’
         input = patchTcsGenericInputImport(inputTy, loc, locOffset, elemIdx, vertexIdx, builder);
                                                                                                ^
In file included from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchInOutImportExport.cpp:32:0:
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/include/lgc/patch/PatchInOutImportExport.h:72:16: note: candidate: llvm::Value* lgc::PatchInOutImportExport::patchTcsGenericInputImport(llvm::Type*, unsigned int, llvm::Value*, llvm::Value*, llvm::Value*, lgc::BuilderBase&)
   llvm::Value *patchTcsGenericInputImport(llvm::Type *inputTy, unsigned location, llvm::Value *locOffset,
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchInOutImportExport.cpp:732:45: error: cannot convert ‘llvm::Type*’ to ‘llvm::Value*’ in assignment
           vertexIdx = inputOp.getArrayIndex();
                                             ^
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchInOutImportExport.cpp:741:50: error: cannot convert ‘llvm::Type*’ to ‘llvm::Value*’ in initialization
         Value *vertexIdx = inputOp.getArrayIndex();
                                                  ^
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchInOutImportExport.cpp:802:59: error: cannot convert ‘llvm::Type*’ to ‘llvm::Value*’ in initialization
       Value *locOffset = outputImportGeneric.getLocOffset();
                                                           ^
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchInOutImportExport.cpp:825:97: error: no matching function for call to ‘lgc::PatchInOutImportExport::patchTcsGenericOutputImport(llvm::Type*&, unsigned int&, llvm::Value*&, llvm::Type*&, llvm::Type*&, lgc::BuilderBase&)’
       output = patchTcsGenericOutputImport(outputTy, loc, locOffset, elemIdx, vertexIdx, builder);
                                                                                                 ^
In file included from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchInOutImportExport.cpp:32:0:
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/include/lgc/patch/PatchInOutImportExport.h:92:16: note: candidate: llvm::Value* lgc::PatchInOutImportExport::patchTcsGenericOutputImport(llvm::Type*, unsigned int, llvm::Value*, llvm::Value*, llvm::Value*, lgc::BuilderBase&)
   llvm::Value *patchTcsGenericOutputImport(llvm::Type *outputTy, unsigned location, llvm::Value *locOffset,
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchResourceCollect.cpp:2740:61: error: cannot convert ‘llvm::Type*’ to ‘llvm::Value* const’ in initialization
         Value *const locOffset = outputImport->getLocOffset();
                                                             ^
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchResourceCollect.cpp:2741:57: error: cannot convert ‘llvm::Type*’ to ‘llvm::Value* const’ in initialization
         Value *const compIdx = outputImport->getElemIdx();
                                                         ^
In file included from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/interface/lgc/BuilderCommon.h:33:0,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/include/lgc/util/BuilderBase.h:33,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/include/lgc/patch/SystemValues.h:35,
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/imported/llvm-dialects/include/llvm-dialects/Dialect/Builder.h:46:24: error: no matching function for call to ‘lgc::InputImportInterpolatedOp::create(llvm_dialects::Builder&, llvm::IntegerType*, bool, unsigned int, llvm::Type*, llvm::Value*&, llvm::PoisonValue*, unsigned int, llvm::Value*)’
     Op *op = Op::create(*this, std::forward<Args>(args)...);
              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/interface/lgc/LgcDialect.h:35:0,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchResourceCollect.cpp:37:
compiler/llpc/llvm/tools/lgc/interface/lgc/LgcDialect.h.inc:163:39: note: candidate: static lgc::InputImportInterpolatedOp* lgc::InputImportInterpolatedOp::create(llvm_dialects::Builder&, llvm::Type*, bool, uint32_t, llvm::Value*, llvm::Value*, llvm::Value*, uint32_t, llvm::Value*)
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/imported/llvm-dialects/include/llvm-dialects/Dialect/Builder.h:46:24: error: no matching function for call to ‘lgc::InputImportGenericOp::create(llvm_dialects::Builder&, llvm::IntegerType*, bool, unsigned int, llvm::Type*, llvm::Value*&, llvm::Type*)’
     Op *op = Op::create(*this, std::forward<Args>(args)...);
              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/interface/lgc/LgcDialect.h:35:0,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchResourceCollect.cpp:37:
compiler/llpc/llvm/tools/lgc/interface/lgc/LgcDialect.h.inc:142:34: note: candidate: static lgc::InputImportGenericOp* lgc::InputImportGenericOp::create(llvm_dialects::Builder&, llvm::Type*, bool, uint32_t, llvm::Value*, llvm::Value*, llvm::Value*)
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/imported/llvm-dialects/include/llvm-dialects/Dialect/Builder.h:46:24: error: no matching function for call to ‘lgc::InputImportInterpolatedOp::create(llvm_dialects::Builder&, llvm::Type*&, bool, unsigned int&, llvm::Type*, llvm::ConstantInt*, llvm::PoisonValue*, unsigned int, llvm::Value*)’
     Op *op = Op::create(*this, std::forward<Args>(args)...);
              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/interface/lgc/LgcDialect.h:35:0,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchResourceCollect.cpp:37:
compiler/llpc/llvm/tools/lgc/interface/lgc/LgcDialect.h.inc:163:39: note: candidate: static lgc::InputImportInterpolatedOp* lgc::InputImportInterpolatedOp::create(llvm_dialects::Builder&, llvm::Type*, bool, uint32_t, llvm::Value*, llvm::Value*, llvm::Value*, uint32_t, llvm::Value*)
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/imported/llvm-dialects/include/llvm-dialects/Dialect/Builder.h:46:24: error: no matching function for call to ‘lgc::InputImportGenericOp::create(llvm_dialects::Builder&, llvm::Type*&, bool, unsigned int&, llvm::Type*, llvm::ConstantInt*, llvm::Type*)’
     Op *op = Op::create(*this, std::forward<Args>(args)...);
              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/interface/lgc/LgcDialect.h:35:0,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/patch/PatchResourceCollect.cpp:37:
compiler/llpc/llvm/tools/lgc/interface/lgc/LgcDialect.h.inc:142:34: note: candidate: static lgc::InputImportGenericOp* lgc::InputImportGenericOp::create(llvm_dialects::Builder&, llvm::Type*, bool, uint32_t, llvm::Value*, llvm::Value*, llvm::Value*)
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llvm-project/llvm/include/llvm/Support/Casting.h:64:64: error: no matching function for call to ‘llvm::ConstantInt::classof(const llvm::Type*)’
   static inline bool doit(const From &Val) { return To::classof(&Val); }
                                                     ~~~~~~~~~~~^~~~~~
In file included from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llvm-project/llvm/include/llvm/IR/ConstantFolder.h:21:0,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llvm-project/llvm/include/llvm/IR/IRBuilder.h:24,
                 from /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/lgc/include/lgc/state/PipelineState.h:40,

**Comment by dstutt** [comment]
Did you actually make changes to dialects?

**Comment by jayfoad** [comment]
> Did you actually make changes to dialects?

Not intentionally but it looks like I messed up its submodule pointer. Should be fixed now.

**Review by dstutt — APPROVED** [review]
LGTM

**Pull request merged**
