### PR TITLE
Use new ballot intrinsics to replace old ballot implementation

### PR DESCRIPTION
**Pull request by amdrexu**
This will generate better code to avoid v_cmp_ne.

### CODE REVIEW

**Review by nhaehnle — DISMISSED** [review]
Thanks!

**Comment by amdvlk-admin** [comment]
37a8d5af6fcf42d117cd55041ef1c01843b84924 Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:3200:65: error: ‘Vkgc::LlpcRaytracingMode’ has not been declared
 3200 |     static_assert(RaytracingNone == static_cast<unsigned>(Vkgc::LlpcRaytracingMode::None));
      |                                                                 ^~~~~~~~~~~~~~~~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:3201:67: error: ‘Vkgc::LlpcRaytracingMode’ has not been declared
 3201 |     static_assert(RaytracingLegacy == static_cast<unsigned>(Vkgc::LlpcRaytracingMode::Legacy));
      |                                                                   ^~~~~~~~~~~~~~~~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:3202:71: error: ‘Vkgc::LlpcRaytracingMode’ has not been declared
 3202 |     static_assert(RaytracingRefactored == static_cast<unsigned>(Vkgc::LlpcRaytracingMode::Gpurt2));
      |                                                                       ^~~~~~~~~~~~~~~~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:3203:31: error: ‘struct Vkgc::RayTracingPipelineBuildInfo’ has no member named ‘mode’
 3203 |     pCreateInfo->pipelineInfo.mode = static_cast<Vkgc::LlpcRaytracingMode>(settings.llpcRaytracingMode);
      |                               ^~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:3203:56: error: ‘LlpcRaytracingMode’ in namespace ‘Vkgc’ does not name a type
 3203 |     pCreateInfo->pipelineInfo.mode = static_cast<Vkgc::LlpcRaytracingMode>(settings.llpcRaytracingMode);
      |                                                        ^~~~~~~~~~~~~~~~~~
[3008/3083] Building CXX object icd/CMakeFiles/xgl.dir/api/vk_debug_report.cpp.o
[3009/3083] Building CXX object icd/CMakeFiles/xgl.dir/api/vk_debug_utils.cpp.o
[3010/3083] Building CXX object icd/CMakeFiles/xgl.dir/api/debug_printf.cpp.o

**Comment by amdvlk-admin** [comment]
### Test summary for commit a45e5cd4b64eb158720887af8af3f9211fb91a7c
<details><summary>CTS tests (Failed: 0/211353)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35147/70456 (49.9%)</li>
<li>Failed: 0/70456 (0.0%)</li>
<li>Not Supported: 35309/70456 (50.1%)</li><li>Warnings: 0/70456 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39026/70456 (55.4%)</li>
<li>Failed: 0/70456 (0.0%)</li>
<li>Not Supported: 31430/70456 (44.6%)</li><li>Warnings: 0/70456 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39058/70441 (55.4%)</li>
<li>Failed: 0/70441 (0.0%)</li>
<li>Not Supported: 31383/70441 (44.6%)</li><li>Warnings: 0/70441 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
Thanks!

**Pull request merged**
