### PR TITLE
Fix {Set,Get}RegCombine Typo

### PR DESCRIPTION
**Pull request by jiaxie-amd**
Signed-off-by: Jiajun Xie <jiaxie@amd.com>

### CODE REVIEW

**Comment by JaxLinAMD** [comment]
please resolve conflicts

**Comment by JaxLinAMD** [comment]
@amdrexu , could you help check is there any issue about coding standard?

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by jiaxie-amd** [comment]
@JaxLinAMD , please merge this change as soon as possible if there's no other issues, thanks.

**Comment by JaxLinAMD** [comment]
merge process is started, please don't force-push any more.

**Pull request merged**
