### PR TITLE
Lowers subgroup operations further in the pass pipeline.

### PR DESCRIPTION
**Pull request by RyanRio**
Could allow more high level optimizations to be done and additionally allows pre-subgroup-lowering analyses to be performed further.

### CODE REVIEW

**Comment by qiaojbao** [comment]
This PR caused psdb test agent hang.
[85319.435948] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
[85379.435913] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
[85439.434669] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
[85499.434360] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
[85559.434664] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
[85619.433408] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!

**Review by nhaehnle — COMMENTED** [review]
Thank you for cleaning this up and splitting it out. Especially since there are apparently hidden bugs, we should try to keep it split-out to help narrow down where the issue is. So first, a couple of high-level notes about how the commits are structured.

1. The golden rule of Git commit messages is that the first line is a special "title" line which should describe what the change does in imperative form. After the title line there *must* be an empty line -- else, tooling breaks. For the first commit, this means I would rewrite the commit message as (and the other commits should get similar treatment):
```
Add DPP support info to GpuProperty

* supportsDpp
* supportsDppRowXmask
* supportsPermLaneDpp
```
2. In a series like this, the main benefit is obtained if each change is a logical change that keeps things working: at a minimum, the code should compile and pass `check-amdllpc` and `check-lgc` after each commit. Our CI infrastructure unfortunately cannot do that, but a helpful tool for testing that locally is to do something like `git rebase -i $(git merge-base HEAD dev) -x "ninja -C <build-dir> check-amdllpc check-lgc"`.
3. For this particular series, this means that the order of changes needs to be revised. From a glance, commits 4&5 need to be moved to the front, while commits 2&3 either need to be squashed or their order reversed.
4. Unfortunately, GitHub and our CI tooling is not good at handling these multi-commit series. They're still useful (it already made it much easier to review, for example), but we'll have to work around the limitations to actually land them. In practice, this means that I would suggest you take the uncontroversial parts (starting with the very first commit) and create a new PR with just that commit so that we can go ahead and land it -- while also keeping this PR open. You'll have to rebase this PR after that other PR has landed.

**Comment by RyanRio** [comment]
> Thank you for cleaning this up and splitting it out. Especially since there are apparently hidden bugs, we should try to keep it split-out to help narrow down where the issue is. So first, a couple of high-level notes about how the commits are structured.
> 
> 1. The golden rule of Git commit messages is that the first line is a special "title" line which should describe what the change does in imperative form. After the title line there _must_ be an empty line -- else, tooling breaks. For the first commit, this means I would rewrite the commit message as (and the other commits should get similar treatment):
> 
> ```
> Add DPP support info to GpuProperty
> 
> * supportsDpp
> * supportsDppRowXmask
> * supportsPermLaneDpp
> ```
> 
> 2. In a series like this, the main benefit is obtained if each change is a logical change that keeps things working: at a minimum, the code should compile and pass `check-amdllpc` and `check-lgc` after each commit. Our CI infrastructure unfortunately cannot do that, but a helpful tool for testing that locally is to do something like `git rebase -i $(git merge-base HEAD dev) -x "ninja -C <build-dir> check-amdllpc check-lgc"`.
> 3. For this particular series, this means that the order of changes needs to be revised. From a glance, commits 4&5 need to be moved to the front, while commits 2&3 either need to be squashed or their order reversed.
> 4. Unfortunately, GitHub and our CI tooling is not good at handling these multi-commit series. They're still useful (it already made it much easier to review, for example), but we'll have to work around the limitations to actually land them. In practice, this means that I would suggest you take the uncontroversial parts (starting with the very first commit) and create a new PR with just that commit so that we can go ahead and land it -- while also keeping this PR open. You'll have to rebase this PR after that other PR has landed.

Thanks, that's all very helpful, I'll revise 🙂

**Comment by nhaehnle** [comment]
I'm assuming you're going to continue peeling off changes from this PR, which works for me. Ping me explicitly if you want another look at this PR as a whole.

**Comment by RyanRio** [comment]
> I'm assuming you're going to continue peeling off changes from this PR, which works for me. Ping me explicitly if you want another look at this PR as a whole.

Yes, that's correct, just keeping this open for reference in the other PRs 🙂

**Comment by RyanRio** [comment]
@nhaehnle I removed the gpuproperty info, squashed the commits and made sure it passes check-amdllpc and check-lgc. Do we want to have this be split apart into 2 commits (and 2 PRs)? Personally I don't see a meaningful way to do that given it is just "move builder code into a later pass"

**Comment by qiaojbao** [comment]
This change caused many failures and 22.04 hang. 
20.04 navi10
[17024/72724] Pass: 5639 Fail: 1054 Skip: 5646 ExpectedFail: 0 UnexpectedPass: 0 Crash: 10 Timeout: 0 Missing: 2525 Flake: 2150 Duration: 18:18 Remaining: 59:53
rhel9 gfx9
[68491/68491] Pass: 34776 Fail: 26 Skip: 22718 ExpectedFail: 0 UnexpectedPass: 0 Crash: 32 Timeout: 0 Missing: 10939 Flake: 0 Duration: 11:34 Remaining: 0

**Comment by nhaehnle** [comment]
It's pretty big, but I think it makes sense to keep this as a single commit.

**Comment by qiaojbao** [comment]
Still observed failures and crash.
gfx9
[66313/66313] Pass: 33425 Fail: 17 Skip: 21516 ExpectedFail: 0 UnexpectedPass: 0 Crash: 34 Timeout: 0 Missing: 11321 Flake: 0 Duration: 11:06 Remaining: 0
gfx10
[19456/70474] Pass: 7063 Fail: 848 Skip: 6357 ExpectedFail: 0 UnexpectedPass: 0 Crash: 17 Timeout: 0 Missing: 3144 Flake: 2027 Duration: 19:11 Remaining: 50:19
navi21
[25984/70466] Pass: 11024 Fail: 1634 Skip: 7434 ExpectedFail: 0 UnexpectedPass: 0 Crash: 16 Timeout: 0 Missing: 4258 Flake: 1618 Duration: 18:46 Remaining: 32:07
And all test timeout.

**Comment by RyanRio** [comment]
Thanks, I'm checking the failed tests now

**Pull request closed without merging**
