### PR TITLE
[LLPC] Refactor the explicit layout

### PR DESCRIPTION
**Pull request by ruiling**
By introducing a new LayoutMode enum, it becomes easy to further extend the transType() family of functions without introducing new argument.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 34d043852bf2b4ff49fb334b37cadf3de933f46e
<details><summary>CTS tests (Failed: 0/215998)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40685/72006 (56.5%)</li>
<li>Failed: 0/72006 (0.0%)</li>
<li>Not Supported: 31321/72006 (43.5%)</li><li>Warnings: 0/72006 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40713/71984 (56.6%)</li>
<li>Failed: 0/71984 (0.0%)</li>
<li>Not Supported: 31271/71984 (43.4%)</li><li>Warnings: 0/71984 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36765/72008 (51.1%)</li>
<li>Failed: 0/72008 (0.0%)</li>
<li>Not Supported: 35243/72008 (48.9%)</li><li>Warnings: 0/72008 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 10a5c064fad750952208f216ed0e20346f136835
<details><summary>CTS tests (Failed: 0/215998)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40685/72006 (56.5%)</li>
<li>Failed: 0/72006 (0.0%)</li>
<li>Not Supported: 31321/72006 (43.5%)</li><li>Warnings: 0/72006 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40713/71984 (56.6%)</li>
<li>Failed: 0/71984 (0.0%)</li>
<li>Not Supported: 31271/71984 (43.4%)</li><li>Warnings: 0/71984 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36765/72008 (51.1%)</li>
<li>Failed: 0/72008 (0.0%)</li>
<li>Not Supported: 35243/72008 (48.9%)</li><li>Warnings: 0/72008 (0.0%)</li>
</ul></details>


</ul></details>

**Review by Flakebi — APPROVED** [review]
Looks good to me

**Review by nhaehnle — APPROVED** [review]
Thanks!

**Pull request merged**
