### PR TITLE
Don't try to merge ELF binaries containing relocs.

### PR DESCRIPTION
**Pull request by jayfoad**
Partial pipeline compilation relies on compiling the shaders in a
pipeline separately and then using llpcElfWriter to merge the ELFs.
Don't do this if the shaders contain global constant data because LLVM
has recently started putting this data in a separate .rodata section and
using relocs in the .text section to refer to it, but llpcElfWriter
doesn't know how to update the relocs when it merges the ELFs.

### CODE REVIEW

**Review by trenouf — APPROVED** [review]
LGTM

**Comment by amdvlk-admin** [comment]
### Test summary for commit c9f494c3b9ec9940cfcac4c40900c3226c325181
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 9074bd0bdaf67fa84399dfabed3ec437951838f8</li>
<li>SPVGEN: dev c054813a9a894e32aaaa04c6717a667c15f60cfd</li>
<li>XGL: dev 598c6832a4983f5b75b38a589fca5be80a2f3bb0</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev ccbc834ac4f92e63a9a003bd5a18cb9fcf3c6121</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/129722)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43245 (52.7%)</li>
<li>Failed: 0/43245 (0.0%)</li>
<li>Skipped: 20461/43245 (47.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22781/43249 (52.7%)</li>
<li><details><summary>Failed: 2/43249 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_storage_texel_buffer.8192
Stack trace: Flake

FAILURE: dEQP-VK.texture.filtering.3d.combinations.nearest_mipmap_nearest.linear.clamp_to_border.mirrored_repeat.clamp_to_border
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 20466/43249 (47.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43228 (50.0%)</li>
<li>Failed: 0/43228 (0.0%)</li>
<li>Skipped: 21619/43228 (50.0%)</li>
</ul></details>


</ul></details>

**Comment by jayfoad** [comment]
retest this please

**Comment by dstutt** [comment]
retest this please

**Comment by trenouf** [comment]
Those two failures look spurious, so I will merge this anyway.

**Comment by amdvlk-admin** [comment]
### Test summary for commit c9f494c3b9ec9940cfcac4c40900c3226c325181
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 9074bd0bdaf67fa84399dfabed3ec437951838f8</li>
<li>SPVGEN: dev c054813a9a894e32aaaa04c6717a667c15f60cfd</li>
<li>XGL: dev 598c6832a4983f5b75b38a589fca5be80a2f3bb0</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev ccbc834ac4f92e63a9a003bd5a18cb9fcf3c6121</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/129722)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43245 (52.7%)</li>
<li>Failed: 0/43245 (0.0%)</li>
<li>Skipped: 20461/43245 (47.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22782/43249 (52.7%)</li>
<li><details><summary>Failed: 1/43249 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.tessellation.invariance.outer_triangle_set.triangles_equal_spacing
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 20466/43249 (47.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43228 (50.0%)</li>
<li>Failed: 0/43228 (0.0%)</li>
<li>Skipped: 21619/43228 (50.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
