### PR TITLE
Fix for LLVM upstream deprecation of BasicBlock::getInstList()

### PR DESCRIPTION
**Pull request by Sisyph**
D139905 makes the function private.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 25e2331be23ad7298e9ca9b94bed9e6089f9e095
<details><summary>CTS tests (Failed: 5/207253)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39094/70470 (55.5%)</li>
<li><details><summary>Failed: 5/70470 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_2.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_2.triangles.degenerate.min
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.0_00
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70470 (44.5%)</li><li>Warnings: 0/70470 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35944/70472 (51.0%)</li>
<li>Failed: 0/70472 (0.0%)</li>
<li>Not Supported: 34528/70472 (49.0%)</li><li>Warnings: 0/70472 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33663/66311 (50.8%)</li>
<li>Failed: 0/66311 (0.0%)</li>
<li>Not Supported: 32648/66311 (49.2%)</li><li>Warnings: 0/66311 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b37baa3afa04bb65f21b332b0c6218eef9020330
<details><summary>CTS tests (Failed: 2/207253)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39097/70470 (55.5%)</li>
<li><details><summary>Failed: 2/70470 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.0_00
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.max
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70470 (44.5%)</li><li>Warnings: 0/70470 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35944/70472 (51.0%)</li>
<li>Failed: 0/70472 (0.0%)</li>
<li>Not Supported: 34528/70472 (49.0%)</li><li>Warnings: 0/70472 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33663/66311 (50.8%)</li>
<li>Failed: 0/66311 (0.0%)</li>
<li>Not Supported: 32648/66311 (49.2%)</li><li>Warnings: 0/66311 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b37baa3afa04bb65f21b332b0c6218eef9020330
<details><summary>CTS tests (Failed: 3/207253)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39096/70470 (55.5%)</li>
<li><details><summary>Failed: 3/70470 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.0_00
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70470 (44.5%)</li><li>Warnings: 0/70470 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35944/70472 (51.0%)</li>
<li>Failed: 0/70472 (0.0%)</li>
<li>Not Supported: 34528/70472 (49.0%)</li><li>Warnings: 0/70472 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33663/66311 (50.8%)</li>
<li>Failed: 0/66311 (0.0%)</li>
<li>Not Supported: 32648/66311 (49.2%)</li><li>Warnings: 0/66311 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b37baa3afa04bb65f21b332b0c6218eef9020330
<details><summary>CTS tests (Failed: 3/207253)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39096/70470 (55.5%)</li>
<li><details><summary>Failed: 3/70470 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.0_00
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70470 (44.5%)</li><li>Warnings: 0/70470 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35944/70472 (51.0%)</li>
<li>Failed: 0/70472 (0.0%)</li>
<li>Not Supported: 34528/70472 (49.0%)</li><li>Warnings: 0/70472 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33663/66311 (50.8%)</li>
<li>Failed: 0/66311 (0.0%)</li>
<li>Not Supported: 32648/66311 (49.2%)</li><li>Warnings: 0/66311 (0.0%)</li>
</ul></details>


</ul></details>

**Review by jayfoad — APPROVED** [review]
You probably don't need the version checks since this was not a flag day change, but they are harmless.

**Comment by amdvlk-admin** [comment]
### Test summary for commit b37baa3afa04bb65f21b332b0c6218eef9020330
<details><summary>CTS tests (Failed: 3/207253)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39096/70470 (55.5%)</li>
<li><details><summary>Failed: 3/70470 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.0_00
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70470 (44.5%)</li><li>Warnings: 0/70470 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35944/70472 (51.0%)</li>
<li>Failed: 0/70472 (0.0%)</li>
<li>Not Supported: 34528/70472 (49.0%)</li><li>Warnings: 0/70472 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33663/66311 (50.8%)</li>
<li>Failed: 0/66311 (0.0%)</li>
<li>Not Supported: 32648/66311 (49.2%)</li><li>Warnings: 0/66311 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b37baa3afa04bb65f21b332b0c6218eef9020330
<details><summary>CTS tests (Failed: 2/207253)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39097/70470 (55.5%)</li>
<li><details><summary>Failed: 2/70470 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_2.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_2.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70470 (44.5%)</li><li>Warnings: 0/70470 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35944/70472 (51.0%)</li>
<li>Failed: 0/70472 (0.0%)</li>
<li>Not Supported: 34528/70472 (49.0%)</li><li>Warnings: 0/70472 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33663/66311 (50.8%)</li>
<li>Failed: 0/66311 (0.0%)</li>
<li>Not Supported: 32648/66311 (49.2%)</li><li>Warnings: 0/66311 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b37baa3afa04bb65f21b332b0c6218eef9020330
<details><summary>CTS tests (Failed: 3/207253)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39096/70470 (55.5%)</li>
<li><details><summary>Failed: 3/70470 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.0_00
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70470 (44.5%)</li><li>Warnings: 0/70470 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35944/70472 (51.0%)</li>
<li>Failed: 0/70472 (0.0%)</li>
<li>Not Supported: 34528/70472 (49.0%)</li><li>Warnings: 0/70472 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33663/66311 (50.8%)</li>
<li>Failed: 0/66311 (0.0%)</li>
<li>Not Supported: 32648/66311 (49.2%)</li><li>Warnings: 0/66311 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
I would prefer if you removed the version checks while we wait for CI to stabilize (unless there is some genuine reason why they're needed).

**Comment by amdvlk-admin** [comment]
b37baa3afa04bb65f21b332b0c6218eef9020330 Jenkins build error.
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/xgl/icd/api/pipeline_compiler.cpp:1568:9: error: ‘struct Vkgc::PipelineOptions’ has no member named ‘optimizeTessFactor’
     dst.optimizeTessFactor                    |= src.optimizeTessFactor;
         ^~~~~~~~~~~~~~~~~~
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/xgl/icd/api/pipeline_compiler.cpp:1568:54: error: ‘const struct Vkgc::PipelineOptions’ has no member named ‘optimizeTessFactor’
     dst.optimizeTessFactor                    |= src.optimizeTessFactor;
                                                      ^~~~~~~~~~~~~~~~~~
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/xgl/icd/api/pipeline_compiler.cpp: In member function ‘void vk::PipelineCompiler::ApplyPipelineOptions(const vk::Device*, VkPipelineCreateFlags, Vkgc::PipelineOptions*)’:
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/xgl/icd/api/pipeline_compiler.cpp:2672:15: error: ‘struct Vkgc::PipelineOptions’ has no member named ‘optimizeTessFactor’
     pOptions->optimizeTessFactor         = settings.optimizeTessFactor;
               ^~~~~~~~~~~~~~~~~~
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/xgl/icd/api/pipeline_compiler.cpp: In member function ‘void vk::PipelineCompiler::SetRayTracingState(const vk::Device*, Vkgc::RtState*, uint32_t)’:
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/xgl/icd/api/pipeline_compiler.cpp:3624:19: error: ‘struct Vkgc::RtState’ has no member named ‘enableRayTracingHwTraversalStack’; did you mean ‘enableRayTracingCounters’?
         pRtState->enableRayTracingHwTraversalStack = 1;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   enableRayTracingCounters
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/xgl/icd/api/pipeline_compiler.cpp:3631:23: error: ‘struct Vkgc::RtState’ has no member named ‘enableRayTracingHwTraversalStack’; did you mean ‘enableRayTracingCounters’?
             pRtState->enableRayTracingHwTraversalStack = 0;
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       enableRayTracingCounters
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/xgl/icd/api/pipeline_compiler.cpp:3635:23: error: ‘struct Vkgc::RtState’ has no member named ‘enableRayTracingHwTraversalStack’; did you mean ‘enableRayTracingCounters’?
             pRtState->enableRayTracingHwTraversalStack = 1;
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       enableRayTracingCounters
[2884/2956] Building CXX object icd/CMakeFiles/xgl.dir/api/pipeline_binary_cache.cpp.o
[2885/2956] Building CXX object icd/CMakeFiles/xgl.dir/api/vk_buffer.cpp.o

**Comment by Sisyph** [comment]
It looks to me like the flag day flags are required. At least in the ci build, it checked out llvm-project bf4edb422a7f334b3d61871bd2d0ec4111190224 , which is quite old, and doesn't contain BasicBlock::splice etc.

**Comment by amdvlk-admin** [comment]
7406a1124cf458e5fc3f8ffe7c0a1a9c82f81eb0 Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/llpc/lgc/patch/Gfx9ConfigBuilder.cpp:1502:52: error: ‘struct lgc::ResourceUsage::<unnamed>’ has no member named ‘xfbStrides’
       xfbStridesInDwords[i] = resUsage->inOutUsage.xfbStrides[i] / sizeof(unsigned);
                                                    ^~~~~~~~~~
[2749/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/FragColorExport.cpp.o
[2750/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/Gfx6ConfigBuilder.cpp.o
[2751/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/elfLinker/ElfLinker.cpp.o
--
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/llpc/lgc/patch/NggPrimShader.cpp:6132:108: error: ‘struct lgc::ResourceUsage::<unnamed>’ has no member named ‘xfbStrides’
       m_pipelineState->getShaderResourceUsage(hasTs ? ShaderStageTessEval : ShaderStageVertex)->inOutUsage.xfbStrides;
                                                                                                            ^~~~~~~~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/llpc/lgc/patch/NggPrimShader.cpp: In member function ‘void lgc::NggPrimShader::processGsXfbOutputExport(llvm::Module*, llvm::Argument*)’:
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/llpc/lgc/patch/NggPrimShader.cpp:6752:45: error: ‘const struct lgc::ResourceUsage::<unnamed>’ has no member named ‘streamXfbBuffers’
   const auto &streamXfbBuffers = inOutUsage.streamXfbBuffers;
                                             ^~~~~~~~~~~~~~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/llpc/lgc/patch/NggPrimShader.cpp:6753:39: error: ‘const struct lgc::ResourceUsage::<unnamed>’ has no member named ‘xfbStrides’
   const auto &xfbStrides = inOutUsage.xfbStrides;
                                       ^~~~~~~~~~
[2754/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/PatchCheckShaderCache.cpp.o
[2755/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/PatchInvariantLoads.cpp.o
[2756/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/PatchCopyShader.cpp.o

**Comment by amdvlk-admin** [comment]
7406a1124cf458e5fc3f8ffe7c0a1a9c82f81eb0 Jenkins build error.
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/llpc/lgc/patch/Gfx9ConfigBuilder.cpp:1502:52: error: ‘struct lgc::ResourceUsage::<unnamed>’ has no member named ‘xfbStrides’
       xfbStridesInDwords[i] = resUsage->inOutUsage.xfbStrides[i] / sizeof(unsigned);
                                                    ^~~~~~~~~~
[2794/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/elfLinker/ElfLinker.cpp.o
[2795/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/FragColorExport.cpp.o
[2796/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/Gfx6ConfigBuilder.cpp.o
--
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/llpc/lgc/patch/NggPrimShader.cpp:6132:108: error: ‘struct lgc::ResourceUsage::<unnamed>’ has no member named ‘xfbStrides’
       m_pipelineState->getShaderResourceUsage(hasTs ? ShaderStageTessEval : ShaderStageVertex)->inOutUsage.xfbStrides;
                                                                                                            ^~~~~~~~~~
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/llpc/lgc/patch/NggPrimShader.cpp: In member function ‘void lgc::NggPrimShader::processGsXfbOutputExport(llvm::Module*, llvm::Argument*)’:
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/llpc/lgc/patch/NggPrimShader.cpp:6752:45: error: ‘const struct lgc::ResourceUsage::<unnamed>’ has no member named ‘streamXfbBuffers’
   const auto &streamXfbBuffers = inOutUsage.streamXfbBuffers;
                                             ^~~~~~~~~~~~~~~~
/home/amdvlk/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/llpc/lgc/patch/NggPrimShader.cpp:6753:39: error: ‘const struct lgc::ResourceUsage::<unnamed>’ has no member named ‘xfbStrides’
   const auto &xfbStrides = inOutUsage.xfbStrides;
                                       ^~~~~~~~~~
[2801/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/PatchImageDerivatives.cpp.o
[2802/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/PatchCopyShader.cpp.o
[2803/2957] Building CXX object compiler/llpc/llvm/tools/lgc/CMakeFiles/LLVMlgc.dir/patch/PatchInvariantLoads.cpp.o

**Comment by qiaojbao** [comment]
Please rebase the PR, Q4.4 released.

**Comment by amdvlk-admin** [comment]
### Test summary for commit b7df40a20acd98e87af39d36f0767ad8fa4af80c
<details><summary>CTS tests (Failed: 0/277243)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38849/70350 (55.2%)</li>
<li>Failed: 0/70350 (0.0%)</li>
<li>Not Supported: 31501/70350 (44.8%)</li><li>Warnings: 0/70350 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39099/70350 (55.6%)</li>
<li>Failed: 0/70350 (0.0%)</li>
<li>Not Supported: 31251/70350 (44.4%)</li><li>Warnings: 0/70350 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35944/70352 (51.1%)</li>
<li>Failed: 0/70352 (0.0%)</li>
<li>Not Supported: 34408/70352 (48.9%)</li><li>Warnings: 0/70352 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33663/66191 (50.9%)</li>
<li>Failed: 0/66191 (0.0%)</li>
<li>Not Supported: 32528/66191 (49.1%)</li><li>Warnings: 0/66191 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by Sisyph** [comment]
I rebased and the checks are passing, can someone please approve it?

**Review by nhaehnle — APPROVED** [review]

**Pull request merged**
