### PR TITLE
lgc: Move handling of GroupMemcpy for mesh/task shaders to MeshTaskShader

### PR DESCRIPTION
**Pull request by xazhangAMD**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit e5ba891624d85ed3ccbb33ae470b13f9239c6c9e
<details><summary>CTS tests (Failed: 0/138362)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35163/69147 (50.9%)</li>
<li>Failed: 0/69147 (0.0%)</li>
<li>Not Supported: 33984/69147 (49.1%)</li><li>Warnings: 0/69147 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35242/69215 (50.9%)</li>
<li>Failed: 0/69215 (0.0%)</li>
<li>Not Supported: 33973/69215 (49.1%)</li><li>Warnings: 0/69215 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit e64fcfe31555d10de2863a3172c6b763bd67cbab
<details><summary>CTS tests (Failed: 0/138443)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35211/69228 (50.9%)</li>
<li>Failed: 0/69228 (0.0%)</li>
<li>Not Supported: 34017/69228 (49.1%)</li><li>Warnings: 0/69228 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35241/69215 (50.9%)</li>
<li>Failed: 0/69215 (0.0%)</li>
<li>Not Supported: 33974/69215 (49.1%)</li><li>Warnings: 0/69215 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
I didn't see the other discussion early enough. Is there really no better way of doing this? For example, if you do move this into its own pass, could use a generic implementation that uses lgc.input.import.builtin or some other pre-existing ops?

I don't particularly fancy a further proliferation of passes, but I think a number of very similar tasks of "lowering operations" like this could be combined into one pass. Though this doesn't necessarily have to happen in this PR.

**Comment by xazhangAMD** [comment]
> I didn't see the other discussion early enough. Is there really no better way of doing this? For example, if you do move this into its own pass, could use a generic implementation that uses lgc.input.import.builtin or some other pre-existing ops?
> 
> I don't particularly fancy a further proliferation of passes, but I think a number of very similar tasks of "lowering operations" like this could be combined into one pass. Though this doesn't necessarily have to happen in this PR.

Rex is going to refactor this for the CS part. My current change is just to make it a little easier for mesh/tash shaders. BTW, I need another PR first because that solves several random mesh/task shader test failures. [2812](https://github.com/GPUOpen-Drivers/llpc/pull/2812)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 98f6e63d43bf6280a32313f34543b6a55d378ba8
<details><summary>CTS tests (Failed: 0/138362)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35163/69147 (50.9%)</li>
<li>Failed: 0/69147 (0.0%)</li>
<li>Not Supported: 33984/69147 (49.1%)</li><li>Warnings: 0/69147 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35242/69215 (50.9%)</li>
<li>Failed: 0/69215 (0.0%)</li>
<li>Not Supported: 33973/69215 (49.1%)</li><li>Warnings: 0/69215 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdrexu** [comment]
> Rex is going to refactor this for the CS part.

Yes, I will revisit this.

> I don't particularly fancy a further proliferation of passes, but I think a number of very similar tasks of "lowering operations" like this could be combined into one pass. 

The pass `PatchInitializeWorkgroupMemory` does similar thing but is not very generic. I will think about it and do some refactoring work. Currently, task/mesh lowering of memory copy requested by Xavi is added to `MeshTaskShader` only CS need to be handled particularly.

**Comment by nhaehnle** [comment]
So just to be clear, do we wait for the revised version on this?

**Comment by xazhangAMD** [comment]
The fix for random thread IDs has been merged so I have a working version for LLPCFE. This PR can be reviewed as is now or I can also wait for Rex's refactor, too.

**Comment by xazhangAMD** [comment]
Close this PR for now

**Pull request closed without merging**
