### PR TITLE
Promotion from AMD internal branch for 2023.Q2.2

### PR DESCRIPTION
**Pull request by WenqingLiAMD**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit c85199a601292ac9233e043ca1ec5c7100935add
<details><summary>CTS tests (Failed: 0/213076)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40074/71028 (56.4%)</li>
<li>Failed: 0/71028 (0.0%)</li>
<li>Not Supported: 30954/71028 (43.6%)</li><li>Warnings: 0/71028 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40112/71018 (56.5%)</li>
<li>Failed: 0/71018 (0.0%)</li>
<li>Not Supported: 30906/71018 (43.5%)</li><li>Warnings: 0/71018 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36218/71030 (51.0%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 34812/71030 (49.0%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 23de3bc4ec4426710d9fc83141599586c389472b
<details><summary>CTS tests (Failed: 0/213076)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40074/71028 (56.4%)</li>
<li>Failed: 0/71028 (0.0%)</li>
<li>Not Supported: 30954/71028 (43.6%)</li><li>Warnings: 0/71028 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40112/71018 (56.5%)</li>
<li>Failed: 0/71018 (0.0%)</li>
<li>Not Supported: 30906/71018 (43.5%)</li><li>Warnings: 0/71018 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36218/71030 (51.0%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 34812/71030 (49.0%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
Looks reasonable at a glance.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8cc7fef3c0c5ee7b1c9aba541c0fab77ca801eac
<details><summary>CTS tests (Failed: 0/213076)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40074/71028 (56.4%)</li>
<li>Failed: 0/71028 (0.0%)</li>
<li>Not Supported: 30954/71028 (43.6%)</li><li>Warnings: 0/71028 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40112/71018 (56.5%)</li>
<li>Failed: 0/71018 (0.0%)</li>
<li>Not Supported: 30906/71018 (43.5%)</li><li>Warnings: 0/71018 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36218/71030 (51.0%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 34812/71030 (49.0%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>


</ul></details>

**Review by Flakebi — APPROVED** [review]

**Review by amdrexu — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit ed8c4b233e8f20a48b9a003a731dc4b4bd1515a0
<details><summary>CTS tests (Failed: 0/213076)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40074/71028 (56.4%)</li>
<li>Failed: 0/71028 (0.0%)</li>
<li>Not Supported: 30954/71028 (43.6%)</li><li>Warnings: 0/71028 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40112/71018 (56.5%)</li>
<li>Failed: 0/71018 (0.0%)</li>
<li>Not Supported: 30906/71018 (43.5%)</li><li>Warnings: 0/71018 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx10</summary><ul>

<li>Passed: 36218/71030 (51.0%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 34812/71030 (49.0%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
