### PR TITLE
Add shader from #214 to shaderdb

### PR DESCRIPTION
**Pull request by kuhar**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by trenouf** [comment]
Hi Jakub. I have just merged #436, which moves llpc into a subdirectory "llpc". Could you rebase this change please. That will need manual intervention to add the new file to llpc/test/... instead of test/...

Sorry.

**Comment by kuhar** [comment]
Thanks for the heads-up, @trenouf. I rebased the patch.

BTW, I can see there's still a top-level test directory with a CMakeFile. Shouldn't it be moved inside the llpc subdirectory too?

**Comment by trenouf** [comment]
This has been stuck for ages waiting for its test result. It looks like the internal build never got triggered, so I have just manually triggered it.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 21d0f50f2f4ba360db6f63d89e88e0532e94b8c1
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 9fab16015e522fff05890a045a1e9d8d3c23a636</li>
<li>SPVGEN: dev a61db14f75728e91c243d4bfc1c39700e9dc0ba6</li>
<li>XGL: dev c0791473c087f5b5d75a21c6f2ace72ccd232a65</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 942/942 (100.0%)</li>
<li>Failed: 0/942 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65463/65463 (100.0%)</li>
<li>Failed: 0/65463 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
