### PR TITLE
Switch to metadata3.0 for gfx9+

### PR DESCRIPTION
**Pull request by xuechen417**
We will swtich to medadata3.0 by default for gfx9+ from this PR. The llpc option `-use-register-field-format` can be used to control the new or old metadata mode. Update the relavant llpc/lgc tests.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit b90e624fabb3750dc5212a74d1e66f025a6e6e68
<details><summary>CTS tests (Failed: 0/211876)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70631 (50.3%)</li>
<li>Failed: 0/70631 (0.0%)</li>
<li>Not Supported: 35135/70631 (49.7%)</li><li>Warnings: 0/70631 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39379/70629 (55.8%)</li>
<li>Failed: 0/70629 (0.0%)</li>
<li>Not Supported: 31250/70629 (44.2%)</li><li>Warnings: 0/70629 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70616 (55.8%)</li>
<li>Failed: 0/70616 (0.0%)</li>
<li>Not Supported: 31203/70616 (44.2%)</li><li>Warnings: 0/70616 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — DISMISSED** [review]

**Comment by xuechen417** [comment]
V1: Resolve the conflicts.

**Comment by xuechen417** [comment]
V2: Update tests to address test failures.

**Review by nhaehnle — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8d75cba5fd42845089c4eeab8f6481b77f703f9f
<details><summary>CTS tests (Failed: 0/211630)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35496/70549 (50.3%)</li>
<li>Failed: 0/70549 (0.0%)</li>
<li>Not Supported: 35053/70549 (49.7%)</li><li>Warnings: 0/70549 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39379/70547 (55.8%)</li>
<li>Failed: 0/70547 (0.0%)</li>
<li>Not Supported: 31168/70547 (44.2%)</li><li>Warnings: 0/70547 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39413/70534 (55.9%)</li>
<li>Failed: 0/70534 (0.0%)</li>
<li>Not Supported: 31121/70534 (44.1%)</li><li>Warnings: 0/70534 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
