### PR TITLE
Refactor Swizzling functions which contains compute_derivative, threa…

### PR DESCRIPTION
**Pull request by ruiminzhao**
…dIdSwizzling and reconfigWorkgroupLayout

1. Remove the redundance implementation between csThreadIdSwizzling and reconfigWorkgroupLayout
2. Combination the swizzling algorithm between Micro-tiling and Macro-tiling.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 40d849568e2ff6cdbeb5862fbb4a59a59ab4b55d
<details><summary>CTS tests (Failed: 0/277947)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70526 (55.1%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31662/70526 (44.9%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70526 (55.5%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31412/70526 (44.5%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70528 (51.0%)</li>
<li>Failed: 0/70528 (0.0%)</li>
<li>Not Supported: 34569/70528 (49.0%)</li><li>Warnings: 0/70528 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66367 (50.7%)</li>
<li>Failed: 0/66367 (0.0%)</li>
<li>Not Supported: 32689/66367 (49.3%)</li><li>Warnings: 0/66367 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4f90ce013b7e8b727964f5d45c05b59fa0fb2df1
<details><summary>CTS tests (Failed: 0/277947)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70526 (55.1%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31662/70526 (44.9%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70526 (55.5%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31412/70526 (44.5%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70528 (51.0%)</li>
<li>Failed: 0/70528 (0.0%)</li>
<li>Not Supported: 34569/70528 (49.0%)</li><li>Warnings: 0/70528 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66367 (50.7%)</li>
<li>Failed: 0/66367 (0.0%)</li>
<li>Not Supported: 32689/66367 (49.3%)</li><li>Warnings: 0/66367 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6781ad8fdea7fb8e6b261553fe23ade706d64108
<details><summary>CTS tests (Failed: 132/277947)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38735/70526 (54.9%)</li>
<li><details><summary>Failed: 132/70526 (0.2%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.clipping.clip_volume.inside.triangle_fan
Stack trace: Flake

FAILURE: dEQP-VK.compute.indirect_dispatch.gen_in_compute.multiple_groups
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.alias.i64_to_u64_std140_func_write
Stack trace: Flake

FAILURE: dEQP-VK.draw.renderpass.instanced.draw_indexed_vk_primitive_topology_point_list_attrib_divisor_1
Stack trace: Flake

FAILURE: dEQP-VK.glsl.440.linkage.varying.component.vert_in.ivec4.as_int_ivec3
Stack trace: Flake

FAILURE: dEQP-VK.glsl.arrays.unnamed_parameter.bool_fragment
Stack trace: Flake

FAILURE: dEQP-VK.glsl.atomic_operations.exchange_float32_tess_eval_reference
Stack trace: Flake

FAILURE: dEQP-VK.glsl.atomic_operations.or_signed64bit_geometry_reference
Stack trace: Flake

FAILURE: dEQP-VK.glsl.builtin.precision_fp16_storage16b.add.compute.scalar
Stack trace: Flake

FAILURE: dEQP-VK.glsl.builtin.precision_fp16_storage32b.atanh.compute.vec2
Stack trace: Flake

FAILURE: dEQP-VK.glsl.conversions.matrix_combine.float_bvec4_ivec4_bool_bool_int_to_mat4x3_fragment
Stack trace: Flake

FAILURE: dEQP-VK.glsl.conversions.vector_combine.bvec3_float_to_vec4_fragment
Stack trace: Flake

FAILURE: dEQP-VK.glsl.functions.datatypes.float_mat2_vertex
Stack trace: Flake

FAILURE: dEQP-VK.glsl.functions.datatypes.mat4x3_vertex
Stack trace: Flake

FAILURE: dEQP-VK.glsl.loops.special.while_constant_iterations.nested_sequence_vertex
Stack trace: Flake

FAILURE: dEQP-VK.glsl.struct.local.loop_assignment_vertex
Stack trace: Flake

FAILURE: dEQP-VK.glsl.struct.local.return_vertex
Stack trace: Flake

FAILURE: dEQP-VK.glsl.swizzles.vector_swizzles.mediump_bvec2_yxy_vertex
Stack trace: Flake

FAILURE: dEQP-VK.glsl.swizzles.vector_swizzles.mediump_bvec4_abba_vertex
Stack trace: Flake

FAILURE: dEQP-VK.graphicsfuzz.cov-sum-uniform-vector-components-round
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 31659/70526 (44.9%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70526 (55.5%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31412/70526 (44.5%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70528 (51.0%)</li>
<li>Failed: 0/70528 (0.0%)</li>
<li>Not Supported: 34569/70528 (49.0%)</li><li>Warnings: 0/70528 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66367 (50.7%)</li>
<li>Failed: 0/66367 (0.0%)</li>
<li>Not Supported: 32689/66367 (49.3%)</li><li>Warnings: 0/66367 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6781ad8fdea7fb8e6b261553fe23ade706d64108
<details><summary>CTS tests (Failed: 0/277947)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70526 (55.1%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31662/70526 (44.9%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70526 (55.5%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31412/70526 (44.5%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70528 (51.0%)</li>
<li>Failed: 0/70528 (0.0%)</li>
<li>Not Supported: 34569/70528 (49.0%)</li><li>Warnings: 0/70528 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66367 (50.7%)</li>
<li>Failed: 0/66367 (0.0%)</li>
<li>Not Supported: 32689/66367 (49.3%)</li><li>Warnings: 0/66367 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by ruiminzhao** [comment]
@nhaehnle  Please have a review on this, this PR has been reviewed internally before, this is the lgc part split which needs to be merged from GPUOpen-Drivers externally.

**Review by nhaehnle — APPROVED** [review]
Thanks!

**Pull request merged**
