### PR TITLE
Fix an issue of unspecified outputs that will be exported to FS

### PR DESCRIPTION
**Pull request by amdrexu**
We encounter a demo. In this demo, an output is not written by VS while its corresponding input is read by FS. The value then involves in some operations in FS and lead to corruption. Of course, this is surely an App issue violating GLSL spec requirements. But we can do something to accept this case.

### CODE REVIEW

**Comment by amdrexu** [comment]
We might encounter more similar issues in other stages. But most cases occurs in VS-FS pipeline. Not sure if it is worth of doing such fix or we should let App fix the issues.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8061138faf72dfc1a5638466a904d40925e69946
<details><summary>CTS tests (Failed: 0/207274)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 38905/70473 (55.2%)</li>
<li>Failed: 0/70473 (0.0%)</li>
<li>Not Supported: 31568/70473 (44.8%)</li><li>Warnings: 0/70473 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35750/70481 (50.7%)</li>
<li>Failed: 0/70481 (0.0%)</li>
<li>Not Supported: 34731/70481 (49.3%)</li><li>Warnings: 0/70481 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33476/66320 (50.5%)</li>
<li>Failed: 0/66320 (0.0%)</li>
<li>Not Supported: 32844/66320 (49.5%)</li><li>Warnings: 0/66320 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
Ugh. Would it be easy to check if the channel is actually read by FS so we don't do this for genuinely unused channels?

**Comment by amdrexu** [comment]
> Ugh. Would it be easy to check if the channel is actually read by FS so we don't do this for genuinely unused channels?

Yes, I should make changes to replace undef with 0.0 for truly used channels. Will update.

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
### Test summary for commit 8061138faf72dfc1a5638466a904d40925e69946
<details><summary>CTS tests (Failed: 0/207274)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 38905/70473 (55.2%)</li>
<li>Failed: 0/70473 (0.0%)</li>
<li>Not Supported: 31568/70473 (44.8%)</li><li>Warnings: 0/70473 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35750/70481 (50.7%)</li>
<li>Failed: 0/70481 (0.0%)</li>
<li>Not Supported: 34731/70481 (49.3%)</li><li>Warnings: 0/70481 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33476/66320 (50.5%)</li>
<li>Failed: 0/66320 (0.0%)</li>
<li>Not Supported: 32844/66320 (49.5%)</li><li>Warnings: 0/66320 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request closed without merging**
