### PR TITLE
 Removed fdiv from .ll library

### PR DESCRIPTION
**Pull request by trenouf**
LowerAlgebraTransform used to turn an fdiv instruction into a call to
fdiv in the .ll library. This commit changes it to generate the
equivalent code (fdiv into 1.0 then fmul) instead.

Change-Id: Ibfaf8c586eb7f684f8f49ee68d2898123a2e5e81

### CODE REVIEW

**Comment by trenouf** [comment]
This PR has multiple commits because it depends on another open PR. Please just review the topmost commit.

**Comment by trenouf** [comment]
Oops, I accidentally created the branch in GPUOpen-Drivers/llpc instead of trenouf/llpc. I'll remove it when this PR is done.

**Comment by amdvlk-admin** [comment]
### Test summary for commit cd0a282716c54ebfd11fafa61aaf052df14cfa36
<details open><summary>Driver commits used in build</summary><ul>

<li>METROHASH: amd-mainline 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 66e78b997748d03d77e1d706c10f1f17e18e5654</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 9b632ef4f132bddc94769702ed8b49efbc39d89c</li>
<li>LLVM: amd-vulkan-dev 9bc5dd4450a6361faf5c5661056a7ee494fad830</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 925/925 (100.0%)</li>
<li>Failed: 0/925 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 6757/6758 (100.0%)</li>
<li><details><summary>Failed: 1/6758 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.buffer.dedicated_alloc.transfer_src.transfer_dst.storage.index.vertex.indirect.create.zero
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 282963/282963 (100.0%)</li>
<li>Failed: 0/282963 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cd0a282716c54ebfd11fafa61aaf052df14cfa36
<details open><summary>Driver commits used in build</summary><ul>

<li>METROHASH: amd-mainline 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 66e78b997748d03d77e1d706c10f1f17e18e5654</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 9b632ef4f132bddc94769702ed8b49efbc39d89c</li>
<li>LLVM: amd-vulkan-dev 9bc5dd4450a6361faf5c5661056a7ee494fad830</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 925/925 (100.0%)</li>
<li>Failed: 0/925 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 366250/366250 (100.0%)</li>
<li>Failed: 0/366250 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 366376/366376 (100.0%)</li>
<li>Failed: 0/366376 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
I will land this.

**Comment by trenouf** [comment]
retest this please

**Comment by amdrexu** [comment]
Please retest this and merge it first.

**Comment by JacobHeAMD** [comment]
retest this please

**Pull request merged**
