### PR TITLE
Revert "[LLPC] Scalarize non-uniform loads inside the waterfall loop"

### PR DESCRIPTION
**Pull request by kmitropoulou**
This reverts commit 108e949cee9727eea4d8b10d30d6aecb57ae7a6e.

### CODE REVIEW

**Comment by kmitropoulou** [comment]
I revert this patch due to performance regressions.

**Comment by kmitropoulou** [comment]
test this please

**Comment by Flakebi** [comment]
Can you please add the details of the crash to the commit message? I.e. is it a CTS test or an app and which one?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9222dc2f287f0a50ae6d585f84b6ef4989e2b860
<details><summary>CTS tests (Failed: 274/208497)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Rhel 8.9, Gfx10</summary><ul>

<li>Passed: 36713/69503 (52.8%)</li>
<li><details><summary>Failed: 274/69503 (0.4%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.blit_image.all_formats.generate_mipmaps.from_base_level.layercount_6.r8g8b8a8_unorm.general_optimal_linear
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.depth_stencil_msaa_copy.whole.d32_sfloat_optimal_optimal_D_8_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.resolve_image.diff_image_size.dst_266_256_1_8_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.buffer_to_buffer_with_offset.5_7
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.resolve_image.copy_with_regions_before_resolving.2_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.core.clear_color_attachment.multiple_layers.b8g8r8a8_snorm_64x11
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.core.clear_color_image.2d.optimal.single_layer.a1r5g5b5_unorm_pack16_multiple_subresourcerange
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.clear_color_attachment.single_layer.r8g8_srgb_33x128_clamp_input
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.dedicated_allocation.clear_depth_stencil_attachment.cube_layers.d16_unorm
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.buffer_device_address.set3.depth2.basessbo.convertcheckuv2.store.replay.std140.frag
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.mutable_descriptor.single.switches.storage_buffer_storage_image.update_write.no_source.no_source.pool_expand_types.pre_update.no_array.frag
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.shader_access.primary_cmd_buf.uniform_buffer_dynamic.tess_ctrl.multiple_discontiguous_descriptor_sets.multiple_contiguous_descriptors.offset_view_nonzero_dynamic_zero
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.shader_access.primary_cmd_buf.with_template.combined_image_sampler_mutable.no_access.multiple_contiguous_descriptors.cube_array_base_slice
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_cull_distance.vert_geom.7_1
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_cull_distance.vert_tess.5_3_fragmentshader_read
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_cull_distance_dynamic_index.vert_geom.1_7
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.zero.u8vec4_array_to_uint8_t_uint8_t_array_4
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.zero.u8vec4_array_to_uvec3_uint16_t_array_1
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.zero.uint16_t_array_to_uvec3_float_array_1
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.zero.uvec4_array_to_uint16_t_array_2
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 32516/69503 (46.8%)</li><li>Warnings: 0/69503 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 41144/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28360/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 41178/69490 (59.3%)</li>
<li>Failed: 0/69490 (0.0%)</li>
<li>Not Supported: 28312/69490 (40.7%)</li><li>Warnings: 0/69490 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by kmitropoulou** [comment]
Baldur's Gate 3 crashed during performance testing.

**Comment by kmitropoulou** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9222dc2f287f0a50ae6d585f84b6ef4989e2b860
<details><summary>CTS tests (Failed: 0/208497)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36978/69503 (53.2%)</li>
<li>Failed: 0/69503 (0.0%)</li>
<li>Not Supported: 32525/69503 (46.8%)</li><li>Warnings: 0/69503 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 41144/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28360/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 41178/69490 (59.3%)</li>
<li>Failed: 0/69490 (0.0%)</li>
<li>Not Supported: 28312/69490 (40.7%)</li><li>Warnings: 0/69490 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9222dc2f287f0a50ae6d585f84b6ef4989e2b860
<details><summary>CTS tests (Failed: 0/208496)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36978/69503 (53.2%)</li>
<li>Failed: 0/69503 (0.0%)</li>
<li>Not Supported: 32525/69503 (46.8%)</li><li>Warnings: 0/69503 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 41144/69503 (59.2%)</li>
<li>Failed: 0/69503 (0.0%)</li>
<li>Not Supported: 28359/69503 (40.8%)</li><li>Warnings: 0/69503 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 41178/69490 (59.3%)</li>
<li>Failed: 0/69490 (0.0%)</li>
<li>Not Supported: 28312/69490 (40.7%)</li><li>Warnings: 0/69490 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by tsymalla** [comment]
Thanks! I was not aware of that crash happening.

**Pull request merged**
