### PR TITLE
Only pass -fno-aligned-new to compilers that recognize it

### PR DESCRIPTION
**Pull request by yavn**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Review by nhaehnle — COMMENTED** [review]
Thanks. Now that I actually look at it again, wouldn't it make more sense to make the condition `if(NOT WIN32)`?

Either the underlying problem doesn't affect Windows because of how DLLs work. In that case, checking based on WIN32 is the right thing to do.

Or the underlying problem *does* affect Windows. In that case, checking the compiler type is the right thing to do, but there'd have to be an else() case for MSVC.

**Comment by yavn** [comment]
I'd say the current condition is more to the point, but I'm happy to let the maintainers decide.

From the description of the change that introduced this code, the original problem seemed Linux-specific. We can always revisit later as the need arises.

**Comment by yavn** [comment]
Can we get this submitted, please?

**Comment by Flakebi** [comment]
I didn’t find any Windows equivalent, so it seems to be a Linux-only issue.

For reference the original issue is https://github.com/ValveSoftware/csgo-osx-linux/issues/2659, it exists for other games like Portal 2 and Dota 2 as well (and tcmalloc hasn’t been updated for them as far as I’m aware, so the root issue still exists there).

**Comment by nhaehnle** [comment]
> I didn’t find any Windows equivalent, so it seems to be a Linux-only issue.
> 
> For reference the original issue is [ValveSoftware/csgo-osx-linux#2659](https://github.com/ValveSoftware/csgo-osx-linux/issues/2659), it exists for other games like Portal 2 and Dota 2 as well (and tcmalloc hasn’t been updated for them as far as I’m aware, so the root issue still exists there).

I'd interpret this as it's a Linux-only issue and the CMakeLists.txt should reflect that.

**Comment by nhaehnle** [comment]
Yes

**Review by Flakebi — APPROVED** [review]

**Review by amdrexu — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 16c67f6ae1ebef40d7e77c237503b62720159f12
<details><summary>CTS tests (Failed: 0/285657)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 36222/72463 (50.0%)</li>
<li>Failed: 0/72463 (0.0%)</li>
<li>Not Supported: 36241/72463 (50.0%)</li><li>Warnings: 0/72463 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 40419/72473 (55.8%)</li>
<li>Failed: 0/72473 (0.0%)</li>
<li>Not Supported: 32054/72473 (44.2%)</li><li>Warnings: 0/72473 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 37135/72477 (51.2%)</li>
<li>Failed: 0/72477 (0.0%)</li>
<li>Not Supported: 35342/72477 (48.8%)</li><li>Warnings: 0/72477 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 34834/68244 (51.0%)</li>
<li>Failed: 0/68244 (0.0%)</li>
<li>Not Supported: 33410/68244 (49.0%)</li><li>Warnings: 0/68244 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
