### PR TITLE
Skip the store instruction when the index is out-of-bound if feature …

### PR DESCRIPTION
**Pull request by AnzhongHuang**
…robustBufferAccess is used. In Vulkan sepc the robustBufferAccess is only for buffer, but in this change it's also applied to private array.

### CODE REVIEW

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8efc37680e6a0701e44cbb0eb8b448920ac06d0a
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev e8b82e5f183f4cfcf4f7b893295c49d0fc929fa0</li>
<li>SPVGEN: dev 59095d3469e4fb7506da0e3d0cd78904ed71682f</li>
<li>XGL: dev 292ea8da8a985a72b9efe4db424f664b2e79d64d</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 836/836 (100.0%)</li>
<li>Failed: 0/836 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 253527/253528 (100.0%)</li>
<li><details><summary>Failed: 1/253528 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.wsi.xlib.surface.create
Stack trace: Failed to open display: '' at tcuLnxX11.cpp:67
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8efc37680e6a0701e44cbb0eb8b448920ac06d0a
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev e8b82e5f183f4cfcf4f7b893295c49d0fc929fa0</li>
<li>SPVGEN: dev 59095d3469e4fb7506da0e3d0cd78904ed71682f</li>
<li>XGL: dev b5440b6a385dbcb11739f1bdb89a94bbe5cd499f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 836/836 (100.0%)</li>
<li>Failed: 0/836 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6c0c968f1471e95e401ad05ae7227f97a3d1c00e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev e8b82e5f183f4cfcf4f7b893295c49d0fc929fa0</li>
<li>SPVGEN: dev 1560d287f779b342e0019499dda85890cb07affc</li>
<li>XGL: dev b5440b6a385dbcb11739f1bdb89a94bbe5cd499f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 836/836 (100.0%)</li>
<li>Failed: 0/836 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
