### PR TITLE
Remove memory intrinsic handling from PatchBufferOp

### PR DESCRIPTION
**Pull request by jayfoad**
This is unused now that LoopIdiomRecognize does not convert loops to memory intrinsics, because we have stopped telling it that memory libfuncs are available.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit a53bd0bcca145e6279132784b5f9fb03221bd0db
<details><summary>CTS tests (Failed: 222/141320)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39954/70667 (56.5%)</li>
<li><details><summary>Failed: 111/70667 (0.2%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.0
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.10
Stack trace: Crash

FAILURE: dEQP-VK.ray_tracing_pipeline.misc.raypayloadin_AABB
Stack trace: Crash

FAILURE: dEQP-VK.ray_tracing_pipeline.misc.raypayloadin_tri
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.abs_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.bitwise_and_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.bitwise_or_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.bitwise_or_test_high_part_zero_tessc
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.constant_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.max_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.max_test_high_part_zero_tessc
Stack trace: Fail

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mod_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.negate_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.negate_test_high_part_zero_tessc
Stack trace: Fail

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.negate_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift16_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift16_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift32_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift8_test_high_part_zero_comp
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 30602/70667 (43.3%)</li><li>Warnings: 0/70667 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39995/70653 (56.6%)</li>
<li><details><summary>Failed: 111/70653 (0.2%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.0
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.10
Stack trace: Crash

FAILURE: dEQP-VK.ray_tracing_pipeline.misc.raypayloadin_AABB
Stack trace: Crash

FAILURE: dEQP-VK.ray_tracing_pipeline.misc.raypayloadin_tri
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.abs_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.bitwise_and_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.bitwise_or_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.bitwise_or_test_high_part_zero_tessc
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.constant_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.max_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.max_test_high_part_zero_tessc
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mod_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.negate_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.negate_test_high_part_zero_tessc
Stack trace: Fail

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.negate_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift16_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift16_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift32_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift8_test_high_part_zero_comp
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 30547/70653 (43.2%)</li><li>Warnings: 0/70653 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
a53bd0bcca145e6279132784b5f9fb03221bd0db Jenkins build error.
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:3200:65: error: ‘Vkgc::LlpcRaytracingMode’ has not been declared
     static_assert(RaytracingNone == static_cast<unsigned>(Vkgc::LlpcRaytracingMode::None));
                                                                 ^~~~~~~~~~~~~~~~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:3201:67: error: ‘Vkgc::LlpcRaytracingMode’ has not been declared
     static_assert(RaytracingLegacy == static_cast<unsigned>(Vkgc::LlpcRaytracingMode::Legacy));
                                                                   ^~~~~~~~~~~~~~~~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:3202:71: error: ‘Vkgc::LlpcRaytracingMode’ has not been declared
     static_assert(RaytracingRefactored == static_cast<unsigned>(Vkgc::LlpcRaytracingMode::Gpurt2));
                                                                       ^~~~~~~~~~~~~~~~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:3203:31: error: ‘struct Vkgc::RayTracingPipelineBuildInfo’ has no member named ‘mode’
     pCreateInfo->pipelineInfo.mode = static_cast<Vkgc::LlpcRaytracingMode>(settings.llpcRaytracingMode);
                               ^~~~
/jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/xgl/icd/api/pipeline_compiler.cpp:3203:56: error: ‘LlpcRaytracingMode’ in namespace ‘Vkgc’ does not name a type
     pCreateInfo->pipelineInfo.mode = static_cast<Vkgc::LlpcRaytracingMode>(settings.llpcRaytracingMode);
                                                        ^~~~~~~~~~~~~~~~~~
[3004/3078] Building CXX object icd/CMakeFiles/xgl.dir/api/virtual_stack_mgr.cpp.o
[3005/3078] Building CXX object icd/CMakeFiles/xgl.dir/api/shader_cache.cpp.o
[3006/3078] Building CXX object icd/CMakeFiles/xgl.dir/api/pipeline_binary_cache.cpp.o

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8a8ce965ca926b320e8e1d513a10a3c74fe566f7
<details><summary>CTS tests (Failed: 280/211258)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38930/70423 (55.3%)</li>
<li><details><summary>Failed: 94/70423 (0.1%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.10
Stack trace: Crash

FAILURE: dEQP-VK.ray_tracing_pipeline.misc.raypayloadin_AABB
Stack trace: Crash

FAILURE: dEQP-VK.ray_tracing_pipeline.misc.raypayloadin_tri
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.abs_test_high_part_zero_tessc
Stack trace: Fail

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mod_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_sdiv_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_test_high_part_zero_tessc
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.negate_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.not_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.not_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift16_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_arithmetic_shift16_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_arithmetic_shift32_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_arithmetic_shift64_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift16_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift32_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift64_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift8_test_high_part_zero_geom
Stack trace: Fail

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.spec_constant_initializer_test_high_part_zero_geom
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 31399/70423 (44.6%)</li><li>Warnings: 0/70423 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 38964/70410 (55.3%)</li>
<li><details><summary>Failed: 94/70410 (0.1%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.10
Stack trace: Crash

FAILURE: dEQP-VK.ray_tracing_pipeline.misc.raypayloadin_AABB
Stack trace: Crash

FAILURE: dEQP-VK.ray_tracing_pipeline.misc.raypayloadin_tri
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.abs_test_high_part_zero_tessc
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mod_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_sdiv_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_test_high_part_zero_tessc
Stack trace: Flake

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.negate_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.not_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.not_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift16_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_arithmetic_shift16_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_arithmetic_shift32_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_arithmetic_shift64_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift16_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift32_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift64_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift8_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.spec_constant_initializer_test_high_part_zero_geom
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 31352/70410 (44.5%)</li><li>Warnings: 0/70410 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35055/70425 (49.8%)</li>
<li><details><summary>Failed: 92/70425 (0.1%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.10
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.abs_test_high_part_zero_tessc
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mod_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_sdiv_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_test_high_part_zero_tessc
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.mul_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.negate_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.not_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.not_test_high_part_zero_frag
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_left_logical_shift16_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_arithmetic_shift16_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_arithmetic_shift32_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_arithmetic_shift64_test_high_part_zero_vert
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift16_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift32_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift64_test_high_part_zero_tesse
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.shift_right_logical_shift8_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.i16.spec_constant_initializer_test_high_part_zero_geom
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.u16.bitwise_and_test_high_part_zero_comp
Stack trace: Crash

FAILURE: dEQP-VK.spirv_assembly.type.scalar.u16.bitwise_or_test_high_part_zero_tessc
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 35278/70425 (50.1%)</li><li>Warnings: 0/70425 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by jayfoad** [comment]
retest this please

**Comment by jayfoad** [comment]
> This is waiting for a prerequisite patch to land in gpuopen.
The prerequisite has been merged now: #2556

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8a8ce965ca926b320e8e1d513a10a3c74fe566f7
<details><summary>CTS tests (Failed: 475/211353)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 8.9, Gfx10</summary><ul>

<li>Passed: 35035/70456 (49.7%)</li>
<li><details><summary>Failed: 113/70456 (0.2%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.10
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.bool
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat2x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat3x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat3x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat2x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat2x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat2x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat4x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat2x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64vec3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.i64vec3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int16_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int64_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.ivec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.u8vec2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.uint16_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.uint32_t
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 35308/70456 (50.1%)</li><li>Warnings: 0/70456 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38779/70456 (55.0%)</li>
<li><details><summary>Failed: 247/70456 (0.4%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.10
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_16_odd_repeat_2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_32_odd_repeat_16
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_32_odd_repeat_2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_4_even_repeat_4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_4_odd_repeat_2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_64_even_repeat_16
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_64_even_repeat_2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.repeat_pipeline.x_64_odd_repeat_16
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_1_3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_2_3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_2_7
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_3_1
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_3_3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_3_4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_3_5
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_4_3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_4_7
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_5_3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.1_5_5
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 31430/70456 (44.6%)</li><li>Warnings: 0/70456 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 38943/70441 (55.3%)</li>
<li><details><summary>Failed: 115/70441 (0.2%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.10
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.composites.3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.bool
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat2x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat3x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f16mat3x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat2x2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat2x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat2x4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f32mat4x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64mat2x3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.f64vec3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.i64vec3
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int16_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.int64_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.ivec4
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.u8vec2
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.uint16_t
Stack trace: Crash

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.types.uint32_t
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 31383/70441 (44.6%)</li><li>Warnings: 0/70441 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
This mostly seems fine in principle, but I've noticed that raytracing creates `memcpy` in a bunch of places. Today, those copies should be in addrspace(5), but I'd rather not have to rely on that never becoming addrspace(7). Any thoughts on that?

**Comment by amdvlk-admin** [comment]
### Test summary for commit bb47f20b2a17a9b6808c74a1c367582c5ad6631c
<details><summary>CTS tests (Failed: 0/211353)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35147/70456 (49.9%)</li>
<li>Failed: 0/70456 (0.0%)</li>
<li>Not Supported: 35309/70456 (50.1%)</li><li>Warnings: 0/70456 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39026/70456 (55.4%)</li>
<li>Failed: 0/70456 (0.0%)</li>
<li>Not Supported: 31430/70456 (44.6%)</li><li>Warnings: 0/70456 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39058/70441 (55.4%)</li>
<li>Failed: 0/70441 (0.0%)</li>
<li>Not Supported: 31383/70441 (44.6%)</li><li>Warnings: 0/70441 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by arsenm** [comment]
FYI removing the dependency on libfunc detection to emit memcpy intrinsics is on my todo list. The intrinsic simply has nothing to do with the libc function and should always be usable

**Review by nhaehnle — CHANGES_REQUESTED** [review]
I interpret @arsenm's comment as: we should not merge this change due to what LLVM plans to do.

**Comment by jayfoad** [comment]
Fair enough.

**Pull request closed without merging**
