### PR TITLE
Fuzzer test no longer fails with pending upstream commit

### PR DESCRIPTION
**Pull request by dstutt**
The test is looking for failures when branch offset is too large for immediate
field.
Upstream change has made the shader shorter so it now always passes.

Removing the test as it doesn't do what it is supposed to any more. We'll need a
new fuzzer test if we want to replicate this.

### CODE REVIEW

**Comment by dstutt** [comment]
I made a couple of attempts to modify the shader to still exhibit the issue, but failed. At this stage it is easier to remove the test to enable the upstream merges to recommence.

**Comment by dstutt** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9b2c4e0589629999e1fbe7eb6147842031ee3fdd
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 9074bd0bdaf67fa84399dfabed3ec437951838f8</li>
<li>SPVGEN: dev c054813a9a894e32aaaa04c6717a667c15f60cfd</li>
<li>XGL: dev 598c6832a4983f5b75b38a589fca5be80a2f3bb0</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c72fe645f96434578da68c6fdb44bd28bb2fa6f1</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/87769)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43895 (51.9%)</li>
<li>Failed: 0/43895 (0.0%)</li>
<li>Skipped: 21111/43895 (48.1%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>No Results</li>

</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43874 (49.3%)</li>
<li>Failed: 0/43874 (0.0%)</li>
<li>Skipped: 22265/43874 (50.7%)</li>
</ul></details>


</ul></details>

**Review by kuhar — APPROVED** [review]

**Review by amdrexu — APPROVED** [review]

**Comment by dstutt** [comment]
retest this please

**Pull request merged**
