### PR TITLE
RegisterMetadaBuilder: fix setting for VGT_GS_VERT_ITEMSIZE and VGT_G…

### PR DESCRIPTION
**Pull request by xuechen417**
…SVS_RING_OFFSET

The metadata for VGT_GS_VERT_ITEMSIZE and VGT_GSVS_RING_OFFSET are array form, and they are not setting correctly in current code.

### CODE REVIEW

**Review by nhaehnle — DISMISSED** [review]
LGTM

**Comment by xuechen417** [comment]
V1: Fix format error.

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 74b3736b8f1cadfbafa7eab8c3f5c49710ab8a15
<details><summary>CTS tests (Failed: 0/211487)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39248/70495 (55.7%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 31247/70495 (44.3%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39498/70495 (56.0%)</li>
<li>Failed: 0/70495 (0.0%)</li>
<li>Not Supported: 30997/70495 (44.0%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36345/70497 (51.6%)</li>
<li>Failed: 0/70497 (0.0%)</li>
<li>Not Supported: 34152/70497 (48.4%)</li><li>Warnings: 0/70497 (0.0%)</li>
</ul></details>


</ul></details>

**Review by dstutt — APPROVED** [review]
LGTM - and the clang compiler warning has gone

**Pull request merged**
