### PR TITLE
Change condition to generate debugPrintf instruction

### PR DESCRIPTION
**Pull request by jiaolu**
Refactor the findResourceNode function and search the debugPrintf descriptor in the user data nodes.

### CODE REVIEW

**Comment by jiaolu** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 67b16779541f0c75824d8cb97503fb654c4c1549
<details><summary>CTS tests (Failed: 0/142046)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71028 (56.9%)</li>
<li>Failed: 0/71028 (0.0%)</li>
<li>Not Supported: 30602/71028 (43.1%)</li><li>Warnings: 0/71028 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71018 (57.0%)</li>
<li>Failed: 0/71018 (0.0%)</li>
<li>Not Supported: 30554/71018 (43.0%)</li><li>Warnings: 0/71018 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
Thanks. Please rename `userDataNode` -> `userDataNodes` in the parameter lists. Looks good to me apart from that.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 67b16779541f0c75824d8cb97503fb654c4c1549
<details><summary>CTS tests (Failed: 0/142046)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71028 (56.9%)</li>
<li>Failed: 0/71028 (0.0%)</li>
<li>Not Supported: 30602/71028 (43.1%)</li><li>Warnings: 0/71028 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71018 (57.0%)</li>
<li>Failed: 0/71018 (0.0%)</li>
<li>Not Supported: 30554/71018 (43.0%)</li><li>Warnings: 0/71018 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b1f759622f62400ea026bcdb2d2eb38c5b78b6e6
<details><summary>CTS tests (Failed: 0/142050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71030 (56.9%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 30604/71030 (43.1%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71020 (57.0%)</li>
<li>Failed: 0/71020 (0.0%)</li>
<li>Not Supported: 30556/71020 (43.0%)</li><li>Warnings: 0/71020 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM

**Comment by jiaolu** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b1f759622f62400ea026bcdb2d2eb38c5b78b6e6
<details><summary>CTS tests (Failed: 0/142050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71030 (56.9%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 30604/71030 (43.1%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71020 (57.0%)</li>
<li>Failed: 0/71020 (0.0%)</li>
<li>Not Supported: 30556/71020 (43.0%)</li><li>Warnings: 0/71020 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
