### PR TITLE
Use debug, release build for docker CI.

### PR DESCRIPTION
**Pull request by JaxLinAMD**
debug build can catch asserts.

### CODE REVIEW

**Comment by JaxLinAMD** [comment]
Hi, @kuhar , could you help check why my pull request failed? thanks.

**Comment by Flakebi** [comment]
The cmake flags are set in the other Dockerfile:
https://github.com/GPUOpen-Drivers/llpc/blob/86b546504899d0b41b6f46f5ea54cb3469907515/docker/amdvlk.Dockerfile#L43-L47

`llpc.Dockerfile` is just building with the already specified options.
Building in debug mode is a good idea, though I think we should do both, debug and release builds to catch errors like #607.

The way to do this is use `[Debug, Release]` in the GitHub workflow files:
https://github.com/GPUOpen-Drivers/llpc/blob/86b546504899d0b41b6f46f5ea54cb3469907515/.github/workflows/build-amdvlk-docker.yml#L17
https://github.com/GPUOpen-Drivers/llpc/blob/86b546504899d0b41b6f46f5ea54cb3469907515/.github/workflows/check-amdllpc-docker.yml#L19

**Comment by JaxLinAMD** [comment]
@Flakebi  thanks, will do that.

**Comment by JaxLinAMD** [comment]
it seems debug and release are built under the same directory.

**Comment by Flakebi** [comment]
You’re right, I think changing `${{ matrix.base-image }}` to `${{ matrix.base-image }}-${{ matrix.config }}`in the workflow files should do the trick.
Unfortunately, I think it’s hard to test these changes without pushing them to the dev branch because they rely on a global state (the base docker image, which gets rebuilt once a day). Unless @kuhar has an idea?

**Comment by amdvlk-admin** [comment]
### Test summary for commit f66a22218cc8b1918ae1791486a907ae2375dd92
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev e2f8eb0ffe21751b300995e795965d37e8d6dd67</li>
<li>SPVGEN: dev e843618d71c8263030551e7692b7683f20f627fe</li>
<li>XGL: dev d7d203bdd4547da678ba6d825a2370a0b18de622</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev f02738a5cf6c158c8c5b25a5048951f3059cabe2</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 958/958 (100.0%)</li>
<li>Failed: 0/958 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103143/103143 (100.0%)</li>
<li>Failed: 0/103143 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103199/103199 (100.0%)</li>
<li>Failed: 0/103199 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 103199/103199 (100.0%)</li>
<li>Failed: 0/103199 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
I thought of having these CI dimensions:
* NoAssertions/Assertions
* GCC/Clang
* NoSanitizers/ASAN/UBSAN
* NoShaderCache/ShaderCache

But that gives 24 build variants, which seems too many. Do you have some suggestions on how manage this in the long term?

**Comment by JaxLinAMD** [comment]
wow, we'd better discuss about in email list.

**Pull request closed without merging**
