### PR TITLE
Include lgc tools in the code coverage report

### PR DESCRIPTION
**Pull request by vettoreldaniele**

### CODE REVIEW

**Comment by Flakebi** [comment]
I guess we can include lgc as well? (should be at builds/ci-build/compiler/llpc/llvm/bin/lgc)

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by vettoreldaniele** [comment]
This seems to be working as expected. For example, LGC's `Disassembler.cpp` now appears in the report.

**Review by kuhar — APPROVED** [review]
Awesome, thanks @vettoreldaniele!

**Review by amdrexu — APPROVED** [review]

**Comment by kuhar** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 405f9a1570785865e0163b3c1205b7d6549b4716
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 2483d46fa27c30502e497ea169ee53b142e9fa06</li>
<li>SPVGEN: dev fa39b110650bc72fd7fda54af621e69306036888</li>
<li>XGL: dev 36c5637649089bf65d42c36b431f47c170b57276</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 007e2c31e995541d6c0a91db17044e3da946c6ed</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/186610)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 38010/67195 (56.6%)</li>
<li>Failed: 0/67195 (0.0%)</li>
<li>Not Supported: 29185/67195 (43.4%)</li><li>Warnings: 0/67195 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 32627/52220 (62.5%)</li>
<li><details><summary>Failed: 1/52220 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.robustness.image_robustness.bind.notemplate.rg32ui.unroll.nonvolatile.sampled_image.no_fmt_qual.img.samples_1.1d_array.comp
Stack trace: Script:
Crash

```
</p></details></li>

<li>Not Supported: 19592/52220 (37.5%)</li><li>Warnings: 0/52220 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 39069/67195 (58.1%)</li>
<li>Failed: 0/67195 (0.0%)</li>
<li>Not Supported: 28126/67195 (41.9%)</li><li>Warnings: 0/67195 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 405f9a1570785865e0163b3c1205b7d6549b4716
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 2483d46fa27c30502e497ea169ee53b142e9fa06</li>
<li>SPVGEN: dev fa39b110650bc72fd7fda54af621e69306036888</li>
<li>XGL: dev 36c5637649089bf65d42c36b431f47c170b57276</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 007e2c31e995541d6c0a91db17044e3da946c6ed</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/201585)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 38010/67195 (56.6%)</li>
<li>Failed: 0/67195 (0.0%)</li>
<li>Not Supported: 29185/67195 (43.4%)</li><li>Warnings: 0/67195 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 37848/67195 (56.3%)</li>
<li>Failed: 0/67195 (0.0%)</li>
<li>Not Supported: 29347/67195 (43.7%)</li><li>Warnings: 0/67195 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 39069/67195 (58.1%)</li>
<li>Failed: 0/67195 (0.0%)</li>
<li>Not Supported: 28126/67195 (41.9%)</li><li>Warnings: 0/67195 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
