### PR TITLE
Internal promotion for 2021.Q4.2

### PR DESCRIPTION
**Pull request by JaxLinAMD**

### CODE REVIEW

**Comment by JaxLinAMD** [comment]
@kuhar  do you know how to fix the clang-tidy error? i changed "#include vfx.h" to "#include tool/vfx/vfx.h", but not work

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit e704d002cdabee4d1d85d90b9aaaf3b842a14102
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 44abc48d199dd28369bf7415eee1751c4bf616d2</li>
<li>SPVGEN: dev 580ade71d630a304805e9468ef22ad263c37d137</li>
<li>XGL: dev b8ed024d536d1bebb35927a0f4f470dca2f2dfc6</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev cdd74831d061bf65fdf5af4a0b6ce99fe2c558a9</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/218612)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 32354/54653 (59.2%)</li>
<li>Failed: 0/54653 (0.0%)</li>
<li>Not Supported: 22299/54653 (40.8%)</li><li>Warnings: 0/54653 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 32194/54653 (58.9%)</li>
<li>Failed: 0/54653 (0.0%)</li>
<li>Not Supported: 22458/54653 (41.1%)</li><li>Warnings: 1/54653 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 32530/54653 (59.5%)</li>
<li>Failed: 0/54653 (0.0%)</li>
<li>Not Supported: 22123/54653 (40.5%)</li><li>Warnings: 0/54653 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 35511/54653 (65.0%)</li>
<li>Failed: 0/54653 (0.0%)</li>
<li>Not Supported: 19142/54653 (35.0%)</li><li>Warnings: 0/54653 (0.0%)</li>
</ul></details>


</ul></details>

**Review by s-perron — COMMENTED** [review]
LGTM

**Pull request merged**
