### PR TITLE
Update lit test with gfxip up to 10.1

### PR DESCRIPTION
**Pull request by xuechen417**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit d2a87426e8244d12fc6e656d88069b25d81eda6b
<details><summary>CTS tests (Failed: 0/69491)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41177/69491 (59.3%)</li>
<li>Failed: 0/69491 (0.0%)</li>
<li>Not Supported: 28314/69491 (40.7%)</li><li>Warnings: 0/69491 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
Thank you!

**Comment by amdvlk-admin** [comment]
### Test summary for commit d2a87426e8244d12fc6e656d88069b25d81eda6b
<details><summary>CTS tests (Failed: 0/208498)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Rhel 8.9, Gfx10</summary><ul>

<li>Passed: 36572/69504 (52.6%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 32932/69504 (47.4%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 41144/69503 (59.2%)</li>
<li>Failed: 0/69503 (0.0%)</li>
<li>Not Supported: 28359/69503 (40.8%)</li><li>Warnings: 0/69503 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41177/69491 (59.3%)</li>
<li>Failed: 0/69491 (0.0%)</li>
<li>Not Supported: 28314/69491 (40.7%)</li><li>Warnings: 0/69491 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit d2a87426e8244d12fc6e656d88069b25d81eda6b
<details><summary>CTS tests (Failed: 0/138995)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 41144/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28360/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41178/69491 (59.3%)</li>
<li>Failed: 0/69491 (0.0%)</li>
<li>Not Supported: 28313/69491 (40.7%)</li><li>Warnings: 0/69491 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by xuechen417** [comment]
V1: Resolve conflicts

**Comment by amdvlk-admin** [comment]
### Test summary for commit 13cb049b5252a3a8f445c7517471be2f6576ca40
<details><summary>CTS tests (Failed: 0/138994)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 41144/69503 (59.2%)</li>
<li>Failed: 0/69503 (0.0%)</li>
<li>Not Supported: 28359/69503 (40.8%)</li><li>Warnings: 0/69503 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41177/69491 (59.3%)</li>
<li>Failed: 0/69491 (0.0%)</li>
<li>Not Supported: 28314/69491 (40.7%)</li><li>Warnings: 0/69491 (0.0%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
