### PR TITLE
for test only

### PR DESCRIPTION
**Pull request by jfactory07**
for test

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1e4b8f10f2b21ef5692889fbfdbcc23f79cbba99
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f924a4fb84efde321f7754031f8cfa5ab35055d3</li>
<li>SPVGEN: dev 328a0990a958f21eb2c6b1ecb092a43629fe5554</li>
<li>XGL: dev bca286c1146f9f0662bbb7c10d193e487579e6f0</li>
<li>LLVM: amd-vulkan-dev 0843ddd6f5a03468d42b90715e98e9798f772555</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 803/803 (100.0%)</li>
<li>Failed: 0/803 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 3783/3784 (100.0%)</li>
<li><details><summary>Failed: 1/3784 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.object_management.multithreaded_per_thread_resources.device_memory_small
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1e4b8f10f2b21ef5692889fbfdbcc23f79cbba99
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f924a4fb84efde321f7754031f8cfa5ab35055d3</li>
<li>SPVGEN: dev 328a0990a958f21eb2c6b1ecb092a43629fe5554</li>
<li>XGL: dev bca286c1146f9f0662bbb7c10d193e487579e6f0</li>
<li>LLVM: amd-vulkan-dev 0843ddd6f5a03468d42b90715e98e9798f772555</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 803/803 (100.0%)</li>
<li>Failed: 0/803 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 312668/312668 (100.0%)</li>
<li>Failed: 0/312668 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312603/312603 (100.0%)</li>
<li>Failed: 0/312603 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Bonaire</summary><ul>

<li>Passed: 253658/253659 (100.0%)</li>
<li><details><summary>Failed: 1/253659 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.wsi.wayland.swapchain.render.basic
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1e4b8f10f2b21ef5692889fbfdbcc23f79cbba99
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f924a4fb84efde321f7754031f8cfa5ab35055d3</li>
<li>SPVGEN: dev 328a0990a958f21eb2c6b1ecb092a43629fe5554</li>
<li>XGL: dev bca286c1146f9f0662bbb7c10d193e487579e6f0</li>
<li>LLVM: amd-vulkan-dev 0843ddd6f5a03468d42b90715e98e9798f772555</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 803/803 (100.0%)</li>
<li>Failed: 0/803 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312603/312603 (100.0%)</li>
<li>Failed: 0/312603 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1e4b8f10f2b21ef5692889fbfdbcc23f79cbba99
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 2e94fa1533a606d076061db8d5be514bb69adfc3</li>
<li>SPVGEN: dev d26082d54930ad2ea97da94a2443137e7325b64c</li>
<li>XGL: dev 0d7c5a69ba314bfabe2d5dbe3e5e4d1ea3228845</li>
<li>LLVM: amd-vulkan-dev 3c7dbb214c3680803f7d3e3c3aed02fddb2f7dbb</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/spvgen/source/spvgen.cpp:972:25: error: ‘VFX_VERSION’ was not declared in this scope
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/spvgen/source/spvgen.cpp:973:27: error: ‘VFX_REVISION’ was not declared in this scope

</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1e4b8f10f2b21ef5692889fbfdbcc23f79cbba99
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 2e94fa1533a606d076061db8d5be514bb69adfc3</li>
<li>SPVGEN: dev d26082d54930ad2ea97da94a2443137e7325b64c</li>
<li>XGL: dev 0d7c5a69ba314bfabe2d5dbe3e5e4d1ea3228845</li>
<li>LLVM: amd-vulkan-dev 3c7dbb214c3680803f7d3e3c3aed02fddb2f7dbb</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/test/jacob_test_llpc/driver_build/drivers/spvgen/source/spvgen.cpp:972:25: error: ‘VFX_VERSION’ was not declared in this scope
/jenkins/workspace/open-source/test/jacob_test_llpc/driver_build/drivers/spvgen/source/spvgen.cpp:973:27: error: ‘VFX_REVISION’ was not declared in this scope

</ul></details>

**Pull request closed without merging**
