### PR TITLE
Re-enable shaderdb tests now upstream llvm changes are propagated

### PR DESCRIPTION
**Pull request by dstutt**
LLVM updates are now in the repo so we can re-enable these tests.

### CODE REVIEW

**Review by Flakebi — DISMISSED** [review]
LGTM if CI passes

**Comment by amdvlk-admin** [comment]
### Test summary for commit 7ecfb527f294b5e412791eed11c472f70f570783
<details><summary>CTS tests (Failed: 1018/138378)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35162/69163 (50.8%)</li>
<li>Failed: 0/69163 (0.0%)</li>
<li>Not Supported: 34001/69163 (49.2%)</li><li>Warnings: 0/69163 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 34235/69215 (49.5%)</li>
<li><details><summary>Failed: 1018/69215 (1.5%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.buffer.suballocation.storage.index.indirect.create.binding
Stack trace: Flake

FAILURE: dEQP-VK.api.buffer.suballocation.transfer_src.uniform_texel.vertex.create.binding_residency
Stack trace: Flake

FAILURE: dEQP-VK.api.buffer_marker.graphics.external_host_mem.bottom_of_pipe.memory_dep.draw
Stack trace: Flake

FAILURE: dEQP-VK.api.buffer_view.access.uniform_texel_buffer.a2b10g10r10_uint_pack32
Stack trace: Flake

FAILURE: dEQP-VK.api.buffer_view.access.uniform_texel_buffer.r16g16_sfloat
Stack trace: Flake

FAILURE: dEQP-VK.api.buffer_view.access.uniform_texel_buffer.r32_sfloat
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.buffer_to_depthstencil.buffer_offset_d32_sfloat_s8_uint_D_S
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.depth_stencil_msaa_copy.whole.d16_unorm_s8_uint_general_optimal_D_4_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.buffer_to_depthstencil.d32_sfloat_s8_uint_S
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.depth_stencil_msaa_copy.whole.d32_sfloat_optimal_general_D_2_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.simple_tests.mirror_y_3d.b8g8r8a8_unorm_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.simple_tests.without_scaling_partial_3d.r32_sfloat_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.buffer_to_buffer.partial
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.buffer_to_depthstencil.buffer_offset_d32_sfloat_s8_uint_DS
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.buffer_to_depthstencil.d16_unorm_s8_uint_S
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.depth_stencil_msaa_copy.whole.d16_unorm_s8_uint_optimal_general_D_2_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.image_to_image.dimensions.src4x8192_dst4x8192.r4g4_unorm_pack8.r8_srgb.general_general
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.image_to_image.simple_tests.partial_image
Stack trace: Flake

FAILURE: dEQP-VK.api.fill_and_update_buffer.dedicated_alloc.fill_buffer_vk_whole_size_0_extra_bytes_offset_0
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.core.clear_color_image.2d.linear.multiple_layers.r32g32b32a32_uint_64x11
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 33962/69215 (49.1%)</li><li>Warnings: 0/69215 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
Seems the llvm update caused many navi2x cts failures
 dev @ 3ab181f6d3ad0c309c702b26143d04a2104d0778

**Comment by dstutt** [comment]
> Seems the llvm update caused many navi2x cts failures dev @ 3ab181f6d3ad0c309c702b26143d04a2104d0778

Maybe - the test agent for navi2x seemed to be in a strange state so I've tried a reboot. But I'm not very sure it'll make any difference.

**Comment by qiaojbao** [comment]
> > Seems the llvm update caused many navi2x cts failures dev @ 3ab181f6d3ad0c309c702b26143d04a2104d0778
> 
> Maybe - the test agent for navi2x seemed to be in a strange state so I've tried a reboot. But I'm not very sure it'll make any difference.
The test agent will try reboot, if there are many amdgpu error info in dmesg.

**Comment by amdvlk-admin** [comment]
### Test summary for commit febcfb662143df77c996591e3a509bceda9d70ac
<details><summary>CTS tests (Failed: 1208/138443)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35211/69228 (50.9%)</li>
<li>Failed: 0/69228 (0.0%)</li>
<li>Not Supported: 34017/69228 (49.1%)</li><li>Warnings: 0/69228 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 34047/69215 (49.2%)</li>
<li><details><summary>Failed: 1208/69215 (1.7%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.buffer.suballocation.transfer_src.uniform_texel.vertex.create.binding_residency
Stack trace: Flake

FAILURE: dEQP-VK.api.buffer.suballocation.vertex.indirect.create.binding_residency
Stack trace: Flake

FAILURE: dEQP-VK.api.buffer_marker.graphics.external_host_mem.bottom_of_pipe.memory_dep.draw
Stack trace: Flake

FAILURE: dEQP-VK.api.buffer_view.access.uniform_texel_buffer.a2b10g10r10_uint_pack32
Stack trace: Flake

FAILURE: dEQP-VK.api.buffer_view.access.uniform_texel_buffer.r32_sfloat
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.blit_image.all_formats.color.3d.a8b8g8r8_sint_pack32.a8b8g8r8_sint_pack32.optimal_optimal_nearest_stripes_x
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.blit_image.all_formats.color.3d.r16g16b16a16_snorm.r16g16b16a16_snorm.optimal_general_linear_stripes_x
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.depth_stencil_msaa_copy.whole.d16_unorm_s8_uint_general_general_D_2_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.resolve_image.diff_image_size.dst_266_256_1_4_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.copy_commands2.resolve_image.with_regions.2_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.blit_image.simple_tests.scaling_whole2_3d.r32_sfloat_nearest
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.buffer_to_depthstencil.d32_sfloat_s8_uint_S
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.depth_stencil_msaa_copy.partial.s8_uint_S_4_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.core.depth_stencil_msaa_copy.whole.d32_sfloat_optimal_general_D_2_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.buffer_to_buffer.partial
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.buffer_to_depthstencil.buffer_offset_d32_sfloat_s8_uint_DS
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.resolve_image.with_regions.2_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.fill_and_update_buffer.dedicated_alloc.fill_buffer_first_one
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.core.clear_color_image.2d.linear.multiple_layers.r32g32b32a32_uint_64x11
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.core.clear_color_image.2d.optimal.remaining_array_layers_twostep.e5b9g9r9_ufloat_pack32
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 33960/69215 (49.1%)</li><li>Warnings: 0/69215 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by dstutt** [comment]
> > > Seems the llvm update caused many navi2x cts failures dev @ 3ab181f6d3ad0c309c702b26143d04a2104d0778
> > 
> > 
> > Maybe - the test agent for navi2x seemed to be in a strange state so I've tried a reboot. But I'm not very sure it'll make any difference.
> > The test agent will try reboot, if there are many amdgpu error info in dmesg.
> > I retrigger this PR, and the navi2x agent run the cts test after a reboot, many failures observed.

I couldn't reproduce these failure locally building from the same sources.

**Comment by dstutt** [comment]
retest this please

**Comment by dstutt** [comment]
test this please

**Review by nhaehnle — APPROVED** [review]
LGTM (unrelated CI issues aside...)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 859edf3ac8ab14e4282f9d031b47051633484fcd
<details><summary>CTS tests (Failed: 0/138443)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35211/69228 (50.9%)</li>
<li>Failed: 0/69228 (0.0%)</li>
<li>Not Supported: 34017/69228 (49.1%)</li><li>Warnings: 0/69228 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35242/69215 (50.9%)</li>
<li>Failed: 0/69215 (0.0%)</li>
<li>Not Supported: 33973/69215 (49.1%)</li><li>Warnings: 0/69215 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
