### PR TITLE
Fix issues of tanh(x) when x=INF or -INF

### PR DESCRIPTION
**Pull request by amdrexu**
We didn't check this special case. We just computed tanh(x) by sinh(x)/cosh(x). But when x=INF or -INF, the limit of tanh(x) is defined as follow:

`  lim(tanh(x)) = 1.0, x -> INF; lim(tanh(x)) = -1.0, x -> -INF`

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 50d32aacabdc438fb1a275482c2ddcc5045d6c8e
<details><summary>CTS tests (Failed: 0/137949)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35353/68947 (51.3%)</li>
<li>Failed: 0/68947 (0.0%)</li>
<li>Not Supported: 33594/68947 (48.7%)</li><li>Warnings: 0/68947 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35424/69002 (51.3%)</li>
<li>Failed: 0/69002 (0.0%)</li>
<li>Not Supported: 33578/69002 (48.7%)</li><li>Warnings: 0/69002 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
I feel like I've had a discussion with @kezhaoAMD about this recently. But I think it was in an llpcfe context. Did you discuss with him? He had a solution using copysign which might be a little better.

**Comment by xazhangAMD** [comment]
> I feel like I've had a discussion with @kezhaoAMD about this recently. But I think it was in an llpcfe context. Did you discuss with him? He had a solution using copysign which might be a little better.

Yes, llpcfe uses a copysign.
```
  Value *FPOne = ConstantFP::get(call->getType(), 1);
  Value *isInf = m_builder->CreateIsInf(val);
  Value *infResult = m_builder->CreateBinaryIntrinsic(Intrinsic::copysign, FPOne, val);
  return m_builder->CreateSelect(isInf, infResult, tanh);
```

**Comment by amdrexu** [comment]
> > I feel like I've had a discussion with @kezhaoAMD about this recently. But I think it was in an llpcfe context. Did you discuss with him? He had a solution using copysign which might be a little better.
> 
> Yes, llpcfe uses a copysign.
> 
> ```
>   Value *FPOne = ConstantFP::get(call->getType(), 1);
>   Value *isInf = m_builder->CreateIsInf(val);
>   Value *infResult = m_builder->CreateBinaryIntrinsic(Intrinsic::copysign, FPOne, val);
>   return m_builder->CreateSelect(isInf, infResult, tanh);
> ```

Thank you. Yes, this is better and saves a v_cndmask. I will follow it.

**Comment by xazhangAMD** [comment]
> > > I feel like I've had a discussion with @kezhaoAMD about this recently. But I think it was in an llpcfe context. Did you discuss with him? He had a solution using copysign which might be a little better.
> > 
> > 
> > Yes, llpcfe uses a copysign.
> > ```
> >   Value *FPOne = ConstantFP::get(call->getType(), 1);
> >   Value *isInf = m_builder->CreateIsInf(val);
> >   Value *infResult = m_builder->CreateBinaryIntrinsic(Intrinsic::copysign, FPOne, val);
> >   return m_builder->CreateSelect(isInf, infResult, tanh);
> > ```
> 
> Thank you. Yes, this is better and saves a v_cndmask. I will follow it.

I didn't add it into lgc because I was not sure whether GLSL spec requires this. I can drop the llpcfe approach when the lgc commit is merged.

**Comment by amdvlk-admin** [comment]
### Test summary for commit db6e682b3a580d55c23833ef0fdc8358dabc1153
<details><summary>CTS tests (Failed: 0/137949)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35353/68947 (51.3%)</li>
<li>Failed: 0/68947 (0.0%)</li>
<li>Not Supported: 33594/68947 (48.7%)</li><li>Warnings: 0/68947 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35424/69002 (51.3%)</li>
<li>Failed: 0/69002 (0.0%)</li>
<li>Not Supported: 33578/69002 (48.7%)</li><li>Warnings: 0/69002 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdrexu** [comment]
> > > > I feel like I've had a discussion with @kezhaoAMD about this recently. But I think it was in an llpcfe context. Did you discuss with him? He had a solution using copysign which might be a little better.
> > > 
> > > 
> > > Yes, llpcfe uses a copysign.
> > > ```
> > >   Value *FPOne = ConstantFP::get(call->getType(), 1);
> > >   Value *isInf = m_builder->CreateIsInf(val);
> > >   Value *infResult = m_builder->CreateBinaryIntrinsic(Intrinsic::copysign, FPOne, val);
> > >   return m_builder->CreateSelect(isInf, infResult, tanh);
> > > ```
> > 
> > 
> > Thank you. Yes, this is better and saves a v_cndmask. I will follow it.
> 
> I didn't add it into lgc because I was not sure whether GLSL spec requires this. I can drop the llpcfe approach when the lgc commit is merged.

Thank you. Actually, GLSL spec allows this but we didn't encounter such issues because there is no test.

**Review by nhaehnle — APPROVED** [review]
Thanks!

**Pull request merged**
