### PR TITLE
lgc: Various cleanups in the color export logic

### PR DESCRIPTION
**Pull request by nhaehnle**
This is a sequence of self-contained commits that try to be small and digestable.

The underlying philosophy here is that color export is split into two phases:

1.   Collect the outputs written by the application shader code. This is primarily about the locations of outputs.
2.    Generate export instructions for the shader, referencing the collected outputs as required. This is primarily about the hwExportTarget of outputs.

The changes aim at bringing us closer to this ideal, which helps make future changes.

In the case of a full pipeline compile, these phases happen right after each other as part of the fragment color export pass. When color export shaders are used, the first phase happens during the fragment color export pass, and the second phase happens when the color export shader is compiled.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3e1cbec8da603ddb61e9dee3f85cd6f13d6dfeb8
<details><summary>CTS tests (Failed: 0/139021)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 41144/69517 (59.2%)</li>
<li>Failed: 0/69517 (0.0%)</li>
<li>Not Supported: 28373/69517 (40.8%)</li><li>Warnings: 0/69517 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 41178/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28326/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 938575d97fcd38d7e6fb9e3e0f03a8c03b5de96f
<details><summary>CTS tests (Failed: 0/139021)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 41144/69517 (59.2%)</li>
<li>Failed: 0/69517 (0.0%)</li>
<li>Not Supported: 28373/69517 (40.8%)</li><li>Warnings: 0/69517 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41178/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28326/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit bce8b302a50f681166b782dba2279554a511e7e1
<details><summary>CTS tests (Failed: 0/139021)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 41144/69517 (59.2%)</li>
<li>Failed: 0/69517 (0.0%)</li>
<li>Not Supported: 28373/69517 (40.8%)</li><li>Warnings: 0/69517 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 41177/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28327/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
ping @amdrexu @Flakebi

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
