### PR TITLE
[CI] Resolve Ubuntu version and GCloud SDK warnings

### PR DESCRIPTION
**Pull request by kuhar**
Resolve the Ubuntu version warning by using 20.04 explicitly. See
https://github.com/actions/virtual-environments/issues/1816.

Resolve the GCloud SDK warning by switching to the new repo and pinning to a newwer version.
See https://github.com/google-github-actions/setup-gcloud.

### CODE REVIEW

**Comment by Flakebi** [comment]
Maybe keep the cppcheck job at 18.04 until GitHub has a newer Ubuntu version available?
It seems like the version in 20.04 finds a false positive, I don’t get this error with cppcheck 2.2 (20.04 has cppcheck 1.90).

**Comment by amdvlk-admin** [comment]
### Test summary for commit b27475286160d5e8bc51f7c0fd886726308c0848
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 32d42f58e8f4c3de99490c36d5a2091f8c59a673</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev 63761ecfd2d3cfa61a756ce0a72e1ca1cdae333a</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fde3d4e2bd90743606ca7b724bf62a53cacf4615</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/144501)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26321/48174 (54.6%)</li>
<li>Failed: 0/48174 (0.0%)</li>
<li>Skipped: 21853/48174 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26319/48174 (54.6%)</li>
<li><details><summary>Failed: 1/48174 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.spirv_assembly.instruction.compute.memory_access.none
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 21854/48174 (45.4%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24852/48153 (51.6%)</li>
<li>Failed: 0/48153 (0.0%)</li>
<li>Skipped: 23301/48153 (48.4%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
> Maybe keep the cppcheck job at 18.04 until GitHub has a newer Ubuntu version available?
> It seems like the version in 20.04 finds a false positive, I don’t get this error with cppcheck 2.2 (20.04 has cppcheck 1.90).

I added an assertion to silence the warning and catch the null dereference if it's actually possible.

**Review by Flakebi — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 80caf495a2830cad8556f4740ae3b221159ab56f
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 32d42f58e8f4c3de99490c36d5a2091f8c59a673</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev 63761ecfd2d3cfa61a756ce0a72e1ca1cdae333a</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fde3d4e2bd90743606ca7b724bf62a53cacf4615</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/96327)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26321/48174 (54.6%)</li>
<li>Failed: 0/48174 (0.0%)</li>
<li>Skipped: 21853/48174 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24852/48153 (51.6%)</li>
<li>Failed: 0/48153 (0.0%)</li>
<li>Skipped: 23301/48153 (48.4%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
