### PR TITLE
Move AbiMetadata from include/lgc/state to interface/lgc

### PR DESCRIPTION
**Pull request by amdrexu**
This is because ABI metadata will be accessed by front-end in the future
to extract certain data and perform ELF patching. Current directory
hierarchy disallows us to do so.

Change-Id: I99380b19cdef50a93d53aa4cefd3e03da5960dd2

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit d19f41931e39b4ef989a9684ce0bd1e515bad139
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 85f858393412732198fcd3dc0a0efb8653f5d3f9</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev 0d602bbcfa1a86fd52f66966554b05e384a10d38</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1598ada40008302abedfd724275329f8e7dea637</li>
</ul></details>

<details><summary>CTS tests (Failed: 3/140859)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 24005/46960 (51.1%)</li>
<li><details><summary>Failed: 1/46960 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.info.image_format_properties.3d.optimal.r64_sint
Stack trace: Fail
```
</p></details></li>

<li>Skipped: 22954/46960 (48.9%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 24004/46960 (51.1%)</li>
<li><details><summary>Failed: 1/46960 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.info.image_format_properties.3d.optimal.r64_sint
Stack trace: Fail
```
</p></details></li>

<li>Skipped: 22955/46960 (48.9%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 22646/46939 (48.2%)</li>
<li><details><summary>Failed: 1/46939 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.info.image_format_properties.3d.optimal.r64_sint
Stack trace: Fail
```
</p></details></li>

<li>Skipped: 24292/46939 (51.8%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
I think we should not do this as it is the wrong abstraction. ELF patching should not be done in the front-end; it should be in LGC, like ELF linking for shader compilation is. (The old code for ELF linking partial pipeline compiles is still in the front-end, but we should retire that in favor of the new scheme.)

**Comment by amdrexu** [comment]
Understand. I close this PR and follow LGC design expectation.

**Comment by trenouf** [comment]
Thank you. Also, reading an ELF file in LGC uses LLVM classes, not ElfReader in vkgc.

**Comment by amdrexu** [comment]
Sure. Will use LLVM native utilities.

**Pull request closed without merging**
