### PR TITLE
[DON'T REVIEW] Temporarily run full testing of NGG GS by enabling it

### PR DESCRIPTION
**Pull request by amdrexu**
Please don't review this PR, merge it, or close it. This is just to test the feature on GFX10. I will close it once all work is done.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit b6718273ee880b8d1c18cff27f6f7dd8161a0ae4
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 40af910391fb8c287cb37bf520c41310bf88d405</li>
<li>SPVGEN: dev ce06cb5e3116ba77a22c3278dfeadfd865a8977c</li>
<li>XGL: dev 7e13a8bd0bb57d3cfb3bc014f6b26a8c9bb8bfd9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c22b8992220d645b9f781e4a47947ae546fcd11c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 35628/35654 (99.9%)</li>
<li><details><summary>Failed: 26/35654 (0.1%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.input_output_float_64_to_16.vector1_rtz_geom
Stack trace: fragment output dat point #1 mismatch

FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.input_output_float_64_to_16.vector5_rtz_geom
Stack trace: fragment output dat point #0 mismatch

FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.input_output_float_64_to_16.vector6_rtz_geom
Stack trace: fragment output dat point #0 mismatch

FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.input_output_float_64_to_16.vector0_rte_geom
Stack trace: fragment output dat point #1 mismatch

FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.input_output_float_32_to_16.vector5_rtz_geom
Stack trace: fragment output dat point #0 mismatch

FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.input_output_float_32_to_16.vector6_rtz_geom
Stack trace: fragment output dat point #0 mismatch

FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.input_output_float_32_to_16.vector3_rte_geom
Stack trace: fragment output dat point #0 mismatch

FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.input_output_float_32_to_16.vector2_unspecified_rnd_mode_geom
Stack trace: fragment output dat point #0 mismatch

FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.16bit_storage.input_output_int_32_to_16.vector_sint1_geom
Stack trace: fragment output dat point #0 mismatch

FAILURE: dEQP-VK.glsl.builtin.function.common.abs.int_mediump_geometry
Stack trace: Result comparison failed

FAILURE: dEQP-VK.glsl.builtin.function.common.abs.ivec2_mediump_geometry
Stack trace: Result comparison failed

FAILURE: dEQP-VK.glsl.builtin.function.common.abs.ivec4_mediump_geometry
Stack trace: Result comparison failed

FAILURE: dEQP-VK.glsl.builtin.function.common.sign.ivec2_highp_geometry
Stack trace: Result comparison failed

FAILURE: dEQP-VK.glsl.builtin.function.common.sign.ivec4_mediump_geometry
Stack trace: Result comparison failed

FAILURE: dEQP-VK.glsl.builtin.function.common.isnan.vec2_mediump_geometry
Stack trace: Result comparison failed

FAILURE: dEQP-VK.glsl.builtin.function.common.isnan.vec2_highp_geometry
Stack trace: Result comparison failed

FAILURE: dEQP-VK.glsl.builtin.function.common.isinf.float_highp_geometry
Stack trace: Result comparison failed

FAILURE: dEQP-VK.glsl.builtin.function.common.isinf.vec2_highp_geometry
Stack trace: Result comparison failed

FAILURE: dEQP-VK.glsl.builtin.function.common.isinf.vec3_mediump_geometry
Stack trace: Result comparison failed

FAILURE: dEQP-VK.glsl.builtin.function.common.floatbitstoint.vec2_mediump_geometry
Stack trace: Result comparison failed
...
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by amdrexu** [comment]
retest this please

**Comment by amdrexu** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit de32b366d7125adfe7b1f3703a98d86fe0140dd8
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 9fab16015e522fff05890a045a1e9d8d3c23a636</li>
<li>SPVGEN: dev a61db14f75728e91c243d4bfc1c39700e9dc0ba6</li>
<li>XGL: dev c0791473c087f5b5d75a21c6f2ace72ccd232a65</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65463/65463 (100.0%)</li>
<li>Failed: 0/65463 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdrexu** [comment]
Close this since all testing are done.

**Pull request closed without merging**
