### PR TITLE
NGG coding rework: Rename m_nggFactor to m_nggInputs

### PR DESCRIPTION
**Pull request by amdrexu**
The name nggFactor is not appropriate. All values in this structure are most system inputs or derived inputs for NGG handling.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2a6c8e775e5f35c0251abcab4f5536d0f1dd5232
<details><summary>CTS tests (Failed: 1/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70485 (55.1%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39113/70485 (55.5%)</li>
<li><details><summary>Failed: 1/70485 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_4.triangles.degenerate.min
Stack trace: Flake
```
</p></details></li>

<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2a6c8e775e5f35c0251abcab4f5536d0f1dd5232
<details><summary>CTS tests (Failed: 0/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70485 (55.1%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70485 (55.5%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3789bcf411e74c27fa7a3f5ecf4077ae279c5556
<details><summary>CTS tests (Failed: 0/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70485 (55.1%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70485 (55.5%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
