### PR TITLE
Changed management of writing PipelineState to IR metadata

### PR DESCRIPTION
**Pull request by trenouf**
Part of the drive to clean up the interface from the front-end into the
middle-end.

* PipelineState now has a dirty flag for its state, and a Flush() method
  that writes it to IR metadata if it is dirty.
* Using BuilderRecorder, a new PipelineState is created just before
  replay, that reads the state from IR metadata.
* Also a new PipelineStateClearer pass removes the PipelineState IR
  metadata at the end of the middle-end, just before codegen.

### CODE REVIEW

**Comment by trenouf** [comment]
Please review just the top-most commit.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 51a5629532469a9138d8b77b5acb602ae2f898a7
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 3e28ea331cf8e7b0e5733e5bd7f7d16582c603c5</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 68e79ff09849f32d0bbe929d94b19d58af7e0850</li>
<li>LLVM: amd-vulkan-dev 21b028dc97ee9b0c6629ff83c2924b3b80c5d6e7</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/context/llpcCompiler.cpp:1221:15: error: ‘class Llpc::Context’ has no member named ‘SetBuilder’; did you mean ‘GetBuilder’?

</ul></details>

**Comment by trenouf** [comment]
V2: Comment change.

Also rebased.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0b64654e714ababed397feaee4f3cfff90ac1758
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 39abe2297ca58a2b84dcd9bc5e238fbc399bd6e0</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 19a031d9f73b95101fd4d3d594aca27c00feb180</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 40fbaf4c5446a361269c241d9112fff26575b5d0</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 64854/64854 (100.0%)</li>
<li>Failed: 0/64854 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 64886/64886 (100.0%)</li>
<li>Failed: 0/64886 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
Closing -- will open new PRs for these changes.

**Comment by trenouf** [comment]
Closing -- will open new PRs for these changes.

**Pull request closed without merging**
