### PR TITLE
Stub out SPV_KHR_post_depth_coverage support

### PR DESCRIPTION
**Pull request by noahfredriks**
This feature is currently not supported.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JacobHeAMD** [comment]
ok to test

**Comment by JacobHeAMD** [comment]
test this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit fe8ceefc4b0b23bc20de5dd08c7572bad7158545
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 7182b2c62fba5756e20a5a0858f22f008f5d9d37</li>
<li>SPVGEN: dev f9f54957780b4e00dfe947d698efabf2999be863</li>
<li>XGL: dev 96d84068b622b2c3ce8cf9aa8ff597260aa5ad3f</li>
<li>LLVM: amd-vulkan-dev 8118692e8aefbd95f791ff49beddb8ce90e8927c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 900/900 (100.0%)</li>
<li>Failed: 0/900 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 366312/366312 (100.0%)</li>
<li>Failed: 0/366312 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 366312/366312 (100.0%)</li>
<li>Failed: 0/366312 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
