### PR TITLE
[CI] Reduce base image size

### PR DESCRIPTION
**Pull request by kuhar**
Based on https://docs.docker.com/v17.09/engine/userguide/eng-image/dockerfile_best-practices.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 97f848a63a24a3031d986077bce59ce1fac24cba
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 9fab16015e522fff05890a045a1e9d8d3c23a636</li>
<li>SPVGEN: dev a61db14f75728e91c243d4bfc1c39700e9dc0ba6</li>
<li>XGL: dev c0791473c087f5b5d75a21c6f2ace72ccd232a65</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ecf0a1496f32eaf34825b3d11432c6b1d03c951</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65463/65463 (100.0%)</li>
<li>Failed: 0/65463 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
Too late due to travel, but... in the future, stuff like the first comment really should go into the commit message.

**Comment by amdrexu** [comment]
It's OK. If you would like to check any PR while you are busy with travel. We can hold it for a few days before merging once it gets approved.

**Comment by kuhar** [comment]
Thanks for pointing this out, @nhaehnle. I got too used to other code review systems were modifying PR description updates the commit message.

**Pull request merged**
