### PR TITLE
Fix an issue of s_sendmsg in mesh shader

### PR DESCRIPTION
**Pull request by amdrexu**
M0 implicitly used in s_sendmsg is SGPR. Therefore, the value written to M0 should be an uniform one. Therefore, we must promote vertex/primitive count to SGPR. This is because LLVM backend is not smart enough to translate IR select to s_cselect. Rather, it uses v_cndmask, which eventually converts vertex/primitive count to VGPR. And LLVM backend reports illegal copy.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit d5f0a0335b069569bb9b6e82167fde7eced05e7d
<details><summary>CTS tests (Failed: 0/286649)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 36222/72710 (49.8%)</li>
<li>Failed: 0/72710 (0.0%)</li>
<li>Not Supported: 36488/72710 (50.2%)</li><li>Warnings: 0/72710 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 40419/72724 (55.6%)</li>
<li>Failed: 0/72724 (0.0%)</li>
<li>Not Supported: 32305/72724 (44.4%)</li><li>Warnings: 0/72724 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 37135/72724 (51.1%)</li>
<li>Failed: 0/72724 (0.0%)</li>
<li>Not Supported: 35589/72724 (48.9%)</li><li>Warnings: 0/72724 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 34834/68491 (50.9%)</li>
<li>Failed: 0/68491 (0.0%)</li>
<li>Not Supported: 33657/68491 (49.1%)</li><li>Warnings: 0/68491 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
Hmm, this kind of thing really shouldn't be necessary. As you point out, it's a weakness of `select` lowering that causes this.

Do you have an `.ll` file that can be used to reproduce the issue in the backend?

**Comment by nhaehnle** [comment]
To be clear, I don't mind this so much for now, but please make sure we can get a reproducer for the backend and also make sure the comment states that it's a workaround for a backend limitation, so that we can eventually remove it.

**Comment by piotrAMD** [comment]
Agreed - we want to fix it in the backend in the long run. 

There is a known limitation with generating a scalar select if the condition is used in multiple selects. I think this may be the case here (`hasZeroCount` used in both). Hopefully, this will be addressed by https://reviews.llvm.org/D133593, when that commit percolates to our branch.

**Comment by amdrexu** [comment]
Thank you. I simplify the shader to show the problem. You can see the attached and use amdllpc to reproduce it: `amdllpc -gfxip=10.3 -v mesh.spv`.

**Comment by amdrexu** [comment]
If I remember correctly, LLVM backend would do SGPR promotion for me by inserting readfirstlane for M0 in the past. But when I sync latest LLVM codes, backend reports illegal VGPR copy and marks SI_ILLEGAL_COPY, which eventually crashes in backend.

**Comment by nhaehnle** [comment]
Thanks for the .zip. Can you please add to the comment that this is a backend bug workaround?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 30b2ef45324592807ad55a93394731a09441c8ad
<details><summary>CTS tests (Failed: 0/286649)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 36222/72710 (49.8%)</li>
<li>Failed: 0/72710 (0.0%)</li>
<li>Not Supported: 36488/72710 (50.2%)</li><li>Warnings: 0/72710 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 40419/72724 (55.6%)</li>
<li>Failed: 0/72724 (0.0%)</li>
<li>Not Supported: 32305/72724 (44.4%)</li><li>Warnings: 0/72724 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 37135/72724 (51.1%)</li>
<li>Failed: 0/72724 (0.0%)</li>
<li>Not Supported: 35589/72724 (48.9%)</li><li>Warnings: 0/72724 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 34834/68491 (50.9%)</li>
<li>Failed: 0/68491 (0.0%)</li>
<li>Not Supported: 33657/68491 (49.1%)</li><li>Warnings: 0/68491 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM

**Pull request merged**
