### PR TITLE
Refactor inputLocInfoMap/outputLocInfoMap

### PR DESCRIPTION
**Pull request by xuechen417**
This PR bases on PR #1031 . Please review the top three commits: 282bc3c, 4247247, fb361ef.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit fb361ef0e078f915ee49453befb54177a8e485d0
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 4ae736bdbc5d5dee59851ac564c5e21d807b44b0</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev 87430a6fa88da11473eed49603def2fa47b51fa0</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 88613f67ca2e3e64cc1c7c4ccd47e126495e6e23</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/140859)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26166/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20794/46960 (44.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26165/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20795/46960 (44.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24702/46939 (52.6%)</li>
<li>Failed: 0/46939 (0.0%)</li>
<li>Skipped: 22237/46939 (47.4%)</li>
</ul></details>


</ul></details>

**Comment by xuechen417** [comment]
Rebase

**Comment by amdvlk-admin** [comment]
### Test summary for commit 361162affc7e9308267df08cdaaaa2a139b5ba78
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 6f6b37dd68ffe37868b14bfc1be7cf029eecc361</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev cb0215b2c243fb7919397e9ad0bbce2ac9c7bbc9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fde3d4e2bd90743606ca7b724bf62a53cacf4615</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/144501)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26321/48174 (54.6%)</li>
<li>Failed: 0/48174 (0.0%)</li>
<li>Skipped: 21853/48174 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26320/48174 (54.6%)</li>
<li><details><summary>Failed: 1/48174 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.win32_keyed_mutex.write_copy_buffer_read_ssbo_fragment.buffer_16384_kmt
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 21853/48174 (45.4%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24852/48153 (51.6%)</li>
<li>Failed: 0/48153 (0.0%)</li>
<li>Skipped: 23301/48153 (48.4%)</li>
</ul></details>


</ul></details>

**Review by linqun — APPROVED** [review]

**Comment by amdrexu** [comment]
@JaxLinAMD The same as https://github.com/GPUOpen-Drivers/llpc/pull/1031. Let's keep it open for a few days in case anyone has more comments.

**Comment by JaxLinAMD** [comment]
got it

**Comment by JaxLinAMD** [comment]
@GPUOpen-Drivers/llpcreviewers , is there anyone want to take a look?

**Comment by amdrexu** [comment]
@JaxLinAMD I thin it is good to go.

**Comment by JaxLinAMD** [comment]
@xuechen417 please resolve conflicts

**Comment by xuechen417** [comment]
V2: Rebase and resolve confilicts.

**Comment by amdvlk-admin** [comment]
### Test summary for commit bbea3a5a667d5c9f3ce0710080208e6a24ba1125
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev eb28c7ef53329f838e693f233696823330e964c0</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev 63761ecfd2d3cfa61a756ce0a72e1ca1cdae333a</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fde3d4e2bd90743606ca7b724bf62a53cacf4615</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/192504)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26321/48174 (54.6%)</li>
<li>Failed: 0/48174 (0.0%)</li>
<li>Skipped: 21853/48174 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26320/48174 (54.6%)</li>
<li>Failed: 0/48174 (0.0%)</li>
<li>Skipped: 21854/48174 (45.4%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24852/48153 (51.6%)</li>
<li>Failed: 0/48153 (0.0%)</li>
<li>Skipped: 23301/48153 (48.4%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx103</summary><ul>

<li>Passed: 26219/48003 (54.6%)</li>
<li>Failed: 0/48003 (0.0%)</li>
<li>Skipped: 21784/48003 (45.4%)</li>
</ul></details>


</ul></details>

**Pull request merged**
