### PR TITLE
Always emit s_wait before GS_DONE

### PR DESCRIPTION
**Pull request by LLJJDD**
Per programming guide, we should do a “s_waitcnt 0,0,0 + s_waitcnt_vscnt 0”
before issueing a "done" in GS. This is true regardless GS is on-chip or
off-chip.

### CODE REVIEW

**Comment by LLJJDD** [comment]
It seems that the failing LGC test is already failing without my PR, should be unrelated to this change.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 73c3442988d124c73bcb803698c9677dfa5e46be
<details><summary>CTS tests (Failed: 0/179654)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35418/63737 (55.6%)</li>
<li>Failed: 0/63737 (0.0%)</li>
<li>Not Supported: 28319/63737 (44.4%)</li><li>Warnings: 0/63737 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27611/52180 (52.9%)</li>
<li>Failed: 0/52180 (0.0%)</li>
<li>Not Supported: 24569/52180 (47.1%)</li><li>Warnings: 0/52180 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37679/63737 (59.1%)</li>
<li>Failed: 0/63737 (0.0%)</li>
<li>Not Supported: 26058/63737 (40.9%)</li><li>Warnings: 0/63737 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit e73719a748df04db20cfed5a10e63204236e9eac
<details><summary>CTS tests (Failed: 0/179654)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35418/63737 (55.6%)</li>
<li>Failed: 0/63737 (0.0%)</li>
<li>Not Supported: 28319/63737 (44.4%)</li><li>Warnings: 0/63737 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27529/52180 (52.8%)</li>
<li>Failed: 0/52180 (0.0%)</li>
<li>Not Supported: 24651/52180 (47.2%)</li><li>Warnings: 0/52180 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37679/63737 (59.1%)</li>
<li>Failed: 0/63737 (0.0%)</li>
<li>Not Supported: 26058/63737 (40.9%)</li><li>Warnings: 0/63737 (0.0%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — DISMISSED** [review]

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit fe52df9509bda5ee05e2083bb4ff8a1121e6169f
<details><summary>CTS tests (Failed: 0/216210)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35422/73547 (48.2%)</li>
<li>Failed: 0/73547 (0.0%)</li>
<li>Not Supported: 38125/73547 (51.8%)</li><li>Warnings: 0/73547 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33115/69116 (47.9%)</li>
<li>Failed: 0/69116 (0.0%)</li>
<li>Not Supported: 36001/69116 (52.1%)</li><li>Warnings: 0/69116 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37683/73547 (51.2%)</li>
<li>Failed: 0/73547 (0.0%)</li>
<li>Not Supported: 35864/73547 (48.8%)</li><li>Warnings: 0/73547 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
