### PR TITLE
[CI] Update dockerfile, install the shader compiler tools for gpurt

### PR DESCRIPTION
**Pull request by qiaojbao**

### CODE REVIEW

**Review by jinjianrong — DISMISSED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit abc9dec859ec6808a1e2f6263b942d1dcbc6aecf
<details><summary>CTS tests (Failed: 0/289625)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx9</summary><ul>

<li>Passed: 32868/69268 (47.5%)</li>
<li>Failed: 0/69268 (0.0%)</li>
<li>Not Supported: 36400/69268 (52.5%)</li><li>Warnings: 0/69268 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/73498 (52.4%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 35007/73498 (47.6%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 34348/73361 (46.8%)</li>
<li>Failed: 0/73361 (0.0%)</li>
<li>Not Supported: 39013/73361 (53.2%)</li><li>Warnings: 0/73361 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35388/73498 (48.1%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 38110/73498 (51.9%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by Flakebi** [comment]
That fails for me with `sudo: command not found`.

I tried building with `docker build -t amdvlk . --file docker/amdvlk.Dockerfile --build-arg BRANCH=dev --build-arg CONFIG=Release --build-arg FEATURES="+clang" --build-arg GENERATOR=Ninja`

**Comment by qiaojbao** [comment]
> That fails for me with `sudo: command not found`.
> 
> I tried building with `docker build -t amdvlk . --file docker/amdvlk.Dockerfile --build-arg BRANCH=dev --build-arg CONFIG=Release --build-arg FEATURES="+clang" --build-arg GENERATOR=Ninja`

I find one place used sudo , I will remove it.

**Comment by qiaojbao** [comment]
@Flakebi, could you help to verify it again, please?

**Comment by qiaojbao** [comment]
@Flakebi, could you help to verify it again, please?

**Comment by Flakebi** [comment]
Still doesn’t build: `E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation`

**Comment by qiaojbao** [comment]
> 

I will try to remove the '--no-install-recommends'

**Review by jinjianrong — DISMISSED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5adb6fedc7714937ed514dd2d71c6261f5d7dd1b
<details><summary>CTS tests (Failed: 0/289625)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx9</summary><ul>

<li>Passed: 32868/69268 (47.5%)</li>
<li>Failed: 0/69268 (0.0%)</li>
<li>Not Supported: 36400/69268 (52.5%)</li><li>Warnings: 0/69268 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/73498 (52.4%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 35007/73498 (47.6%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 34348/73361 (46.8%)</li>
<li>Failed: 0/73361 (0.0%)</li>
<li>Not Supported: 39013/73361 (53.2%)</li><li>Warnings: 0/73361 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35388/73498 (48.1%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 38110/73498 (51.9%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by Flakebi** [comment]
This Dockerfile should work (still building locally):

<details>
<summary>Dockerfile</summary>

```Dockerfile
#
# Dockerfile for LLPC Continuous Integration.
# Contains the base image used for incremental builds of llpc.
# Sample invocation:
#    docker build . --file docker/amdvlk.Dockerfile               \
#                   --build-arg BRANCH=dev                        \
#                   --build-arg CONFIG=Release                    \
#                   --build-arg FEATURES="+clang+ubsan+asan"      \
#                   --build-arg GENERATOR=Ninja                   \
#                   --tag kuhar/amdvlk:nightly
#
# Required arguments:
# - BRANCH: The base AMDVLK branch to use (e.g., master, dev, releases/<name>)
# - CONFIG: Debug or Release
# - FEATURES: A '+'-separated set of features to enable
# - GENERATOR: CMake generator to use (e.g., "Unix Makefiles", Ninja)
#

FROM ubuntu:20.04

ARG BRANCH
ARG CONFIG
ARG FEATURES
ARG GENERATOR

# Use bash instead of sh in this docker file.
SHELL ["/bin/bash", "-c"]

# Install required packages.
# Use pip to install an up-to-date version of CMake. The apt package is
# too old for LLVM.
RUN export DEBIAN_FRONTEND=noninteractive && export TZ=America/New_York \
    && apt-get update \
    && apt-get install -yqq --no-install-recommends \
       build-essential pkg-config ninja-build \
       software-properties-common dirmngr gpg-agent \
       gcc g++ binutils-gold \
       llvm-11 clang-11 clang-tidy-12 libclang-common-11-dev lld-11 \
       python python3 python3-distutils python3-pip \
       libssl-dev libx11-dev libxcb1-dev x11proto-dri2-dev libxcb-dri3-dev \
       libxcb-dri2-0-dev libxcb-present-dev libxshmfence-dev libxrandr-dev \
       libwayland-dev \
       git curl wget openssh-client \
    && rm -rf /var/lib/apt/lists/* \
    && python3 -m pip install --no-cache-dir --upgrade pip \
    && python3 -m pip install --no-cache-dir --upgrade cmake \
    && for tool in clang clang++ llvm-cov llvm-profdata llvm-symbolizer lld ld.lld ; do \
         update-alternatives --install /usr/bin/"$tool" "$tool" /usr/bin/"$tool"-11 10 ; \
        done \
    && update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-12 10 \
    && update-alternatives --install /usr/bin/ld ld /usr/bin/ld.gold 10

# Update the VulkanSDK 1.3.216 or higher, install the shader compiler tools for gpurt.
RUN apt-key adv --fetch-keys https://packages.lunarg.com/lunarg-signing-key-pub.asc \
    && apt-add-repository 'deb https://packages.lunarg.com/vulkan/1.3.216 focal main' \
    && apt-get install -yqq --no-install-recommends dxc glslang-tools \
    && rm -rf /var/lib/apt/lists/* \
    && dxc --version \
    && spirv-remap --version

# Checkout all repositories. Replace llpc with the version in LLPC_SOURCE_DIR.
# The /vulkandriver/env.sh file is for extra env variables used by later commands.
WORKDIR /vulkandriver
RUN wget -P /usr/bin/ https://storage.googleapis.com/git-repo-downloads/repo \
    && chmod +x /usr/bin/repo \
    && repo init -u https://github.com/GPUOpen-Drivers/AMDVLK.git -b "$BRANCH" -m build_with_tools.xml \
    && repo sync -c --no-clone-bundle -j$(nproc) \
    && touch ./env.sh

# Copy update script into container
COPY docker/update-llpc.sh /vulkandriver/

# Build LLPC.
WORKDIR /vulkandriver/builds/ci-build
RUN EXTRA_COMPILER_FLAGS=() \
    && EXTRA_LINKER_FLAGS=() \
    && EXTRA_FLAGS=("-DXGL_BUILD_CACHE_CREATOR=ON") \
    && SANITIZERS=() \
    && if echo "$FEATURES" | grep -q "+gcc" ; then \
         EXTRA_FLAGS+=("-DCMAKE_C_COMPILER=gcc"); \
         EXTRA_FLAGS+=("-DCMAKE_CXX_COMPILER=g++"); \
       fi \
    && if echo "$FEATURES" | grep -q "+clang" ; then \
         EXTRA_FLAGS+=("-DCMAKE_C_COMPILER=clang"); \
         EXTRA_FLAGS+=("-DCMAKE_CXX_COMPILER=clang++"); \
         EXTRA_FLAGS+=("-DLLVM_USE_LINKER=lld"); \
         EXTRA_LINKER_FLAGS+=("-fuse-ld=lld"); \
       fi \
    && if echo "$FEATURES" | grep -q "+shadercache" ; then \
         EXTRA_FLAGS+=("-DLLPC_ENABLE_SHADER_CACHE=1"); \
       fi \
    && if echo "$FEATURES" | grep -q "+asan" ; then \
         SANITIZERS+=("Address"); \
         echo "export ASAN_OPTIONS=detect_leaks=0" >> /vulkandriver/env.sh; \
         echo "export LD_PRELOAD=$(clang -print-file-name=libclang_rt.asan-x86_64.so)" >> /vulkandriver/env.sh; \
       fi \
    && if echo "$FEATURES" | grep -q "+ubsan" ; then \
         SANITIZERS+=("Undefined"); \
       fi \
    && if echo "$FEATURES" | grep -q "+tsan" ; then \
         SANITIZERS+=("Thread"); \
       fi \
    && if [ ${#SANITIZERS[@]} -ne 0 ]; then  \
         SANITIZERS_SEPARATED_LIST="${SANITIZERS[@]}"; \
         SANITIZERS_SEPARATED_LIST="${SANITIZERS_SEPARATED_LIST// /;}"; \
         EXTRA_FLAGS+=("-DXGL_USE_SANITIZER='${SANITIZERS_SEPARATED_LIST}'"); \
       fi \
    && if echo "$FEATURES" | grep -q "+coverage" ; then \
         EXTRA_COMPILER_FLAGS+=("-fprofile-instr-generate=/vulkandriver/profile%2m.profraw" "-fcoverage-mapping"); \
         EXTRA_LINKER_FLAGS+=("-fprofile-instr-generate=/vulkandriver/profile%2m.profraw" "-fcoverage-mapping"); \
       fi \
    && if echo "$FEATURES" | grep -q "+assertions" ; then \
         EXTRA_FLAGS+=("-DXGL_ENABLE_ASSERTIONS=ON"); \
       fi \
    && if [ ${#EXTRA_COMPILER_FLAGS[@]} -ne 0 ]; then \
         EXTRA_FLAGS+=("-DCMAKE_C_FLAGS='${EXTRA_COMPILER_FLAGS[*]}'" "-DCMAKE_CXX_FLAGS='${EXTRA_COMPILER_FLAGS[*]}'"); \
       fi \
    && if [ ${#EXTRA_LINKER_FLAGS[@]} -ne 0 ]; then \
         EXTRA_FLAGS+=("-DCMAKE_EXE_LINKER_FLAGS='${EXTRA_LINKER_FLAGS[*]}'" "-DCMAKE_SHARED_LINKER_FLAGS='${EXTRA_LINKER_FLAGS[*]}'"); \
       fi \
    && echo "Extra CMake flags: ${EXTRA_FLAGS[@]}" \
    && echo "Extra env vars (/vulkandriver/env.sh): " \
    && cat /vulkandriver/env.sh \
    && source /vulkandriver/env.sh \
    && cmake "/vulkandriver/drivers/xgl" \
          -G "$GENERATOR" \
          -DCMAKE_BUILD_TYPE="$CONFIG" \
          -DXGL_BUILD_TESTS=ON \
          -DXGL_BUILD_TOOLS=ON \
          -DICD_ANALYSIS_WARNINGS_AS_ERRORS=OFF \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          "${EXTRA_FLAGS[@]}" \
    && cmake --build . \
    && cmake --build . --target lgc spvgen count FileCheck llvm-objdump not

# Run the lit test suite.
RUN source /vulkandriver/env.sh \
    && cmake --build . --target check-amdllpc check-amdllpc-units -- -v \
    && cmake --build . --target check-lgc check-lgc-units -- -v

# Save build info to /vulkandriver/build_info.txt.
RUN cd /vulkandriver \
    && (printf "Base image built on $(date)\n\n" | tee build_info.txt) \
    && (repo forall -p -c "git log -1 --pretty=format:'%H %s by %an <%ae>'" | tee -a build_info.txt) \
    && (echo | tee -a build_info.txt)
```
</details>

I added software-properties-common, dirmngr and gpg-agent to the install list and used `apt-add-repository`.
Diff to the current PR:
```diff
diff --git a/docker/amdvlk.Dockerfile b/docker/amdvlk.Dockerfile
index 350f9941..c1e862f0 100644
--- a/docker/amdvlk.Dockerfile
+++ b/docker/amdvlk.Dockerfile
@@ -33,6 +33,7 @@ RUN export DEBIAN_FRONTEND=noninteractive && export TZ=America/New_York \
     && apt-get update \
     && apt-get install -yqq --no-install-recommends \
        build-essential pkg-config ninja-build \
+       software-properties-common dirmngr gpg-agent \
        gcc g++ binutils-gold \
        llvm-11 clang-11 clang-tidy-12 libclang-common-11-dev lld-11 \
        python python3 python3-distutils python3-pip \
@@ -50,10 +51,10 @@ RUN export DEBIAN_FRONTEND=noninteractive && export TZ=America/New_York \
     && update-alternatives --install /usr/bin/ld ld /usr/bin/ld.gold 10

 # Update the VulkanSDK 1.3.216 or higher, install the shader compiler tools for gpurt.
-RUN wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | apt-key add - \
-    && wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.216-focal.list https://packages.lunarg.com/vulkan/1.3.216/lunarg-vulkan-1.3.216-focal.list \
-    && apt-get update \
-    && apt-get install -y dxc glslang-tools \
+RUN apt-key adv --fetch-keys https://packages.lunarg.com/lunarg-signing-key-pub.asc \
+    && apt-add-repository 'deb https://packages.lunarg.com/vulkan/1.3.216 focal main' \
+    && apt-get install -yqq --no-install-recommends dxc glslang-tools \
+    && rm -rf /var/lib/apt/lists/* \
     && dxc --version \
     && spirv-remap --version

```

**Comment by qiaojbao** [comment]
E: Unable to locate package software-properties-common
E: Unable to locate package dirmngr
E: Unable to locate package gpg-agent

**Comment by amdvlk-admin** [comment]
### Test summary for commit d024a0c6a80fba851138ccc364de2ca19dde158b
<details><summary>CTS tests (Failed: 0/289625)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx9</summary><ul>

<li>Passed: 32868/69268 (47.5%)</li>
<li>Failed: 0/69268 (0.0%)</li>
<li>Not Supported: 36400/69268 (52.5%)</li><li>Warnings: 0/69268 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/73498 (52.4%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 35007/73498 (47.6%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 34348/73361 (46.8%)</li>
<li>Failed: 0/73361 (0.0%)</li>
<li>Not Supported: 39013/73361 (53.2%)</li><li>Warnings: 0/73361 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35388/73498 (48.1%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 38110/73498 (51.9%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>


</ul></details>

**Review by jinjianrong — APPROVED** [review]

**Comment by qiaojbao** [comment]
it works now.
 Preparing to unpack .../dxc_1.4.0.2274-1187~rc1-1lunarg20.04-1_amd64.deb ...
Unpacking dxc (1.4.0.2274-1187~rc1-1lunarg20.04-1) ...
Selecting previously unselected package glslang-tools.
Preparing to unpack .../glslang-tools_11.10.0~rc1-1lunarg20.04-1_amd64.deb ...
Unpacking glslang-tools (11.10.0~rc1-1lunarg20.04-1) ...
Setting up dxc (1.4.0.2274-1187~rc1-1lunarg20.04-1) ...
Setting up glslang-tools (11.10.0~rc1-1lunarg20.04-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
dxcompiler.dll: 1.7(dev)
spirv-remap version 0.97

**Comment by qiaojbao** [comment]
@Flakebi , thanks

**Review by Flakebi — APPROVED** [review]
Thanks!

**Comment by amdvlk-admin** [comment]
### Test summary for commit 939006cf122098af0ce1a06a661d09a5c689a2ad
<details><summary>CTS tests (Failed: 0/289625)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx9</summary><ul>

<li>Passed: 32868/69268 (47.5%)</li>
<li>Failed: 0/69268 (0.0%)</li>
<li>Not Supported: 36400/69268 (52.5%)</li><li>Warnings: 0/69268 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/73498 (52.4%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 35007/73498 (47.6%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 34348/73361 (46.8%)</li>
<li>Failed: 0/73361 (0.0%)</li>
<li>Not Supported: 39013/73361 (53.2%)</li><li>Warnings: 0/73361 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35388/73498 (48.1%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 38110/73498 (51.9%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
