### PR TITLE
Statically link spvgen into amdllpc

### PR DESCRIPTION
**Pull request by Flakebi**
Based on #1703 plus removes the spvgen-dir option and the tests that tested spvgen in a shared library.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5fdf2662ecae9654411c83dee3e8b7af36d63d0e
<details><summary>CTS tests (Failed: 0/195808)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 38337/67464 (56.8%)</li>
<li>Failed: 0/67464 (0.0%)</li>
<li>Not Supported: 29127/67464 (43.2%)</li><li>Warnings: 0/67464 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33521/60880 (55.1%)</li>
<li>Failed: 0/60880 (0.0%)</li>
<li>Not Supported: 27359/60880 (44.9%)</li><li>Warnings: 0/60880 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 39335/67464 (58.3%)</li>
<li>Failed: 0/67464 (0.0%)</li>
<li>Not Supported: 28129/67464 (41.7%)</li><li>Warnings: 0/67464 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
@Flakebi this is a very large diff, is that intentional?

**Comment by Flakebi** [comment]
Yes, that’s the [Update shaderdb tests](https://github.com/GPUOpen-Drivers/llpc/pull/1774/commits/5fdf2662ecae9654411c83dee3e8b7af36d63d0e) commit. That’s removing all the `-spvgen-dir` arguments on the tests.
You can review the other two commits on their own (actually only the middle one is new, as the first commit is from #1703), they are quite small.

**Comment by kuhar** [comment]
> Yes, that’s the [Update shaderdb tests](https://github.com/GPUOpen-Drivers/llpc/pull/1774/commits/5fdf2662ecae9654411c83dee3e8b7af36d63d0e) commit. That’s removing all the `-spvgen-dir` arguments on the tests. You can review the other two commits on their own (actually only the middle one is new, as the first commit is from #1703), they are quite small.

Could you split it into two PRs? This would be easier for us because it would give us more time to make a similar change in our internal code base. And second, github is really bad at reviewing big changes and I cannot write a code review right because of how slow it is on my laptop.

**Comment by kuhar** [comment]
IE link statically in the first PR and update test in the second one.

**Comment by kosarev** [comment]
Just in case: it's always possible to fetch the Sebastian's fork and then just ask git to show the diff. Probably not as convenient as all the review UI here, but still might be helpful for reviewing large patches.

**Comment by kuhar** [comment]
The issue is that I can't even fill out the 'finish the review' prompt and click submit because it freezes almost instantly.

> The rest is already split out into https://github.com/GPUOpen-Drivers/llpc/pull/1703. If I understand it correctly, the only open comment on that PR is that we should either remove the option to load spvgen dynamically or leave in the tests. This PR takes the first approach and removes the ability to load spvgen dynamically into amdllpc.

Thanks for the explanation, it's more clear to me now.

**Comment by Flakebi** [comment]
Rebased (no changes). The spvgen fix went in and a base image build finished, so I hope the tests are passing now.

> The issue is that I can't even fill out the 'finish the review' prompt and click submit because it freezes almost instantly.

Does the review button not appear on the site that shows only a single commit? (like [here](https://github.com/GPUOpen-Drivers/llpc/pull/1774/commits/e384d364f55b43d3f4d12884580198f12f76531f))
I hope it’s also fine to just ignore the tooling and comment if you approve or disapprove :)

**Review by kuhar — COMMENTED** [review]
test

**Comment by kuhar** [comment]
@Flakebi ah, it does work if I select the commit first, instead of review and then commit. Thanks! I'll take a closer look later today.

**Review by kuhar — COMMENTED** [review]
Commit 2 LGTM.

**Review by kuhar — DISMISSED** [review]

**Comment by kuhar** [comment]
@Flakebi Seems like some tests might need updating:
```
/vulkandriver/drivers/llpc/llpc/test/shaderdb/extensions/OpExtInst_Print_InlineAsm_Error_NoArg.frag:4:15: error: SHADERTEST: expected string not found in input
; SHADERTEST: Not enough arguments for inline assembly {{.*}} 'my %ra'
              ^
<stdin>:1:1: note: scanning from here
amdllpc: Unknown command line argument '-spvgen-dir=/vulkandriver/builds/ci-build/spvgen'. Try: '/vulkandriver/builds/ci-build/compiler/llpc/amdllpc --help'
^
<stdin>:1:18: note: possible intended match here
amdllpc: Unknown command line argument '-spvgen-dir=/vulkandriver/builds/ci-build/spvgen'. Try: '/vulkandriver/builds/ci-build/compiler/llpc/amdllpc --help'
```

There are also some crashes, do we know what the issue is?

**Comment by kuhar** [comment]
> > There are also some crashes, do we know what the issue is?
> 
> No idea. When running with asan locally, it complains that the one-definition-rule is violated (of some static variables defined in glslang), but when I disable that asan check it runs through just fine.

TSan seems to complain a lot: https://github.com/GPUOpen-Drivers/llpc/runs/6080798908?check_suite_focus=true.

**Comment by Flakebi** [comment]
Finally found the problem after adding enough printfs and looking at the assembly.
Some definition is different between vfx and llpc (i.e. an `#ifdef` block is included when compiling a header for llpc, but it’s not when the header is included in vfx), leading to different struct sizes and wrong offsets on some fields.
For the docker containers, a nullptr is accessed due to that. Fortunately that was nicely reproducible.

**Review by kuhar — DISMISSED** [review]
LGTM

**Review by amdrexu — APPROVED** [review]

**Comment by Flakebi** [comment]
Rebased on the merged vkgc_headers library

**Comment by amdvlk-admin** [comment]
### Test summary for commit 7eeaa28c5f413fab85f3050158ac6c8473eccfba
<details><summary>CTS tests (Failed: 1/187820)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 36645/65225 (56.2%)</li>
<li>Failed: 0/65225 (0.0%)</li>
<li>Not Supported: 28580/65225 (43.8%)</li><li>Warnings: 0/65225 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31111/57370 (54.2%)</li>
<li>Failed: 0/57370 (0.0%)</li>
<li>Not Supported: 26259/57370 (45.8%)</li><li>Warnings: 0/57370 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37802/65225 (58.0%)</li>
<li><details><summary>Failed: 1/65225 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.multi_secondary_command_buffer
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, *fence): VK_TIMEOUT at vktSynchronizationBasicEventTests.cpp:337

```
</p></details></li>

<li>Not Supported: 27422/65225 (42.0%)</li><li>Warnings: 0/65225 (0.0%)</li>
</ul></details>


</ul></details>

**Review by kuhar — APPROVED** [review]

**Pull request merged**
