### PR TITLE
Switched LowerGlobal to use Builder methods for input/output

### PR DESCRIPTION
**Pull request by trenouf**
This switches the frontend to use the Builder methods for shader
input/output that were added in the last commit.

Change-Id: I4850e2229d6a33d43b2d6e2d7abcf1392458bbce

### CODE REVIEW

**Comment by trenouf** [comment]
This PR contains two commits. The first one is also in PR149, so please just review the second one.

**Comment by amdrexu** [comment]
Please update this commit when the first part is merged and the second is modified according to review comments.

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by trenouf** [comment]
Rebased this on an update to pr149 so hopefully it will pass testing this time.

**Comment by amdrexu** [comment]
I will review this commit tomorrow. If builder change is merged, you can update this pull request.

**Comment by trenouf** [comment]
Rebased on newly-landed PR #149. This PR now contains only one commit.

**Comment by trenouf** [comment]
That test passes for me locally on vega10.

**Comment by trenouf** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit c0c4888f6343ef647896ac9f6e99a747f1b297c6
<details open><summary>Driver commits used in build</summary><ul>

<li>METROHASH: amd-mainline 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 66e78b997748d03d77e1d706c10f1f17e18e5654</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 9b632ef4f132bddc94769702ed8b49efbc39d89c</li>
<li>LLVM: amd-vulkan-dev 9bc5dd4450a6361faf5c5661056a7ee494fad830</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 925/925 (100.0%)</li>
<li>Failed: 0/925 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 366250/366250 (100.0%)</li>
<li>Failed: 0/366250 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 366376/366376 (100.0%)</li>
<li>Failed: 0/366376 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
