### PR TITLE
Fix descriptor table in indirect layout mode

### PR DESCRIPTION
**Pull request by AMD-dwang**
In indirect mode, PushConst is subnode of DescriptorTableVaPtr, when

compiling unlinked shader, it will use 0 as the index, others are "set + 1". Please see PatchEntryPointMutate::gatherUserDataUsage.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 99ddc2632b026911555749747dcca46830dc4c5a
<details><summary>CTS tests (Failed: 0/286530)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 36222/72652 (49.9%)</li>
<li>Failed: 0/72652 (0.0%)</li>
<li>Not Supported: 36430/72652 (50.1%)</li><li>Warnings: 0/72652 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 40419/72699 (55.6%)</li>
<li>Failed: 0/72699 (0.0%)</li>
<li>Not Supported: 32280/72699 (44.4%)</li><li>Warnings: 0/72699 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 37135/72706 (51.1%)</li>
<li>Failed: 0/72706 (0.0%)</li>
<li>Not Supported: 35571/72706 (48.9%)</li><li>Warnings: 0/72706 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 34834/68473 (50.9%)</li>
<li>Failed: 0/68473 (0.0%)</li>
<li>Not Supported: 33639/68473 (49.1%)</li><li>Warnings: 0/68473 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
Can you please add a test that shows the difference / issue?

**Comment by nhaehnle** [comment]
To clarify, I think this whole ResourceLayoutScheme interface is pretty awkward and should probably be cleaned up somehow, but that's not necessarily a task for today. Meanwhile, we should ensure that any such future cleanup will be guarded by the existence of a test.

**Comment by AMD-dwang** [comment]
@nhaehnle There is already a test for `ResourceLayoutScheme` https://github.com/GPUOpen-Drivers/llpc/blob/dev/llpc/test/shaderdb/general/PipelineVsFs_TestIndirectResourceLayout.pipe.

This change is fixing relocated compilation. I will add a test for it.

**Review by nhaehnle — APPROVED** [review]
Great, thank you!

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 89af61dcbd1fa7ad2d6bc61d934ed92a5b246010
<details><summary>CTS tests (Failed: 0/285657)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 36222/72463 (50.0%)</li>
<li>Failed: 0/72463 (0.0%)</li>
<li>Not Supported: 36241/72463 (50.0%)</li><li>Warnings: 0/72463 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 40419/72473 (55.8%)</li>
<li>Failed: 0/72473 (0.0%)</li>
<li>Not Supported: 32054/72473 (44.2%)</li><li>Warnings: 0/72473 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 37135/72477 (51.2%)</li>
<li>Failed: 0/72477 (0.0%)</li>
<li>Not Supported: 35342/72477 (48.8%)</li><li>Warnings: 0/72477 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 34834/68244 (51.0%)</li>
<li>Failed: 0/68244 (0.0%)</li>
<li>Not Supported: 33410/68244 (49.0%)</li><li>Warnings: 0/68244 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
