### PR TITLE
Simplify input utils code. NFC.

### PR DESCRIPTION
**Pull request by kuhar**
This utilities are covered by the unit tests from https://github.com/GPUOpen-Drivers/llpc/pull/1395.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 53edcd9d80a32c60687d7a52eebfad9559a30be7
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 8e5baae7cfdd885974013337e556e9dc955b6737</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev b39135da435a761ee417609d1106c96fc9da2cc7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 68e5420f0ba94be9cae6fbac848d746592d03f42</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/221024)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31225/55256 (56.5%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24031/55256 (43.5%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31225/55256 (56.5%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24031/55256 (43.5%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31591/55256 (57.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 23665/55256 (42.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34350/55256 (62.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 20906/55256 (37.8%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
Ping for code review @amdrexu @trenouf @dstutt

**Review by dstutt — APPROVED** [review]
LGTM

**Comment by JaxLinAMD** [comment]
@kuhar do you know why this error happens in our build system?

C:\Jenkins\workspace\vulkan\vulkan-psdb>tail -n 40 C:\Jenkins\workspace\vulkan\vulkan-psdb/driver_build/logs/driver_build.txt 
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(850): error C2144: syntax error: 'unknown-type' should be preceded by ')'
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(850): error C2144: syntax error: 'unknown-type' should be preceded by ';'
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(850): error C2143: syntax error: missing ')' before '<'
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(850): error C2143: syntax error: missing ';' before '<'
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(850): error C2059: syntax error: ')'
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(857): error C2589: '(': illegal token on right side of '::'
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(857): error C2062: type 'unknown-type' unexpected
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(857): error C2059: syntax error: ')'
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(864): error C2589: '(': illegal token on right side of '::'
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(864): error C2062: type 'unknown-type' unexpected
[2021-09-14T06:07:50.328Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\StringRef.h(864): error C2059: syntax error: ')'
[2021-09-14T06:07:50.329Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\Support\MathExtras.h(100): warning C4003: not enough arguments for function-like macro invocation 'max'
[2021-09-14T06:07:50.329Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\Support\MathExtras.h(241): warning C4003: not enough arguments for function-like macro invocation 'max'
[2021-09-14T06:07:50.329Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\Support\MathExtras.h(282): warning C4003: not enough arguments for function-like macro invocation 'max'
[2021-09-14T06:07:50.329Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\Support\MathExtras.h(810): warning C4003: not enough arguments for function-like macro invocation 'max'
[2021-09-14T06:07:50.329Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\Support\MathExtras.h(835): warning C4003: not enough arguments for function-like macro invocation 'max'
[2021-09-14T06:07:50.329Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\Support\MathExtras.h(955): warning C4003: not enough arguments for function-like macro invocation 'max'
[2021-09-14T06:07:50.330Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\Support\MathExtras.h(957): warning C4003: not enough arguments for function-like macro invocation 'max'
[2021-09-14T06:07:50.330Z] C:\Jenkins\workspace\vulkan\vulkan-psdb\driver_build\drivers\xgl\icd\imported\llvm-project\llvm\include\llvm\ADT\APSInt.h(30): fatal error C1903: unable to recover from previous error(s); stopping compilation
[2021-09-14T06:07:50.330Z] INTERNAL COMPILER ERROR in 'C:\dk\win\VC\14.29.30133\bin\HostX64\x64\cl.exe'
[2021-09-14T06:07:50.330Z]     Please choose the Technical Support command on the Visual C++
[2021-09-14T06:07:50.330Z]     Help menu, or open the Technical Support help file for more information
[2021-09-14T06:07:50.880Z] make[8]: *** [../../../../../../../../../../make/win_commonrules:2292: llpcCompilationUtils.obj] Error -1073741819

**Comment by kuhar** [comment]
@amdrexu ping for approval.

**Review by amdrexu — APPROVED** [review]

**Comment by kuhar** [comment]
@JaxLinAMD could we get this merged?

**Pull request merged**
