### PR TITLE
NGG coding rework: [NFC] Some small renaming and comment revising

### PR DESCRIPTION
**Pull request by amdrexu**

### CODE REVIEW

**Review by nhaehnle — DISMISSED** [review]
Thanks, LGTM

**Comment by amdvlk-admin** [comment]
### Test summary for commit fcbf473a5a883d209ee9c3553db9080b35c48a75
<details><summary>CTS tests (Failed: 1/282025)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39248/70507 (55.7%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31259/70507 (44.3%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39497/70507 (56.0%)</li>
<li><details><summary>Failed: 1/70507 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.object_management.max_concurrent.graphics_pipeline
Stack trace: Timeout
```
</p></details></li>

<li>Not Supported: 31009/70507 (44.0%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 36345/70509 (51.5%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34164/70509 (48.5%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 36247/70502 (51.4%)</li>
<li>Failed: 0/70502 (0.0%)</li>
<li>Not Supported: 34255/70502 (48.6%)</li><li>Warnings: 0/70502 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit fcbf473a5a883d209ee9c3553db9080b35c48a75
<details><summary>CTS tests (Failed: 1/282025)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39248/70507 (55.7%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31259/70507 (44.3%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39497/70507 (56.0%)</li>
<li><details><summary>Failed: 1/70507 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.object_management.max_concurrent.graphics_pipeline
Stack trace: Timeout
```
</p></details></li>

<li>Not Supported: 31009/70507 (44.0%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 36345/70509 (51.5%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34164/70509 (48.5%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 36247/70502 (51.4%)</li>
<li>Failed: 0/70502 (0.0%)</li>
<li>Not Supported: 34255/70502 (48.6%)</li><li>Warnings: 0/70502 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit fcbf473a5a883d209ee9c3553db9080b35c48a75
<details><summary>CTS tests (Failed: 1/282013)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39248/70504 (55.7%)</li>
<li>Failed: 0/70504 (0.0%)</li>
<li>Not Supported: 31256/70504 (44.3%)</li><li>Warnings: 0/70504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39497/70504 (56.0%)</li>
<li><details><summary>Failed: 1/70504 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.object_management.max_concurrent.graphics_pipeline
Stack trace: Timeout
```
</p></details></li>

<li>Not Supported: 31006/70504 (44.0%)</li><li>Warnings: 0/70504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 36345/70506 (51.5%)</li>
<li>Failed: 0/70506 (0.0%)</li>
<li>Not Supported: 34161/70506 (48.5%)</li><li>Warnings: 0/70506 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 36247/70499 (51.4%)</li>
<li>Failed: 0/70499 (0.0%)</li>
<li>Not Supported: 34252/70499 (48.6%)</li><li>Warnings: 0/70499 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]

**Pull request merged**
