### PR TITLE
Fixes for standalone LLPC build with ray-tracing

### PR DESCRIPTION
**Pull request by trenouf**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9dbf7ef3b4ed268c4e81248410526e90c355108e
<details><summary>CTS tests (Failed: 1072/211487)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38712/70495 (54.9%)</li>
<li><details><summary>Failed: 536/70495 (0.8%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.0_update_0_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_0_0_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_0_compaction_lowmemory
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_update_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_0_0_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_0_0_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fastbuild_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fastbuild_update_0_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.padded.0_0_compaction_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.padded.0_update_compaction_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.nopadding.0_update_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fastbuild_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fastbuild_0_compaction_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fasttrace_update_compaction_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.nopadding.fasttrace_update_compaction_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.0_0_compaction_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.fastbuild_update_0_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.fasttrace_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.nopadding.0_0_compaction_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.nopadding.0_update_compaction_0_bottomgeneric
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 31247/70495 (44.3%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 38962/70495 (55.3%)</li>
<li><details><summary>Failed: 536/70495 (0.8%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.0_update_0_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_0_0_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_0_compaction_lowmemory
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_update_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_0_0_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_0_0_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fastbuild_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fastbuild_update_0_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.padded.0_0_compaction_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.padded.0_update_compaction_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.nopadding.0_update_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fastbuild_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fastbuild_0_compaction_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fasttrace_update_compaction_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.nopadding.fasttrace_update_compaction_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.0_0_compaction_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.fastbuild_update_0_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.fasttrace_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.nopadding.0_0_compaction_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.nopadding.0_update_compaction_0_bottomgeneric
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 30997/70495 (44.0%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36345/70497 (51.6%)</li>
<li>Failed: 0/70497 (0.0%)</li>
<li>Not Supported: 34152/70497 (48.4%)</li><li>Warnings: 0/70497 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit e42a1d54c22512ed69a62ff61d924cc1ba1ab137
<details><summary>CTS tests (Failed: 1072/211487)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38712/70495 (54.9%)</li>
<li><details><summary>Failed: 536/70495 (0.8%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.0_update_0_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_0_0_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_0_compaction_lowmemory
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_update_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_0_0_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_0_0_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fastbuild_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fastbuild_update_0_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.padded.0_0_compaction_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.padded.0_update_compaction_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.nopadding.0_update_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fastbuild_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fastbuild_0_compaction_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fasttrace_update_compaction_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.nopadding.fasttrace_update_compaction_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.0_0_compaction_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.fastbuild_update_0_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.fasttrace_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.nopadding.0_0_compaction_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.nopadding.0_update_compaction_0_bottomgeneric
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 31247/70495 (44.3%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 38962/70495 (55.3%)</li>
<li><details><summary>Failed: 536/70495 (0.8%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.0_update_0_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_0_0_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_0_compaction_lowmemory
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_update_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_0_0_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_0_0_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fastbuild_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fastbuild_update_0_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.padded.0_0_compaction_lowmemory_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.padded.0_update_compaction_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.nopadding.0_update_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fastbuild_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fastbuild_0_compaction_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fasttrace_update_compaction_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.nopadding.fasttrace_update_compaction_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.0_0_compaction_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.fastbuild_update_0_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.padded.fasttrace_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.nopadding.0_0_compaction_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.nopadding.0_update_compaction_0_bottomgeneric
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 30997/70495 (44.0%)</li><li>Warnings: 0/70495 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 36345/70497 (51.6%)</li>
<li>Failed: 0/70497 (0.0%)</li>
<li>Not Supported: 34152/70497 (48.4%)</li><li>Warnings: 0/70497 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
Clearly something bad is going on with the tests, which is very surprising since this change looks fine to me.

**Comment by trenouf** [comment]
Yes; my approach of "hope it was a stray alpha particle and kick the tests off again" didn't work.

**Comment by trenouf** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit e4c6ac12fe2de22de9059673d36499869b053578
<details><summary>CTS tests (Failed: 994/205121)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 35844/68158 (52.6%)</li>
<li><details><summary>Failed: 497/68158 (0.7%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.0_0_compaction_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_0_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_update_0_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.fastbuild_update_compaction_lowmemory
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fastbuild_update_0_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fasttrace_0_compaction_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fasttrace_update_compaction_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.nopadding.0_update_0_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.nopadding.0_update_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.0_update_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fastbuild_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fasttrace_update_0_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.nopadding.0_update_compaction_lowmemory
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.nopadding.fastbuild_0_compaction_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fastbuild_update_compaction_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fastbuild_update_compaction_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fasttrace_0_compaction_lowmemory
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fasttrace_update_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fasttrace_update_compaction_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances_aop.nopadding.0_update_0_0
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 31817/68158 (46.7%)</li><li>Warnings: 0/68158 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 36072/68158 (52.9%)</li>
<li><details><summary>Failed: 497/68158 (0.7%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.0_0_compaction_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.nopadding.fasttrace_0_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_update_0_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.fastbuild_update_compaction_lowmemory
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fastbuild_update_0_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fasttrace_0_compaction_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances_aop.nopadding.fasttrace_update_compaction_0_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.nopadding.0_update_0_0_bottomgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.nopadding.0_update_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.0_update_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fastbuild_0_0_0_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fasttrace_update_0_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.nopadding.0_update_compaction_lowmemory
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances_aop.nopadding.fastbuild_0_compaction_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fastbuild_update_compaction_lowmemory_bothgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fastbuild_update_compaction_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fasttrace_0_compaction_lowmemory
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fasttrace_update_compaction_0
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fasttrace_update_compaction_lowmemory_topgeneric
Stack trace: Fail

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances_aop.nopadding.0_update_0_0
Stack trace: Fail
...
```
</p></details></li>

<li>Not Supported: 31589/68158 (46.3%)</li><li>Warnings: 0/68158 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 34225/68805 (49.7%)</li>
<li>Failed: 0/68805 (0.0%)</li>
<li>Not Supported: 34580/68805 (50.3%)</li><li>Warnings: 0/68805 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0a91a3ca31343d0cf8690e3ed942dc0bb9e3fe77
<details><summary>CTS tests (Failed: 0/205163)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 36341/68172 (53.3%)</li>
<li>Failed: 0/68172 (0.0%)</li>
<li>Not Supported: 31831/68172 (46.7%)</li><li>Warnings: 0/68172 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 36569/68172 (53.6%)</li>
<li>Failed: 0/68172 (0.0%)</li>
<li>Not Supported: 31603/68172 (46.4%)</li><li>Warnings: 0/68172 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 34225/68819 (49.7%)</li>
<li>Failed: 0/68819 (0.0%)</li>
<li>Not Supported: 34594/68819 (50.3%)</li><li>Warnings: 0/68819 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — DISMISSED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit cc05c8e5db424a4167d07870175a19ff6936eee7
<details><summary>CTS tests (Failed: 0/207163)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 36989/69061 (53.6%)</li>
<li>Failed: 0/69061 (0.0%)</li>
<li>Not Supported: 32072/69061 (46.4%)</li><li>Warnings: 0/69061 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 37209/69039 (53.9%)</li>
<li>Failed: 0/69039 (0.0%)</li>
<li>Not Supported: 31830/69039 (46.1%)</li><li>Warnings: 0/69039 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 34228/69063 (49.6%)</li>
<li>Failed: 0/69063 (0.0%)</li>
<li>Not Supported: 34835/69063 (50.4%)</li><li>Warnings: 0/69063 (0.0%)</li>
</ul></details>


</ul></details>

**Review by Flakebi — APPROVED** [review]

**Review by nhaehnle — APPROVED** [review]

**Pull request merged**
