### PR TITLE
LGC: Mark subgroup/barrier functions convergent

### PR DESCRIPTION
**Pull request by ruiling**
I belive this is necessary to stop some bad optimization.

### CODE REVIEW

**Comment by jayfoad** [comment]
Looks reasonable to me, although some of the SubgroupBallot* functions like SubgroupBallotBitCount don't actually do anything convergent, they just manipulate the result of a previous convergent function like SubgroupBallot.

Also I'm not sure about SubgroupMbcnt. The underlying LLVM intrinsic amdgcn_mbcnt_lo is not marked as convergent, but perhaps it should be?

**Comment by ruiling** [comment]
> Looks reasonable to me, although some of the SubgroupBallot* functions like SubgroupBallotBitCount don't actually do anything convergent, they just manipulate the result of a previous convergent function like SubgroupBallot.
> 
> Also I'm not sure about SubgroupMbcnt. The underlying LLVM intrinsic amdgcn_mbcnt_lo is not marked as convergent, but perhaps it should be?
I agree with your idea we may need to carefully check each of the subgroup functions. I am not quite familiar with ALL of the function right now. So just keep them convergent for simplicity. I can add some comment to document that we need to revisit later. I guess marking them convergent should have not much performance hurt. Let me try whether I can figure out what all these subgroup functions are really doing in short time.

**Comment by amdvlk-admin** [comment]
### Test summary for commit bd84eac33c90bc00cf12be7fc4440956df4b85bc
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 0168557a0715bf47a55ffe9858276cde1e74cc1d</li>
<li>SPVGEN: dev 5bf4618ac00d4675f57ca5b571a485bbc4d4fa33</li>
<li>XGL: dev d5d37d69a0d4bd01cc93b8e806b18f4040a13e6d</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 2d65a54ff6a0f09b40937c3efb03c82d42002187</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/225198)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30577/56304 (54.3%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 25727/56304 (45.7%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30577/56304 (54.3%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 25727/56304 (45.7%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30682/56286 (54.5%)</li>
<li>Failed: 0/56286 (0.0%)</li>
<li>Not Supported: 25604/56286 (45.5%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34150/56304 (60.7%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 22154/56304 (39.3%)</li>
</ul></details>


</ul></details>

**Comment by piotrAMD** [comment]
Convergent practically stops code motion (like code sinking) so it can potentially affects performance. I agree we should not set it for ops they do not need it.

**Comment by ruiling** [comment]
> Convergent practically stops code motion (like code sinking) so it can potentially affects performance. I agree we should not set it for ops that do not need it.

Yes, I understand your point. I take some further look.

**Comment by s-perron** [comment]
Is it possible to write tests to demonstrate that the bad optimizations are not being applied?

**Comment by ruiling** [comment]
> Looks reasonable to me, although some of the SubgroupBallot* functions like SubgroupBallotBitCount don't actually do anything convergent, they just manipulate the result of a previous convergent function like SubgroupBallot.
Yes, you are right.
> 
> Also I'm not sure about SubgroupMbcnt. The underlying LLVM intrinsic amdgcn_mbcnt_lo is not marked as convergent, but perhaps it should be?
mbcnt result highly depends on the execution-mask, so yes, it should be.

**Review by amdrexu — APPROVED** [review]

**Comment by ruiling** [comment]
Please wait. I am sorry not updating status in time, because the thing is a little bit tricky. The biggest factor to the problem is 'ReadNone' attribute, without 'ReadNone' attribute, we can hardly see any mis-optimization at least for the case I see. And some fix patch still not merged like https://reviews.llvm.org/D85604. So it seems hard for me to give a test for such change now as I can not give a immediate form of failure for this fix. But I have some update to the patch, will send out soon.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 958ad4aa21225faea8b76b76601613110ef56722
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev de5f376ca30a108f1fc1fd5cdf33fdfe9f9d5dbb</li>
<li>SPVGEN: dev 5bf4618ac00d4675f57ca5b571a485bbc4d4fa33</li>
<li>XGL: dev d81362ec6baf91a98895572d721ce7497efc8eeb</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev f4a2a23c8dd892c93384572bf0699ec3566e0e17</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/213593)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30577/56304 (54.3%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 25727/56304 (45.7%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 28320/44699 (63.4%)</li>
<li><details><summary>Failed: 1/44699 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.subgroups.clustered.compute.subgroupclusteredadd_uint8_t
Stack trace: Script:
Crash

```
</p></details></li>

<li>Not Supported: 16378/44699 (36.6%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30682/56286 (54.5%)</li>
<li>Failed: 0/56286 (0.0%)</li>
<li>Not Supported: 25604/56286 (45.5%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34150/56304 (60.7%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 22154/56304 (39.3%)</li>
</ul></details>


</ul></details>

**Comment by ruiling** [comment]
Why there was failure like:
warning: repo is not tracking a remote branch, so it will not receive updates
repo reset: error: Entry 'docs/internal-fs-layout.md' not uptodate. Cannot merge.
fatal: Could not reset index file to revision '339f2df1ddd741070e340ec01d6882dd1eee617c'.
anybody know the reason?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 651e242579f4fa2d37717b4ff1bd8c414c61dc6c
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev de5f376ca30a108f1fc1fd5cdf33fdfe9f9d5dbb</li>
<li>SPVGEN: dev 5bf4618ac00d4675f57ca5b571a485bbc4d4fa33</li>
<li>XGL: dev d81362ec6baf91a98895572d721ce7497efc8eeb</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev f4a2a23c8dd892c93384572bf0699ec3566e0e17</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/225198)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30577/56304 (54.3%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 25727/56304 (45.7%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30577/56304 (54.3%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 25727/56304 (45.7%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30682/56286 (54.5%)</li>
<li>Failed: 0/56286 (0.0%)</li>
<li>Not Supported: 25604/56286 (45.5%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34150/56304 (60.7%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 22154/56304 (39.3%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
@ruiling CI is broken at the moment because of openssh-client not being installed by default. The error I've seen elsewhere is a bit different, but maybe it also affects this PR.
I opened a PR that should fix the ssh issue: https://github.com/GPUOpen-Drivers/llpc/pull/1246.

**Pull request merged**
