### PR TITLE
Add inline pass header for future use

### PR DESCRIPTION
**Pull request by jiaolu**

### CODE REVIEW

**Comment by amdrexu** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 458eea52f6281815d8741bd1be931b21cf5f0812
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 45f531beaf2c2b0bc2272e63a2da0022f1b07ccf</li>
<li>SPVGEN: dev 81f6794e048edd31d8c03343b9ed10dd4c0331ca</li>
<li>XGL: dev 8024f27f9457e3235bf4fcde0d2879bbaae7b0f2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev a163b38723cbc05f3014d4eaa1936c82bbfbf3ea</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 945/945 (100.0%)</li>
<li>Failed: 0/945 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.0-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 102981/102982 (100.0%)</li>
<li><details><summary>Failed: 1/102982 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.driver_properties.conformance_version
Stack trace: Wrong driver conformance version at vktApiDriverPropertiesTests.cpp:149
```
</p></details></li>


</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 102925/102926 (100.0%)</li>
<li><details><summary>Failed: 1/102926 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.driver_properties.conformance_version
Stack trace: Wrong driver conformance version at vktApiDriverPropertiesTests.cpp:149
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
@jiaolu , following tests are not passed

Failing Tests (3):
    LLPC_SHADERTEST :: shaderdb/ObjInput_TestIndexingInterpOfInputArray_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpDPdx_TestFineCoarse_lit.frag
    LLPC_SHADERTEST :: shaderdb/OpDPdy_TestFineCoarse_lit.frag

**Comment by trenouf** [comment]
> following tests are not passed

That's weird. The change only adds a #include. Maybe a rebase would help.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
> following tests are not passed
> 
> That's weird. The change only adds a #include. Maybe a rebase would help.

That's right, @jiaolu , could you rebase your commit?

**Comment by jiaolu** [comment]
> > following tests are not passed
> > That's weird. The change only adds a #include. Maybe a rebase would help.
> 
> That's right, @jiaolu , could you rebase your commit?

rebased

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6d726c73ba3b07c9f4b8562fcf1673d9f4a12994
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 45f531beaf2c2b0bc2272e63a2da0022f1b07ccf</li>
<li>SPVGEN: dev 81f6794e048edd31d8c03343b9ed10dd4c0331ca</li>
<li>XGL: dev 8024f27f9457e3235bf4fcde0d2879bbaae7b0f2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 878d4bd14afe9bc670911954adfb7c16b71e7cae</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 960/960 (100.0%)</li>
<li>Failed: 0/960 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 102962/102962 (100.0%)</li>
<li>Failed: 0/102962 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 102961/102961 (100.0%)</li>
<li>Failed: 0/102961 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 102906/102906 (100.0%)</li>
<li>Failed: 0/102906 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
