### PR TITLE
Remove dump CFG support from legacy pass manager

### PR DESCRIPTION
**Pull request by dstutt**
Upstream CFGPrinter support is being updated to remove legacy pass manager support.

LGC only supports this option in legacy pass manager so removing the option entirely. LGC now mostly uses the new pass manager, so the option is of limited use and can only be enabled for backend passes anyway.

### CODE REVIEW

**Review by nhaehnle — DISMISSED** [review]

**Review by trenouf — DISMISSED** [review]
LGTM

**Review by trenouf — APPROVED** [review]
I guess that was a clang-format fix.

Still LGTM.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 344e92f9a2e6726628897e58417eb0959f9d8625
<details><summary>CTS tests (Failed: 0/138378)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35162/69163 (50.8%)</li>
<li>Failed: 0/69163 (0.0%)</li>
<li>Not Supported: 34001/69163 (49.2%)</li><li>Warnings: 0/69163 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35241/69215 (50.9%)</li>
<li>Failed: 0/69215 (0.0%)</li>
<li>Not Supported: 33974/69215 (49.1%)</li><li>Warnings: 0/69215 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit de3170dc8a1975089af97653b09f083254df4ae2
<details><summary>CTS tests (Failed: 0/138378)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35162/69163 (50.8%)</li>
<li>Failed: 0/69163 (0.0%)</li>
<li>Not Supported: 34001/69163 (49.2%)</li><li>Warnings: 0/69163 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35242/69215 (50.9%)</li>
<li>Failed: 0/69215 (0.0%)</li>
<li>Not Supported: 33973/69215 (49.1%)</li><li>Warnings: 0/69215 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
