### PR TITLE
Fix cull&clip distance param location, it may cause param mismatch

### PR DESCRIPTION
**Pull request by KOTOKORURU**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Review by nhaehnle — COMMENTED** [review]
When / why can `clipDistance` be greater than 4? And this looks like it doesn't do the right thing if `clipDistance == 4` and `cullDistance == 1`.

**Comment by KOTOKORURU** [comment]
@nhaehnle  MaxClipCullDistanceCount is 8, one interInfo is for 4, so if 4 clip with 4 cull, the origin code will generte 3 param(this is not right), for your case, it still Right.

**Comment by amdrexu** [comment]
> When / why can `clipDistance` be greater than 4? And this looks like it doesn't do the right thing if `clipDistance == 4` and `cullDistance == 1`.

ClipDistance could be float[8]. If we have `float gl_ClipDistance[4]` and `float gl_CullDistance[1]`. The location and start channel of them are:
```
gl_ClipDistance: startChannel = 0, location = N, location count = 1
gl_CullDistance: startChannel = 0, location = N + 1, location count = 1
```

**Comment by qiaojbao** [comment]
ok to test

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3896ea20634dce6a52a6f14fc923addfc2bd2090
<details><summary>CTS tests (Failed: 0/142050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71030 (56.9%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 30604/71030 (43.1%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71020 (57.0%)</li>
<li>Failed: 0/71020 (0.0%)</li>
<li>Not Supported: 30556/71020 (43.0%)</li><li>Warnings: 0/71020 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
