### PR TITLE
Remove PAL_CLIENT_INTERFACE_MAJOR_VERSION in LLPC

### PR DESCRIPTION
**Pull request by amdrexu**
These checks are old and PAL version for LLPC has already be bumped.

Change-Id: I8062afd371d858e3db1f2876ef1846bedc76e819

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit af5c5f018d65f87ca9368f917261c57b53b4eee9
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev f49a7f3f706dd721d9a7b620be1482217ef63b6e</li>
<li>SPVGEN: dev efa3cec20c6ebc66254ff9cca9b3ea124811d7a3</li>
<li>XGL: dev c3d047085243c811583a612b5ae016a513705465</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev cdd74831d061bf65fdf5af4a0b6ce99fe2c558a9</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/225388)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31425/56347 (55.8%)</li>
<li>Failed: 0/56347 (0.0%)</li>
<li>Not Supported: 24922/56347 (44.2%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31413/56347 (55.7%)</li>
<li>Failed: 0/56347 (0.0%)</li>
<li>Not Supported: 24934/56347 (44.3%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31748/56347 (56.3%)</li>
<li>Failed: 0/56347 (0.0%)</li>
<li>Not Supported: 24599/56347 (43.7%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34582/56347 (61.4%)</li>
<li>Failed: 0/56347 (0.0%)</li>
<li>Not Supported: 21765/56347 (38.6%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
@amdrexu We are checking whether we can update past 674 soon. Can you please wait a few days before merging?

**Comment by vettoreldaniele** [comment]
We are expecting to be on 687 in about two weeks, could this PR wait until then before being merged? I can report back here once we have upgraded.

**Comment by amdrexu** [comment]
Thank you. I will hold it until you ping me.

**Comment by vettoreldaniele** [comment]
We are good on Google's side, you can safely merge this PR. Thanks for waiting!

**Comment by amdrexu** [comment]
> We are good on Google's side, you can safely merge this PR. Thanks for waiting!

Thank you for confirmation.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 26301fb8820032c2991a01ca820b8bda80d29487
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 44abc48d199dd28369bf7415eee1751c4bf616d2</li>
<li>SPVGEN: dev 580ade71d630a304805e9468ef22ad263c37d137</li>
<li>XGL: dev 38aa59bcf134d1cb340ddd2459b34b6eda798abe</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 9f7a59928db862a2baded0b45582ce3683d83762</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/218612)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 32354/54653 (59.2%)</li>
<li>Failed: 0/54653 (0.0%)</li>
<li>Not Supported: 22299/54653 (40.8%)</li><li>Warnings: 0/54653 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 32194/54653 (58.9%)</li>
<li>Failed: 0/54653 (0.0%)</li>
<li>Not Supported: 22458/54653 (41.1%)</li><li>Warnings: 1/54653 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 32530/54653 (59.5%)</li>
<li>Failed: 0/54653 (0.0%)</li>
<li>Not Supported: 22123/54653 (40.5%)</li><li>Warnings: 0/54653 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 35511/54653 (65.0%)</li>
<li>Failed: 0/54653 (0.0%)</li>
<li>Not Supported: 19142/54653 (35.0%)</li><li>Warnings: 0/54653 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
