### PR TITLE
Fix flaky tests with leading zeros

### PR DESCRIPTION
**Pull request by Flakebi**
If a matched hash ends up with a leading zero, FileCheck will only
match the number without leading zeros on further uses of that captured
value.

Specify the number of digits of the matched hashes to get passing tests
also with leading zeros in hashes.

### CODE REVIEW

**Review by piotrAMD — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3e0c0339d352f35577b2d5b7d7952a74db5fd8a9
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev b638e90ca4e6e5a6fc4f00029d62f8e064aa18eb</li>
<li>SPVGEN: dev 6c2f36bcf0f8ff7ba8d20c8b789ca6346d1e16b1</li>
<li>XGL: dev 89a4cf115b9a2972ff00e2fe4959f4f1c8e7175b</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev b439932ec28c68cd68daf8420cc649c18f9fe955</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/151518)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 37585/66643 (56.4%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 29058/66643 (43.6%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 11814/18232 (64.8%)</li>
<li><details><summary>Failed: 1/18232 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.binding_model.descriptorset_random.sets8.dynindexed.ubolimithigh.sbolimitlow.sampledimglow.outimgtexlow.iublimitlow.nouab.comp.noia.0
Stack trace: Script:
Crash

```
</p></details></li>

<li>Not Supported: 6417/18232 (35.2%)</li><li>Warnings: 0/18232 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 38645/66643 (58.0%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 27998/66643 (42.0%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>


</ul></details>

**Review by kuhar — APPROVED** [review]
Thanks!

**Comment by kuhar** [comment]
@Flakebi
Clarifying question: have you noticed flakiness between runs of the same binaries, or after updating submodules? The former should not happen.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3e0c0339d352f35577b2d5b7d7952a74db5fd8a9
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev b638e90ca4e6e5a6fc4f00029d62f8e064aa18eb</li>
<li>SPVGEN: dev 6c2f36bcf0f8ff7ba8d20c8b789ca6346d1e16b1</li>
<li>XGL: dev 89a4cf115b9a2972ff00e2fe4959f4f1c8e7175b</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev b439932ec28c68cd68daf8420cc649c18f9fe955</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/199929)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 37585/66643 (56.4%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 29058/66643 (43.6%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 37436/66643 (56.2%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 29207/66643 (43.8%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 38645/66643 (58.0%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 27998/66643 (42.0%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by Flakebi** [comment]
The hashes were consistent between runs. Our internal Jenkins failed one test and locally it failed on another test (I should have the same llpc version but maybe different versions on other driver parts).

**Pull request merged**
