### PR TITLE
Disable ngg culling when there is no position fetch

### PR DESCRIPTION
**Pull request by bsaleil**
This patch is to disable ngg culling when there is no position fetch.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit d6cd0b03d2d7383b192206d8221979e9bb88e4fa
<details><summary>CTS tests (Failed: 0/141320)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40065/70667 (56.7%)</li>
<li>Failed: 0/70667 (0.0%)</li>
<li>Not Supported: 30602/70667 (43.3%)</li><li>Warnings: 0/70667 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40106/70653 (56.8%)</li>
<li>Failed: 0/70653 (0.0%)</li>
<li>Not Supported: 30547/70653 (43.2%)</li><li>Warnings: 0/70653 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
willHaveFetchShader -> hasVertexFetch (we try to avoid separate fetch shaders)

This could benefit from a brief "why" in the comment. As I understand it, this is a heuristic to detect vertex shaders that produce very simple calculated positions, which are often used to e.g. draw fullscreen quads that are never going to be culled.

**Review by nhaehnle — APPROVED** [review]
Thanks!

**Comment by amdvlk-admin** [comment]
### Test summary for commit ac7c7ae83799c7191c2a2a7375d02a65752e9eb0
<details><summary>CTS tests (Failed: 0/141320)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40065/70667 (56.7%)</li>
<li>Failed: 0/70667 (0.0%)</li>
<li>Not Supported: 30602/70667 (43.3%)</li><li>Warnings: 0/70667 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40106/70653 (56.8%)</li>
<li>Failed: 0/70653 (0.0%)</li>
<li>Not Supported: 30547/70653 (43.2%)</li><li>Warnings: 0/70653 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
