### PR TITLE
Pull request jenkins tests---Please don't approve it

### PR DESCRIPTION
**Pull request by JacobHeAMD**

### CODE REVIEW

**Comment by JacobHeAMD** [comment]
### Test summary for commit b4fc3b398ad9d1f3fd37e634592bc3378d03681e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: f40b53f526b1221a4efbd7beb00152ab32036882 HEAD</li>
<li>SPVGEN: 1560d287f779b342e0019499dda85890cb07affc HEAD</li>
<li>XGL: 42e8b58860e4c049a3545d2559ba56420841dd1f HEAD</li>
<li>LLVM: 97cc33415120ae3ed472b6dd5cb234b74a80bd80 HEAD</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 902/902 (100.0%)</li>
<li>Failed: 0/902 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Vega20</summary><ul>

<li>Passed: 312687/312687 (100.0%)</li>
<li>Failed: 0/312687 (0.0%)</li>
</ul></details>


</ul></details>


<details><summary>Build Failed</summary><ul>

buildLog.txt
</ul></details>

**Comment by JacobHeAMD** [comment]
### Test summary for commit b4fc3b398ad9d1f3fd37e634592bc3378d03681e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f40b53f526b1221a4efbd7beb00152ab32036882</li>
<li>SPVGEN: dev 1560d287f779b342e0019499dda85890cb07affc</li>
<li>XGL: dev 42e8b58860e4c049a3545d2559ba56420841dd1f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 902/902 (100.0%)</li>
<li>Failed: 0/902 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Vega20</summary><ul>

<li>Passed: 98/98 (100.0%)</li>
<li>Failed: 0/98 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
### Test summary for commit b4fc3b398ad9d1f3fd37e634592bc3378d03681e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f40b53f526b1221a4efbd7beb00152ab32036882</li>
<li>SPVGEN: dev 1560d287f779b342e0019499dda85890cb07affc</li>
<li>XGL: dev 42e8b58860e4c049a3545d2559ba56420841dd1f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 902/902 (100.0%)</li>
<li>Failed: 0/902 (0.0%)</li>
</ul></details>

**Comment by JacobHeAMD** [comment]
### Test summary for commit b4fc3b398ad9d1f3fd37e634592bc3378d03681e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f40b53f526b1221a4efbd7beb00152ab32036882</li>
<li>SPVGEN: dev 1560d287f779b342e0019499dda85890cb07affc</li>
<li>XGL: dev 42e8b58860e4c049a3545d2559ba56420841dd1f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>No Results</li>

</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
### Test summary for commit b4fc3b398ad9d1f3fd37e634592bc3378d03681e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f40b53f526b1221a4efbd7beb00152ab32036882</li>
<li>SPVGEN: dev 1560d287f779b342e0019499dda85890cb07affc</li>
<li>XGL: dev 42e8b58860e4c049a3545d2559ba56420841dd1f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 902/902 (100.0%)</li>
<li>Failed: 0/902 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>No Results</li>

</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b4fc3b398ad9d1f3fd37e634592bc3378d03681e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f40b53f526b1221a4efbd7beb00152ab32036882</li>
<li>SPVGEN: dev 1560d287f779b342e0019499dda85890cb07affc</li>
<li>XGL: dev 42e8b58860e4c049a3545d2559ba56420841dd1f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 902/902 (100.0%)</li>
<li>Failed: 0/902 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>No Results</li>

</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b4fc3b398ad9d1f3fd37e634592bc3378d03681e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f40b53f526b1221a4efbd7beb00152ab32036882</li>
<li>SPVGEN: dev 1560d287f779b342e0019499dda85890cb07affc</li>
<li>XGL: dev 42e8b58860e4c049a3545d2559ba56420841dd1f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 902/902 (100.0%)</li>
<li>Failed: 0/902 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Vega20</summary><ul>

<li>Passed: 98/98 (100.0%)</li>
<li>Failed: 0/98 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b4fc3b398ad9d1f3fd37e634592bc3378d03681e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f40b53f526b1221a4efbd7beb00152ab32036882</li>
<li>SPVGEN: dev 1560d287f779b342e0019499dda85890cb07affc</li>
<li>XGL: dev 42e8b58860e4c049a3545d2559ba56420841dd1f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 896da6a8ee08902c9f55c1dcf21534f179d5c808
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev f40b53f526b1221a4efbd7beb00152ab32036882</li>
<li>SPVGEN: dev 1560d287f779b342e0019499dda85890cb07affc</li>
<li>XGL: dev 42e8b58860e4c049a3545d2559ba56420841dd1f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 901/901 (100.0%)</li>
<li>Failed: 0/901 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 21/21 (100.0%)</li>
<li>Failed: 0/21 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 896da6a8ee08902c9f55c1dcf21534f179d5c808
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 14045067091d226072437527359a54c8b8e898eb</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 54194f5ebb7d1d6b44b9eb87217041f44e08f789</li>
<li>LLVM: amd-vulkan-dev 1ca248e6fc6d4d15491756f92f4da139222ef3ca</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpAtomicIIncrement_TestStorageBlock_lit.spvas:10:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpAtomicIIncrement_TestVariablePointer_lit.spvas:8:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpAtomicXXX_TestStorageBlock_lit.frag:67:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpEmitVertex_TestGeneral_lit.geom:30:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpEmitStreamVertex_TestGeneral_lit.geom:30:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpExtInst_TestRadiansVec4Const_lit.frag:25:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpExtInst_TestPowVec4Const_lit.frag:28:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpMatrixTimesScalar_TestMat4X2xConstFloat_lit.frag:21:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpReturnValue_TestEarlyReturn_lit.frag:34:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpReturnValue_TestReturnInNestedLoop_lit.frag:36:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpSwitch_Test64BitCaseLabel_lit.spvas:11:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpSwitch_TestFallThrough_lit.frag:34:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpSwitch_TestGeneral_lit.frag:37:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpSwitch_TestMergedBranches_lit.frag:33:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/OpUnreachable_TestGeneral_lit.spvas:5:15: error: SHADERTEST: expected string not found in input
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/test/shaderdb/gfx9/ExtShaderInt8_TestVsInOut_lit.vert:24:15: error: SHADERTEST: expected string not found in input

</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit bd78d20050b48a2fa7ffb55b95e8f193a28622e0
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 14045067091d226072437527359a54c8b8e898eb</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 54194f5ebb7d1d6b44b9eb87217041f44e08f789</li>
<li>LLVM: amd-vulkan-dev 1ca248e6fc6d4d15491756f92f4da139222ef3ca</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 901/901 (100.0%)</li>
<li>Failed: 0/901 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Vega20</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8a0370ff86c597a6f8b07393cc781dc4e5a035c8
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev b563d58ad6dc7c2daee9b73801dcc1321686b73b</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>XGL: dev 54194f5ebb7d1d6b44b9eb87217041f44e08f789</li>
<li>LLVM: amd-vulkan-dev 1ca248e6fc6d4d15491756f92f4da139222ef3ca</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 901/901 (100.0%)</li>
<li>Failed: 0/901 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Vega20</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
### Test summary for commit b4fc3b398ad9d1f3fd37e634592bc3378d03681e
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 7182b2c62fba5756e20a5a0858f22f008f5d9d37</li>
<li>SPVGEN: dev f9f54957780b4e00dfe947d698efabf2999be863</li>
<li>XGL: dev 96d84068b622b2c3ce8cf9aa8ff597260aa5ad3f</li>
<li>LLVM: amd-vulkan-dev 8118692e8aefbd95f791ff49beddb8ce90e8927c</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>No Results</li>

</ul></details>


</ul></details>

**Pull request closed without merging**
