### PR TITLE
fix the issue when running vlk_cts spirv_assembly.instruction.compute…

### PR DESCRIPTION
**Pull request by reallyzhao**
….opudotaccsatkhr.*_out32

This issue has been root-caused. It's due to incorrect using for LLVM intrinsic: "llvm.sadd.sat.i32", it should use llvm.uadd.sat when the operators are unsigned  and llvm.sadd.sat.i32 when operators are signed.

Please refer the description as below:

The ‘llvm.sadd.sat’ family of intrinsic functions perform signed saturating addition on the 2 arguments.

The ‘llvm.uadd.sat’ family of intrinsic functions perform unsigned saturating addition on the 2 arguments.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JaxLinAMD** [comment]
ok to test

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9ca408f3e330cd40ef81342de3a2713fb58f6d17
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev b638e90ca4e6e5a6fc4f00029d62f8e064aa18eb</li>
<li>SPVGEN: dev 6c2f36bcf0f8ff7ba8d20c8b789ca6346d1e16b1</li>
<li>XGL: dev 89a4cf115b9a2972ff00e2fe4959f4f1c8e7175b</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev afe13751c21d672a992d83f7d33856958f7d2f3b</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/187777)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 37585/66643 (56.4%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 29058/66643 (43.6%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33613/54491 (61.7%)</li>
<li><details><summary>Failed: 1/54491 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.subgroups.quad.compute.subgroupquadswapdiagonal_i64vec2
Stack trace: Script:
Crash

```
</p></details></li>

<li>Not Supported: 20877/54491 (38.3%)</li><li>Warnings: 0/54491 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 38645/66643 (58.0%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 27998/66643 (42.0%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 580bce44ed1f3b2289d129523b9222d934ccda8c
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev b638e90ca4e6e5a6fc4f00029d62f8e064aa18eb</li>
<li>SPVGEN: dev 6c2f36bcf0f8ff7ba8d20c8b789ca6346d1e16b1</li>
<li>XGL: dev 89a4cf115b9a2972ff00e2fe4959f4f1c8e7175b</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev afe13751c21d672a992d83f7d33856958f7d2f3b</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/199929)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 37585/66643 (56.4%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 29058/66643 (43.6%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 37436/66643 (56.2%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 29207/66643 (43.8%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 38645/66643 (58.0%)</li>
<li>Failed: 0/66643 (0.0%)</li>
<li>Not Supported: 27998/66643 (42.0%)</li><li>Warnings: 0/66643 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request closed without merging**
