### PR TITLE
Fix the alignment of the copy shader.

### PR DESCRIPTION
**Pull request by s-perron**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2d6e3ef1ac0f99ff34feb56d8e8d0894ea9e6c56
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 0e83f232d8b70c6823f62bbd9dbf286a68037fe2</li>
<li>SPVGEN: dev a46945586e83a71cb07b11936eb5fe503afd6360</li>
<li>XGL: dev ec89b84f0b8a83aa2b29ed25cfd741c90f9e2688</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev e1fa8201843985dccfa72acebf9a48ea98920c87</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/228724)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 32108/57181 (56.2%)</li>
<li>Failed: 0/57181 (0.0%)</li>
<li>Not Supported: 25073/57181 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 32108/57181 (56.2%)</li>
<li>Failed: 0/57181 (0.0%)</li>
<li>Not Supported: 25073/57181 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 32488/57181 (56.8%)</li>
<li>Failed: 0/57181 (0.0%)</li>
<li>Not Supported: 24693/57181 (43.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 35419/57181 (61.9%)</li>
<li>Failed: 0/57181 (0.0%)</li>
<li>Not Supported: 21762/57181 (38.1%)</li>
</ul></details>


</ul></details>

**Review by trenouf — DISMISSED** [review]
LGTM

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by kuhar** [comment]
Seems like the rebase action did not work because this PR is too far from `dev` (rebasing would result in changing github workflow files, which githubs protects against).

**Comment by s-perron** [comment]
V3: Rebase.  No change.

**Comment by amdvlk-admin** [comment]
### Test summary for commit b3a412e9679df9e293c1f030e751523af0aefdcb
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev cd4f8b28b5d923e8d65a1ef1d3dee5137a89d6bd</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev 133ef76a809deb8078ebdbacea4d9b8bfe5dad93</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 02a00c5cd4463687bf52d043ed3b7caa14374689</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/228848)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 32108/57212 (56.1%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 25104/57212 (43.9%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 32108/57212 (56.1%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 25104/57212 (43.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 32488/57212 (56.8%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 24724/57212 (43.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 35419/57212 (61.9%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 21793/57212 (38.1%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
