### PR TITLE
Enabled unused variable error on gcc build

### PR DESCRIPTION
**Pull request by trenouf**
Also fixed a couple of problems it showed up.

Change-Id: Ie523533038578abff778f6a9de96ac606b1998d1

### CODE REVIEW

**Comment by trenouf** [comment]
This will fail for now because it also needs a couple of fixes in pal. I am pushing the pal fixes through internally.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6e74663d9bd776ec90b00b3402d3e82e570a3ead
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 3e28ea331cf8e7b0e5733e5bd7f7d16582c603c5</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 68e79ff09849f32d0bbe929d94b19d58af7e0850</li>
<li>LLVM: amd-vulkan-dev 21b028dc97ee9b0c6629ff83c2924b3b80c5d6e7</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 50133/50134 (100.0%)</li>
<li><details><summary>Failed: 1/50134 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.image.swapchain_mutable.xlib.2d.r8g8b8a8_unorm_r8g8b8a8_snorm_copy_texture_format_list
Stack trace: Failed to open display: '' at tcuLnxX11.cpp:67
```
</p></details></li>


</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
That was a spurious CTS failure, rather than the blatant compile error I was expecting. So clearly my change doesn't enable the error I thought it would enable.

**Comment by trenouf** [comment]
V2: Actually made unused variable an error

**Comment by amdvlk-admin** [comment]
### Test summary for commit e462ac95970129282b762d2a01ba0b21804a45d3
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 39abe2297ca58a2b84dcd9bc5e238fbc399bd6e0</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 19a031d9f73b95101fd4d3d594aca27c00feb180</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 40fbaf4c5446a361269c241d9112fff26575b5d0</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/core/palPipelineAbi.h:182:20: error: ‘Util::Abi::PipelineMetadataNameStrings’ defined but not used [-Werror=unused-variable]
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palElf.h:428:20: error: ‘Util::Elf::SectionNameStringTable’ defined but not used [-Werror=unused-variable]
cc1plus: some warnings being treated as errors

</ul></details>

**Comment by trenouf** [comment]
That's more like the failure I was hoping for:
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/core/palPipelineAbi.h:182:20: error: ‘Util::Abi::PipelineMetadataNameStrings’ defined but not used [-Werror=unused-variable]
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palElf.h:428:20: error: ‘Util::Elf::SectionNameStringTable’ defined but not used [-Werror=unused-variable]

**Comment by amdvlk-admin** [comment]
### Test summary for commit eca10d0d10cd681899b5d43c77777a1ba7645b9a
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 39abe2297ca58a2b84dcd9bc5e238fbc399bd6e0</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 19a031d9f73b95101fd4d3d594aca27c00feb180</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 40fbaf4c5446a361269c241d9112fff26575b5d0</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/core/palPipelineAbi.h:182:20: error: ‘Util::Abi::PipelineMetadataNameStrings’ defined but not used [-Werror=unused-variable]
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palElf.h:428:20: error: ‘Util::Elf::SectionNameStringTable’ defined but not used [-Werror=unused-variable]
cc1plus: some warnings being treated as errors

</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 71c30fae93c68da78d0c4583f44dd71e10706e5e
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 39abe2297ca58a2b84dcd9bc5e238fbc399bd6e0</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 19a031d9f73b95101fd4d3d594aca27c00feb180</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 40fbaf4c5446a361269c241d9112fff26575b5d0</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/core/palPipelineAbi.h:182:20: error: ‘Util::Abi::PipelineMetadataNameStrings’ defined but not used [-Werror=unused-variable]
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/../pal/inc/util/palElf.h:428:20: error: ‘Util::Elf::SectionNameStringTable’ defined but not used [-Werror=unused-variable]
cc1plus: some warnings being treated as errors

</ul></details>

**Comment by trenouf** [comment]
V6: More fixes, and rebased

**Pull request merged**
