### PR TITLE
[lgcdis][NFC] Give the code outputting instructions a separate function.

### PR DESCRIPTION
**Pull request by kosarev**
A follow-up from https://github.com/GPUOpen-Drivers/llpc/pull/1752#discussion_r839573968.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Review by dstutt — APPROVED** [review]
LGTM

**Comment by Flakebi** [comment]
ok to test

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by kosarev** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit ee31d0afdb82e82520f8553b0d3559a50ffdf609
<details><summary>CTS tests (Failed: 0/216210)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35449/73547 (48.2%)</li>
<li>Failed: 0/73547 (0.0%)</li>
<li>Not Supported: 38098/73547 (51.8%)</li><li>Warnings: 0/73547 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33142/69116 (48.0%)</li>
<li>Failed: 0/69116 (0.0%)</li>
<li>Not Supported: 35974/69116 (52.0%)</li><li>Warnings: 0/69116 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37710/73547 (51.3%)</li>
<li>Failed: 0/73547 (0.0%)</li>
<li>Not Supported: 35837/73547 (48.7%)</li><li>Warnings: 0/73547 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
