### PR TITLE
Use IRBuilder<>::InsertPointGuard to save/restore insert point

### PR DESCRIPTION
**Pull request by amdrexu**
Make some code clean-up.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0eac0c9d0441197027f99df2a831fc24c7f06af2
<details><summary>CTS tests (Failed: 0/207253)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 38905/70466 (55.2%)</li>
<li>Failed: 0/70466 (0.0%)</li>
<li>Not Supported: 31561/70466 (44.8%)</li><li>Warnings: 0/70466 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35750/70474 (50.7%)</li>
<li>Failed: 0/70474 (0.0%)</li>
<li>Not Supported: 34724/70474 (49.3%)</li><li>Warnings: 0/70474 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33476/66313 (50.5%)</li>
<li>Failed: 0/66313 (0.0%)</li>
<li>Not Supported: 32837/66313 (49.5%)</li><li>Warnings: 0/66313 (0.0%)</li>
</ul></details>


</ul></details>

**Review by Flakebi — APPROVED** [review]
Nice, I didn’t know about `InsertPointGuard`.
There are two more that can be replaced, do you want to change them as well?
- `BuilderImplBase::createWaterfallLoop`
- `ImageBuilder::enforceReadFirstLane`

**Comment by amdrexu** [comment]
> Nice, I didn’t know about `InsertPointGuard`. There are two more that can be replaced, do you want to change them as well?
> 
> * `BuilderImplBase::createWaterfallLoop`
> * `ImageBuilder::enforceReadFirstLane`

Thank you. I noticed this useful method when Nicolai made review comments last time and I found we have more code places doing the awkward restore/save operations.
I make a update now.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9ec7fc2c80faa0f60318135be9f912e834ff1c38
<details><summary>CTS tests (Failed: 0/207253)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 38905/70466 (55.2%)</li>
<li>Failed: 0/70466 (0.0%)</li>
<li>Not Supported: 31561/70466 (44.8%)</li><li>Warnings: 0/70466 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35750/70474 (50.7%)</li>
<li>Failed: 0/70474 (0.0%)</li>
<li>Not Supported: 34724/70474 (49.3%)</li><li>Warnings: 0/70474 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33476/66313 (50.5%)</li>
<li>Failed: 0/66313 (0.0%)</li>
<li>Not Supported: 32837/66313 (49.5%)</li><li>Warnings: 0/66313 (0.0%)</li>
</ul></details>


</ul></details>

**Review by Flakebi — APPROVED** [review]

**Pull request merged**
