### PR TITLE
Move non-LLPC declarations and code out of llpc directory

### PR DESCRIPTION
**Pull request by xuechen417**
This PR is to move non-LLPC specific code out of llpc directory to make a common pipeline dump and vfx library for the driver.

### CODE REVIEW

**Comment by xuechen417** [comment]
Hi, The LLPC Docker CI fails due to using the old vfx directory. How to trigger a clean build for this PR?

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
Build failed because spvgen can’t find vfx files, It seems to me you ‘d better change spvgen/CmakeLists.txt:

if(EXISTS ${PROJECT_SOURCE_DIR}/../llpc/tool/vfx)
    set(XGL_VFX_PATH ${PROJECT_SOURCE_DIR}/../llpc/tool/vfx CACHE PATH "The path of vfx.")
else()
    set(XGL_VFX_PATH ${PROJECT_SOURCE_DIR}/../llpc/llpc/tool/vfx CACHE PATH "The path of vfx.")
endif()

change above code to:

set(XGL_VFX_PATH ${PROJECT_SOURCE_DIR}/../llpc/llpc/tool/vfx CACHE PATH "The path of vfx.")

could you try it? @trenouf , @JacobHeAMD  what do you think?

**Comment by xuechen417** [comment]
In this PR, llpc/llpc/tool/vfx is moved to llpc/tool/vfx. The code in spvgen/CMakeLists.txt is to support both old and new path. Could we remove the cmake cache file which remembers the old path?

**Comment by xuechen417** [comment]
I created a PR in spvgen to fix the XGL_VFX_PATH issue. @JacobHeAMD @trenouf @JaxLinAMD Please review it. Thanks.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by trenouf** [comment]
I suspect a "retest this" will test it again with the same spvgen. If so, it'll need a rebase to test it with the updated spvgen.

**Comment by JaxLinAMD** [comment]
How to re-trigger Docker CI?

**Comment by xuechen417** [comment]
Rebased to trigger new test check.

**Comment by amdvlk-admin** [comment]
### Test summary for commit e62dc2072137b5f0b4ac003c323cccd767225541
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev e642f608a62887d40d1f25509d2951a4a3576985</li>
<li>SPVGEN: dev d16fddddf22a1eb3a3f4ce05cbcb95a337f708b1</li>
<li>XGL: dev 80e5a4b11ad2058097e77746772ddc9ab2118e07</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 5c958c70bc6366298296dc778e903f65528c3b0f</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 960/960 (100.0%)</li>
<li>Failed: 0/960 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
> How to re-trigger Docker CI?

There should be a restart button when you go to the dashboard for a failed run. I think it only shows up to the PR author and maybe admins (?).

**Comment by amdvlk-admin** [comment]
### Test summary for commit dd7279934a3d9b3317aeb5aa3f6ad49ec031322f
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev e642f608a62887d40d1f25509d2951a4a3576985</li>
<li>SPVGEN: dev d70f9800ce70f89aedb3821f06a69776c58d1d39</li>
<li>XGL: dev 80e5a4b11ad2058097e77746772ddc9ab2118e07</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev b2b163fba8298b8ec6e36cee9666123d0069bfa8</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 960/960 (100.0%)</li>
<li>Failed: 0/960 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by xuechen417** [comment]
Rebased and modified commit "Renamed namespace to Vkgc out of llpc directory"

**Comment by xuechen417** [comment]
Resovled conflicts.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b27926e5f656a78507014ae0f0e7f3a5a514474a
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev bb7398b1c7509a30ba4f7d947b5ad5549a4d58db</li>
<li>SPVGEN: dev b30c124e7a042c5251aeb20780a83089355e74a1</li>
<li>XGL: dev ffd39443fec0ce821b7702173eba7184855c7b5e</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ebc431ac299fa294a4e730432520d37f326843c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 960/960 (100.0%)</li>
<li>Failed: 0/960 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103137/103137 (100.0%)</li>
<li>Failed: 0/103137 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by xuechen417** [comment]
Resolved conflicts.

**Pull request merged**
