### PR TITLE
Use more literal struct types instead of identified struct types

### PR DESCRIPTION
**Pull request by jayfoad**
Identified struct types are by definition not uniqued, even if you try
to create another one with the same name and the same members, so
creating lots of them unnecessarily is wasteful.

You can see this in the output of "amdllpc -print-after-all", where the
initial IR sometimes has hundreds of structs like this:

%llpc.matrix.row.220 = type <{ [4 x float] }>
%llpc.matrix.row.221 = type <{ [4 x float] }>
%llpc.matrix.row.222 = type <{ [4 x float] }>

... which are all identical except that LLVM has been forced to pick a
suffix for each name just to make them different.

### CODE REVIEW

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
@jayfoad dEQP-VK.ubo.random.basic_arrays.2 failed, please take a look.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by jayfoad** [comment]
> @jayfoad dEQP-VK.ubo.random.basic_arrays.2 failed, please take a look.

I can reproduce these failures and I have investigated. It is to do with how the SPIRVReader detects that it needs to "launder" a row major matrix. I need to think more about the best way to fix it.

**Comment by JacobHeAMD** [comment]
Please rebase to the latest the LLPC since there is compatible issue between LLPC and LLVM

**Comment by amdvlk-admin** [comment]
### Test summary for commit f6fb0e8c09c850853bb10d8afc9f0362871a2541
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 5d72cf9890fe2fbb1b87eecc497114e04afaa277</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 83c89cd727653c4514e2abe30e1633220fdb666e</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 0549a86140ab4e138db4f2a6ea72fbacb69bdddb</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 46027/46028 (100.0%)</li>
<li><details><summary>Failed: 1/46028 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ubo.random.basic_arrays.2
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 46059/46060 (100.0%)</li>
<li><details><summary>Failed: 1/46060 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ubo.random.basic_arrays.2
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 46059/46060 (100.0%)</li>
<li><details><summary>Failed: 1/46060 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ubo.random.basic_arrays.2
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by amdrexu** [comment]
@jayfoad Do you have a chance to revisit this commit?

**Comment by jayfoad** [comment]
> @jayfoad Do you have a chance to revisit this commit?

Not yet. Sorry. Should I close the PR until I have more time to work on it?

**Comment by amdrexu** [comment]
OK. You can close this PR and reopen it once your change is ready once again.

**Pull request closed without merging**
