### PR TITLE
Amd/dev/jrehders/sc1 4737 add continufy pass

### PR DESCRIPTION
**Pull request by JanRehders-AMD**
WIP PR for @ruiling to take over. Comments are in the source with known issues marked as TODO

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by qiaojbao** [comment]
test this please

**Comment by qiaojbao** [comment]
11:46:14  /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/llpc/lower/llpcSpirvLowerRayQuery.cpp: In member function ‘llvm::Value* Llpc::SpirvLowerRayQuery::createLoadInstanceIndex(llvm::Value*)’:
11:46:14  /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/llpc/lower/llpcSpirvLowerRayQuery.cpp:1313:57: error: ‘getInt32PtrTy’ is not a member of ‘llvm::Type’
11:46:14   1313 |   loadValue = m_builder->CreateBitCast(loadValue, Type::getInt32PtrTy(*m_context, SPIRAS_Global));
11:46:14        |                                                         ^~~~~~~~~~~~~
11:46:14  /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/llpc/lower/llpcSpirvLowerRayQuery.cpp: In member function ‘llvm::Value* Llpc::SpirvLowerRayQuery::createLoadInstanceId(llvm::Value*)’:
11:46:14  /jenkins/workspace/vulkan/sanitized-opensource/Github-PR/llpc-github-pr/driver_build/drivers/llpc/llpc/lower/llpcSpirvLowerRayQuery.cpp:1370:57: error: ‘getInt32PtrTy’ is not a member of ‘llvm::Type’
11:46:14   1370 |   loadValue = m_builder->CreateBitCast(loadValue, Type::getInt32PtrTy(*m_context, SPIRAS_Global));
11:46:14        |                                                         ^~~~~~~~~~~~~
11:46:14  [2939/3112] Building CXX object compiler/llpc/CMakeFiles/llpcinternal.dir/lower/llpcSpirvLower.cpp.o

**Comment by tsymalla** [comment]
Can we close this in favor of #2677 ?

**Pull request closed without merging**
