### PR TITLE
Cleanup pipeline hash and cache hash mixup

### PR DESCRIPTION
**Pull request by s-perron**
The uses of the the "pipeline hash" and "cache hash" in the pipeline
context got confused.  That needs to be cleaned up.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9141ef006a41507735f2f24547e2afc037d2b95a
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 5262df4eae038624c412904f0a250b66db92194b</li>
<li>SPVGEN: dev 6e35eab398b519b8056a13a57dafc6c64b3df13a</li>
<li>XGL: dev 181630cb6bf68773d2840353c7dbe69530bb1819</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fef6a69e1cc922638cd248e8d73670df38fa63a1</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/237021)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 27608/59232 (46.6%)</li>
<li>Failed: 0/59232 (0.0%)</li>
<li>Skipped: 31624/59232 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27607/59232 (46.6%)</li>
<li>Failed: 0/59232 (0.0%)</li>
<li>Skipped: 31625/59232 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 26167/59325 (44.1%)</li>
<li><details><summary>Failed: 1/59325 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.creation_feedback.graphics_tests.vertex_stage_fragment_stage_no_cache
Stack trace: Fail
```
</p></details></li>

<li>Skipped: 33157/59325 (55.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 28269/59232 (47.7%)</li>
<li>Failed: 0/59232 (0.0%)</li>
<li>Skipped: 30963/59232 (52.3%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9141ef006a41507735f2f24547e2afc037d2b95a
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 5262df4eae038624c412904f0a250b66db92194b</li>
<li>SPVGEN: dev 6e35eab398b519b8056a13a57dafc6c64b3df13a</li>
<li>XGL: dev 181630cb6bf68773d2840353c7dbe69530bb1819</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fef6a69e1cc922638cd248e8d73670df38fa63a1</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/237021)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 27608/59232 (46.6%)</li>
<li>Failed: 0/59232 (0.0%)</li>
<li>Skipped: 31624/59232 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27606/59232 (46.6%)</li>
<li><details><summary>Failed: 1/59232 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.1024
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 31625/59232 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 26812/59325 (45.2%)</li>
<li><details><summary>Failed: 1/59325 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.creation_feedback.graphics_tests.vertex_stage_fragment_stage_no_cache
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 32512/59325 (54.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 28269/59232 (47.7%)</li>
<li>Failed: 0/59232 (0.0%)</li>
<li>Skipped: 30963/59232 (52.3%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9141ef006a41507735f2f24547e2afc037d2b95a
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 95494513896a18924512ef426834e4c49967da56</li>
<li>SPVGEN: dev 6e35eab398b519b8056a13a57dafc6c64b3df13a</li>
<li>XGL: dev 181630cb6bf68773d2840353c7dbe69530bb1819</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fef6a69e1cc922638cd248e8d73670df38fa63a1</li>
</ul></details>

<details><summary>CTS tests (Failed: 12/237021)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 27608/59232 (46.6%)</li>
<li>Failed: 0/59232 (0.0%)</li>
<li>Skipped: 31624/59232 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27607/59232 (46.6%)</li>
<li>Failed: 0/59232 (0.0%)</li>
<li>Skipped: 31625/59232 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 26813/59325 (45.2%)</li>
<li>Failed: 0/59325 (0.0%)</li>
<li>Skipped: 32512/59325 (54.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 28255/59232 (47.7%)</li>
<li><details><summary>Failed: 12/59232 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.glsl.matrix.post_decrement.mediump_mat2x3_float_vertex
Stack trace: Flake

FAILURE: dEQP-VK.glsl.swizzles.vector_swizzles.mediump_ivec4_yyyy_fragment
Stack trace: Flake

FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_storage_texel_buffer.8192
Stack trace: Flake

FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_uniform_texel_buffer.1024
Stack trace: Flake

FAILURE: dEQP-VK.pipeline.stencil.format.d16_unorm_s8_uint_separate_layouts.states.fail_incc.pass_decc.dfail_decw.comp_less_or_equal
Stack trace: Flake

FAILURE: dEQP-VK.renderpass2.dedicated_allocation.attachment.8.639
Stack trace: Flake

FAILURE: dEQP-VK.sparse_resources.image_sparse_residency.cube_array.rg32i.137_137_3
Stack trace: Flake

FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.float_controls.fp16.input_args.denorm_vmuls_inf_preserve_frag
Stack trace: Flake

FAILURE: dEQP-VK.spirv_assembly.type.vec2.i16.not_tesse
Stack trace: Flake

FAILURE: dEQP-VK.subgroups.clustered.compute.subgroupclusteredmax_i64vec2
Stack trace: Flake

FAILURE: dEQP-VK.subgroups.clustered.compute.subgroupclusteredmin_u16vec3
Stack trace: Flake

FAILURE: dEQP-VK.ubo.multi_nested_struct.per_block_buffer.std430_instance_array_vertex
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 30965/59232 (52.3%)</li>
</ul></details>


</ul></details>

**Review by jaebaek — APPROVED** [review]

**Comment by JaxLinAMD** [comment]
retest this please

**Review by JaxLinAMD — APPROVED** [review]

**Pull request merged**
