### PR TITLE
lgc: fix warning for ignored virtual base class initialization

### PR DESCRIPTION
**Pull request by trenouf**

### CODE REVIEW

**Comment by Flakebi** [comment]
This doesn’t work on some compilers unfortunately (see also #1013).
Maybe we should add a comment :)

**Comment by trenouf** [comment]
> This doesn’t work on some compilers unfortunately (see also #1013).
> Maybe we should add a comment :)

Oh, that's a shame.

**Comment by amdvlk-admin** [comment]
### Test summary for commit cbaa11f2e5b785295152f43bced66022516b7052
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 5262df4eae038624c412904f0a250b66db92194b</li>
<li>SPVGEN: dev 6e35eab398b519b8056a13a57dafc6c64b3df13a</li>
<li>XGL: dev 8823a4383d17e6c1f09a129e17951a136ff338b2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 58afc07107d45ebc3fb97961c771090035620ee3</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/177782)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 27609/59230 (46.6%)</li>
<li>Failed: 0/59230 (0.0%)</li>
<li>Skipped: 31621/59230 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 26168/59322 (44.1%)</li>
<li>Failed: 0/59322 (0.0%)</li>
<li>Skipped: 33154/59322 (55.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 28270/59230 (47.7%)</li>
<li>Failed: 0/59230 (0.0%)</li>
<li>Skipped: 30960/59230 (52.3%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 43c1733e8992dfbeb821b95abd63862116354b86
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 5262df4eae038624c412904f0a250b66db92194b</li>
<li>SPVGEN: dev 6e35eab398b519b8056a13a57dafc6c64b3df13a</li>
<li>XGL: dev 8823a4383d17e6c1f09a129e17951a136ff338b2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 58afc07107d45ebc3fb97961c771090035620ee3</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/237012)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 27608/59230 (46.6%)</li>
<li><details><summary>Failed: 1/59230 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.creation_feedback.graphics_tests.vertex_stage_fragment_stage_no_cache
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 31621/59230 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27607/59230 (46.6%)</li>
<li><details><summary>Failed: 1/59230 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.image_clearing.core.clear_color_image.3d.optimal.single_layer.r16g16b16a16_unorm_multiple_subresourcerange
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 31622/59230 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 26168/59322 (44.1%)</li>
<li>Failed: 0/59322 (0.0%)</li>
<li>Skipped: 33154/59322 (55.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 28270/59230 (47.7%)</li>
<li>Failed: 0/59230 (0.0%)</li>
<li>Skipped: 30960/59230 (52.3%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
