### PR TITLE
Remove -enable-shader-module-opt

### PR DESCRIPTION
**Pull request by kuhar**
It is unclear if this code is in a working state and there are no tests.
Also bump the LLPC major version.

### CODE REVIEW

**Comment by kuhar** [comment]
V1: Remove a leftover pointer.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 983ea341bf8b3a5afaaea888a13359522cbe4109
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev ad24e368a2e7a0dcebef9b18af68893051cda329</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev 7e2070be478a90852ca88c2aee36406b9d19c861</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 8207d5d4fbe8b5848ad54eee18977b5ab5aaa48e</li>
</ul></details>

<details><summary>CTS tests (Failed: 47786/133127)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 10088/31438 (32.1%)</li>
<li><details><summary>Failed: 12752/31438 (40.6%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.command_buffers.order_bind_pipeline
Stack trace: Script:
Invalid result values


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1024_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1024_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.8192_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.8192_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.65536_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.65536_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1024_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1024_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.8192_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.8192_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.65536_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.65536_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1048576_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1048576_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.all_device.1024_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.all_device.1024_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.all_device.8192_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed

...
```
</p></details></li>

<li>Not Supported: 8598/31438 (27.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 10300/31438 (32.8%)</li>
<li><details><summary>Failed: 12539/31438 (39.9%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.command_buffers.order_bind_pipeline
Stack trace: Script:
Invalid result values


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1024_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1024_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.8192_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.8192_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.65536_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.65536_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.1024
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.8192
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.65536
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.1048576
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1024_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1024_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.8192_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.8192_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.65536_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.65536_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1048576_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed

...
```
</p></details></li>

<li>Not Supported: 8599/31438 (27.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 16479/38813 (42.5%)</li>
<li><details><summary>Failed: 9473/38813 (24.4%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.command_buffers.order_bind_pipeline
Stack trace: Script:
Invalid result values


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1024_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1024_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.8192_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.8192_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.65536_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.65536_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.1024
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.8192
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.65536
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.1048576
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1024_vertex_buffer_stride_2
Stack trace: Script:
6:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1024_vertex_buffer_stride_4
Stack trace: Script:
6:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.8192_vertex_buffer_stride_2
Stack trace: Script:
6:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.8192_vertex_buffer_stride_4
Stack trace: Script:
6:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.65536_vertex_buffer_stride_2
Stack trace: Script:
6:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.65536_vertex_buffer_stride_4
Stack trace: Script:
6:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1048576_vertex_buffer_stride_2
Stack trace: Script:
6:SubmitRenderPass Image comparison failed

...
```
</p></details></li>

<li>Not Supported: 12861/38813 (33.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 10153/31438 (32.3%)</li>
<li><details><summary>Failed: 13022/31438 (41.4%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.command_buffers.order_bind_pipeline
Stack trace: Script:
Invalid result values


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1024_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1024_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.8192_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.8192_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.65536_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.65536_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_2
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_4
Stack trace: Script:
1:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1024_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1024_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.8192_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.8192_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.65536_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.65536_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1048576_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_dst_vertex_buffer.1048576_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.all_device.1024_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.all_device.1024_vertex_buffer_stride_4
Stack trace: Script:
7:SubmitRenderPass Image comparison failed


FAILURE: dEQP-VK.memory.pipeline_barrier.all_device.8192_vertex_buffer_stride_2
Stack trace: Script:
7:SubmitRenderPass Image comparison failed

...
```
</p></details></li>

<li>Not Supported: 8263/31438 (26.3%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9d9a5c1a74c4e26619936c572da7b84e7ae6d203
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev ad24e368a2e7a0dcebef9b18af68893051cda329</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev 7e2070be478a90852ca88c2aee36406b9d19c861</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 8207d5d4fbe8b5848ad54eee18977b5ab5aaa48e</li>
</ul></details>

<details><summary>CTS tests (Failed: 482/221132)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31197/55283 (56.4%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 24086/55283 (43.6%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31196/55283 (56.4%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 24087/55283 (43.6%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31058/55283 (56.2%)</li>
<li><details><summary>Failed: 482/55283 (0.9%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole.2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole.4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole.8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.partial.2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.partial.4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.partial.8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.with_regions.2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.with_regions.4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.with_regions.8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole_copy_before_resolving.4_bit
Stack trace: Script:
Intermediate verification failed for coordinates (16, 16) sample 0


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole_copy_before_resolving.8_bit
Stack trace: Script:
Intermediate verification failed for coordinates (8, 8) sample 0


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole_array_image.4_bit
Stack trace: Script:
Intermediate verification failed for coordinates (8, 8) sample 0


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_266_256_1_2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_266_256_1_4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_266_256_1_8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_512_1_2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_512_1_4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_512_1_8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_256_11_2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_256_11_4_bit
Stack trace: Script:
CopiesAndBlitting test

...
```
</p></details></li>

<li>Not Supported: 23743/55283 (42.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34313/55283 (62.1%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 20970/55283 (37.9%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 55210431e758d0b5553b1bfec32938d33ab74b36
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev ad24e368a2e7a0dcebef9b18af68893051cda329</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev 7e2070be478a90852ca88c2aee36406b9d19c861</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 8207d5d4fbe8b5848ad54eee18977b5ab5aaa48e</li>
</ul></details>

<details><summary>CTS tests (Failed: 463/221132)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31197/55283 (56.4%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 24086/55283 (43.6%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31196/55283 (56.4%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 24087/55283 (43.6%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31077/55283 (56.2%)</li>
<li><details><summary>Failed: 463/55283 (0.8%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole.2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole.4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole.8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.partial.2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.partial.4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.partial.8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.with_regions.2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.with_regions.4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.with_regions.8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole_copy_before_resolving.4_bit
Stack trace: Script:
Intermediate verification failed for coordinates (16, 16) sample 0


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole_copy_before_resolving.8_bit
Stack trace: Script:
Intermediate verification failed for coordinates (0, 0) sample 0


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole_array_image.4_bit
Stack trace: Script:
Intermediate verification failed for coordinates (0, 0) sample 0


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_266_256_1_2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_266_256_1_4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_266_256_1_8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_512_1_2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_512_1_4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_512_1_8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_256_11_2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_256_11_4_bit
Stack trace: Script:
CopiesAndBlitting test

...
```
</p></details></li>

<li>Not Supported: 23743/55283 (42.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34313/55283 (62.1%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 20970/55283 (37.9%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
@JaxLinAMD is there something wrong with Jenkins, or should I look into these CTS failures? I made another test commit and it failed the same way, so I'm leaning towards the former.

**Review by amdrexu — APPROVED** [review]

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
I will reboot the agent

**Comment by amdvlk-admin** [comment]
### Test summary for commit 55210431e758d0b5553b1bfec32938d33ab74b36
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev ad24e368a2e7a0dcebef9b18af68893051cda329</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev 7e2070be478a90852ca88c2aee36406b9d19c861</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 8207d5d4fbe8b5848ad54eee18977b5ab5aaa48e</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/221132)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31197/55283 (56.4%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 24086/55283 (43.6%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31196/55283 (56.4%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 24087/55283 (43.6%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31540/55283 (57.1%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 23743/55283 (42.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34313/55283 (62.1%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 20970/55283 (37.9%)</li>
</ul></details>


</ul></details>

**Comment by piotrAMD** [comment]
Thanks for doing this clean-up.

We have plans to experiment with moving part of the compilation early, but as it stands now, the option does not work. For instance, some changes are needed in SPIRVReader.cpp to make the code independent on the pipeline context.

**Comment by kuhar** [comment]
Thanks for the context, @piotrAMD. To clarify, are you fine with the way this PR cleans it up?

**Comment by piotrAMD** [comment]
> Thanks for the context, @piotrAMD. To clarify, are you fine with the way this PR cleans it up?

Yes, thanks.

**Review by piotrAMD — APPROVED** [review]

**Pull request merged**
