### PR TITLE
Add tool/update_llpc_test_checks.py

### PR DESCRIPTION
**Pull request by nhaehnle**
The goal is to allow us to test the frontend (LLPC) IR emission with tests that are more meaningful and also easier to maintain and update than the status quo.

This is obviously built on LLVM's update_test_checks tools, so a reasonable question is whether we can re-use those tools. The existing UTC tools themselves make too many assumptions about how the underlying tool is invoked and about the input language(s), so a new tool is appropriate.

Since the utils Python scripts aren't typically seen as a publically exposed interface of LLVM, I decided to just copy the helper library. This makes it easier for us to make the changes in the library that we need (and there are some) and should avoid random breakage due to upstream changes.

I've changed an arbitrary existing test to demonstrate the kind of test file that results.

### CODE REVIEW

**Comment by jasilvanus** [comment]
> This makes it easier for us to make the changes in the library that we need (and there are some) and should avoid random breakage due to upstream changes.

Are there already changes made, or is this anticipating upcoming changes?

**Comment by nhaehnle** [comment]
> > This makes it easier for us to make the changes in the library that we need (and there are some) and should avoid random breakage due to upstream changes.
> 
> Are there already changes made, or is this anticipating upcoming changes?

Yes, I had to make some changes. The biggest one is that the existing UTC scripts assume that tools accept input on stdin, which amdllpc doesn't, and changing that is a bit annoying because amdllpc actually looks at the filename to determine what to do (e.g. like glslang, there's a difference between .comp and .frag, and so on).

**Comment by jasilvanus** [comment]
Maybe we can then split the commits into the copy and the edit part, so your changes are kept in history, and possibly allowing to merge with upstream changes later on?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 406d63d6102377dcd0ef13dd640e146f408f5e9a
<details><summary>CTS tests (Failed: 0/207274)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 38905/70473 (55.2%)</li>
<li>Failed: 0/70473 (0.0%)</li>
<li>Not Supported: 31568/70473 (44.8%)</li><li>Warnings: 0/70473 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35750/70481 (50.7%)</li>
<li>Failed: 0/70481 (0.0%)</li>
<li>Not Supported: 34731/70481 (49.3%)</li><li>Warnings: 0/70481 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33476/66320 (50.5%)</li>
<li>Failed: 0/66320 (0.0%)</li>
<li>Not Supported: 32844/66320 (49.5%)</li><li>Warnings: 0/66320 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
> Maybe we can then split the commits into the copy and the edit part, so your changes are kept in history, and possibly allowing to merge with upstream changes later on?

Done for common.py. I technically also based update_llpc_test_checks.py on update_test_checks.py, but the difference are large enough that any changes to the base script will likely have to be manually ported anyway.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8edb3872a6fcbb4eb47151df70f627e4b6ebe0e8
<details><summary>CTS tests (Failed: 0/207274)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 38905/70473 (55.2%)</li>
<li>Failed: 0/70473 (0.0%)</li>
<li>Not Supported: 31568/70473 (44.8%)</li><li>Warnings: 0/70473 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35750/70481 (50.7%)</li>
<li>Failed: 0/70481 (0.0%)</li>
<li>Not Supported: 34731/70481 (49.3%)</li><li>Warnings: 0/70481 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33476/66320 (50.5%)</li>
<li>Failed: 0/66320 (0.0%)</li>
<li>Not Supported: 32844/66320 (49.5%)</li><li>Warnings: 0/66320 (0.0%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
