### PR TITLE
LGC Patch: Change UndefValue to PoisonValue

### PR DESCRIPTION
**Pull request by amdrexu**
To follow the upcoming LLVM change: https://reviews.llvm.org/D152658.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit e6e06f6568491913bea503cdedc62300c1107a32
<details><summary>CTS tests (Failed: 0/141320)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40065/70667 (56.7%)</li>
<li>Failed: 0/70667 (0.0%)</li>
<li>Not Supported: 30602/70667 (43.3%)</li><li>Warnings: 0/70667 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40106/70653 (56.8%)</li>
<li>Failed: 0/70653 (0.0%)</li>
<li>Not Supported: 30547/70653 (43.2%)</li><li>Warnings: 0/70653 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit ee23d358e4d98f580775ed1aedf8ada38b726c76
<details><summary>CTS tests (Failed: 0/141320)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40065/70667 (56.7%)</li>
<li>Failed: 0/70667 (0.0%)</li>
<li>Not Supported: 30602/70667 (43.3%)</li><li>Warnings: 0/70667 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40106/70653 (56.8%)</li>
<li>Failed: 0/70653 (0.0%)</li>
<li>Not Supported: 30547/70653 (43.2%)</li><li>Warnings: 0/70653 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit ee23d358e4d98f580775ed1aedf8ada38b726c76
<details><summary>CTS tests (Failed: 0/140881)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39058/70446 (55.4%)</li>
<li>Failed: 0/70446 (0.0%)</li>
<li>Not Supported: 31388/70446 (44.6%)</li><li>Warnings: 0/70446 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39090/70435 (55.5%)</li>
<li>Failed: 0/70435 (0.0%)</li>
<li>Not Supported: 31345/70435 (44.5%)</li><li>Warnings: 0/70435 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8b4be06daa44300de88ae2b6201ad504c88c9c4a
<details><summary>CTS tests (Failed: 0/140881)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39058/70446 (55.4%)</li>
<li>Failed: 0/70446 (0.0%)</li>
<li>Not Supported: 31388/70446 (44.6%)</li><li>Warnings: 0/70446 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39090/70435 (55.5%)</li>
<li>Failed: 0/70435 (0.0%)</li>
<li>Not Supported: 31345/70435 (44.5%)</li><li>Warnings: 0/70435 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8b4be06daa44300de88ae2b6201ad504c88c9c4a
<details><summary>CTS tests (Failed: 0/140881)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39058/70446 (55.4%)</li>
<li>Failed: 0/70446 (0.0%)</li>
<li>Not Supported: 31388/70446 (44.6%)</li><li>Warnings: 0/70446 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39090/70435 (55.5%)</li>
<li>Failed: 0/70435 (0.0%)</li>
<li>Not Supported: 31345/70435 (44.5%)</li><li>Warnings: 0/70435 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit be3f92de43b72d4df81b278d45be9be7d5582705
<details><summary>CTS tests (Failed: 0/140881)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39058/70446 (55.4%)</li>
<li>Failed: 0/70446 (0.0%)</li>
<li>Not Supported: 31388/70446 (44.6%)</li><li>Warnings: 0/70446 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39090/70435 (55.5%)</li>
<li>Failed: 0/70435 (0.0%)</li>
<li>Not Supported: 31345/70435 (44.5%)</li><li>Warnings: 0/70435 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
FYI, PoisonValue is actually derived from UndefValue and so `isa<UndefValue>(x)` is true for poison as well. This means some of the changes here are technically not necessary, but it's also fine to leave it as-is.

**Pull request merged**
