### PR TITLE
Use string type variable for global variable name

### PR DESCRIPTION
**Pull request by jiaolu**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6aed81cb66b73ee6b5999eb695d8c9c489db741f
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 3e28ea331cf8e7b0e5733e5bd7f7d16582c603c5</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 3252b6223947f9fc67399e0798b1062983925fce</li>
<li>LLVM: amd-vulkan-dev 21b028dc97ee9b0c6629ff83c2924b3b80c5d6e7</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 68331/68331 (100.0%)</li>
<li>Failed: 0/68331 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 68363/68363 (100.0%)</li>
<li>Failed: 0/68363 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit ae8857503d7d86e014a158ff6afe20958a1df066
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 3e28ea331cf8e7b0e5733e5bd7f7d16582c603c5</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 68e79ff09849f32d0bbe929d94b19d58af7e0850</li>
<li>LLVM: amd-vulkan-dev 21b028dc97ee9b0c6629ff83c2924b3b80c5d6e7</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 50133/50134 (100.0%)</li>
<li><details><summary>Failed: 1/50134 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.image.swapchain_mutable.xlib.2d.r8g8b8a8_unorm_r8g8b8a8_snorm_copy_texture_format_list
Stack trace: Failed to open display: '' at tcuLnxX11.cpp:67
```
</p></details></li>


</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit ae8857503d7d86e014a158ff6afe20958a1df066
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 3e28ea331cf8e7b0e5733e5bd7f7d16582c603c5</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 68e79ff09849f32d0bbe929d94b19d58af7e0850</li>
<li>LLVM: amd-vulkan-dev cb206549e1422e0722b93a49a7029d0dd489c70b</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:659:55: error: no matching function for call to ‘llvm::LoadInst::setAlignment(unsigned int)’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/patch/llpcPatchBufferOp.cpp:1568:57: error: no matching function for call to ‘llvm::LoadInst::setAlignment(unsigned int)’

</ul></details>

**Comment by trenouf** [comment]
I think this latest failure is because llvm has been updated and llpc now needs #253.

**Comment by jiaolu** [comment]
> I think this latest failure is because llvm has been updated and llpc now needs #253.

yes, i need to do a rebase

**Comment by trenouf** [comment]
Oh yes, I think you're right, you just need a rebase. We already have the equivalent of #253 from the merge from master.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3c700c14e191366f6b72c9b1b7ddcbe30996635c
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 39abe2297ca58a2b84dcd9bc5e238fbc399bd6e0</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 68e79ff09849f32d0bbe929d94b19d58af7e0850</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 40fbaf4c5446a361269c241d9112fff26575b5d0</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/xgl/icd/api/vk_pipeline.cpp:192:9: error: static assertion failed: Util::Abi::ApiShaderType to Pal::ShaderType mapping does not match!

</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3c700c14e191366f6b72c9b1b7ddcbe30996635c
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 39abe2297ca58a2b84dcd9bc5e238fbc399bd6e0</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 19a031d9f73b95101fd4d3d594aca27c00feb180</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 40fbaf4c5446a361269c241d9112fff26575b5d0</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 64854/64854 (100.0%)</li>
<li>Failed: 0/64854 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 64886/64886 (100.0%)</li>
<li>Failed: 0/64886 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
