### PR TITLE
Test PR. Do not approve.

### PR DESCRIPTION
**Pull request by kuhar**
Do not merge.

### CODE REVIEW

**Comment by kuhar** [comment]
@JaxLinAMD : the rebase action seems to be working when the original PR already contains the rebase action workflow

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0dbc1617ea5a62d097477e774a24172905355193
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 173662704ec193436c8cde216d536775f8cace0a</li>
<li>SPVGEN: dev 79f8e32dd7242d7d34fa0074f761c9d794f11811</li>
<li>XGL: dev 45a98d826d546e6829a021268ff0c599150411cb</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 7da5ed485404334756d765594dd151e1ad31af55</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/225557)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30786/56392 (54.6%)</li>
<li>Failed: 0/56392 (0.0%)</li>
<li>Not Supported: 25606/56392 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30785/56392 (54.6%)</li>
<li>Failed: 0/56392 (0.0%)</li>
<li>Not Supported: 25607/56392 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30917/56381 (54.8%)</li>
<li>Failed: 0/56381 (0.0%)</li>
<li>Not Supported: 25464/56381 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34387/56392 (61.0%)</li>
<li>Failed: 0/56392 (0.0%)</li>
<li>Not Supported: 22005/56392 (39.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
ok, thank you !

**Pull request closed without merging**
