### PR TITLE
llpc: export more variables to shader module data

### PR DESCRIPTION
**Pull request by amingriyue**
1. export entry name and pushConstant size
2. fix issue when getting fsOutInfo
3. reverse set/binding/arraysize order in std::set
4. collect compute pipeline layout

Signed-off-by: Chunming Zhou <david1.zhou@amd.com>

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3df65df95defe75d82ec71cf8fd46ccb5d41c9f5
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 831f334a9f4ef429b5d4e953b86b4624a7c2db54</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 54a1ba508fd82ed2a11d0960f0f2f35f975b2f12</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev cc0df5ace776584f5f7c0c20704d28f445f0e074</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4aa410cfd9e01a41fa1f7d1048a9a79f1c2acea8
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 831f334a9f4ef429b5d4e953b86b4624a7c2db54</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 54a1ba508fd82ed2a11d0960f0f2f35f975b2f12</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev cc0df5ace776584f5f7c0c20704d28f445f0e074</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit fcf41b69d32d042de2ee801ebc0ed9a288ce0846
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 831f334a9f4ef429b5d4e953b86b4624a7c2db54</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 54a1ba508fd82ed2a11d0960f0f2f35f975b2f12</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev cc0df5ace776584f5f7c0c20704d28f445f0e074</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amingriyue** [comment]
Ping...

**Comment by nhaehnle** [comment]
I'm still a bit concerned about this overall design of exporting the information to the user of LLPC. I understand that in the design of pipeline auto-layout, the guessing of a likely layout is going to be API-specific and therefore needs to form part of LLPC's input, but the fact that it's also part of LLPC's output smells wrong to me. It suggests that the caching design is more complicated than it should be.

**Comment by trenouf** [comment]
Is this for caching? Surely all you need for caching is already in the IR module for the shader. You shouldn't need to export anything else.

**Comment by amingriyue** [comment]
I think the background of design to export is to give shader cache a hint to hit when creating the whole pipeline, and also interfaces can be shared by scpc compiler.

**Pull request merged**
