### PR TITLE
Remove CS fixed layout user data support

### PR DESCRIPTION
**Pull request by trenouf**
It is only required for PAL version < 624.
    
Change-Id: I5a6f7f8ffe7a949be790767ecae41a367ab21c97

### CODE REVIEW

**Comment by trenouf** [comment]
Only the topmost commit "Remove CS fixed layout user data support" belongs to this PR. The other commit is from a different PR.

**Comment by amdvlk-admin** [comment]
### Test summary for commit fe25af8f5ebcf1fca8403704d4170b25968126d1
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 007816f4bd2fd3ace30f8af9629cff7ec1dcb998</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev b25c1eac19f1773b753ed727314aa3cf2c0897dd</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev e09ed8b4a5ed4201e59b8d5dc66e17dd05eca428</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/140859)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26166/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20794/46960 (44.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26165/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20795/46960 (44.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24702/46939 (52.6%)</li>
<li>Failed: 0/46939 (0.0%)</li>
<li>Skipped: 22237/46939 (47.4%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
V2: Remove more thoroughly.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 13584eb6d8ce223d6c078f66f1b0c29268986ab9
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 007816f4bd2fd3ace30f8af9629cff7ec1dcb998</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev b25c1eac19f1773b753ed727314aa3cf2c0897dd</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev e09ed8b4a5ed4201e59b8d5dc66e17dd05eca428</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/140859)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26166/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20794/46960 (44.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26164/46960 (55.7%)</li>
<li><details><summary>Failed: 1/46960 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.depth.nocolor.format.d16_unorm_s8_uint_separate_layouts.compare_ops.not_equal_always_always_equal_depth_bounds_test
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 20795/46960 (44.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24702/46939 (52.6%)</li>
<li>Failed: 0/46939 (0.0%)</li>
<li>Skipped: 22237/46939 (47.4%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
That's a single flake.

**Comment by trenouf** [comment]
V3: Rebase, and remove even more thoroughly.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4a1a774e7e576e3ff9d968d6f8b92f2d1c6825d3
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 007816f4bd2fd3ace30f8af9629cff7ec1dcb998</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev b25c1eac19f1773b753ed727314aa3cf2c0897dd</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev e09ed8b4a5ed4201e59b8d5dc66e17dd05eca428</li>
</ul></details>

<details><summary>CTS tests (Failed: 3/140859)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26166/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20794/46960 (44.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26164/46960 (55.7%)</li>
<li><details><summary>Failed: 2/46960 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.external.semaphore.opaque_win32.import_multiple_times_temporary
Stack trace: Flake

FAILURE: dEQP-VK.pipeline.blend.format.b4g4r4a4_unorm_pack16.states.color_z_1mdc_rsub_alpha_1msa_cc_sub-color_da_1msc_min_alpha_1msc_sc_add-color_sa_sas_add_alpha_z_o_sub-color_dc_1msc_max_alpha_sa_da_sub
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 20794/46960 (44.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24701/46939 (52.6%)</li>
<li><details><summary>Failed: 1/46939 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ubo.single_struct.single_buffer.std140_instance_array_vertex_comp_access
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 22237/46939 (47.4%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
"Remove CS fixed layout user data support" looks good to me -- hooray for removing code :)

**Comment by trenouf** [comment]
Rebase.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6394db2b6d5e6d4b8c300b0bb79655abd16a472c
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 007816f4bd2fd3ace30f8af9629cff7ec1dcb998</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev b25c1eac19f1773b753ed727314aa3cf2c0897dd</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev e09ed8b4a5ed4201e59b8d5dc66e17dd05eca428</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/140859)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26166/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20794/46960 (44.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26165/46960 (55.7%)</li>
<li>Failed: 0/46960 (0.0%)</li>
<li>Skipped: 20795/46960 (44.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24702/46939 (52.6%)</li>
<li>Failed: 0/46939 (0.0%)</li>
<li>Skipped: 22237/46939 (47.4%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Comment by trenouf** [comment]
V4: Remove now-unneeded mustSpill flag.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4dd92564108ec7c36759f198f0c4e869cea85263
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 16871e90b0f2e6937aecee415af4d2556384bd7f</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev f623fc7ca78c3cec2123a16700a8819f3ccf0656</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 6d7376cb11eeeb48833cd87a055249b7e0a8d9b5</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/144501)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26321/48174 (54.6%)</li>
<li>Failed: 0/48174 (0.0%)</li>
<li>Skipped: 21853/48174 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26320/48174 (54.6%)</li>
<li>Failed: 0/48174 (0.0%)</li>
<li>Skipped: 21854/48174 (45.4%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24852/48153 (51.6%)</li>
<li>Failed: 0/48153 (0.0%)</li>
<li>Skipped: 23301/48153 (48.4%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
Out of disk space failure. Everything else passed.

**Pull request merged**
