### PR TITLE
Change LLPC interface version

### PR DESCRIPTION
**Pull request by yjaelex**
It is missed by last commit. Set it to 33.

### CODE REVIEW

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdrexu** [comment]
I encounter a crash when I enable the interface version 33. So I think there might be a bug when implementing load scalarizer. To reproduce this, update version to 33 and run
amdllpc -v PipelineVsGs_TestBuiltinInOut.pipe
The pipeline is in shader database.

**Comment by amdrexu** [comment]
I will make a patch. We incorrectly handle copy shader when try to get pipeline shader info.

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdrexu** [comment]
Please see this https://github.com/GPUOpen-Drivers/llpc/pull/194. Without this, some tests will crash.

**Comment by amdrexu** [comment]
retest this please

**Comment by JacobHeAMD** [comment]
retest this please

**Pull request merged**
