### PR TITLE
CI test - please do not merge this

### PR DESCRIPTION
**Pull request by mariusz-sikora-at-amd**

### CODE REVIEW

**Comment by mariusz-sikora-at-amd** [comment]
retest this please

**Comment by mariusz-sikora-at-amd** [comment]
retest this please

> The navi31 test hang. 00:39:06 [10240/70485] Pass: 5667 Fail: 0 Skip: 2890 ExpectedFail: 0 UnexpectedPass: 0 Crash: 0 Timeout: 0 Missing: 1683 Flake: 0 Duration: 14:42 Remaining: 1:26:29
> 
> [45807.825062] amdgpu 0000:03:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:6 pasid:32772, for process deqp-vk pid 30362 thread deqp-vk pid 30362) [45807.825071] amdgpu 0000:03:00.0: amdgpu: in page starting at address 0x0000000202e00000 from client 10 [45807.825074] amdgpu 0000:03:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00601A30 [45807.825075] amdgpu 0000:03:00.0: amdgpu: Faulty UTCL2 client ID: SDMA0 (0xd) [45807.825077] amdgpu 0000:03:00.0: amdgpu: MORE_FAULTS: 0x0 [45807.825078] amdgpu 0000:03:00.0: amdgpu: WALKER_ERROR: 0x0 [45807.825079] amdgpu 0000:03:00.0: amdgpu: PERMISSION_FAULTS: 0x3 [45807.825080] amdgpu 0000:03:00.0: amdgpu: MAPPING_ERROR: 0x0 [45807.825081] amdgpu 0000:03:00.0: amdgpu: RW: 0x0 [45817.842120] [drm:amdgpu_job_timedout [amdgpu]] _ERROR_ ring sdma0 timeout, signaled seq=10138559, emitted seq=10138562 [45817.842309] [drm:amdgpu_job_timedout [amdgpu]] _ERROR_ Process information: process deqp-vk pid 30362 thread deqp-vk pid 30362 [45818.866092] [drm:sdma_v6_0_ring_test_ib [amdgpu]] _ERROR_ amdgpu: IB test timed out [45818.866303] amdgpu 0000:03:00.0: amdgpu: IP block:sdma_v6_0 is hung! [45818.866305] amdgpu 0000:03:00.0: amdgpu: GPU reset begin! [45822.866268] amdgpu 0000:03:00.0: amdgpu: failed to suspend display audio [45822.972495] amdgpu 0000:03:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] _ERROR_ ring sdma0 test failed (-110) [45822.972648] amdgpu 0000:03:00.0: amdgpu: soft reset failed, will fallback to full reset! [45825.077531] amdgpu 0000:03:00.0: amdgpu: free PSP TMR buffer [45825.107762] amdkcl: cancel_work function is not supported [45825.107764] amdgpu 0000:03:00.0: amdgpu: MODE1 reset [45825.107768] amdgpu 0000:03:00.0: amdgpu: GPU mode1 reset [45825.108561] amdgpu 0000:03:00.0: amdgpu: GPU smu mode1 reset [45825.618128] amdgpu 0000:03:00.0: amdgpu: GPU reset succeeded, trying to resume

Thanks @qiaojbao , I will re-run it once again and if it will repeat, than I will try to verify it locally.

**Comment by mariusz-sikora-at-amd** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 81c71327f7ccac28f23286d5bb64d9b0e4301769
<details><summary>CTS tests (Failed: 0/277947)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70526 (55.1%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31662/70526 (44.9%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70526 (55.5%)</li>
<li>Failed: 0/70526 (0.0%)</li>
<li>Not Supported: 31412/70526 (44.5%)</li><li>Warnings: 0/70526 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70528 (51.0%)</li>
<li>Failed: 0/70528 (0.0%)</li>
<li>Not Supported: 34569/70528 (49.0%)</li><li>Warnings: 0/70528 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33678/66367 (50.7%)</li>
<li>Failed: 0/66367 (0.0%)</li>
<li>Not Supported: 32689/66367 (49.3%)</li><li>Warnings: 0/66367 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by mariusz-sikora-at-amd** [comment]
This was needed only to test changes in CI.

**Pull request closed without merging**
