### PR TITLE
Update tests to handle new version of llvm

### PR DESCRIPTION
**Pull request by mbrkusanin**
Handle upstream llvm changes for https://reviews.llvm.org/D159084
"InstCombine: Fold is.fpclass(x, fcInf) to fabs+fcmp"

### CODE REVIEW

**Review by dstutt — APPROVED** [review]
Thanks

LGTM

**Comment by amdvlk-admin** [comment]
### Test summary for commit d67dbaf4f34b9bf091f35227e57778f70bf075c9
<details><summary>CTS tests (Failed: 177/209324)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 34560/69779 (49.5%)</li>
<li><details><summary>Failed: 177/69779 (0.3%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.all_formats.color.1d.r16g16b16a16_unorm.r16g16b16a16_unorm.general_optimal_linear
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.simple_tests.mirror_subregions_3d.b8g8r8a8_unorm_linear
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.simple_tests.whole_3d.b8g8r8a8_unorm_linear
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.core.partial_clear_color_attachment.single_layer.r8g8b8a8_sint_200x180
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.mutable_descriptor.single.storage_buffer.update_copy.nonmutable_source.normal_source.pool_same_types.update_after_bind.no_array.vert
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.mutable_descriptor.single.switches.storage_texel_buffer_sampled_image.update_copy.mutable_source.normal_source.pool_expand_types.pre_update.no_array.vert
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_distance.vert.1
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_distance.vert_tess_geom.5_fragmentshader_read
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.alias.u64_to_i64_std140_func_read_write_barrier
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.zero.uint_array_to_uint16_t_dvec4_array_4
Stack trace: Flake

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.shared_memory_blocks.workgroup_size_8x2x8
Stack trace: Flake

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.4_7_2
Stack trace: Flake

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.5_3_3
Stack trace: Flake

FAILURE: dEQP-VK.compute.zero_initialize_workgroup_memory.specialize_workgroup.6_7_4
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.clear_attachments.condition_host_memory_inherited_expect_noop.clear_attachments
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.dispatch.condition_local_memory_secondary_buffer_expect_execution_inverted.dispatch
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.draw.condition_local_memory_expect_execution.draw_indexed_indirect
Stack trace: Flake

FAILURE: dEQP-VK.conditional_rendering.draw_clear.clear.depth.discard_no_invert_full_no_offset_local_memory
Stack trace: Flake

FAILURE: dEQP-VK.descriptor_indexing.combined_image_sampler_with_lod_minNonUniform
Stack trace: Flake

FAILURE: dEQP-VK.fragment_operations.scissor.multi_viewport.scissor_6
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 35042/69779 (50.2%)</li><li>Warnings: 0/69779 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38617/69779 (55.3%)</li>
<li>Failed: 0/69779 (0.0%)</li>
<li>Not Supported: 31162/69779 (44.7%)</li><li>Warnings: 0/69779 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 38651/69766 (55.4%)</li>
<li>Failed: 0/69766 (0.0%)</li>
<li>Not Supported: 31115/69766 (44.6%)</li><li>Warnings: 0/69766 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by mbrkusanin** [comment]
!help

**Comment by dstutt** [comment]
We shouldn't see any CTS test failures since this change is only fixing up (and actually disabling temporarily) 2 tests. Must be unrelated (but I agree the failures seem peculiar).

**Comment by amdvlk-admin** [comment]
### Test summary for commit d67dbaf4f34b9bf091f35227e57778f70bf075c9
<details><summary>CTS tests (Failed: 236/209324)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 34502/69779 (49.4%)</li>
<li><details><summary>Failed: 236/69779 (0.3%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.all_formats.color.1d.r16g16b16a16_unorm.r16g16b16a16_unorm.general_optimal_linear
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.simple_tests.mirror_subregions_3d.b8g8r8a8_unorm_linear
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.simple_tests.scaling_and_offset.b8g8r8a8_unorm_linear
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.blit_image.simple_tests.whole_3d.b8g8r8a8_unorm_linear
Stack trace: Flake

FAILURE: dEQP-VK.api.copy_and_blit.dedicated_allocation.depth_stencil_msaa_copy.whole.s8_uint_general_optimal_S_8_bit
Stack trace: Flake

FAILURE: dEQP-VK.api.image_clearing.core.partial_clear_color_attachment.single_layer.r8g8b8a8_sint_200x180
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.buffer_device_address.set31.depth1.baseubo.convertchecku64.nostore.single.std140.frag
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.buffer_device_address.set31.depth1.baseubo.load.nostore.multi.std140.frag
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.descriptor_copy.compute.storage_image_array2
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.descriptor_update.samplerless.input_attachment_sampler_zero
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.mutable_descriptor.single.storage_buffer.update_copy.nonmutable_source.normal_source.pool_same_types.update_after_bind.no_array.vert
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.mutable_descriptor.single.switches.storage_texel_buffer_sampled_image.update_copy.mutable_source.normal_source.pool_expand_types.pre_update.no_array.vert
Stack trace: Flake

FAILURE: dEQP-VK.binding_model.shader_access.secondary_cmd_buf.with_push.sampler_mutable.fragment.single_descriptor.2d
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_cull_distance.vert_geom.2_6_fragmentshader_read
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_cull_distance.vert_geom.4_4_fragmentshader_read
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_cull_distance.vert_tess.7_1
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_distance.vert.1
Stack trace: Flake

FAILURE: dEQP-VK.clipping.user_defined.clip_distance.vert_tess_geom.5_fragmentshader_read
Stack trace: Flake

FAILURE: dEQP-VK.compute.indirect_dispatch.upload_buffer.small_offset
Stack trace: Flake

FAILURE: dEQP-VK.compute.workgroup_memory_explicit_layout.alias.u64_to_i64_std140_func_read_write_barrier
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 35041/69779 (50.2%)</li><li>Warnings: 0/69779 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38617/69779 (55.3%)</li>
<li>Failed: 0/69779 (0.0%)</li>
<li>Not Supported: 31162/69779 (44.7%)</li><li>Warnings: 0/69779 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 38651/69766 (55.4%)</li>
<li>Failed: 0/69766 (0.0%)</li>
<li>Not Supported: 31115/69766 (44.6%)</li><li>Warnings: 0/69766 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by Flakebi** [comment]
Oh, it got more than before. @qiaojbao, it looks like something is unstable on the gfx10 system.

**Comment by amdvlk-admin** [comment]
### Test summary for commit d67dbaf4f34b9bf091f35227e57778f70bf075c9
<details><summary>CTS tests (Failed: 0/209324)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 34735/69779 (49.8%)</li>
<li>Failed: 0/69779 (0.0%)</li>
<li>Not Supported: 35044/69779 (50.2%)</li><li>Warnings: 0/69779 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38617/69779 (55.3%)</li>
<li>Failed: 0/69779 (0.0%)</li>
<li>Not Supported: 31162/69779 (44.7%)</li><li>Warnings: 0/69779 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 38651/69766 (55.4%)</li>
<li>Failed: 0/69766 (0.0%)</li>
<li>Not Supported: 31115/69766 (44.6%)</li><li>Warnings: 0/69766 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
