### PR TITLE
Run check-continuations in CI

### PR DESCRIPTION
**Pull request by Flakebi**
Add check-continuations to the GitHub Actions workflows.

### CODE REVIEW

**Comment by nhaehnle** [comment]
Doesn't actually pass. Part apart from that it LGTM.

**Comment by Flakebi** [comment]
Rebased and now also runs `check-continuations-units`.

**Comment by amdvlk-admin** [comment]
### Test summary for commit a22df284c7b3abde8b3d26211ae7800e50bfbdbb
<details><summary>CTS tests (Failed: 0/137949)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35353/68947 (51.3%)</li>
<li>Failed: 0/68947 (0.0%)</li>
<li>Not Supported: 33594/68947 (48.7%)</li><li>Warnings: 0/68947 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35424/69002 (51.3%)</li>
<li>Failed: 0/69002 (0.0%)</li>
<li>Not Supported: 33578/69002 (48.7%)</li><li>Warnings: 0/69002 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — DISMISSED** [review]

**Comment by Flakebi** [comment]
Sanitizers found the first bug in continuations :)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3b34a48ffe5138cfed8fc9631d6373a4ce6b3a6a
<details><summary>CTS tests (Failed: 0/137941)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35353/68939 (51.3%)</li>
<li>Failed: 0/68939 (0.0%)</li>
<li>Not Supported: 33586/68939 (48.7%)</li><li>Warnings: 0/68939 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35424/69002 (51.3%)</li>
<li>Failed: 0/69002 (0.0%)</li>
<li>Not Supported: 33578/69002 (48.7%)</li><li>Warnings: 0/69002 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
Nice :)

**Comment by Flakebi** [comment]
Cherry-pick an internal patch to fix tests.

**Review by nhaehnle — APPROVED** [review]
Thanks!

**Comment by Flakebi** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 09ef5e57cbeb752724ec795d5f89504e3528e0fc
<details><summary>CTS tests (Failed: 0/138020)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu navi3x, Srdcvk</summary><ul>

<li>Passed: 35401/69018 (51.3%)</li>
<li>Failed: 0/69018 (0.0%)</li>
<li>Not Supported: 33617/69018 (48.7%)</li><li>Warnings: 0/69018 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu navi2x, Srdcvk</summary><ul>

<li>Passed: 35424/69002 (51.3%)</li>
<li>Failed: 0/69002 (0.0%)</li>
<li>Not Supported: 33578/69002 (48.7%)</li><li>Warnings: 0/69002 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
