### PR TITLE
Move LGC into its own directory

### PR DESCRIPTION
**Pull request by trenouf**
This commit moves LGC (LLPC middle-end) code into its own lgc directory.

There may be future commits to change the filenames and directory
structure within LGC.

Change-Id: I4c4c3f77b32c90182e0ad791e642c37f0e9a6afc

### CODE REVIEW

**Comment by trenouf** [comment]
New version with the extra two commits to remove LGC's PAL dependencies, and also to build LGC as an LLVM external project (which will make it easier to add lit tests).

**Comment by trenouf** [comment]
Fixes from internal testing.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b1f9ef58b7b108a1bd42d7a17244c27bcd800756
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev bb7398b1c7509a30ba4f7d947b5ad5549a4d58db</li>
<li>SPVGEN: dev b30c124e7a042c5251aeb20780a83089355e74a1</li>
<li>XGL: dev ffd39443fec0ce821b7702173eba7184855c7b5e</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1ebc431ac299fa294a4e730432520d37f326843c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 960/960 (100.0%)</li>
<li>Failed: 0/960 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103137/103137 (100.0%)</li>
<li>Failed: 0/103137 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 43257/43258 (100.0%)</li>
<li><details><summary>Failed: 1/43258 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.spirv_assembly.type.vec4.u64.shift_left_logical_shift64_tesse
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by trenouf** [comment]
retest this please

**Comment by trenouf** [comment]
Rebased, and added "Fixed up spurious diffs" commit to make the rebase go more smoothly.

**Pull request merged**
