### PR TITLE
Some coding changes in ShaderMerger

### PR DESCRIPTION
**Pull request by amdrexu**
1. Use vector to argument addressing in merger shader. This is more clear.
2. Some VGPR semantics are changed in the future generation. Try to make preliminary change.
3. Do some renaming to make variable meanings more specific.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3bac4b799e1f89f6a0ef8fe13067584e96e379ae
<details><summary>CTS tests (Failed: 0/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70485 (55.1%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70485 (55.5%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4c96639fb0806d746e5ed41ad3912636c62fcb68
<details><summary>CTS tests (Failed: 0/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70485 (55.1%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70485 (55.5%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 63440196e45bf7736340702be77fbf55c08aaaf1
<details><summary>CTS tests (Failed: 2/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38862/70485 (55.1%)</li>
<li><details><summary>Failed: 2/70485 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.memory.pipeline_barrier.all.1048576_vertex_buffer_stride_2
Stack trace: Timeout

FAILURE: dEQP-VK.memory.pipeline_barrier.all.65536_vertex_buffer_stride_2
Stack trace: Timeout
```
</p></details></li>

<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70485 (55.5%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 63440196e45bf7736340702be77fbf55c08aaaf1
<details><summary>CTS tests (Failed: 1/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70485 (55.1%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39113/70485 (55.5%)</li>
<li><details><summary>Failed: 1/70485 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.0_00
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 63440196e45bf7736340702be77fbf55c08aaaf1
<details><summary>CTS tests (Failed: 0/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70485 (55.1%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70485 (55.5%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
LGTM

**Pull request merged**
