### PR TITLE
Fix for removal of ElementCount constructors in upstream LLVM.

### PR DESCRIPTION
**Pull request by perlfu**
Replace implicit ElementCount objects with ElementCount::get().

### CODE REVIEW

**Review by amdrexu — APPROVED** [review]

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by jayfoad** [comment]
There's no point testing this yet. It won't compile until https://github.com/llvm/llvm-project/commit/264afb9e6aebc98c353644dd0700bec808501cab has been merged into https://github.com/GPUOpen-Drivers/llvm-project.

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
just to confirm, I will merge it when build pass

**Comment by dstutt** [comment]
retest this please

**Comment by Flakebi** [comment]
Reopening, I assume Tim did not plan to close this by mentioning this fix.

**Comment by amdvlk-admin** [comment]
### Test summary for commit e1f69da9901a09e56a1151a0c9c9930ac1c23d21
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 9074bd0bdaf67fa84399dfabed3ec437951838f8</li>
<li>SPVGEN: dev c054813a9a894e32aaaa04c6717a667c15f60cfd</li>
<li>XGL: dev 598c6832a4983f5b75b38a589fca5be80a2f3bb0</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 18263376524150c0db067a1061003d1a8140aa5b</li>
</ul></details>

<details><summary>CTS tests (Failed: 4/131648)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43887 (51.9%)</li>
<li>Failed: 0/43887 (0.0%)</li>
<li>Skipped: 21103/43887 (48.1%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22783/43891 (51.9%)</li>
<li>Failed: 0/43891 (0.0%)</li>
<li>Skipped: 21108/43891 (48.1%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21605/43870 (49.2%)</li>
<li><details><summary>Failed: 4/43870 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.all_unordered_and_missing.56
Stack trace: Flake

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.basic_arrays.11
Stack trace: Flake

FAILURE: dEQP-VK.transform_feedback.fuzz.random_geometry.basic_instance_arrays.21
Stack trace: Fail

FAILURE: dEQP-VK.transform_feedback.fuzz.single_basic_type.dmat3x4.geometry
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 22261/43870 (50.7%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
wait for llvm come into internal branch , then merge

**Pull request merged**
