### PR TITLE
For CI test.

### PR DESCRIPTION
**Pull request by qiaojbao**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit b2e1a1c4f6260a380fd829885fbf98d9047e853d
<details><summary>CTS tests (Failed: 3/207298)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39111/70485 (55.5%)</li>
<li><details><summary>Failed: 3/70485 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.0_00
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.max
Stack trace: Fail

FAILURE: dEQP-VK.rasterization.conservative.overestimate.samples_8.triangles.degenerate.min
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b2e1a1c4f6260a380fd829885fbf98d9047e853d
<details><summary>CTS tests (Failed: 0/277243)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38849/70350 (55.2%)</li>
<li>Failed: 0/70350 (0.0%)</li>
<li>Not Supported: 31501/70350 (44.8%)</li><li>Warnings: 0/70350 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39099/70350 (55.6%)</li>
<li>Failed: 0/70350 (0.0%)</li>
<li>Not Supported: 31251/70350 (44.4%)</li><li>Warnings: 0/70350 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35944/70352 (51.1%)</li>
<li>Failed: 0/70352 (0.0%)</li>
<li>Not Supported: 34408/70352 (48.9%)</li><li>Warnings: 0/70352 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33663/66191 (50.9%)</li>
<li>Failed: 0/66191 (0.0%)</li>
<li>Not Supported: 32528/66191 (49.1%)</li><li>Warnings: 0/66191 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — CHANGES_REQUESTED** [review]
Just to make sure it isn't merged accidentally.

**Comment by amdvlk-admin** [comment]
### Test summary for commit b2e1a1c4f6260a380fd829885fbf98d9047e853d
<details><summary>CTS tests (Failed: 1/277243)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38849/70350 (55.2%)</li>
<li>Failed: 0/70350 (0.0%)</li>
<li>Not Supported: 31501/70350 (44.8%)</li><li>Warnings: 0/70350 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39098/70350 (55.6%)</li>
<li><details><summary>Failed: 1/70350 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.spirv_assembly.type.vec4.u16.ulessthan_tesse
Stack trace: Flake
```
</p></details></li>

<li>Not Supported: 31251/70350 (44.4%)</li><li>Warnings: 0/70350 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35944/70352 (51.1%)</li>
<li>Failed: 0/70352 (0.0%)</li>
<li>Not Supported: 34408/70352 (48.9%)</li><li>Warnings: 0/70352 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33663/66191 (50.9%)</li>
<li>Failed: 0/66191 (0.0%)</li>
<li>Not Supported: 32528/66191 (49.1%)</li><li>Warnings: 0/66191 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b2e1a1c4f6260a380fd829885fbf98d9047e853d
<details><summary>CTS tests (Failed: 0/277783)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38864/70485 (55.1%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31621/70485 (44.9%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39114/70485 (55.5%)</li>
<li>Failed: 0/70485 (0.0%)</li>
<li>Not Supported: 31371/70485 (44.5%)</li><li>Warnings: 0/70485 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70487 (51.0%)</li>
<li>Failed: 0/70487 (0.0%)</li>
<li>Not Supported: 34528/70487 (49.0%)</li><li>Warnings: 0/70487 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.6, Gfx9</summary><ul>

<li>Passed: 33678/66326 (50.8%)</li>
<li>Failed: 0/66326 (0.0%)</li>
<li>Not Supported: 32648/66326 (49.2%)</li><li>Warnings: 0/66326 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request closed without merging**
