### PR TITLE
NGG: Resolve issues caught by tests "OverestimateTriangleDegenerate"

### PR DESCRIPTION
**Pull request by amdrexu**
1. According to Vulkan spec, any triangle which is not front-facing
   is back-facing, including zero-area triangles. We have a test that
   produces a degenerate triangle by "gl_Position = vec4(x, y, 0.0,
   1.0)". In this case, all three vertices take the same coordinates
   of x and y, resulting in a zero-area. This case is in conservative
   rasterization mode and the cull mode is set to "disable front and
   back cull". Thus, the expectation is this triangle should not be
   culled. We remove zero-area check in backface culling algorithm
   and treat it as a part of back cull.

2. Culling-control register fetch uses "volatile" load. This is to
   generate "s_load_" in LLVM backend. Initially, backend might
   translate non-volatile loads to global loads. This is unexpected
   and is performance-harmful. The problem is gone now.

3. Set "afn" as fast math flags in NGG IR builder. After LLVM
   promotion. Translating "fdiv(1.0/x)" to "rcp(x)" depends on this.
   Thus, unexpected "div" instructions will be produced.

4. Also, fix some comment issues.

Change-Id: I13dac663f79cfcb10c60cc2ff86b1c48ef509e1f

### CODE REVIEW

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b17cf2b26997cc01ab989a26acf8c9a43d99416e
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 7ce7cdb9b22229245c7c0e836584561baeb8f776</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Ellesmere</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b17cf2b26997cc01ab989a26acf8c9a43d99416e
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev a3a42838c576cc219e61500bc469a4a05ce0db68</li>
<li>SPVGEN: dev a25eab81bf58bc6a95e178d44db16c48e8bf7da1</li>
<li>XGL: dev c7b65e3a8497318edd4ff1c290fbfa47398090d7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 7ce7cdb9b22229245c7c0e836584561baeb8f776</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 979/979 (100.0%)</li>
<li>Failed: 0/979 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 142137/142137 (100.0%)</li>
<li>Failed: 0/142137 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Ellesmere</summary><ul>

<li>Passed: 142043/142043 (100.0%)</li>
<li>Failed: 0/142043 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
