### PR TITLE
Support `R8G8B8` vertex attribute formats

### PR DESCRIPTION
**Pull request by AMD-dwang**
RGB_8_8_8 are the same as _8_8_8_8 which are not supported by HW, we

regard them as _8_8_8_8, just the number of channels will be 3.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3d405d3e3f84661d054369b90b3b9b3a3046fdef
<details><summary>CTS tests (Failed: 0/205121)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 36341/68158 (53.3%)</li>
<li>Failed: 0/68158 (0.0%)</li>
<li>Not Supported: 31817/68158 (46.7%)</li><li>Warnings: 0/68158 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 36569/68158 (53.7%)</li>
<li>Failed: 0/68158 (0.0%)</li>
<li>Not Supported: 31589/68158 (46.3%)</li><li>Warnings: 0/68158 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 34225/68805 (49.7%)</li>
<li>Failed: 0/68805 (0.0%)</li>
<li>Not Supported: 34580/68805 (50.3%)</li><li>Warnings: 0/68805 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — COMMENTED** [review]
I think it would be better to keep `getVertexFormatInfo` as-is, and instead change the logic at the top of `addVertexFetchInst` to make sure we take the per-component-fetch path.

**Comment by AMD-dwang** [comment]
> I think it would be better to keep `getVertexFormatInfo` as-is, and instead change the logic at the top of `addVertexFetchInst` to make sure we take the per-component-fetch path.

Updated. Thanks.

**Comment by amdvlk-admin** [comment]
### Test summary for commit f70a8d1d4590f4bf008a2ac884da9e97c32a9c41
<details><summary>CTS tests (Failed: 0/205121)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 36341/68158 (53.3%)</li>
<li>Failed: 0/68158 (0.0%)</li>
<li>Not Supported: 31817/68158 (46.7%)</li><li>Warnings: 0/68158 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 36569/68158 (53.7%)</li>
<li>Failed: 0/68158 (0.0%)</li>
<li>Not Supported: 31589/68158 (46.3%)</li><li>Warnings: 0/68158 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 34225/68805 (49.7%)</li>
<li>Failed: 0/68805 (0.0%)</li>
<li>Not Supported: 34580/68805 (50.3%)</li><li>Warnings: 0/68805 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — APPROVED** [review]
Thanks!

**Pull request merged**
