### PR TITLE
Fix some typos in comments and in option descriptions.

### PR DESCRIPTION
**Pull request by tsymalla**
Fixes some typos, one of them being in the description text of the `check-auto-layout-compatible` option.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JaxLinAMD** [comment]
ok to test

**Review by amdrexu — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8c0ec8be9f408ac5d6a46eb64e2bf934ac23014a
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev de5f376ca30a108f1fc1fd5cdf33fdfe9f9d5dbb</li>
<li>SPVGEN: dev 5bf4618ac00d4675f57ca5b571a485bbc4d4fa33</li>
<li>XGL: dev d81362ec6baf91a98895572d721ce7497efc8eeb</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev f4a2a23c8dd892c93384572bf0699ec3566e0e17</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/225198)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30577/56304 (54.3%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 25727/56304 (45.7%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30577/56304 (54.3%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 25727/56304 (45.7%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30682/56286 (54.5%)</li>
<li>Failed: 0/56286 (0.0%)</li>
<li>Not Supported: 25604/56286 (45.5%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34150/56304 (60.7%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 22154/56304 (39.3%)</li>
</ul></details>


</ul></details>

**Comment by tsymalla** [comment]
> @tsymalla The code review convention requires to submit one commit per PR. When you want to make changes to an existing PR, you can simply rebase/amend and then force-push. See https://github.com/GPUOpen-Drivers/llpc/blob/dev/docs/ReviewProcess.md#address-review-comments

Will re-do this, somehow my git history got messed up locally.

**Comment by kuhar** [comment]
> Will re-do this, somehow my git history got messed up locally.
You could also use `git rebase -i HEAD~2` and mark the new commit as `fixup`, and then force-push. No need to move to a new PR.

**Pull request closed without merging**
