### PR TITLE
Move utility code out of amdllpc.cpp. NFCI. (Do not merge)

### PR DESCRIPTION
**Pull request by kuhar**
The high level goal is to make the code in `amdllpc.cpp` reusable so that can create new compiler tools based on the same
common logic, and to be able to test parts of that logic with unit tests.

This shared code lives in a new library: `llpc_standalone_compiler`, which `amdllpc` and the unit tests link with.
The goal is to keep this library free of global state (including command line options).

I tried keep the changes to the code minimal. I only simplified some of the input utils, and added unit tests for all
functions that I modified beyond stylistic changes.

In the future PRs, I plan to move more code out of `amdllpc.cpp`.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit ec1672ee9eee5a04cd1c5a8088fb320adb9b37d5
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev cd4f8b28b5d923e8d65a1ef1d3dee5137a89d6bd</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev 133ef76a809deb8078ebdbacea4d9b8bfe5dad93</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 02a00c5cd4463687bf52d043ed3b7caa14374689</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/228848)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 32108/57212 (56.1%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 25104/57212 (43.9%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 32108/57212 (56.1%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 25104/57212 (43.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 32488/57212 (56.8%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 24724/57212 (43.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 35419/57212 (61.9%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 21793/57212 (38.1%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
V3: Rebase

**Comment by amdvlk-admin** [comment]
### Test summary for commit 46bf417ae8f6bc6cd3a82ccbb5c554be9f568ca8
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev cd4f8b28b5d923e8d65a1ef1d3dee5137a89d6bd</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev 133ef76a809deb8078ebdbacea4d9b8bfe5dad93</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 02a00c5cd4463687bf52d043ed3b7caa14374689</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/228848)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 32108/57212 (56.1%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 25104/57212 (43.9%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 32106/57212 (56.1%)</li>
<li><details><summary>Failed: 2/57212 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.memory.pipeline_barrier.all.1048576_vertex_buffer_stride_2
Stack trace: Script:
47:HostMemoryAccess Result differs from reference, Expected: 0x00000094, Got: 0x0000008d, At offset: 18982


FAILURE: dEQP-VK.memory.pipeline_barrier.all.1048576_vertex_buffer_stride_4
Stack trace: Script:
3:HostMemoryAccess Result differs from reference, Expected: 0x000000a8, Got: 0x000000bb, At offset: 504450

```
</p></details></li>

<li>Not Supported: 25104/57212 (43.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 32488/57212 (56.8%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 24724/57212 (43.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 35419/57212 (61.9%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 21793/57212 (38.1%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b95daa34001be49d4e124776348ee44315fd0edf
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev cd4f8b28b5d923e8d65a1ef1d3dee5137a89d6bd</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev b78601f5e66f80505bce5222fbd92f4e27e704c2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 02a00c5cd4463687bf52d043ed3b7caa14374689</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/228848)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 32108/57212 (56.1%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 25104/57212 (43.9%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 32108/57212 (56.1%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 25104/57212 (43.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 32488/57212 (56.8%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 24724/57212 (43.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 35419/57212 (61.9%)</li>
<li>Failed: 0/57212 (0.0%)</li>
<li>Not Supported: 21793/57212 (38.1%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2b77e5c6573ac8cc8fe1733079b3b8ae17f6c54c
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev cd4f8b28b5d923e8d65a1ef1d3dee5137a89d6bd</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev b78601f5e66f80505bce5222fbd92f4e27e704c2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fd071e5c2971c07fd4cd4b22c69f7bc0d6ddc59b</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/221024)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31436/55256 (56.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 23820/55256 (43.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34187/55256 (61.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 21069/55256 (38.1%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0929a127a09cc0abc1c4a0f43825c22444ba49e9
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev cd4f8b28b5d923e8d65a1ef1d3dee5137a89d6bd</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev b78601f5e66f80505bce5222fbd92f4e27e704c2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fd071e5c2971c07fd4cd4b22c69f7bc0d6ddc59b</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/210064)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 28695/44296 (64.8%)</li>
<li><details><summary>Failed: 1/44296 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.subgroups.clustered.graphics.subgroupclusteredmul_uint16_t
Stack trace: Script:
Crash

```
</p></details></li>

<li>Not Supported: 15600/44296 (35.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31436/55256 (56.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 23820/55256 (43.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34187/55256 (61.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 21069/55256 (38.1%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
V4: Rebase

**Comment by amdvlk-admin** [comment]
### Test summary for commit 29030ed80396817f52850d976744829f29398e44
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev cd4f8b28b5d923e8d65a1ef1d3dee5137a89d6bd</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev eecbf8b682753c266cac6b2d1f3032733e5d2049</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 68e5420f0ba94be9cae6fbac848d746592d03f42</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/221024)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31436/55256 (56.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 23820/55256 (43.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34187/55256 (61.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 21069/55256 (38.1%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9c6e5a70ee5fae71e39094b6885709fc89bc0a92
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev cd4f8b28b5d923e8d65a1ef1d3dee5137a89d6bd</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev eecbf8b682753c266cac6b2d1f3032733e5d2049</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 68e5420f0ba94be9cae6fbac848d746592d03f42</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/221024)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31062/55256 (56.2%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 24194/55256 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31436/55256 (56.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 23820/55256 (43.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34187/55256 (61.9%)</li>
<li>Failed: 0/55256 (0.0%)</li>
<li>Not Supported: 21069/55256 (38.1%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit b64d609d76508d73ee0b91002ec75ef6ce4b57fa
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev ad24e368a2e7a0dcebef9b18af68893051cda329</li>
<li>SPVGEN: dev 8705e87a8b4aaed55a89f79ed423612ca310bfdd</li>
<li>XGL: dev 7e2070be478a90852ca88c2aee36406b9d19c861</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 8207d5d4fbe8b5848ad54eee18977b5ab5aaa48e</li>
</ul></details>

<details><summary>CTS tests (Failed: 473/221132)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31197/55283 (56.4%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 24086/55283 (43.6%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31196/55283 (56.4%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 24087/55283 (43.6%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31067/55283 (56.2%)</li>
<li><details><summary>Failed: 473/55283 (0.9%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole.2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole.4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole.8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.partial.2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.partial.4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.partial.8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.with_regions.2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.with_regions.4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.with_regions.8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole_copy_before_resolving.4_bit
Stack trace: Script:
Intermediate verification failed for coordinates (0, 0) sample 0


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole_copy_before_resolving.8_bit
Stack trace: Script:
Intermediate verification failed for coordinates (0, 0) sample 0


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole_array_image.4_bit
Stack trace: Script:
Intermediate verification failed for coordinates (24, 24) sample 0


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.whole_array_image.8_bit
Stack trace: Script:
Intermediate verification failed for coordinates (52, 52) sample 0


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_266_256_1_2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_266_256_1_4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_266_256_1_8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_512_1_2_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_512_1_4_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_512_1_8_bit
Stack trace: Script:
CopiesAndBlitting test


FAILURE: dEQP-VK.api.copy_and_blit.core.resolve_image.diff_image_size.src_256_256_11_2_bit
Stack trace: Script:
CopiesAndBlitting test

...
```
</p></details></li>

<li>Not Supported: 23743/55283 (42.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34313/55283 (62.1%)</li>
<li>Failed: 0/55283 (0.0%)</li>
<li>Not Supported: 20970/55283 (37.9%)</li>
</ul></details>


</ul></details>

**Pull request closed without merging**
