### PR TITLE
Re-enable LGC test disabled for LLVM update

### PR DESCRIPTION
**Pull request by perlfu**
Re-enable CsBuiltIns test disabled in #1844.

### CODE REVIEW

**Comment by perlfu** [comment]
This will not pass yet as LLVM backend is not yet at the right version.
Just creating this PR now so it is not forgotten.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 583db4b390e1c3099ea16c3f665a133eeee81b67
<details><summary>CTS tests (Failed: 0/186371)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 36631/65208 (56.2%)</li>
<li>Failed: 0/65208 (0.0%)</li>
<li>Not Supported: 28577/65208 (43.8%)</li><li>Warnings: 0/65208 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 29989/55953 (53.6%)</li>
<li>Failed: 0/55953 (0.0%)</li>
<li>Not Supported: 25964/55953 (46.4%)</li><li>Warnings: 0/55953 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 38930/65210 (59.7%)</li>
<li>Failed: 0/65210 (0.0%)</li>
<li>Not Supported: 26280/65210 (40.3%)</li><li>Warnings: 0/65210 (0.0%)</li>
</ul></details>


</ul></details>

**Review by dstutt — APPROVED** [review]
LGTM
I guess you'll monitor the llvm version and merge when ready?

**Comment by perlfu** [comment]
Great, thanks!
When the correct LLVM version goes in we can rerun the tests and then merge.

**Comment by Flakebi** [comment]
This test has been re-enabled and now sits in `lgc/test/BuiltIns/cs-subgroupid.lgc`, so I’ll close this.

**Pull request closed without merging**
