### PR TITLE
Revert "Set the afn (ApproxFunc) fast-math flag."

### PR DESCRIPTION
**Pull request by trenouf**
That change causes conformance test failures in AMD internal builds:
dEQP-VK.glsl.builtin.precision_double.smoothstep.compute.scalar
dEQP-VK.glsl.builtin.precision_double.smoothstep.compute.vec2
dEQP-VK.glsl.builtin.precision_double.smoothstep.compute.vec3
dEQP-VK.glsl.builtin.precision_double.smoothstep.compute.vec4
dEQP-VK.glsl.builtin.precision_double.inverse.compute.mat2

Reverts PR #656.

Change-Id: Ib551ce26481245e87ffaa8252723ad48b1a909ba

### CODE REVIEW

**Comment by trenouf** [comment]
(I have already merged this in our internal branch.)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 06035b37ebb5058f0733597270525fc7343d6370
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev ddcaa1009ecde219613042a5a53c6d3752bf4b9d</li>
<li>SPVGEN: dev d4817ab957f79762da83b7fc1d3f2816dbdc13fd</li>
<li>XGL: dev 2ecd2e14e2ae4f2712df4a2220e2dd36265c66d1</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 53692d985a53a336e07907c2d4b86bf2deb66908</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 959/959 (100.0%)</li>
<li>Failed: 0/959 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103143/103143 (100.0%)</li>
<li>Failed: 0/103143 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103199/103199 (100.0%)</li>
<li>Failed: 0/103199 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 103199/103199 (100.0%)</li>
<li>Failed: 0/103199 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
> Do we know why this causes failures? Is the approximation expected? Or maybe we forget to check something additional provided by SPIR-V in front-end when use "afn" flags.

No, I don't know. I'll leave that to Jay to investigate.

**Comment by jayfoad** [comment]
> Do we know why this causes failures? Is the approximation expected? Or maybe we forget to check something additional provided by SPIR-V in front-end when use "afn" flags.

It's because the afn attribute enables another optimization where instruction selection replaces division with multiplication by (approximate) reciprocal. Apparently this changes the results and makes some CTS tests fail.

When I run CTS locally, 21 dEQP-VK.glsl.builtin.precision_double.* tests fail anyway. Setting afn just adds 5 more, so 26 failures in total. I wonder how we deal with the others.

**Comment by amdrexu** [comment]
> Setting afn just adds 5 more, so 26 failures in total. I wonder how we deal with the others.

You can file an issue ticket with "Vulkan Windows" triage to Mais Alnasser, cc Maciej Jesionowski, mention you encounter CTS failures.

**Pull request merged**
