### PR TITLE
Promote llvm-dialects

### PR DESCRIPTION
**Pull request by tsymalla**
Promotion to [e7464fe](https://github.com/GPUOpen-Drivers/llvm-dialects/commit/e7464fe)

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by nhaehnle** [comment]
ok to test

**Review by nhaehnle — APPROVED** [review]
LGTM

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2fd7039f9858fc903db135dfee7f5336d41d29ce
<details><summary>CTS tests (Failed: 0/142050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71030 (56.9%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 30604/71030 (43.1%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71020 (57.0%)</li>
<li>Failed: 0/71020 (0.0%)</li>
<li>Not Supported: 30556/71020 (43.0%)</li><li>Warnings: 0/71020 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 2fd7039f9858fc903db135dfee7f5336d41d29ce
<details><summary>CTS tests (Failed: 0/142050)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40426/71030 (56.9%)</li>
<li>Failed: 0/71030 (0.0%)</li>
<li>Not Supported: 30604/71030 (43.1%)</li><li>Warnings: 0/71030 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40464/71020 (57.0%)</li>
<li>Failed: 0/71020 (0.0%)</li>
<li>Not Supported: 30556/71020 (43.0%)</li><li>Warnings: 0/71020 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
