### PR TITLE
Removed clearFastMathFlags TODOs

### PR DESCRIPTION
**Pull request by trenouf**
The previous commit "Consistently set FMF in builder" attempted to not
    have any generated code changes by adding some clearFastMathFlags, with
    some TODOs to remove them. This commit removes them, making more FP
    operations have fast math flags.

### CODE REVIEW

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by trenouf** [comment]
V2: Rebased on target-aware TLI fix.

**Comment by trenouf** [comment]
V3: Revert last commit's test fixup, as optimizing pow(2.0,x) to
        llvm.exp2 works again.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 498a4f19f3f33e6241d137cd9a2eca2f707a8aba
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 88d997710b4e405f3a8e3fd60a38afee9e3e77e2</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 2cb5558b94c5dc839e093cb439057a1802426c8e</li>
<li>LLVM: amd-vulkan-dev 1fc1a7d4248b4749c3df21eb48f7ae97b6cddf74</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 927/927 (100.0%)</li>
<li>Failed: 0/927 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 68331/68331 (100.0%)</li>
<li>Failed: 0/68331 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 68363/68363 (100.0%)</li>
<li>Failed: 0/68363 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
