### PR TITLE
Add  LLPC_INTERFACE_MAJOR_VERSION

### PR DESCRIPTION
**Pull request by linqun**
1. Add  LLPC_INTERFACE_MAJOR_VERSION to support LLPC github overlay build

2. LLPC interface change
- Add entryStage in PipelineShaderInfo
- Refine IPipelineDumper::BeginPipelineDump

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3cc355ef35234072876e7dd639a7d548369a4471
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 94501ac9adc214f5c61de042205929eb8681d175</li>
<li>SPVGEN: dev 59095d3469e4fb7506da0e3d0cd78904ed71682f</li>
<li>XGL: dev f2af4b0c33963842f544107d005f0a6c82ea513f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:268:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:459:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:468:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:268:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:459:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:468:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:268:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:459:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:468:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:268:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:459:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:468:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:268:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:459:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:468:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:268:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:459:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:468:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:268:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:459:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:468:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:268:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:459:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/include/llpc.h:468:41: error: operator '>=' has no left operand
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/util/llpcPipelineDumper.h:69:48: error: ‘PipelineBuildInfo’ has not been declared
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/util/llpcPipelineDumper.h:84:48: error: ‘PipelineBuildInfo’ has not been declared

</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6681ce20c90274263ce904b4567beb742e65db49
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 94501ac9adc214f5c61de042205929eb8681d175</li>
<li>SPVGEN: dev 59095d3469e4fb7506da0e3d0cd78904ed71682f</li>
<li>XGL: dev f2af4b0c33963842f544107d005f0a6c82ea513f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details><summary>Build Failed</summary><ul>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit d8e8eccf46edda85701fd2ed2476f00e9e361211
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 94501ac9adc214f5c61de042205929eb8681d175</li>
<li>SPVGEN: dev 59095d3469e4fb7506da0e3d0cd78904ed71682f</li>
<li>XGL: dev f2af4b0c33963842f544107d005f0a6c82ea513f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/util/llpcPipelineDumper.h:69:48: error: ‘PipelineBuildInfo’ has not been declared
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/util/llpcPipelineDumper.h:84:48: error: ‘PipelineBuildInfo’ has not been declared

</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3f955ea6b8860a0d73abff208751a7097520af8a
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 94501ac9adc214f5c61de042205929eb8681d175</li>
<li>SPVGEN: dev 59095d3469e4fb7506da0e3d0cd78904ed71682f</li>
<li>XGL: dev f2af4b0c33963842f544107d005f0a6c82ea513f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 831/831 (100.0%)</li>
<li>Failed: 0/831 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 312687/312687 (100.0%)</li>
<li>Failed: 0/312687 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 66a40435a30d511521c024905db3c88d77a31b0f
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 94501ac9adc214f5c61de042205929eb8681d175</li>
<li>SPVGEN: dev 59095d3469e4fb7506da0e3d0cd78904ed71682f</li>
<li>XGL: dev f2af4b0c33963842f544107d005f0a6c82ea513f</li>
<li>LLVM: amd-vulkan-dev 97cc33415120ae3ed472b6dd5cb234b74a80bd80</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 831/831 (100.0%)</li>
<li>Failed: 0/831 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 312687/312687 (100.0%)</li>
<li>Failed: 0/312687 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
Please don't merge this change, the internal test is failed.

**Pull request merged**
