### PR TITLE
Jenkins Pipeline Github Integration Test

### PR DESCRIPTION
**Pull request by jasonc-piano**
Jenkinsfile test

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by amdvlk-admin** [comment]
okay to test

**Comment by amdvlk-admin** [comment]
test this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
Test results for commit a2a4b4704aa69faf39ce61f6dbd133d56d12bc25:<br/><br/>Test run totals:<br/>Passed:        159792/303811 (52.6%)<br/>Failed:        3/303811 (0.0%)<br/>Not supported: 144016/303811 (47.4%)<br/>Warnings:      0/303811 (0.0%)<br/><br/><details><summary>Expand for test failures</summary><br/>FAILURE: dEQP-VK.api.info.device.extensions<br/>Stack trace: Unknown extension VK_KHR_draw_indirect_count<br/><br/>FAILURE: dEQP-VK.wsi.display.get_display_plane_capabilities<br/>Stack trace: No planes defined at vktWsiDisplayTests.cpp:1357<br/><br/>FAILURE: dEQP-VK.wsi.display.create_display_plane_surface<br/>Stack trace: No planes defined at vktWsiDisplayTests.cpp:1504</details>

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 897e6c46a34725ccb83bbc8d072540f875d3c347
<details><summary>Driver branches used in build</summary><p>

* PAL: _dev_
* XGL: _dev_
* LLVM: _amd-vulkan-dev_
</p></details>

<details><summary>ShaderDB test</summary><p>

* Passed: 795/795 (100.0%)
* Failed: 0/795 (0.0%)
</p></details>

#### CTS tests (built with branch _Vulkan-CTS-1.1.1.2-cherry-picks_)
<details><summary>ubuntu, 18-04, ellesmere</summary><p>

* Passed: 312610/312610 (100.0%)
* Failed: 0/312610 (0.0%)
</p></details>

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 897e6c46a34725ccb83bbc8d072540f875d3c347
<details><summary>Driver branches used in build</summary><p>

* PAL: _dev_
* XGL: _dev_
* LLVM: _amd-vulkan-dev_
</p></details>

<details><summary>ShaderDB test</summary><p>

* Passed: 795/795 (100.0%)
* Failed: 0/795 (0.0%)
</p></details>

#### CTS tests (built with branch _Vulkan-CTS-1.1.1.2-cherry-picks_)
<details><summary>ubuntu, 18-04, ellesmere</summary><p>

* Passed: 312610/312610 (100.0%)
* Failed: 0/312610 (0.0%)
</p></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Pull request closed without merging**
