### PR TITLE
Fix wrong comments in llpcSpirvProcessGpuRtLibrary

### PR DESCRIPTION
**Pull request by tsymalla**
Comments referred to a non-existant class.

### CODE REVIEW

**Comment by dstutt** [comment]
ok to test

**Comment by tsymalla** [comment]
retest this please

**Comment by Flakebi** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit f22e8c93c0271f190d5a05142c2307f4d1b578b5
<details><summary>CTS tests (Failed: 0/138994)</summary><ul><li>Built with version 1.3.5.2</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 41144/69504 (59.2%)</li>
<li>Failed: 0/69504 (0.0%)</li>
<li>Not Supported: 28360/69504 (40.8%)</li><li>Warnings: 0/69504 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 41178/69490 (59.3%)</li>
<li>Failed: 0/69490 (0.0%)</li>
<li>Not Supported: 28312/69490 (40.7%)</li><li>Warnings: 0/69490 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
