### PR TITLE
Fixed clang compile errors from 'Support translate and lower phase in…

### PR DESCRIPTION
**Pull request by trenouf**
… shader module [Part 2]'

- Fixed a few unused variables.
- Clang complained of ambiguity in calls to the BinaryStream set and map
  methods, so I separated BinaryStream into BinaryIStream and
  BinaryOStream.

Change-Id: I38af08d310fc7ef19b696e2af33d1a49aa31bb8c

### CODE REVIEW

**Comment by trenouf** [comment]
I will land this.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 24c1998dd9f9d4c2868b0416fbe95cd74c30c011
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 66e78b997748d03d77e1d706c10f1f17e18e5654</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 9b632ef4f132bddc94769702ed8b49efbc39d89c</li>
<li>LLVM: amd-vulkan-dev 9bc5dd4450a6361faf5c5661056a7ee494fad830</li>
</ul></details>

<details><summary>Build Failed</summary><ul>

/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/context/llpcCompiler.cpp:356:15: error: explicit specialization in non-namespace scope ‘class Llpc::BinaryIStream<Stream>’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/context/llpcCompiler.cpp:372:15: error: explicit specialization in non-namespace scope ‘class Llpc::BinaryIStream<Stream>’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/context/llpcCompiler.cpp:410:15: error: explicit specialization in non-namespace scope ‘class Llpc::BinaryOStream<Stream>’
/jenkins/workspace/open-source/llpc-github-pr/driver_build/drivers/llpc/context/llpcCompiler.cpp:424:15: error: explicit specialization in non-namespace scope ‘class Llpc::BinaryOStream<Stream>’

</ul></details>

**Comment by trenouf** [comment]
Looks like it does not build on gcc now. :-(

**Comment by amdvlk-admin** [comment]
### Test summary for commit 70a965a81d6d1931b167f786442d6c5c4c1a3a2a
<details open><summary>Driver commits used in build</summary><ul>

<li>PAL: dev 66e78b997748d03d77e1d706c10f1f17e18e5654</li>
<li>SPVGEN: dev 2f31d1170e8a12a66168b23235638c4bbc43ecdc</li>
<li>XGL: dev 9b632ef4f132bddc94769702ed8b49efbc39d89c</li>
<li>LLVM: amd-vulkan-dev 9bc5dd4450a6361faf5c5661056a7ee494fad830</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 925/925 (100.0%)</li>
<li>Failed: 0/925 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 365531/365531 (100.0%)</li>
<li>Failed: 0/365531 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 365657/365657 (100.0%)</li>
<li>Failed: 0/365657 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
