### PR TITLE
Promotion from AMD internal branch for  2022.Q4.1

### PR DESCRIPTION
**Pull request by WenqingLiAMD**

### CODE REVIEW

**Review by nhaehnle — COMMENTED** [review]
Looks reasonable to me.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 800ad2df16f495fab8974fbde4efd01790b3fb99
<details><summary>CTS tests (Failed: 0/0)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Timeout or crash</li>

</ul></details>


</ul></details>

**Comment by WenqingLiAMD** [comment]
Close and reopen to run docker tests.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8537c732df09e8e4306f1519e5b50fa19dfc0333
<details><summary>CTS tests (Failed: 0/277760)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 34841/70472 (49.4%)</li>
<li>Failed: 0/70472 (0.0%)</li>
<li>Not Supported: 35631/70472 (50.6%)</li><li>Warnings: 0/70472 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38907/70483 (55.2%)</li>
<li>Failed: 0/70483 (0.0%)</li>
<li>Not Supported: 31576/70483 (44.8%)</li><li>Warnings: 0/70483 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35750/70483 (50.7%)</li>
<li>Failed: 0/70483 (0.0%)</li>
<li>Not Supported: 34733/70483 (49.3%)</li><li>Warnings: 0/70483 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 33476/66322 (50.5%)</li>
<li>Failed: 0/66322 (0.0%)</li>
<li>Not Supported: 32846/66322 (49.5%)</li><li>Warnings: 0/66322 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request closed without merging**
