### PR TITLE
Simplify wave-size selection on gfx11+

### PR DESCRIPTION
**Pull request by Flakebi**
The PatchWaveSizeAdjust pass used wave64 for basically every shader. To simplify this, just set the preferred wave size to wave64 for gfx11+.

This shouldn’t cause changes, except for (almost) empty shaders.
On the ~9000 pipelines I tested, there was no difference.

The code in `setShaderDefaultWaveSize` tries to set wave32 as the default for geometry shaders on gfx11+, which gets overwritten. We may want to change that, but it should be a separate PR as this one is basically NFC. (The further change affects 11/9000 pipelines, so it seems rather minor.)

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 62e80a40f382e28c77285499a5042cf88e0ca7dc
<details><summary>CTS tests (Failed: 0/141320)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 40065/70667 (56.7%)</li>
<li>Failed: 0/70667 (0.0%)</li>
<li>Not Supported: 30602/70667 (43.3%)</li><li>Warnings: 0/70667 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 40106/70653 (56.8%)</li>
<li>Failed: 0/70653 (0.0%)</li>
<li>Not Supported: 30547/70653 (43.2%)</li><li>Warnings: 0/70653 (0.0%)</li>
</ul></details>


</ul></details>

**Review by nhaehnle — DISMISSED** [review]
Yes, good riddance of code that doesn't make sense.

**Comment by Flakebi** [comment]
Rebased to fix conflict

**Review by nhaehnle — APPROVED** [review]
LGTM

**Pull request merged**
