### PR TITLE
Fix glue shader strings

### PR DESCRIPTION
**Pull request by s-perron**
The glue shader string will include a pointer, which can be different
even if they point to the same thing.  This change will write the
ColorExportInfo and the VertexFetchInfo out member by member, expanding
the point to the type to the type string.

### CODE REVIEW

**Comment by s-perron** [comment]
@trenouf @JaxLinAMD Is there a unit test framework I can use to get this?  A shaderdb test is not appropriate for this.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1490655156aebfeacc4e227a540ab56c49f99b8e
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 0168557a0715bf47a55ffe9858276cde1e74cc1d</li>
<li>SPVGEN: dev 5bf4618ac00d4675f57ca5b571a485bbc4d4fa33</li>
<li>XGL: dev d5d37d69a0d4bd01cc93b8e806b18f4040a13e6d</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 2d65a54ff6a0f09b40937c3efb03c82d42002187</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/225198)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30577/56304 (54.3%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 25727/56304 (45.7%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30577/56304 (54.3%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 25727/56304 (45.7%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30682/56286 (54.5%)</li>
<li>Failed: 0/56286 (0.0%)</li>
<li>Not Supported: 25604/56286 (45.5%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34150/56304 (60.7%)</li>
<li>Failed: 0/56304 (0.0%)</li>
<li>Not Supported: 22154/56304 (39.3%)</li>
</ul></details>


</ul></details>

**Review by trenouf — APPROVED** [review]
LGTM.

Re test: We don't have a precedent of a unit test linked into the compiler build in the same way as they do on LLVM. How about modifying the code to dump the glue shader string when -v is on, and then FileChecking for that when running the lgc command to do the link?

**Comment by s-perron** [comment]
Okay, I'll add the logging when I add the code that uses these string.

**Comment by s-perron** [comment]
@JaxLinAMD I think this should be okay to merge.  Testing will be done in another PR when we use the string to check the cache.

**Pull request merged**
