### PR TITLE
Dummy change to test updated llvm dev

### PR DESCRIPTION
**Pull request by trenouf**
Change-Id: I859fdfdca21fe7d5113182f449f088dfbc0ad508

### CODE REVIEW

**Comment by trenouf** [comment]
Please do not approve or merge.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1c6e82af64b00e4380cf430826afb687dee8870a
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 831f334a9f4ef429b5d4e953b86b4624a7c2db54</li>
<li>SPVGEN: dev f1bc2ba988273c3724afffe72fe9cd933a022ce7</li>
<li>XGL: dev 54a1ba508fd82ed2a11d0960f0f2f35f975b2f12</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 9dad44387cc94c678e83a9e944179b37ba4e282d</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 88fe384e4961f0955a59e58d3f1d688d114fcc78
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 40af910391fb8c287cb37bf520c41310bf88d405</li>
<li>SPVGEN: dev ce06cb5e3116ba77a22c3278dfeadfd865a8977c</li>
<li>XGL: dev 7e13a8bd0bb57d3cfb3bc014f6b26a8c9bb8bfd9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c22b8992220d645b9f781e4a47947ae546fcd11c</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 5d99d19b9384eae8fbdec77aa3a9fbf1d2fb3975
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 40af910391fb8c287cb37bf520c41310bf88d405</li>
<li>SPVGEN: dev ce06cb5e3116ba77a22c3278dfeadfd865a8977c</li>
<li>XGL: dev 7e13a8bd0bb57d3cfb3bc014f6b26a8c9bb8bfd9</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 08268e9955d48ca075b239ae46328694ddff2413</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 939/939 (100.0%)</li>
<li>Failed: 0/939 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.2.3-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 65433/65433 (100.0%)</li>
<li>Failed: 0/65433 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 65465/65465 (100.0%)</li>
<li>Failed: 0/65465 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by trenouf** [comment]
Looks like a problem with the test system:
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 5, column 97

**Comment by trenouf** [comment]
Testing just-updated llvm-project.

**Comment by trenouf** [comment]
I think this is the suspected spurious error that we've seen elsewhere:
Test case 'dEQP-VK.api.object_management.multithreaded_shared_resources.compute_pipeline'..
  ResourceError (vk.createComputePipelines(device, pipelineCache, 1u, pCreateInfo, pAllocator, &object): VK_ERROR_OUT_OF_HOST_MEMORY at vkRefUtil.cpp:49)

**Comment by amdvlk-admin** [comment]
### Test summary for commit c39436c6455b91b8710e4d240f9e4f0032cc48b3
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 45f531beaf2c2b0bc2272e63a2da0022f1b07ccf</li>
<li>SPVGEN: dev 81f6794e048edd31d8c03343b9ed10dd4c0331ca</li>
<li>XGL: dev 8024f27f9457e3235bf4fcde0d2879bbaae7b0f2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 878d4bd14afe9bc670911954adfb7c16b71e7cae</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 960/960 (100.0%)</li>
<li>Failed: 0/960 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.0-cherry-picks)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 102925/102926 (100.0%)</li>
<li><details><summary>Failed: 1/102926 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.driver_properties.conformance_version
Stack trace: Wrong driver conformance version at vktApiDriverPropertiesTests.cpp:149
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 130f978a5c683bf3774c63596bef2f3655a7d2fb
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev 45f531beaf2c2b0bc2272e63a2da0022f1b07ccf</li>
<li>SPVGEN: dev f2d32c98de40d445656b41f14756f207264cc8bb</li>
<li>XGL: dev 8024f27f9457e3235bf4fcde0d2879bbaae7b0f2</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 0aab7f3563c5f895192af12cb62b17797201fe82</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 960/960 (100.0%)</li>
<li>Failed: 0/960 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103193/103193 (100.0%)</li>
<li>Failed: 0/103193 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 56026d9d56004ae57ab860f66c6417d4fe376a61
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 20bc469e9806bb60b22559f727c1321354091898</li>
<li>SPVGEN: dev c054813a9a894e32aaaa04c6717a667c15f60cfd</li>
<li>XGL: dev feb87bf013f2b4bd16f7a1da39a5a97fdaa7470d</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev d3f03b36d914d6f4c4d27709bf29b89c4803c9cf</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/131664)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22981/43895 (52.4%)</li>
<li>Failed: 0/43895 (0.0%)</li>
<li>Skipped: 20914/43895 (47.6%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22980/43895 (52.4%)</li>
<li>Failed: 0/43895 (0.0%)</li>
<li>Skipped: 20915/43895 (47.6%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21622/43874 (49.3%)</li>
<li>Failed: 0/43874 (0.0%)</li>
<li>Skipped: 22252/43874 (50.7%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4fc5bc7591bf0535c3cd5fbfc296353cf97ea79c
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev c9937b277c491a55c689eec7cdd48fb238b8004c</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev c6c90450fb1abf5f414acf1e38a0f51a72c426c1</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev bf987708faa5335d515b11a05d898442674fd6ed</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/131664)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 24006/43895 (54.7%)</li>
<li>Failed: 0/43895 (0.0%)</li>
<li>Skipped: 19889/43895 (45.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 24004/43895 (54.7%)</li>
<li><details><summary>Failed: 1/43895 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.renderpass2.suballocation.formats.r8g8_uint.load.draw
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 19890/43895 (45.3%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 22647/43874 (51.6%)</li>
<li>Failed: 0/43874 (0.0%)</li>
<li>Skipped: 21227/43874 (48.4%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 1844656c87251c862746c24008e168dd2ebbff00
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 16871e90b0f2e6937aecee415af4d2556384bd7f</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev f623fc7ca78c3cec2123a16700a8819f3ccf0656</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 6d7376cb11eeeb48833cd87a055249b7e0a8d9b5</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/144366)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 26276/48129 (54.6%)</li>
<li>Failed: 0/48129 (0.0%)</li>
<li>Skipped: 21853/48129 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26275/48129 (54.6%)</li>
<li>Failed: 0/48129 (0.0%)</li>
<li>Skipped: 21854/48129 (45.4%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 24807/48108 (51.6%)</li>
<li>Failed: 0/48108 (0.0%)</li>
<li>Skipped: 23301/48108 (48.4%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
a test comment:
[https://github.com/GPUOpen-Drivers/pal/blob/dev/src/util/lnx/lnxSysUtil.cpp](url)

**Comment by nhaehnle** [comment]
I'm going to go out on a limb and assume this can be closed ;)

**Pull request closed without merging**
