### PR TITLE
lgc/patch: Fix an outdated comment

### PR DESCRIPTION
**Pull request by nhaehnle**
There hasn't been an external bitcode library to link against for a
while now..

### CODE REVIEW

**Review by amdrexu — APPROVED** [review]

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 015b6992acd3d3062b5acd89fe80f8f27769f9cd
<details><summary>CTS tests (Failed: 1/216287)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35463/73567 (48.2%)</li>
<li>Failed: 0/73567 (0.0%)</li>
<li>Not Supported: 38104/73567 (51.8%)</li><li>Warnings: 0/73567 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33155/69153 (47.9%)</li>
<li><details><summary>Failed: 1/69153 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.sparse_resources.image_sparse_memory_aliasing.2d_array.rg32i.512_256_6
Stack trace: Flake
```
</p></details></li>

<li>Not Supported: 35997/69153 (52.1%)</li><li>Warnings: 0/69153 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37728/73567 (51.3%)</li>
<li>Failed: 0/73567 (0.0%)</li>
<li>Not Supported: 35839/73567 (48.7%)</li><li>Warnings: 0/73567 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by nhaehnle** [comment]
Looks like a flaky test

**Comment by nhaehnle** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 015b6992acd3d3062b5acd89fe80f8f27769f9cd
<details><summary>CTS tests (Failed: 0/216287)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35463/73567 (48.2%)</li>
<li>Failed: 0/73567 (0.0%)</li>
<li>Not Supported: 38104/73567 (51.8%)</li><li>Warnings: 0/73567 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33156/69153 (47.9%)</li>
<li>Failed: 0/69153 (0.0%)</li>
<li>Not Supported: 35997/69153 (52.1%)</li><li>Warnings: 0/69153 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37728/73567 (51.3%)</li>
<li>Failed: 0/73567 (0.0%)</li>
<li>Not Supported: 35839/73567 (48.7%)</li><li>Warnings: 0/73567 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
