### PR TITLE
raytracing: push context acquires closer to leaf functions in llpcCompiler

### PR DESCRIPTION
**Pull request by nhaehnle**
This should fix an issue with DialectContext guards @piotrAMD

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 31ab6da7edb0a95862034f1eb58406a10fb02b4e
<details><summary>CTS tests (Failed: 2476/211518)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 36636/70507 (52.0%)</li>
<li><details><summary>Failed: 2476/70507 (3.5%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.regular.ahit
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.regular.call
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.regular.chit
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.regular.miss
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.regular.rgen
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.regular.sect
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push.ahit
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push.call
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push.chit
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push.miss
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push.rgen
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push.sect
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push_template.ahit
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push_template.call
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push_template.chit
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push_template.miss
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push_template.rgen
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_push_template.sect
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_template.ahit
Stack trace: Crash

FAILURE: dEQP-VK.binding_model.descriptor_update.acceleration_structure.ray_query.with_template.call
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 31395/70507 (44.5%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70509 (51.0%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34550/70509 (49.0%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 35861/70502 (50.9%)</li>
<li>Failed: 0/70502 (0.0%)</li>
<li>Not Supported: 34641/70502 (49.1%)</li><li>Warnings: 0/70502 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by jiaolu** [comment]
Accquire/releaseContexts are moved to the buildRayTracingPipelineInternal.  what's intention of code change?

**Comment by nhaehnle** [comment]
Hi @jiaolu, there was an observed problem with the DialectContext guards for the original main context being nested with the context that the main thread switches to. Though @piotrAMD reported that there is still some issue, so let's see what that investigation gives us.

**Comment by jiaolu** [comment]
> Hi @jiaolu, there was an observed problem with the DialectContext guards for the original main context being nested with the context that the main thread switches to. Though @piotrAMD reported that there is still some issue, so let's see what that investigation gives us.

thanks . The code LGTM now.

**Comment by piotrAMD** [comment]
Could be that the guard is missing in `helperThreadBuildRayTracingPipelineElf`. I can get the game to load properly if I cherry-pick the patch and add the guard in there.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 0cff7d4a58ff994e2113c4dc9935c06ee7d32e2b
<details><summary>CTS tests (Failed: 0/282025)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 38862/70507 (55.1%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31645/70507 (44.9%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi2x</summary><ul>

<li>Passed: 39112/70507 (55.5%)</li>
<li>Failed: 0/70507 (0.0%)</li>
<li>Not Supported: 31395/70507 (44.5%)</li><li>Warnings: 0/70507 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 35959/70509 (51.0%)</li>
<li>Failed: 0/70509 (0.0%)</li>
<li>Not Supported: 34550/70509 (49.0%)</li><li>Warnings: 0/70509 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 35861/70502 (50.9%)</li>
<li>Failed: 0/70502 (0.0%)</li>
<li>Not Supported: 34641/70502 (49.1%)</li><li>Warnings: 0/70502 (0.0%)</li>
</ul></details>


</ul></details>

**Review by amdrexu — APPROVED** [review]

**Pull request merged**
